
   CREATE SEQUENCE  SEQ_AKSJONSPUNKT_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
   CREATE SEQUENCE  SEQ_BEHANDLING_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
   CREATE SEQUENCE  SEQ_BEHANDLING_STEG_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
   CREATE SEQUENCE  SEQ_BEHANDLING_VEDTAK_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
   CREATE SEQUENCE  SEQ_FAGSAK_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
   CREATE SEQUENCE  SEQ_VEDTAK_UTBETALING_DVH  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 50 START WITH 1     NO CYCLE ;
  CREATE TABLE AKSJONSPUNKT_DVH 
   (	TRANS_ID NUMERIC(19,0),
	BEHANDLING_STEG_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	AKSJONSPUNKT_ID NUMERIC(19,0),
	BEHANDLING_ID NUMERIC(19,0),
	FUNKSJONELL_TID TIMESTAMP (3), 
	BEHANDLENDE_ENHET_KODE VARCHAR(10),
	ENDRET_AV VARCHAR(20),
	ANSVARLIG_BESLUTTER VARCHAR(100),
	ANSVARLIG_SAKSBEHANDLER VARCHAR(100),
	AKSJONSPUNKT_STATUS VARCHAR(100),
	AKSJONSPUNKT_DEF VARCHAR(20),
	TOTRINN_BEHANDLING VARCHAR(1) DEFAULT 'N',
	TOTRINN_BEHANDLING_GODKJENT VARCHAR(1) DEFAULT 'N'
   ) ;

   COMMENT ON COLUMN AKSJONSPUNKT_DVH.TRANS_ID IS 'Primær nøkkel for aksjonspunkt transaksjoner';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.AKSJONSPUNKT_ID IS 'Id til aksjonspunkt';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.BEHANDLENDE_ENHET_KODE IS 'Behandlende enhet.';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlig beslutningstager for aksjonspunktet.';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Saksbehandler ansvarlig for aksjonspunktet om det finnes. ';
   COMMENT ON COLUMN AKSJONSPUNKT_DVH.AKSJONSPUNKT_STATUS IS 'Aksjonspunkt status';
   COMMENT ON TABLE AKSJONSPUNKT_DVH  IS 'En transaksjonstabell med alle endringer på aksjonspunkt tilknytte en behandling.';
  CREATE TABLE BEHANDLING_DVH 
   (	TRANS_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	BEHANDLING_ID NUMERIC(19,0),
	FAGSAK_ID NUMERIC(19,0),
	VEDTAK_ID NUMERIC(19,0),
	OPPRETTET_DATO DATE, 
	FUNKSJONELL_TID TIMESTAMP (3), 
	BEHANDLING_RESULTAT_TYPE VARCHAR(100),
	BEHANDLING_TYPE VARCHAR(100),
	BEHANDLING_STATUS VARCHAR(100),
	BEHANDLENDE_ENHET VARCHAR(10),
	UTLANDSTILSNITT VARCHAR(100),
	ENDRET_AV VARCHAR(20),
	ANSVARLIG_BESLUTTER VARCHAR(100),
	ANSVARLIG_SAKSBEHANDLER VARCHAR(100),
	TOTRINNSBEHANDLING VARCHAR(1) DEFAULT 'N',
	RELATERT_TIL NUMERIC(19,0),
	FERDIG CHAR(1),
	VEDTATT CHAR(1),
	AVBRUTT CHAR(1)
   ) ;

   COMMENT ON COLUMN BEHANDLING_DVH.TRANS_ID IS 'Primær nøkkel for behandling transaksjoner';
   COMMENT ON COLUMN BEHANDLING_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_ID IS 'Id til Behandling';
   COMMENT ON COLUMN BEHANDLING_DVH.FAGSAK_ID IS 'Id til Fagsak';
   COMMENT ON COLUMN BEHANDLING_DVH.OPPRETTET_DATO IS 'Dato da fagsaken ble opprettet';
   COMMENT ON COLUMN BEHANDLING_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_RESULTAT_TYPE IS 'Behandlingsresultat type.';
   COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_TYPE IS 'Behandlingstype';
   COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_STATUS IS 'Behandlingsstatus';
   COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLENDE_ENHET IS 'Enheten som sitter på behandlinge på dette tidspunktet.';
   COMMENT ON COLUMN BEHANDLING_DVH.UTLANDSTILSNITT IS 'Kodeverk: UTLAND, NASJONAL. ';
   COMMENT ON COLUMN BEHANDLING_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN BEHANDLING_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlige saksbehandler.';
   COMMENT ON COLUMN BEHANDLING_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Ansvarlig besluttningstager';
   COMMENT ON COLUMN BEHANDLING_DVH.RELATERT_TIL IS 'Behandling ID til forrige behandling';
   COMMENT ON COLUMN BEHANDLING_DVH.FERDIG IS 'Angir om behandlingen er ferdig (fedig utbetalt eller fattet avslag)';
   COMMENT ON COLUMN BEHANDLING_DVH.VEDTATT IS 'Angir om behandlingen har fått et positivt eller negativt vedtak';
   COMMENT ON COLUMN BEHANDLING_DVH.AVBRUTT IS 'Angir om behandlingen har blitt avbrutt';
   COMMENT ON TABLE BEHANDLING_DVH  IS 'En transaksjonstabell med alle endringer på behandlingen.';
  CREATE TABLE BEHANDLING_STEG_DVH 
   (	TRANS_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	BEHANDLING_STEG_ID NUMERIC(19,0),
	BEHANDLING_ID NUMERIC(19,0),
	FUNKSJONELL_TID TIMESTAMP (3), 
	ENDRET_AV VARCHAR(20),
	BEHANDLING_STEG_TYPE VARCHAR(100),
	BEHANDLING_STEG_STATUS VARCHAR(100)
   ) ;

   COMMENT ON COLUMN BEHANDLING_STEG_DVH.TRANS_ID IS 'Primær nøkkel for behandling steg transaksjoner';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_ID IS 'BEHANDLING_STEG_TILSTAND.ID';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_TYPE IS 'Steg type';
   COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_STATUS IS 'Steg status';
   COMMENT ON TABLE BEHANDLING_STEG_DVH  IS 'En transaksjonstabell av alle endringer på behandlingen steg.';
  CREATE TABLE BEHANDLING_VEDTAK_DVH 
   (	TRANS_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	VEDTAK_ID NUMERIC(19,0),
	BEHANDLING_ID NUMERIC(19,0),
	OPPRETTET_DATO DATE, 
	FUNKSJONELL_TID TIMESTAMP (3), 
	VEDTAK_DATO DATE, 
	IVERKSETTING_STATUS VARCHAR(100),
	GODKJENNENDE_ENHET VARCHAR(10),
	ENDRET_AV VARCHAR(20),
	ANSVARLIG_BESLUTTER VARCHAR(100),
	ANSVARLIG_SAKSBEHANDLER VARCHAR(100),
	VEDTAK_RESULTAT_TYPE_KODE VARCHAR(100)
   ) ;

   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.TRANS_ID IS 'Primær nøkkel for behandling vedtak transaksjoner';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.BEHANDLING_ID IS 'Id til behandling';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.OPPRETTET_DATO IS 'Dato da vedtak ble opprettet';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.VEDTAK_DATO IS 'Datoen da vedtaket ble vedtatt.';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.IVERKSETTING_STATUS IS 'Iverksettingsstatus';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.GODKJENNENDE_ENHET IS 'Enheten som godkjener vedtaket. ';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlig beslutningstager';
   COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Ansvarlig saksbehandler';
   COMMENT ON TABLE BEHANDLING_VEDTAK_DVH  IS 'En transaksjonstabell med alle endringer på behandlingsvedtak.';
  CREATE TABLE FAGSAK_DVH 
   (	TRANS_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	FAGSAK_ID NUMERIC(19,0),
	BRUKER_ID NUMERIC(19,0),
	OPPRETTET_DATO DATE, 
	FUNKSJONELL_TID TIMESTAMP (3), 
	SAKSNUMMER NUMERIC(19,0),
	ENDRET_AV VARCHAR(20),
	FAGSAK_STATUS VARCHAR(100),
	FAGSAK_YTELSE VARCHAR(100),
	FAGSAK_AARSAK VARCHAR(100),
	BRUKER_AKTOER_ID VARCHAR(20),
	EPS_AKTOER_ID VARCHAR(20)
   ) ;

   COMMENT ON COLUMN FAGSAK_DVH.TRANS_ID IS 'Primær nøkkel for fagsak transaksjoner';
   COMMENT ON COLUMN FAGSAK_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_ID IS 'Id til Fagsak';
   COMMENT ON COLUMN FAGSAK_DVH.BRUKER_ID IS 'Bruker id til fagsaken';
   COMMENT ON COLUMN FAGSAK_DVH.OPPRETTET_DATO IS 'Dato da fagsaken ble opprettet';
   COMMENT ON COLUMN FAGSAK_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN FAGSAK_DVH.SAKSNUMMER IS 'Saksnummer som åpent for saksbehandler';
   COMMENT ON COLUMN FAGSAK_DVH.ENDRET_AV IS 'Samme som opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_STATUS IS 'Fagsaksstatus';
   COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_YTELSE IS 'Fagssaksytelse';
   COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_AARSAK IS 'Fagssaksårsak';
   COMMENT ON TABLE FAGSAK_DVH  IS 'En transaksjonstabell med alle endringer på fagsaken.';
  CREATE TABLE KONTROLL_DVH 
   (	ID NUMERIC(19,0),
	FAGSAK_TRANS_ID_MAX NUMERIC(19,0),
	BEH_TRANS_ID_MAX NUMERIC(19,0),
	BEH_STEG_TRANS_ID_MAX NUMERIC(19,0),
	BEH_AKSJONS_TRANS_ID_MAX NUMERIC(19,0),
	BEH_VEDTAKS_TRANS_ID_MAX NUMERIC(19,0),
	LAST_FLAGG VARCHAR(1)
   ) ;

   COMMENT ON COLUMN KONTROLL_DVH.ID IS 'Meta-data tabell som forteller hva siste leste trans id for de forskjellig transaksjonstabellene som er blitt lest av DVH. ';
   COMMENT ON COLUMN KONTROLL_DVH.FAGSAK_TRANS_ID_MAX IS 'Sist leste id fra fagsak_dvh';
   COMMENT ON COLUMN KONTROLL_DVH.BEH_TRANS_ID_MAX IS 'Sist leste id fra behandling_dvh';
   COMMENT ON COLUMN KONTROLL_DVH.BEH_STEG_TRANS_ID_MAX IS 'Sist leste id fra behandling_steg_dvh';
   COMMENT ON COLUMN KONTROLL_DVH.BEH_AKSJONS_TRANS_ID_MAX IS 'Sist leste id fra aksjonspunkt_dvh';
   COMMENT ON COLUMN KONTROLL_DVH.BEH_VEDTAKS_TRANS_ID_MAX IS 'Sist leste id fra behandlings_vedtak_dvh';
  CREATE TABLE VEDTAK_UTBETALING_DVH 
   (	TRANS_ID NUMERIC(19,0),
	TRANS_TID TIMESTAMP (3), 
	XML_CLOB TEXT,
	FAGSAK_ID NUMERIC(19,0),
	BEHANDLING_ID NUMERIC(19,0),
	VEDTAK_ID NUMERIC(19,0),
	BEHANDLING_TYPE VARCHAR(100),
	SOEKNAD_TYPE VARCHAR(100),
	FAGSAK_TYPE VARCHAR(100),
	VEDTAK_DATO DATE, 
	FUNKSJONELL_TID TIMESTAMP (3), 
	ENDRET_AV VARCHAR(20)
   ) ;

   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.TRANS_ID IS 'Primær nøkkel';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.XML_CLOB IS 'XML for Vedtak og utbetaling.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.FAGSAK_ID IS 'Id til Fagsak.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.BEHANDLING_ID IS 'Id til Behandling.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.VEDTAK_ID IS 'Id til Vedtak.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.BEHANDLING_TYPE IS 'Type behandling.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.SOEKNAD_TYPE IS 'Type søknad, fødsel eller adopsjon.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.VEDTAK_DATO IS 'Dato vedtaket ble fattet.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN VEDTAK_UTBETALING_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON TABLE VEDTAK_UTBETALING_DVH  IS 'En tabell med med informasjon om alle vedtak fattet i VL, inkluderer utbetalingsinfo';
  
  /*CREATE UNIQUE INDEX PK_AKSJONSPUNKT_DVH ON AKSJONSPUNKT_DVH (TRANS_ID)
  ;
  CREATE UNIQUE INDEX PK_BEHANDLING_DVH ON BEHANDLING_DVH (TRANS_ID) 
  ;
  CREATE UNIQUE INDEX PK_BEHANDLING_STEG_DVH ON BEHANDLING_STEG_DVH (TRANS_ID) 
  ;
  CREATE UNIQUE INDEX PK_BEHANDLING_VEDTAK_DVH ON BEHANDLING_VEDTAK_DVH (TRANS_ID) 
  ;
  CREATE UNIQUE INDEX PK_FAGSAK_DVH ON FAGSAK_DVH (TRANS_ID) 
  ;
  CREATE UNIQUE INDEX PK_KONTROLL_DVH ON KONTROLL_DVH (ID) 
  ;
  CREATE UNIQUE INDEX PK_VEDTAK_UTBETALING_DVH ON VEDTAK_UTBETALING_DVH (TRANS_ID) 
  ;*/
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN AKSJONSPUNKT_DEF SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ADD CONSTRAINT PK_AKSJONSPUNKT_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN AKSJONSPUNKT_STATUS SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN BEHANDLING_ID SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN AKSJONSPUNKT_ID SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE AKSJONSPUNKT_DVH ALTER COLUMN TRANS_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ADD CONSTRAINT PK_BEHANDLING_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN BEHANDLING_STATUS SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN BEHANDLING_TYPE SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN OPPRETTET_DATO SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN FAGSAK_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN BEHANDLING_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_DVH ALTER COLUMN TRANS_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_STEG_DVH ADD CONSTRAINT PK_BEHANDLING_STEG_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE BEHANDLING_STEG_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_STEG_DVH ALTER COLUMN BEHANDLING_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_STEG_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_STEG_DVH ALTER COLUMN TRANS_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ADD CONSTRAINT PK_BEHANDLING_VEDTAK_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN IVERKSETTING_STATUS SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN VEDTAK_DATO SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN OPPRETTET_DATO SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN BEHANDLING_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN VEDTAK_ID SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE BEHANDLING_VEDTAK_DVH ALTER COLUMN TRANS_ID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN BRUKER_AKTOER_ID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ADD CONSTRAINT PK_FAGSAK_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN FAGSAK_AARSAK SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN FAGSAK_YTELSE SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN FAGSAK_STATUS SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN OPPRETTET_DATO SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN BRUKER_ID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN FAGSAK_ID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE FAGSAK_DVH ALTER COLUMN TRANS_ID SET NOT NULL;
  ALTER TABLE KONTROLL_DVH ADD CONSTRAINT PK_KONTROLL_DVH PRIMARY KEY (ID) ;
  ALTER TABLE KONTROLL_DVH ALTER COLUMN ID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ADD CONSTRAINT PK_VEDTAK_UTBETALING_DVH PRIMARY KEY (TRANS_ID) ;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN FUNKSJONELL_TID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN VEDTAK_DATO SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN FAGSAK_TYPE SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN SOEKNAD_TYPE SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN BEHANDLING_TYPE SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN VEDTAK_ID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN BEHANDLING_ID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN FAGSAK_ID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN XML_CLOB SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN TRANS_TID SET NOT NULL;
  ALTER TABLE VEDTAK_UTBETALING_DVH ALTER COLUMN TRANS_ID SET NOT NULL;

  -- setter opp lese -og skriverettigheter til DVH-tabeller
GRANT SELECT on SEQ_FAGSAK_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_STEG_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_AKSJONSPUNKT_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_VEDTAK_DVH to FPSAK_HIST_SKRIVE_ROLE;

REVOKE ALL ON FAGSAK_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON FAGSAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON FAGSAK_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_STEG_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_STEG_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_STEG_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON AKSJONSPUNKT_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON AKSJONSPUNKT_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON AKSJONSPUNKT_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_VEDTAK_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_VEDTAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_VEDTAK_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON KONTROLL_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT, INSERT ON KONTROLL_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT, INSERT ON KONTROLL_DVH TO FPSAK_HIST_LESE_ROLE;

