
   CREATE SEQUENCE  "SEQ_AKSJONSPUNKT_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "SEQ_BEHANDLING_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "SEQ_BEHANDLING_STEG_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "SEQ_BEHANDLING_VEDTAK_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "SEQ_FAGSAK_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "SEQ_VEDTAK_UTBETALING_DVH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  CREATE TABLE "AKSJONSPUNKT_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"BEHANDLING_STEG_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"AKSJONSPUNKT_ID" NUMBER(19,0), 
	"BEHANDLING_ID" NUMBER(19,0), 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"BEHANDLENDE_ENHET_KODE" VARCHAR2(10 CHAR), 
	"ENDRET_AV" VARCHAR2(20 CHAR), 
	"ANSVARLIG_BESLUTTER" VARCHAR2(100 CHAR), 
	"ANSVARLIG_SAKSBEHANDLER" VARCHAR2(100 CHAR), 
	"AKSJONSPUNKT_STATUS" VARCHAR2(100 CHAR), 
	"AKSJONSPUNKT_DEF" VARCHAR2(20 CHAR), 
	"TOTRINN_BEHANDLING" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"TOTRINN_BEHANDLING_GODKJENT" VARCHAR2(1 CHAR) DEFAULT 'N'
   ) ;

   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."TRANS_ID" IS 'Primær nøkkel for aksjonspunkt transaksjoner';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."AKSJONSPUNKT_ID" IS 'Id til aksjonspunkt';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."BEHANDLENDE_ENHET_KODE" IS 'Behandlende enhet.';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."ENDRET_AV" IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."ANSVARLIG_BESLUTTER" IS 'Ansvarlig beslutningstager for aksjonspunktet.';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."ANSVARLIG_SAKSBEHANDLER" IS 'Saksbehandler ansvarlig for aksjonspunktet om det finnes. ';
   COMMENT ON COLUMN "AKSJONSPUNKT_DVH"."AKSJONSPUNKT_STATUS" IS 'Aksjonspunkt status';
   COMMENT ON TABLE "AKSJONSPUNKT_DVH"  IS 'En transaksjonstabell med alle endringer på aksjonspunkt tilknytte en behandling.';
  CREATE TABLE "BEHANDLING_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"BEHANDLING_ID" NUMBER(19,0), 
	"FAGSAK_ID" NUMBER(19,0), 
	"VEDTAK_ID" NUMBER(19,0), 
	"OPPRETTET_DATO" DATE, 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"BEHANDLING_RESULTAT_TYPE" VARCHAR2(100 CHAR), 
	"BEHANDLING_TYPE" VARCHAR2(100 CHAR), 
	"BEHANDLING_STATUS" VARCHAR2(100 CHAR), 
	"BEHANDLENDE_ENHET" VARCHAR2(10 CHAR), 
	"UTLANDSTILSNITT" VARCHAR2(100 CHAR), 
	"ENDRET_AV" VARCHAR2(20 CHAR), 
	"ANSVARLIG_BESLUTTER" VARCHAR2(100 CHAR), 
	"ANSVARLIG_SAKSBEHANDLER" VARCHAR2(100 CHAR), 
	"TOTRINNSBEHANDLING" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"RELATERT_TIL" NUMBER(19,0), 
	"FERDIG" CHAR(1 BYTE), 
	"VEDTATT" CHAR(1 BYTE), 
	"AVBRUTT" CHAR(1 BYTE)
   ) ;

   COMMENT ON COLUMN "BEHANDLING_DVH"."TRANS_ID" IS 'Primær nøkkel for behandling transaksjoner';
   COMMENT ON COLUMN "BEHANDLING_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN "BEHANDLING_DVH"."BEHANDLING_ID" IS 'Id til Behandling';
   COMMENT ON COLUMN "BEHANDLING_DVH"."FAGSAK_ID" IS 'Id til Fagsak';
   COMMENT ON COLUMN "BEHANDLING_DVH"."OPPRETTET_DATO" IS 'Dato da fagsaken ble opprettet';
   COMMENT ON COLUMN "BEHANDLING_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "BEHANDLING_DVH"."BEHANDLING_RESULTAT_TYPE" IS 'Behandlingsresultat type.';
   COMMENT ON COLUMN "BEHANDLING_DVH"."BEHANDLING_TYPE" IS 'Behandlingstype';
   COMMENT ON COLUMN "BEHANDLING_DVH"."BEHANDLING_STATUS" IS 'Behandlingsstatus';
   COMMENT ON COLUMN "BEHANDLING_DVH"."BEHANDLENDE_ENHET" IS 'Enheten som sitter på behandlinge på dette tidspunktet.';
   COMMENT ON COLUMN "BEHANDLING_DVH"."UTLANDSTILSNITT" IS 'Kodeverk: UTLAND, NASJONAL. ';
   COMMENT ON COLUMN "BEHANDLING_DVH"."ENDRET_AV" IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN "BEHANDLING_DVH"."ANSVARLIG_BESLUTTER" IS 'Ansvarlige saksbehandler.';
   COMMENT ON COLUMN "BEHANDLING_DVH"."ANSVARLIG_SAKSBEHANDLER" IS 'Ansvarlig besluttningstager';
   COMMENT ON COLUMN "BEHANDLING_DVH"."RELATERT_TIL" IS 'Behandling ID til forrige behandling';
   COMMENT ON COLUMN "BEHANDLING_DVH"."FERDIG" IS 'Angir om behandlingen er ferdig (fedig utbetalt eller fattet avslag)';
   COMMENT ON COLUMN "BEHANDLING_DVH"."VEDTATT" IS 'Angir om behandlingen har fått et positivt eller negativt vedtak';
   COMMENT ON COLUMN "BEHANDLING_DVH"."AVBRUTT" IS 'Angir om behandlingen har blitt avbrutt';
   COMMENT ON TABLE "BEHANDLING_DVH"  IS 'En transaksjonstabell med alle endringer på behandlingen.';
  CREATE TABLE "BEHANDLING_STEG_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"BEHANDLING_STEG_ID" NUMBER(19,0), 
	"BEHANDLING_ID" NUMBER(19,0), 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"ENDRET_AV" VARCHAR2(20 CHAR), 
	"BEHANDLING_STEG_TYPE" VARCHAR2(100 CHAR), 
	"BEHANDLING_STEG_STATUS" VARCHAR2(100 CHAR)
   ) ;

   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."TRANS_ID" IS 'Primær nøkkel for behandling steg transaksjoner';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."BEHANDLING_STEG_ID" IS 'BEHANDLING_STEG_TILSTAND.ID';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."ENDRET_AV" IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."BEHANDLING_STEG_TYPE" IS 'Steg type';
   COMMENT ON COLUMN "BEHANDLING_STEG_DVH"."BEHANDLING_STEG_STATUS" IS 'Steg status';
   COMMENT ON TABLE "BEHANDLING_STEG_DVH"  IS 'En transaksjonstabell av alle endringer på behandlingen steg.';
  CREATE TABLE "BEHANDLING_VEDTAK_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"VEDTAK_ID" NUMBER(19,0), 
	"BEHANDLING_ID" NUMBER(19,0), 
	"OPPRETTET_DATO" DATE, 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"VEDTAK_DATO" DATE, 
	"IVERKSETTING_STATUS" VARCHAR2(100 CHAR), 
	"GODKJENNENDE_ENHET" VARCHAR2(10 CHAR), 
	"ENDRET_AV" VARCHAR2(20 CHAR), 
	"ANSVARLIG_BESLUTTER" VARCHAR2(100 CHAR), 
	"ANSVARLIG_SAKSBEHANDLER" VARCHAR2(100 CHAR), 
	"VEDTAK_RESULTAT_TYPE_KODE" VARCHAR2(100 CHAR)
   ) ;

   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."TRANS_ID" IS 'Primær nøkkel for behandling vedtak transaksjoner';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."BEHANDLING_ID" IS 'Id til behandling';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."OPPRETTET_DATO" IS 'Dato da vedtak ble opprettet';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."VEDTAK_DATO" IS 'Datoen da vedtaket ble vedtatt.';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."IVERKSETTING_STATUS" IS 'Iverksettingsstatus';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."GODKJENNENDE_ENHET" IS 'Enheten som godkjener vedtaket. ';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."ENDRET_AV" IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."ANSVARLIG_BESLUTTER" IS 'Ansvarlig beslutningstager';
   COMMENT ON COLUMN "BEHANDLING_VEDTAK_DVH"."ANSVARLIG_SAKSBEHANDLER" IS 'Ansvarlig saksbehandler';
   COMMENT ON TABLE "BEHANDLING_VEDTAK_DVH"  IS 'En transaksjonstabell med alle endringer på behandlingsvedtak.';
  CREATE TABLE "FAGSAK_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"FAGSAK_ID" NUMBER(19,0), 
	"BRUKER_ID" NUMBER(19,0), 
	"OPPRETTET_DATO" DATE, 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"SAKSNUMMER" NUMBER(19,0), 
	"ENDRET_AV" VARCHAR2(20 CHAR), 
	"FAGSAK_STATUS" VARCHAR2(100 CHAR), 
	"FAGSAK_YTELSE" VARCHAR2(100 CHAR), 
	"FAGSAK_AARSAK" VARCHAR2(100 CHAR), 
	"BRUKER_AKTOER_ID" VARCHAR2(20 CHAR), 
	"EPS_AKTOER_ID" VARCHAR2(20 CHAR)
   ) ;

   COMMENT ON COLUMN "FAGSAK_DVH"."TRANS_ID" IS 'Primær nøkkel for fagsak transaksjoner';
   COMMENT ON COLUMN "FAGSAK_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff. ';
   COMMENT ON COLUMN "FAGSAK_DVH"."FAGSAK_ID" IS 'Id til Fagsak';
   COMMENT ON COLUMN "FAGSAK_DVH"."BRUKER_ID" IS 'Bruker id til fagsaken';
   COMMENT ON COLUMN "FAGSAK_DVH"."OPPRETTET_DATO" IS 'Dato da fagsaken ble opprettet';
   COMMENT ON COLUMN "FAGSAK_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "FAGSAK_DVH"."SAKSNUMMER" IS 'Saksnummer som åpent for saksbehandler';
   COMMENT ON COLUMN "FAGSAK_DVH"."ENDRET_AV" IS 'Samme som opprettet_av eller endret_av i VL';
   COMMENT ON COLUMN "FAGSAK_DVH"."FAGSAK_STATUS" IS 'Fagsaksstatus';
   COMMENT ON COLUMN "FAGSAK_DVH"."FAGSAK_YTELSE" IS 'Fagssaksytelse';
   COMMENT ON COLUMN "FAGSAK_DVH"."FAGSAK_AARSAK" IS 'Fagssaksårsak';
   COMMENT ON TABLE "FAGSAK_DVH"  IS 'En transaksjonstabell med alle endringer på fagsaken.';
  CREATE TABLE "KONTROLL_DVH" 
   (	"ID" NUMBER(19,0), 
	"FAGSAK_TRANS_ID_MAX" NUMBER(19,0), 
	"BEH_TRANS_ID_MAX" NUMBER(19,0), 
	"BEH_STEG_TRANS_ID_MAX" NUMBER(19,0), 
	"BEH_AKSJONS_TRANS_ID_MAX" NUMBER(19,0), 
	"BEH_VEDTAKS_TRANS_ID_MAX" NUMBER(19,0), 
	"LAST_FLAGG" VARCHAR2(1 CHAR)
   ) ;

   COMMENT ON COLUMN "KONTROLL_DVH"."ID" IS 'Meta-data tabell som forteller hva siste leste trans id for de forskjellig transaksjonstabellene som er blitt lest av DVH. ';
   COMMENT ON COLUMN "KONTROLL_DVH"."FAGSAK_TRANS_ID_MAX" IS 'Sist leste id fra fagsak_dvh';
   COMMENT ON COLUMN "KONTROLL_DVH"."BEH_TRANS_ID_MAX" IS 'Sist leste id fra behandling_dvh';
   COMMENT ON COLUMN "KONTROLL_DVH"."BEH_STEG_TRANS_ID_MAX" IS 'Sist leste id fra behandling_steg_dvh';
   COMMENT ON COLUMN "KONTROLL_DVH"."BEH_AKSJONS_TRANS_ID_MAX" IS 'Sist leste id fra aksjonspunkt_dvh';
   COMMENT ON COLUMN "KONTROLL_DVH"."BEH_VEDTAKS_TRANS_ID_MAX" IS 'Sist leste id fra behandlings_vedtak_dvh';
  CREATE TABLE "VEDTAK_UTBETALING_DVH" 
   (	"TRANS_ID" NUMBER(19,0), 
	"TRANS_TID" TIMESTAMP (3), 
	"XML_CLOB" CLOB, 
	"FAGSAK_ID" NUMBER(19,0), 
	"BEHANDLING_ID" NUMBER(19,0), 
	"VEDTAK_ID" NUMBER(19,0), 
	"BEHANDLING_TYPE" VARCHAR2(100 BYTE), 
	"SOEKNAD_TYPE" VARCHAR2(100 BYTE), 
	"FAGSAK_TYPE" VARCHAR2(100 BYTE), 
	"VEDTAK_DATO" DATE, 
	"FUNKSJONELL_TID" TIMESTAMP (3), 
	"ENDRET_AV" VARCHAR2(20 CHAR)
   ) ;

   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."TRANS_ID" IS 'Primær nøkkel';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."TRANS_TID" IS 'Timestamp som forteller nå transaksjonen inntraff.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."XML_CLOB" IS 'XML for Vedtak og utbetaling.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."FAGSAK_ID" IS 'Id til Fagsak.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."BEHANDLING_ID" IS 'Id til Behandling.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."VEDTAK_ID" IS 'Id til Vedtak.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."BEHANDLING_TYPE" IS 'Type behandling.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."SOEKNAD_TYPE" IS 'Type søknad, fødsel eller adopsjon.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."VEDTAK_DATO" IS 'Dato vedtaket ble fattet.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."FUNKSJONELL_TID" IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
   COMMENT ON COLUMN "VEDTAK_UTBETALING_DVH"."ENDRET_AV" IS 'Opprettet_av eller endret_av i VL';
   COMMENT ON TABLE "VEDTAK_UTBETALING_DVH"  IS 'En tabell med med informasjon om alle vedtak fattet i VL, inkluderer utbetalingsinfo';
  
  CREATE UNIQUE INDEX "PK_AKSJONSPUNKT_DVH" ON "AKSJONSPUNKT_DVH" ("TRANS_ID") 
  ;
  CREATE UNIQUE INDEX "PK_BEHANDLING_DVH" ON "BEHANDLING_DVH" ("TRANS_ID") 
  ;
  CREATE UNIQUE INDEX "PK_BEHANDLING_STEG_DVH" ON "BEHANDLING_STEG_DVH" ("TRANS_ID") 
  ;
  CREATE UNIQUE INDEX "PK_BEHANDLING_VEDTAK_DVH" ON "BEHANDLING_VEDTAK_DVH" ("TRANS_ID") 
  ;
  CREATE UNIQUE INDEX "PK_FAGSAK_DVH" ON "FAGSAK_DVH" ("TRANS_ID") 
  ;
  CREATE UNIQUE INDEX "PK_KONTROLL_DVH" ON "KONTROLL_DVH" ("ID") 
  ;
  CREATE UNIQUE INDEX "PK_VEDTAK_UTBETALING_DVH" ON "VEDTAK_UTBETALING_DVH" ("TRANS_ID") 
  ;
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("AKSJONSPUNKT_DEF" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" ADD CONSTRAINT "PK_AKSJONSPUNKT_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("AKSJONSPUNKT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("BEHANDLING_ID" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("AKSJONSPUNKT_ID" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "AKSJONSPUNKT_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" ADD CONSTRAINT "PK_BEHANDLING_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("BEHANDLING_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("BEHANDLING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("OPPRETTET_DATO" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("FAGSAK_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("BEHANDLING_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_STEG_DVH" ADD CONSTRAINT "PK_BEHANDLING_STEG_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "BEHANDLING_STEG_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_STEG_DVH" MODIFY ("BEHANDLING_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_STEG_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_STEG_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" ADD CONSTRAINT "PK_BEHANDLING_VEDTAK_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("IVERKSETTING_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("VEDTAK_DATO" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("OPPRETTET_DATO" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("BEHANDLING_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("VEDTAK_ID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "BEHANDLING_VEDTAK_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("BRUKER_AKTOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" ADD CONSTRAINT "PK_FAGSAK_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "FAGSAK_DVH" MODIFY ("FAGSAK_AARSAK" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("FAGSAK_YTELSE" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("FAGSAK_STATUS" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("OPPRETTET_DATO" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("BRUKER_ID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("FAGSAK_ID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "FAGSAK_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "KONTROLL_DVH" ADD CONSTRAINT "PK_KONTROLL_DVH" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "KONTROLL_DVH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" ADD CONSTRAINT "PK_VEDTAK_UTBETALING_DVH" PRIMARY KEY ("TRANS_ID") ENABLE;
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("FUNKSJONELL_TID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("VEDTAK_DATO" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("FAGSAK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("SOEKNAD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("BEHANDLING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("VEDTAK_ID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("BEHANDLING_ID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("FAGSAK_ID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("XML_CLOB" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("TRANS_TID" NOT NULL ENABLE);
  ALTER TABLE "VEDTAK_UTBETALING_DVH" MODIFY ("TRANS_ID" NOT NULL ENABLE);

  -- setter opp lese -og skriverettigheter til DVH-tabeller
GRANT SELECT on SEQ_FAGSAK_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_STEG_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_AKSJONSPUNKT_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT on SEQ_BEHANDLING_VEDTAK_DVH to FPSAK_HIST_SKRIVE_ROLE;

REVOKE ALL ON FAGSAK_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON FAGSAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON FAGSAK_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_STEG_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_STEG_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_STEG_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON AKSJONSPUNKT_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON AKSJONSPUNKT_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON AKSJONSPUNKT_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON BEHANDLING_VEDTAK_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT INSERT ON BEHANDLING_VEDTAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT ON BEHANDLING_VEDTAK_DVH TO FPSAK_HIST_LESE_ROLE;

REVOKE ALL ON KONTROLL_DVH FROM FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT, INSERT ON KONTROLL_DVH TO FPSAK_HIST_SKRIVE_ROLE;
GRANT SELECT, INSERT ON KONTROLL_DVH TO FPSAK_HIST_LESE_ROLE;

