alter table PERSONOPPLYSNING add FORRIGE_TPS_OPPLYSNING_ID number(19,0);
alter table PERSONOPPLYSNING add constraint FK_PERSONOPPLYSNING_11 foreign key (FORRIGE_TPS_OPPLYSNING_ID) references VALGT_OPPLYSNING (ID);
create index IDX_PERSONOPPLYSNING_11 on PERSONOPPLYSNING(FORRIGE_TPS_OPPLYSNING_ID);
