sudo: required
language: java
jdk:
- openjdk11
before_install:
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
script:
- docker pull postgres:11-alpine
- docker run -p 5432:5432 -v `pwd`:/usr/src --name postgres -e POSTGRES_PASSWORD=spsak
  -e POSTGRES_USER=spsak -d postgres:11-alpine
- until docker exec postgres psql -v ON_ERROR_STOP=1 --username spsak -c "select 1";
  do sleep 1; done
- docker exec postgres sh /usr/src/docker/localdev/initdb.sh
- cd felles && mvn install && cd ..
- cd kontrakter && mvn install && cd ..
- cd saksbehandling && mvn install
- docker build --pull -t navikt/spsak:$COMMIT_SHORT .
- cd ..
- cd vtp-mock && mvn install && cd ..
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push navikt/spsak:$COMMIT_SHORT
  fi
env:
  global:
  - secure: oZ1T6ORhEahJC4GEKUMrhkpqHpafIG2zSIpK1dF92DT+iQ8bqkD1ZoznPlqZHLDsusiEaY+YU6KlMqiwG7Xz8DH3m6bM8jpxWjTsyB2NhLYMFi8jMiqc+xmBSqFV6NgUeXGRdpJGVxpK6hPkfWOWRVLW6/9vhRdYlTu4qGq1JxX1gUgUC+1Z6xfPdC7zHnd8hjWCckr+xAsv6y4IDd15RkhNjX9Oq4dw8USmHYNSKCiCmXoZKBGJYi7YOgIcuAvmCU9ybSiej+SbeCdrNgQB01d5rq9hJ6P3WEfyXyU6Psrq4dnaDdd3pcFrX0UWph3wyCxbt8CPgc75ifxF4ZEfIL4Jn+xU2i233U2zc/4wl5Rh3iKb/iVeTJNL9yvZDQM1oSLFWtzt6M/UMunNTEjygYP87+KM7Kg2zv4xmOXBef5JNdtQ/R728uqok+3NEwr7LD+3Wa//RBYEggava2VGLIH2ve/1RxTkCFqwbquW/xg3bHHp4o60r7Kh7b6Ljwuk/Tuik78TCAtDEPOLo0gUb3BDRtNqmXoHUbCNrRre8WGmrrafxcNp8EU+Qcb2e8D/n5Q4M0SeeEJSe1B9+U2AQLRoggUAH7g7sdI0o2NabZQi0EAGqMrD4ic0SbOFcarBdXfBwOmrLp/anM6XY6IrW4Evd+wlZn7xjvNq6OVstmY=
  - secure: r0x2YnpXY2yRiTUnkHKHP6M180Nw0MIY03B/YwMPfeABlJoZpoH+W1OrDlsNqmXAalLHPkBxHDIWvbwcea+WNdkCGoD4K5vyKbPeKBlDDfIKza+YBA5DBHSj4vfFKjrlGdYg2rRSAhcgGY2bAhi4OVIPPDD42F6CmjKKLkZKcLaOUDJCCDMz9TzS+RMtNbF5ds/Wq56lmurTLk7HBrRZQu8Eb/8agtGTjGL0N/DYgnvP4XbaZC8zRxaFSHSEZkxP4qf6mznYFf4wPZdj5vDHJf3xhXfxIAsCyAUIfRPV4jrCF6NkEAW3t3NliWmee3cvYiAQULLmNkt5IbpnUueThWgGKLGY3IYksjmr/kYhuHyqj8oudCW6giEs8Io8y55xFJvWxzfaTjgCuQS0yE4go6MsqPhlz1KQ1gwiZcTK447upc8ZEuvjPSpqCBwFykGYPd6laJH5BclpVGfzYQlx1XR5LDRCQuT4EKO40Y/K5Mkm1BXM8ZQ4HCEmRLoo7X/7t40B4jX5j8ZEnbSRdgPfRQINrTINH1RLoL4QAO3y2PCAmm0s/cCCyn1fSrhwl5hXyO4Wgne4nm1Da+fcI88vpLUXUznJ69Vx0+9v4QfBEEmyVaXF4rbIi4zL8Syj9iDKUPTDaqjPVAA1hkr6lzWET4TUHo48ekmxUnRfzSy8okY=
notifications:
  slack:
    secure: eSA6UwaYRmaH3NIWMvi473vzpZYINlPBJaPFDyG0shb/oriGrkbvHfbbGqV40PeXal4pAf99T3HZFyRaoile7QZSQLPuTSlIRukHnGFOQkAmmUL4VV7W4kA2vpC+Xcie8KMbYApKfFlS+0st/GvZ0KwJRHG9Qsw0P62vxqh0HPNczEgFcXIe5LeJyVwSZ1u8avtYQ5eaWxZWXwrvoFi7fWGwiFN+SXE+VhIMJaBzznFvKqIc88f9pfgWXdFBMXntSr6NEMkb5UVv9V8jXhvbLj0zrThDwY6wIqSLsVLGPrnujlVD1jgaur2DFBavhebPfK1zlA4yV0AZ8XQ1DsImQieFu0njxFV2NqL9NUd5KAHq+1lanE+YDDAplj6YHe/UpOm72v0w+Tg+DaoarI0cEQErUdUpZyDoNMzidly22keBoaF3/uD0IX5QjC6+O8zuKFhK8Q4g0EBbezkY66DJnTsGldP0zklkY4bvNC90ZF5FzxmS20KA/cYYVJcxAD7q/m2PIMINgXqMRG5D1EDrYwMFdHVKY5idjru2bas4QogJIABWX5gKOi8KLq0B1tMkK8tDuCBdkEY9a3WyYuejG2HNwZUie1nuhXSlhElk4GhMaVlczHncBzppSqPzQ5DGCjwvAKCneKKE0yW+eG4g5bopgYrahpkq7zEuEXjSX6g=
