ALTER TABLE BEHANDLING_TYPE_STEG_SEKV DISABLE CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_01;
ALTER TABLE BEHANDLING_STEG_TILSTAND DISABLE CONSTRAINT FK_BEHANDLING_STEG_TILSTAND_2;
ALTER TABLE VURDERINGSPUNKT_DEF DISABLE CONSTRAINT FK_VURDERINGSPUNKT_DEF_1;
ALTER TABLE AKSJONSPUNKT_DEF DISABLE CONSTRAINT FK_AKSJONSPUNKT_DEF_2;
 
UPDATE BEHANDLING_STEG_TYPE SET KODE = 'KLAGEUI'  WHERE KODE = 'KLAGENFP';
UPDATE BEHANDLING_STEG_TYPE SET KODE = 'KLAGEOI'  WHERE KODE = 'KLAGENK';

UPDATE BEHANDLING_STEG_TILSTAND SET BEHANDLING_STEG = 'KLAGEUI' WHERE BEHANDLING_STEG  = 'KLAGENFP';
UPDATE BEHANDLING_STEG_TILSTAND SET BEHANDLING_STEG = 'KLAGEOI' WHERE BEHANDLING_STEG  = 'KLAGENK';

UPDATE BEHANDLING_TYPE_STEG_SEKV SET BEHANDLING_STEG_TYPE = 'KLAGEUI' WHERE BEHANDLING_STEG_TYPE = 'KLAGENFP';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET BEHANDLING_STEG_TYPE = 'KLAGEOI' WHERE BEHANDLING_STEG_TYPE = 'KLAGENK';

UPDATE VURDERINGSPUNKT_DEF SET BEHANDLING_STEG = 'KLAGEUI', KODE = 'KLAGEUI.UT' WHERE BEHANDLING_STEG = 'KLAGENFP';
UPDATE VURDERINGSPUNKT_DEF SET BEHANDLING_STEG = 'KLAGEOI', KODE = 'KLAGEOI.UT' WHERE BEHANDLING_STEG = 'KLAGENK';

UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'KLAGEUI.UT' WHERE VURDERINGSPUNKT = 'KLAGENFP.UT';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'KLAGEOI.UT' WHERE VURDERINGSPUNKT = 'KLAGENK.UT';

ALTER TABLE BEHANDLING_TYPE_STEG_SEKV ENABLE CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_01;
ALTER TABLE BEHANDLING_STEG_TILSTAND ENABLE CONSTRAINT FK_BEHANDLING_STEG_TILSTAND_2;
ALTER TABLE VURDERINGSPUNKT_DEF ENABLE CONSTRAINT FK_VURDERINGSPUNKT_DEF_1;
ALTER TABLE AKSJONSPUNKT_DEF ENABLE CONSTRAINT FK_AKSJONSPUNKT_DEF_2;