UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 1 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'VRSLREV';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 2 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'INREG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 3 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'KOFAK';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 4 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'VURDEROP';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 5 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'VURDERBV';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 6 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'VURDERMV';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 7 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'VURDERSFV';

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (id, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-004', 'VURDERSAMLET', 8);

UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 9 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'BERYT';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 10 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'FORVEDSTEG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 11 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'FVEDSTEG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 12 WHERE BEHANDLING_TYPE='BT-004' AND BEHANDLING_STEG_TYPE = 'IVEDSTEG';
