version: '3.4'

services:

  db:
    build: 
      context: ./
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
   
volumes:
    data:
    

      
      