package no.nav.foreldrepenger.domene.uttak.fastsettuttaksgrunnlag.impl;

enum Endringsdato {
    FØDSELSDATO,
    FØRSTE_UTTAKSDATO_GJELDENDE_VEDTAK,
    FØRSTE_UTTAKSDATO_SØKNAD,
    ENDRINGSDATO_I_BEHANDLING_SOM_FØRTE_TIL_BERØRT_BEHANDLING,
    MANUELT_SATT_FØRSTE_UTTAKSDATO,
    OMSORGSOVERTAKELSEDATO,
    FØRSTE_UTTAKSDATO_SØKNAD_FORRIGE_BEHANDLING, ANKOMST_NORGE_DATO
}
