-- Tabellene under har 1:1-forhold til parent (aggregat) BEHANDLING_GRUNNLAG
DROP INDEX IDX_SOEKNAD_1;
CREATE UNIQUE INDEX UIDX_SOEKNAD_1 ON SOEKNAD (BEHANDLING_GRUNNLAG_ID);
DROP INDEX IDX_FOEDSEL_1;
CREATE UNIQUE INDEX UIDX_FOEDSEL_1 ON FOEDSEL (BEHANDLING_GRUNNLAG_ID);
DROP INDEX IDX_TERMINBEKREFTELSE_1;
CREATE UNIQUE INDEX UIDX_TERMINBEKREFTELSE_1 ON TERMINBEKREFTELSE (BEHANDLING_GRUNNLAG_ID);
DROP INDEX IDX_ADOPSJON_1;
CREATE UNIQUE INDEX UIDX_ADOPSJON_1 ON ADOPSJON (BEHANDLING_GRUNNLAG_ID);
