-- Rettelser fra V1.8.0_32__Vilkårkorrigeringer_dok.sql (flaut)
UPDATE AKSJONSPUNKT_DEF SET VILKAR_TYPE = 'FP_VK_8' WHERE KODE = '5013';
UPDATE OMSORGSOVERTAKELSE_VILKAR_TYPE SET KODE = 'FP_VK_33' WHERE KODE = 'FP_VK_9';
