--------------------------------------------------------
--  DDL for Table AKSJONSPUNKT_TYPE
--------------------------------------------------------

CREATE TABLE AKSJONSPUNKT_TYPE(
  kode VARCHAR2(20 char) not null,
  navn varchar2(40 char) not null,
  beskrivelse varchar2(4000 CHAR),
  opprettet_av    VARCHAR2(20 char) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 char),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_AKSJONSPUNKT_TYPE PRIMARY KEY (KODE)
);

COMMENT ON COLUMN AKSJONSPUNKT_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN AKSJONSPUNKT_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON TABLE AKSJONSPUNKT_TYPE  IS 'Kodetabell som definerer type aksjonspunktet faller under (Autopunkt, Manuell, OVERSTYRING)';

INSERT INTO AKSJONSPUNKT_TYPE (kode, navn, beskrivelse) VALUES ('MANU', 'Manuell', 'Et punkt laget automatisk og løses manuelt');
INSERT INTO AKSJONSPUNKT_TYPE (kode, navn, beskrivelse) VALUES ('AUTO', 'Autopunkt','Et punkt laget automatisk og løses automatisk');
INSERT INTO AKSJONSPUNKT_TYPE (kode, navn, beskrivelse) VALUES ('OVST', 'Overstyring', 'Et punkt laget manuelt og løses manuelt');

ALTER TABLE AKSJONSPUNKT_DEF ADD AKSJONSPUNKT_TYPE VARCHAR2(20) DEFAULT 'MANU';

UPDATE AKSJONSPUNKT_DEF set AKSJONSPUNKT_TYPE = 'MANU' where KODE IN (
  5001, 5002, 5003, 5010, 5007, 5004, 5005, 5006, 5008, 5009,
  5011, 5012, 5013, 5014, 5015, 5016, 5019,
  5020, 5021, 5022, 5023);

UPDATE AKSJONSPUNKT_DEF set AKSJONSPUNKT_TYPE = 'AUTO' where KODE IN (
  7002);

ALTER TABLE AKSJONSPUNKT_DEF ADD FOREIGN KEY (AKSJONSPUNKT_TYPE) REFERENCES AKSJONSPUNKT_TYPE (KODE);


ALTER TABLE AKSJONSPUNKT ADD behandling_steg_funnet    VARCHAR2(20 CHAR);
ALTER TABLE AKSJONSPUNKT ADD behandling_resultat_id    NUMBER(19);
ALTER TABLE AKSJONSPUNKT ADD aksjonspunkt_status       VARCHAR2(7 CHAR);
ALTER TABLE AKSJONSPUNKT ADD aksjonspunkt_def          VARCHAR2(50 CHAR);
ALTER TABLE AKSJONSPUNKT ADD versjon                   NUMBER(19) DEFAULT 0 NOT NULL;
ALTER TABLE AKSJONSPUNKT ADD frist_tid                 TIMESTAMP(3);
ALTER TABLE AKSJONSPUNKT ADD opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL;
ALTER TABLE AKSJONSPUNKT ADD opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL;
ALTER TABLE AKSJONSPUNKT ADD endret_av                 VARCHAR2(20 CHAR);
ALTER TABLE AKSJONSPUNKT ADD endret_tid                TIMESTAMP(3);

ALTER TABLE AKSJONSPUNKT ADD CONSTRAINT FK_AKSJONSPUNKT_1 FOREIGN KEY (behandling_steg_funnet) REFERENCES BEHANDLING_STEG_TYPE;
ALTER TABLE AKSJONSPUNKT ADD CONSTRAINT FK_AKSJONSPUNKT_2 FOREIGN KEY (behandling_resultat_id) REFERENCES BEHANDLING_RESULTAT;
ALTER TABLE AKSJONSPUNKT ADD CONSTRAINT FK_AKSJONSPUNKT_3 FOREIGN KEY (aksjonspunkt_status) REFERENCES AKSJONSPUNKT_STATUS;
ALTER TABLE AKSJONSPUNKT ADD CONSTRAINT FK_AKSJONSPUNKT_4 FOREIGN KEY (aksjonspunkt_def) REFERENCES AKSJONSPUNKT_DEF;

DROP TABLE AUTOPUNKT;

DROP TABLE ABSTRAKTPUNKT;


