INSERT INTO LAND_REGION(LANDKODE, REGION, OPPRETTET_AV)
VALUES ('NOR', 'NORDEN', 'VL');

INSERT INTO LAND_REGION(LANDKODE, REGION, OPPRETTET_AV)
VALUES ('SWE', 'NORDEN', 'VL');

INSERT INTO LAND_REGION(LANDKODE, REGION, OPPRETTET_AV)
VALUES ('USA', 'ANNET', 'VL');
