UPDATE AKSJONSPUNKT_DEF SET ALLTID_TOTRINNSBEHANDLING = 'Y' WHERE KODE IN(5005, 5007, 5011, 5013, 5014);
UPDATE AKSJONSPUNKT SET TOTRINNSBEHANDLING = 'Y' WHERE TOTRINNSBEHANDLING = '1';
UPDATE AKSJONSPUNKT SET TOTRINNSBEHANDLING = 'N' WHERE TOTRINNSBEHANDLING = '0';
