ALTER TABLE VILKAR DROP CONSTRAINT FK_VILKAR_5;

ALTER TABLE AVSLAGSARSAK RENAME COLUMN AVSLAG_KODE TO KODE;
ALTER TABLE AVSLAGSARSAK DROP CONSTRAINT PK_AVSLAGSARSAK;
ALTER TABLE AVSLAGSARSAK ADD CONSTRAINT PK_AVSLAGSARSAK PRIMARY KEY (kode);

ALTER TABLE VILKAR ADD CONSTRAINT FK_VILKAR_5 FOREIGN KEY (avslag_kode) REFERENCES AVSLAGSARSAK;

-- Nye avslagskoder for medlemskapsvilkåret:
INSERT INTO AVSLAGSARSAK (KODE, VILKAR_KODE, NAVN) VALUES ('1020', 'FP_VK_2', 'Søker er ikke medlem');
INSERT INTO AVSLAGSARSAK (KODE, VILKAR_KODE, NAVN) VALUES ('1021', 'FP_VK_2', 'Søker er utvandret');
INSERT INTO AVSLAGSARSAK (KODE, VILKAR_KODE, NAVN) VALUES ('1023', 'FP_VK_2', 'Søker har ikke lovlig opphold');
INSERT INTO AVSLAGSARSAK (KODE, VILKAR_KODE, NAVN) VALUES ('1024', 'FP_VK_2', 'Søker har ikke oppholdsrett');
INSERT INTO AVSLAGSARSAK (KODE, VILKAR_KODE, NAVN) VALUES ('1025', 'FP_VK_2', 'Søker er ikke bosatt');
