-- Tabell BEHANDLING_VENT
CREATE TABLE BEHANDLING_VENT (
	id number(19)        NOT NULL,
	behandling_id        NUMBER(19) NOT NULL,
	frist_tid            TIMESTAMP(3) NOT NULL,
	ferdigstilt_av       VARCHAR2(20 CHAR),
	ferdigstilt_tid      TIMESTAMP(3),
  versjon              NUMBER(19) DEFAULT 0 NOT NULL,
  opprettet_av         VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid        TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av            VARCHAR2(20 CHAR),
  endret_tid           TIMESTAMP(3),
	CONSTRAINT PK_BEHANDLING_VENT PRIMARY KEY (ID),
	CONSTRAINT FK_BEHANDLING_VENT_1 FOREIGN KEY ( behandling_id ) REFERENCES behandling ( id )
);

CREATE SEQUENCE SEQ_BEHANDLING_VENT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell ABSTRAKTPUNKT
CREATE TABLE ABSTRAKTPUNKT (
	abstraktpunkt_id          NUMBER(19) NOT NULL,
	abstraktpunkt_type        VARCHAR2(20 CHAR),
	behandling_steg_funnet    VARCHAR2(20 CHAR),
	behandling_resultat_id    NUMBER(19) NOT NULL,
	aksjonspunkt_status       VARCHAR2(7 CHAR) NOT NULL,
	aksjonspunkt_def          VARCHAR2(50 CHAR) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
	CONSTRAINT PK_ABSTRAKTPUNKT PRIMARY KEY (abstraktpunkt_id),
	CONSTRAINT FK_ABSTRAKTPUNKT_1 FOREIGN KEY (behandling_steg_funnet) REFERENCES BEHANDLING_STEG_TYPE,
	CONSTRAINT FK_ABSTRAKTPUNKT_2 FOREIGN KEY (behandling_resultat_id) REFERENCES BEHANDLING_RESULTAT,
	CONSTRAINT FK_ABSTRAKTPUNKT_3 FOREIGN KEY (aksjonspunkt_status) REFERENCES AKSJONSPUNKT_STATUS,
	CONSTRAINT FK_ABSTRAKTPUNKT_4 FOREIGN KEY (aksjonspunkt_def) REFERENCES AKSJONSPUNKT_DEF
);

CREATE SEQUENCE SEQ_ABSTRAKTPUNKT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell AUTOPUNKT
CREATE TABLE AUTOPUNKT (
	autopunkt_id        NUMBER(19)   NOT NULL,
	frist_tid           TIMESTAMP(3) NOT NULL,
	CONSTRAINT PK_AUTOPUNKT PRIMARY KEY (autopunkt_id),
	CONSTRAINT FK_AUTOPUNKT_1 FOREIGN KEY (autopunkt_id) REFERENCES ABSTRAKTPUNKT (abstraktpunkt_id)
);

CREATE SEQUENCE SEQ_AUTOPUNKT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Endring i tabell AKSJONSPUNKT
ALTER TABLE AKSJONSPUNKT DROP CONSTRAINT FK_AKSJONSPUNKT_1;
ALTER TABLE AKSJONSPUNKT DROP CONSTRAINT FK_AKSJONSPUNKT_2;
ALTER TABLE AKSJONSPUNKT DROP CONSTRAINT FK_AKSJONSPUNKT_3;
ALTER TABLE AKSJONSPUNKT DROP CONSTRAINT FK_AKSJONSPUNKT_4;
ALTER TABLE AKSJONSPUNKT DROP (behandling_steg_funnet, behandling_resultat_id, aksjonspunkt_status, aksjonspunkt_def,
  versjon, opprettet_av, opprettet_tid, endret_av, endret_tid);





