INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '874707112', 'Stortinget');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '982110777', 'Stortingets Kontrollutvalg for Etterretnings-, Overvåkings- Og Sikkerhetstjeneste, Eos-utvalget');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '982164176', 'Stortingets Kontrollutvalg for Etterretnings-, Overvåkings- Og Sikkerhetstjeneste, Eos-utvalget');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '971527439', 'Ombudsmannen for Forsvaret');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '974721198', 'Ombudsmannen for Forsvaret');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '974760843', 'Riksrevisjonen');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '974707314', 'Riksrevisjonen');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '974761270', 'Sivilombudsmannen Stortingets Ombudsmann for Forvaltningen');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '974720590', 'Sivilombudsmannen Stortingets Ombudsmann for Forvaltningen');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '914781175', 'Norges Nasjonale Institusjon for Menneskerettigheter Avd Kautokeino');
INSERT INTO ORG_MANUELL_BEHANDLING (id, Virksomhetsnummer, Manuell_beh_arsak) VALUES (SEQ_ORG_MANUELL_BEHANDLING.nextval, '885002862', 'Norges Nasjonale Institusjon for Menneskerettigheter Avd Kautokeino');
