update BEHANDLING_TYPE set NAV_OFFISIELL_KODE = 'ae0043' where KODE = 'BT-001';
update BEHANDLING_TYPE set NAV_OFFISIELL_KODE = 'ae0043' where KODE = 'BT-002';
update BEHANDLING_TYPE set NAV_OFFISIELL_KODE = 'ae0058' where KODE = 'BT-003';
update BEHANDLING_TYPE set NAV_OFFISIELL_KODE = 'ae0028' where KODE = 'BT-004';

