ALTER TABLE UTTAK_AKTIVITET RENAME COLUMN arbforhold_id TO arbeidsforhold_id;

ALTER TABLE UTTAK_AKTIVITET ADD VIRKSOMHET_ID NUMBER(19);
ALTER TABLE UTTAK_AKTIVITET ADD CONSTRAINT FK_UTTAK_AKTIVITET_2 FOREIGN KEY (VIRKSOMHET_ID) REFERENCES VIRKSOMHET(ID);
CREATE INDEX IDX_UTTAK_AKTIVITET_2 ON UTTAK_AKTIVITET (VIRKSOMHET_ID);

UPDATE UTTAK_AKTIVITET SET VIRKSOMHET_ID = (
  SELECT id from virksomhet
  WHERE uttak_aktivitet.ARBFORHOLD_ORGNR IS NOT NULL
  AND virksomhet.orgnr = uttak_aktivitet.ARBFORHOLD_ORGNR
);

ALTER TABLE UTTAK_AKTIVITET DROP COLUMN ARBFORHOLD_ORGNR;

