DELETE FROM VILKAR_TYPE_AVSLAGSARSAK_KOBLE
WHERE AVSLAGSARSAK_KODE = '1011' AND VILKAR_TYPE_KODE = 'FP_VK_1';

DELETE FROM VILKAR_TYPE_AVSLAGSARSAK_KOBLE
WHERE AVSLAGSARSAK_KODE = '1031' AND VILKAR_TYPE_KODE = 'FP_VK_4';

DELETE FROM VILKAR_TYPE_AVSLAGSARSAK_KOBLE
WHERE AVSLAGSARSAK_KODE = '1031' AND VILKAR_TYPE_KODE = 'FP_VK_5';

