ALTER TABLE INNTEKT ADD AKTOER_ID NUMBER(19);

MERGE INTO INNTEKT I
USING (SELECT * FROM PERSONOPPLYSNING) P
ON (I.NAVN = P.NAVN AND I.BEHANDLING_GRUNNLAG_ID = P.BEHANDLING_GRUNNLAG_ID)
WHEN MATCHED THEN UPDATE SET I.AKTOER_ID = P.AKTOER_ID;

ALTER TABLE INNTEKT MODIFY (AKTOER_ID NOT NULL);
ALTER TABLE INNTEKT DROP COLUMN NAVN;
