DECLARE
  CURSOR BEHANDLING_IDER IS
    SELECT
      SEQ_GR_ARBEID_INNTEKT.NEXTVAL      AS GAI_ID,
      SEQ_INNTEKT_ARBEID_YTELSER.NEXTVAL AS IAY_ID,
      SEQ_RELATERTE_YTELSER.NEXTVAL      AS RY_ID,
      B_ID
    FROM (
      SELECT DISTINCT B.ORIGINAL_BEHANDLING_ID AS B_ID
      FROM BEHANDLING_REL_YTELSER BRY INNER JOIN BEHANDLING_GRUNNLAG B ON B.ID = BRY.BEHANDLING_GRUNNLAG_ID
      MINUS
      SELECT DISTINCT B.ORIGINAL_BEHANDLING_ID
      FROM INNTEKT I INNER JOIN BEHANDLING_GRUNNLAG B ON B.ID = I.BEHANDLING_GRUNNLAG_ID);
BEGIN
  FOR LOOP_BE IN BEHANDLING_IDER LOOP
    INSERT INTO GR_ARBEID_INNTEKT (ID, BEHANDLING_ID, INNTEKT_ARBEID_YTELSER_ID)
    VALUES (LOOP_BE.GAI_ID, LOOP_BE.B_ID, LOOP_BE.IAY_ID);

    INSERT INTO INNTEKT_ARBEID_YTELSER (ID, YTELSE_OPPLYSNINGER_ID)
    VALUES (LOOP_BE.IAY_ID, LOOP_BE.RY_ID);

    INSERT INTO RELATERTE_YTELSER (ID, INNTEKT_ARBEID_YTELSER_ID)
    VALUES (LOOP_BE.RY_ID, LOOP_BE.IAY_ID);
  END LOOP;
END;