INSERT INTO RELATERTE_YTELSER (ID, INNTEKT_ARBEID_YTELSER_ID)
  SELECT
    SEQ_RELATERTE_YTELSER.NEXTVAL,
    IAY_ID
  FROM (
    SELECT IAY.ID AS IAY_ID
    FROM INNTEKT_ARBEID_YTELSER IAY
    WHERE IAY.ID IN (
      SELECT IAY.ID
      FROM GR_ARBEID_INNTEKT GAR
        INNER JOIN INNTEKT_ARBEID_YTELSER IAY ON GAR.INNTEKT_ARBEID_YTELSER_ID = IAY.ID
      WHERE GAR.BEHANDLING_ID IN (SELECT DISTINCT B.ORIGINAL_BEHANDLING_ID AS BE_ID
                                  FROM BEHANDLING_REL_YTELSER BRY
                                    INNER JOIN BEHANDLING_GRUNNLAG B
                                      ON B.ID = BRY.BEHANDLING_GRUNNLAG_ID
                                    INNER JOIN INNTEKT I
                                      ON B.ID = I.BEHANDLING_GRUNNLAG_ID)));

MERGE INTO BEHANDLING_REL_YTELSER bry_update
USING (SELECT
         bry.id AS bry_id,
         ry.ID  AS ry_id
       FROM BEHANDLING_REL_YTELSER bry INNER JOIN BEHANDLING_GRUNNLAG bg ON bry
                                                                            .BEHANDLING_GRUNNLAG_ID = bg.ID
         INNER JOIN GR_ARBEID_INNTEKT gri ON gri.BEHANDLING_ID = bg.ORIGINAL_BEHANDLING_ID
         INNER JOIN RELATERTE_YTELSER ry ON ry.INNTEKT_ARBEID_YTELSER_ID = gri.INNTEKT_ARBEID_YTELSER_ID) resultat
ON (bry_update.id = resultat.bry_id)
WHEN MATCHED THEN UPDATE SET bry_update.RELATERTE_YTELSER_ID = resultat.ry_id;