-- flytt dokument_id fra DOKUMENT_DATA til DOKUMENT_FELLES
ALTER TABLE DOKUMENT_FELLES ADD DOKUMENT_ID VARCHAR2(20) NULL;

comment on column DOKUMENT_DATA.DOKUMENT_ID is 'Referanse til dokumentet i Joark.';

ALTER TABLE DOKUMENT_DATA DROP COLUMN DOKUMENT_ID;

-- endre type på DOKUMENT_FELLES.JOURNALPOST_ID
ALTER TABLE DOKUMENT_FELLES DROP COLUMN JOURNALPOST_ID;
ALTER TABLE DOKUMENT_FELLES ADD JOURNALPOST_ID VARCHAR2(20) NULL;
