/*HISTORIKKINNSLAG*/
INSERT INTO HISTORIKKINNSLAG_TYPE(kode, navn) VALUES ('KLAGEBEH_STARTET', 'Klage mottatt');

/*PROSESS-STEG*/
update BEHANDLING_TYPE_STEG_SEKV set SEKVENS_NR = SEKVENS_NR + 1 where behandling_type = 'BT-003';
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-003','REGSØK','1');
