--Comments som er satt til 'MISSING COLUMN COMMENT'

--COMMENT ON TABLE OPPDRAG_KONTROLL IS '';
--COMMENT ON TABLE OKO_OPPDRAG_110 IS '';
--COMMENT ON TABLE OKO_OPPDRAG_ENHET_120 IS '';
--COMMENT ON TABLE OKO_AVSTEMMING_115 IS '';
--COMMENT ON TABLE OKO_OPPDRAG_LINJE_150 IS '';
--COMMENT ON TABLE OKO_ATTESTANT_180 IS '';
--COMMENT ON TABLE BARN IS '';
--COMMENT ON TABLE JOURNALDOKUMENT IS '';
COMMENT ON TABLE BEHANDLING_TYPE_STEG_SEKV IS 'Rekkefølgen av steg for de forskjellige typene behandling';
COMMENT ON TABLE BEREGNING_RESULTAT IS '';
COMMENT ON TABLE PROSESS_TASK_FEILHAND IS 'Kodetabell for feilhåndterings-metoder. For eksempel antall ganger å prøve på nytt og til hvilke tidspunkt';
COMMENT ON TABLE PROSESS_TASK_TYPE IS 'Kodetabell for typer prosesser med beskrivelse og informasjon om hvilken feilhåndteringen som skal benyttes';
COMMENT ON TABLE DOKUMENT_FELLES IS 'Generell informasjon tilhørdende en brevutsendelse';
COMMENT ON TABLE ADOPSJON IS 'Adopsjon inneholder bekreftet informasjon angående en adopsjon.';
--COMMENT ON TABLE DOKUMENT_TYPE_DATA IS '';


--Comments som er NULL

--COMMENT ON TABLE VALGT_OPPLYSNING IS '';
COMMENT ON TABLE PERSONOPPLYSNING IS 'Personopplysninger for aktør';
COMMENT ON TABLE OPPLYSNING_ADRESSE IS 'Informasjon om hva slags adressetp';
COMMENT ON TABLE FAMILIERELASJON IS 'Relasjon mellom personer';
COMMENT ON TABLE BEHANDLING_ARSAK IS 'Årsak for rebehandling';
COMMENT ON TABLE ETTERKONTROLL_LOGG IS 'Logging av etterkontroller';
--COMMENT ON TABLE schema_version_testdata IS '';
--COMMENT ON TABLE schema_version IS '';

-- Column ID
COMMENT ON COLUMN BEHANDLING_ARSAK.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING_STEG_TILSTAND.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_MOTTAKER.ID IS 'Primary Key';
COMMENT ON COLUMN ETTERKONTROLL_LOGG.ID IS 'Primary Key';
COMMENT ON COLUMN FAMILIERELASJON.ID IS 'Primary Key';
COMMENT ON COLUMN INNTEKT.ID IS 'Primary Key';
COMMENT ON COLUMN MEDLEMSKAP.ID IS 'Primary Key';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.ID IS 'Primary Key';
COMMENT ON COLUMN OMSORGSOVERTAKELSE.ID IS 'Primary Key';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.ID IS 'Primary Key';
COMMENT ON COLUMN PERSONOPPLYSNING.ID IS 'Primary Key';
COMMENT ON COLUMN PROSESS_TASK.ID IS 'Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING_METADATA.ID IS 'Primary Key';
COMMENT ON COLUMN VALGT_OPPLYSNING.ID IS 'Primary Key';
COMMENT ON COLUMN VERGE.ID IS 'Primary Key';
COMMENT ON COLUMN VURDER_PAA_NYTT_AARSAK.ID IS 'Primary Key';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.ID IS 'Primary Key';
COMMENT ON COLUMN KODELISTE.ID IS 'Primary Key';
COMMENT ON COLUMN KODELISTE_RELASJON.ID IS 'Primary Key';

-- Column NAVN
COMMENT ON COLUMN AKSJONSPUNKT_DEF.NAVN IS 'Lesbart navn på aksjonspunktdefinisjon';
-- COMMENT ON COLUMN AVSLAGSARSAK.NAVN IS 'Lesbart navn på avslagsårsak';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.NAVN IS 'Lesbart navn på dokumentmaltype';
COMMENT ON COLUMN PERSONOPPLYSNING.NAVN IS 'Personens navn';
COMMENT ON COLUMN PROSESS_TASK_FEILHAND.NAVN IS 'Lesbart navn på type feilhåndtering brukt i prosesstask';
COMMENT ON COLUMN PROSESS_TASK_TYPE.NAVN IS 'Lesbart navn på prosesstasktype';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT_TYPE.NAVN IS 'Lesbart navn på dokumenttype';
COMMENT ON COLUMN SAKSOPPLYSNING_KILDE.NAVN IS 'Lesbart navn på kilde til saksopplysning';
COMMENT ON COLUMN SAKSOPPLYSNING_TYPE.NAVN IS 'Lesbart navn på saksopplysningstype';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.NAVN IS 'Navn på annen forelder i søknad';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.NAVN IS 'Lesbart navn på definisjon av vurderingspunkt';
COMMENT ON COLUMN VURDER_ARSAK.NAVN IS 'Lesbart navn på årsak for revurdering';

-- BEHANDLING_GRUNNLAG_ID
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN DOKUMENT_MOTTAKER.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN INNTEKT.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN MEDLEMSKAP.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN OMSORGSOVERTAKELSE.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN PERSONOPPLYSNING.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';

-- BEHANDLING_ID
COMMENT ON COLUMN BEHANDLING_ARSAK.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN ETTERKONTROLL_LOGG.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.BEHANDLING_ID IS 'FK: BEHANDLING';

COMMENT ON COLUMN AKSJONSPUNKT.BEHANDLING_RESULTAT_ID IS 'FK: BEHANDLING_RESULTAT';
COMMENT ON COLUMN HISTORIKKINNSLAG.FAGSAK_ID IS 'FK: FAGSAK';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.VERDI IS 'Verdi';

COMMENT ON COLUMN FAGSAK.SAKSNUMMER IS 'Saksnummer i vedtaksløsningen';
COMMENT ON COLUMN OPPDRAG_KONTROLL.SAKSNUMMER IS 'Saksnummer i GSAK';

COMMENT ON COLUMN AKSJONSPUNKT_DEF.VILKAR_TYPE IS 'FK: VILKAR_TYPE';
COMMENT ON COLUMN OMSORGSOVERTAKELSE.VILKAR_TYPE IS 'FK: VILKAR_TYPE';

-- BRUKER_KJOENN
COMMENT ON COLUMN HISTORIKKINNSLAG.BRUKER_KJOENN IS 'FK: BRUKER_KJOENN';
COMMENT ON COLUMN VALGT_OPPLYSNING.BRUKER_KJOENN IS 'FK: BRUKER_KJOENN';

COMMENT ON COLUMN BRUKER.SPRAK_KODE IS 'FK: SPRAAK_KODE';

COMMENT ON COLUMN MOTTATTE_DOKUMENT.ELEKTRONISK_REGISTRERT IS 'Elektronisk registrert søknad';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.MOTTATT_DATO IS 'Mottatt dato';

-- BARN
COMMENT ON COLUMN BARN.AKTOER_ID IS 'Aktør ID';
COMMENT ON COLUMN BARN.NORSK_IDENT IS 'Fødselsnummer eller D-nummer.';
COMMENT ON COLUMN BARN.FOEDSEL_DATO IS 'Fødselsdatoen til barnet.';

COMMENT ON COLUMN VURDER_ARSAK.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VURDER_ARSAK.BESKRIVELSE IS 'Beskrivelse på årsak for revurdering';

COMMENT ON COLUMN KONFIG_VERDI.KONFIG_GRUPPE IS 'Angir gruppe en konfigurerbar verdi kode tilhører (hvis noen - kan også spesifiseres som INGEN).';

-- SAKSOPPLYSNING_METADATA
COMMENT ON COLUMN SAKSOPPLYSNING_METADATA.TAG IS 'Navn på metadata';
COMMENT ON COLUMN SAKSOPPLYSNING_METADATA.VALUE IS 'Verdi på metadata';

-- PERSONOPPLYSNING
COMMENT ON COLUMN PERSONOPPLYSNING.AKTOER_ID IS 'Aktør ID';
COMMENT ON COLUMN PERSONOPPLYSNING.REGION IS 'Geografisk område';
COMMENT ON COLUMN PERSONOPPLYSNING.PERSONSTATUS_TYPE IS 'Fremmednøkkel til personstatustype';
COMMENT ON COLUMN PERSONOPPLYSNING.OVERSTYRT_PERSONSTATUS_TYPE IS 'Fremmednøkkel til personens statsborgerskap. Satt dersom personstatustype er overstyrt.';
COMMENT ON COLUMN PERSONOPPLYSNING.BRUKER_KJOENN IS 'Fremmednøkkel til personens kjønn';
COMMENT ON COLUMN PERSONOPPLYSNING.STATSBORGERSKAP IS 'Fremmedøkkel til personens statsborgerskap';
COMMENT ON COLUMN PERSONOPPLYSNING.SIVILSTAND_TYPE IS 'Fremmednøkkel til sivilstandstype';
COMMENT ON COLUMN PERSONOPPLYSNING.DISKRESJONSKODE IS 'Fremmednøkkel til diskresjonskode';
COMMENT ON COLUMN PERSONOPPLYSNING.FOEDSELSDATO IS 'Fødselsdatoen til personen';
COMMENT ON COLUMN PERSONOPPLYSNING.DOEDSDATO IS 'Dødsdato til personen';
COMMENT ON COLUMN PERSONOPPLYSNING.OPPLYSNINGSKILDE IS 'Fremmednøkkel til opplysningskilde';
COMMENT ON COLUMN PERSONOPPLYSNING.VALGT_OPPLYSNING_ID IS 'FK: VALGT_OPPLYSNING. Settes til initielle verdier fra TPS og senere til det saksbehandler har valgt ved endringer.';
COMMENT ON COLUMN PERSONOPPLYSNING.FORRIGE_TPS_OPPLYSNING_ID IS 'FK: VALGT_OPPLYSNING. Settes til gamle verdier dersom det kommer endringer i TPS-verdiene.';
--COMMENT ON COLUMN PERSONOPPLYSNING.NUMMER IS '';

-- DOKUMENT_FELLES
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_ID IS 'Dokumentets Dokument ID i JOARK';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS 'Saksnummer i GSAK';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_NAVN IS 'Navn på adressat';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATA_ID IS 'FK: DOKUMENT_DATA';
COMMENT ON COLUMN DOKUMENT_FELLES.JOURNALPOST_ID IS 'Journalpostens ID i JOARK';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_GEO_ENHET IS 'Navn på signerende beslutters geografiske enhet';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ID IS 'Fødselsnummer eller D-nummer til dokumentmottaker';
COMMENT ON COLUMN DOKUMENT_FELLES.NAVN_AVSENDER_ENHET IS 'Navn på NAV-enhet som har sendt dokumentet';
COMMENT ON COLUMN DOKUMENT_FELLES.NUMMER_AVSENDER_ENHET IS 'ID til NAV-enhet som har sendt dokumentet';
COMMENT ON COLUMN DOKUMENT_FELLES.KONTAKT_TLF IS 'Dokumentmottakers kontaktnummer';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS 'Dato dokumentet er produsert';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_SAKSBEHANDLER_NAVN IS 'Signerende saksbehandlers navn';
COMMENT ON COLUMN DOKUMENT_FELLES.AUTOMATISK_BEHANDLET IS 'Er saken blitt automatisk behandlet?';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_ID IS 'Fødselsnummer eller D-nummer til bruker saken gjelder';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_NAVN IS 'Navn på bruker saken gjelder';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_NAVN IS 'Signerende beslutters navn';

-- VURDER_PAA_NYTT_AARSAK
COMMENT ON COLUMN VURDER_PAA_NYTT_AARSAK.AARSAK_TYPE_ID IS 'FK: VURDER_PAA_NYTT_AARSAK_TYPE';
COMMENT ON COLUMN VURDER_PAA_NYTT_AARSAK.AKSJONSPUNKT_ID IS 'FK: AKSJONSPUNKT';

COMMENT ON COLUMN BEHANDLING_GRUNNLAG.OPPLYSNINGER_OPPDATERT_TID IS 'Sist tidspunkt for maskinell oppdatering av registeropplysninger';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.MEDL_ID IS 'Unik ID i MEDL for perioden';

-- ADOPSJON_BARN
COMMENT ON COLUMN ADOPSJON_BARN.SOKNAD_ADOPSJON_BARN_ID IS 'FK: SOEKNAD_ADOPSJON_BARN';

-- AKSJONSPUNKT
COMMENT ON COLUMN AKSJONSPUNKT.TOTRINN_BEHANDLING_GODKJENT IS 'Beslutter har godkjent totrinnsbehandlingen';
COMMENT ON COLUMN AKSJONSPUNKT.BEHANDLING_STEG_FUNNET IS 'Hvilket steg ble dette aksjonspunktet funnet i?';
COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_STATUS IS 'FK: AKSJONSPUNKT_STATUS';
COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_DEF IS 'FK: AKSJONSPUNKT_DEF';
COMMENT ON COLUMN AKSJONSPUNKT.FRIST_TID IS 'Behandling blir automatisk gjenopptatt etter dette tidspunktet';

-- AKSJONSPUNKT_DEF
COMMENT ON COLUMN AKSJONSPUNKT_DEF.AKSJONSPUNKT_TYPE IS 'FK: AKSJONSPUNKT_TYPE';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.FRIST_PERIODE IS 'Lengde på fristperioden for behandling av aksjonspunkt med denne definisjonen';

-- BEHANDLING
COMMENT ON COLUMN BEHANDLING.BEHANDLENDE_ENHET IS 'NAV-enhet som behandler behandlingen';
COMMENT ON COLUMN BEHANDLING.ANSVARLIG_BESLUTTER IS 'Beslutter som har fattet vedtaket';

COMMENT ON COLUMN DOKUMENT_DATA.BESTILT_TID IS 'Tidspunkt dokumentet ble bestilt';
COMMENT ON COLUMN BEHANDLING_GRUNNLAG.OPPLYSNINGER_OPPDATERT_TID IS 'Tidspunkt opplysningene i grunnlaget sist ble oppdatert';
COMMENT ON COLUMN MEDLEMSKAP.ER_EOS_BORGER IS 'Er personen EØS-borger?';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.XML_PAYLOAD IS 'Strukturert informasjon fra det mottatte dokumentet';

-- KL% kolonner
COMMENT ON COLUMN AKSJONSPUNKT.KL_AKSJONSPUNKT_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.KL_VILKAR_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.KL_AKSJONSPUNKT_KATEGORI IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.KL_AKSJONSPUNKT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
-- COMMENT ON COLUMN AVSLAGSARSAK.KL_VILKAR_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING.KL_BEHANDLING_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING.KL_BEHANDLING_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_GRUNNLAG.KL_RELATERTE_YTELSER_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_RESULTAT IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_TILSTAND IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_SAKSTYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_BEH_TEMA IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_RELATERT_YTELSE_TEMA IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_RESULTAT.KL_BEHANDLING_RESULTAT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_STEG_TILSTAND.KL_BEHANDLING_STEG_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.KL_BEHANDLING_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_VEDTAK.KL_IVERKSETTING_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_VEDTAK.KL_VEDTAK_RESULTAT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BRUKER.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BRUKER.KL_SPRAAK_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_FELLES.KL_SPRAAK_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KL_DOKUMENT_MAL_RESTRIKSJON IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAGSAK.KL_FAGSAK_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAGSAK.KL_BRUKER_ROLLE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAGSAK_RELASJON.KL_FAGSAK_YTELSE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAGSAK_RELASJON.KL_FAGSAK_ARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAMILIERELASJON.KL_RELASJONSROLLE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG.KL_HISTORIKK_AKTOER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN INNGANGSVILKAR_RESULTAT.KL_VILKAR_RESULTAT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.KL_KLAGE_VURDERT_AV IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.KL_KLAGEVURDERING IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.KL_KLAGE_AVVIST_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.KL_KLAGE_MEDHOLD_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KL_KONFIG_VERDI_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KONFIG_VERDI_KODE.KL_KONFIG_VERDI_GRUPPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN LAGRET_VEDTAK.KL_LAGRET_VEDTAK_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN LAND_REGION.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN LAND_REGION.KL_REGION IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MEDLEMSKAP.KL_MEDLEMSKAP_MANUELL_VURD IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KL_MEDLEMSKAP_DEKNING IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KL_MEDLEMSKAP_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KL_MEDLEMSKAP_KILDE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.KL_DOKUMENT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OMSORGSOVERTAKELSE.KL_OMSORGSOVERTAKELSE_VILKAR IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.KL_OPPGAVE_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.KL_OPPLYSNING_ADRESSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_REGION IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_PERSONSTATUS_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_DISKRESJONSKODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_OPPLYSNINGSKILDE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.KL_SIVILSTAND_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN SATS.KL_SATS_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN SOEKNAD.KL_FAR_SOEKER_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.KL_SOEKNAD_ANNEN_PART IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.KL_INNSENDINGSVALG IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN TILKNYTNING_HJEMLAND.KL_PERIODE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTLANDSOPPHOLD.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VALGT_OPPLYSNING.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VALGT_OPPLYSNING.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VALGT_OPPLYSNING.KL_PERSONSTATUS_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VERGE.KL_VERGE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR.KL_VILKAR_UTFALL_MERKNAD IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR.KL_VILKAR_UTFALL_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR.KL_VILKAR_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR.REGEL_EVALUERING IS 'JSON struktur som beskriver regel-evalueringen.';
COMMENT ON COLUMN VILKAR_TYPE_AVSLAGSARSAK_KOBLE.VILKAR_TYPE_KODE IS 'FK: KODELISTE';
COMMENT ON COLUMN VILKAR_TYPE_AVSLAGSARSAK_KOBLE.AVSLAGSARSAK_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR_TYPE_AVSLAGSARSAK_KOBLE.KL_VILKAR_TYPE IS 'FK: KODELISTE';
COMMENT ON COLUMN VILKAR_TYPE_AVSLAGSARSAK_KOBLE.KL_AVSLAGSARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR.KL_AVSLAGSARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_RESULTAT.KL_AVSLAGSARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

COMMENT ON COLUMN SOEKNAD.NAVN_PAA_TERMINBEKREFTELSE IS 'Legens navn på terminbekreftelsen';
COMMENT ON COLUMN SOEKNAD.BEGRUNNELSE_FOR_SEN_INNSENDING IS 'Begrunnelse for sen innsending';

-- OKO_%
COMMENT ON COLUMN OKO_ATTESTANT_180.ATTESTANT_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_AVSTEMMING_115.KODE_KOMPONENT IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_AVSTEMMING_115.NOKKEL_AVSTEMMING IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_AVSTEMMING_115.TIDSPNKT_MELDING IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_AKSJON IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_ENDRING IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_FAGOMRADE IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.FAGSYSTEM_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.UTBET_FREKVENS IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAG_GJELDER_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_110.SAKSBEH_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.TYPE_ENHET IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.ENHET IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.DATO_ENHET_FOM IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_ENDRING_LINJE IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_STATUS_LINJE IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_STATUS_FOM IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.VEDTAK_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DELYTELSE_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_FOM IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_TOM IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_KLASSIFIK IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SATS IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.FRADRAG_TILLEGG IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.TYPE_SATS IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.BRUK_KJORE_PLAN IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SAKSBEH_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.UTBETALES_TIL_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_FAGSYSTEM_ID IS 'Felt i oppdragsmelding';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_DELYTELSE_ID IS 'Felt i oppdragsmelding';
