update BEHANDLING_STEG_TYPE set BEHANDLING_STATUS_DEF = 'UTRED' where KODE='FORVEDSTEG';

update BEHANDLING set BEHANDLING_STATUS = 'UTRED' where BEHANDLING_STATUS = 'FORVED';

delete from KODELISTE where KODEVERK = 'BEHANDLING_STATUS' and KODE ='FORVED';
