-- Legg til felt for aktørId
ALTER TABLE MOTTATTE_DOKUMENT ADD (FAGSAK_ID NUMBER(19));

COMMENT ON COLUMN MOTTATTE_DOKUMENT.FAGSAK_ID IS 'FK: FAGSAKORIGINAL_BEHANDLING_ID';

update MOTTATTE_DOKUMENT m set m.FAGSAK_ID = (select b.fagsak_id from BEHANDLING b where b.id = m.BEHANDLING_ID);

ALTER TABLE MOTTATTE_DOKUMENT MODIFY FAGSAK_ID NOT NULL;

ALTER TABLE MOTTATTE_DOKUMENT MODIFY BEHANDLING_ID NUMBER(19) NULL;
