ALTER TABLE JOURNALDOKUMENT RENAME TO JOURNALPOST;
ALTER TABLE JOURNALPOST RENAME CONSTRAINT PK_JOURNALDOKUMENT TO PK_JOURNALPOST;
ALTER TABLE JOURNALPOST RENAME CONSTRAINT FK_JOURNALDOKUMENT TO FK_JOURNALPOST;
ALTER INDEX PK_JOURNALDOKUMENT RENAME TO PK_JOURNALPOST;
ALTER INDEX IDX_JOURNALDOKUMENT_1 RENAME TO IDX_JOURNALPOST_1;
ALTER INDEX UIDX_JOURNALDOKUMENT_1 RENAME TO UIDX_JOURNALPOST_1;
RENAME SEQ_JOURNALDOKUMENT TO SEQ_JOURNALPOST;
COMMENT ON TABLE JOURNALPOST IS 'Journalposter som er blitt knyttet til saken';
COMMENT ON COLUMN JOURNALPOST.JOURNALPOST_ID IS 'Journalpostens ID i JOARK';
