-- Tabell SOEKNAD_GJELDER_TYPE
CREATE TABLE SOEKNAD_GJELDER_TYPE (
  kode            VARCHAR2(20 CHAR) NOT NULL,
  navn            VARCHAR2(40 CHAR) NOT NULL,
  beskrivelse     VARCHAR2(4000 CHAR),
  opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 CHAR),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_SOEKNAD_GJELDER_TYPE PRIMARY KEY (KODE)
);
INSERT INTO SOEKNAD_GJELDER_TYPE (kode, navn) VALUES ('MORA', 'Søker som mor');
INSERT INTO SOEKNAD_GJELDER_TYPE (kode, navn) VALUES ('FARA', 'Søker som far');

-- Tabell SOEKNAD_TYPE
CREATE TABLE SOEKNAD_TYPE (
  kode            VARCHAR2(20 CHAR) NOT NULL,
  navn            VARCHAR2(40 CHAR) NOT NULL,
  beskrivelse     VARCHAR2(4000 CHAR),
  opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 CHAR),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_SOEKNAD_TYPE PRIMARY KEY (kode)
);
INSERT INTO SOEKNAD_TYPE (kode, navn) VALUES ('ST-001', 'Fødsel');
INSERT INTO SOEKNAD_TYPE (kode, navn) VALUES ('ST-002', 'Adopsjon');

-- Tabell FAR_SOEKER_TYPE
CREATE TABLE FAR_SOEKER_TYPE (
  kode            VARCHAR2(20 CHAR) NOT NULL,
  navn            VARCHAR2(40 CHAR) NOT NULL,
  beskrivelse     VARCHAR2(4000 CHAR),
  opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 CHAR),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_FAR_SOEKER_TYPE PRIMARY KEY (kode)
);
INSERT INTO FAR_SOEKER_TYPE (kode, navn) VALUES ('ADOPTERER_ALENE', 'Adopterer barnet eller barna alene');
INSERT INTO FAR_SOEKER_TYPE (kode, navn) VALUES ('ANDRE_FORELDER_DØD', 'Den andre forelderen er død');
INSERT INTO FAR_SOEKER_TYPE (kode, navn) VALUES ('OVERTATT_OMSORG', 'Overtatt omsorg < 56 uker');


-- Tabell SOEKNAD
ALTER TABLE SOEKNAD ADD SOEKNAD_GJELDER VARCHAR(20) DEFAULT 'MORA' NOT NULL;
ALTER TABLE SOEKNAD ADD SOEKNAD_TYPE VARCHAR(20) DEFAULT 'ST-001' NOT NULL;
ALTER TABLE SOEKNAD ADD FAR_SOEKER_TYPE VARCHAR(20) NULL;
ALTER TABLE SOEKNAD ADD ADOP_OMSORGOVER_DATO DATE NULL;

ALTER TABLE SOEKNAD ADD CONSTRAINT FK_SOEKNAD_2 FOREIGN KEY ( soeknad_gjelder ) REFERENCES SOEKNAD_GJELDER_TYPE ( kode );
ALTER TABLE SOEKNAD ADD CONSTRAINT FK_SOEKNAD_3 FOREIGN KEY ( soeknad_type ) REFERENCES SOEKNAD_TYPE ( kode );
ALTER TABLE SOEKNAD ADD CONSTRAINT FK_SOEKNAD_4 FOREIGN KEY ( far_soeker_type ) REFERENCES FAR_SOEKER_TYPE ( kode );


-- Tabell SOEKNAD_ADOPSJON_BARN
CREATE TABLE SOEKNAD_ADOPSJON_BARN (
  id              NUMBER(19) NOT NULL,
  foedselsdato    DATE NOT NULL,
  soeknad_id      NUMBER(19) NOT NULL,
  versjon         NUMBER(19) DEFAULT 0 NOT NULL,
  opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 CHAR),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_SOEKNAD_ADOPSJON_BARN PRIMARY KEY ( id )
);
ALTER TABLE SOEKNAD_ADOPSJON_BARN ADD CONSTRAINT FK_SOEKNAD_ADOPSJON_BARN_1 FOREIGN KEY ( soeknad_id ) REFERENCES SOEKNAD ( id );
CREATE INDEX IDX_SOEKNAD_ADOP_BARN_1 ON SOEKNAD_ADOPSJON_BARN (soeknad_id);
CREATE SEQUENCE SEQ_SOEKNAD_ADOPSJON_BARN MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell ADOPSJON
CREATE TABLE ADOPSJON (
  id                        NUMBER(19) NOT NULL,
  omsorgsovertakelse_dato   DATE,
  ektefelles_barn           VARCHAR2(1 CHAR),
  adopterer_alene           VARCHAR2(1 CHAR),
  behandling_grunnlag_id    NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_ADOPSJON PRIMARY KEY ( id )
);
ALTER TABLE ADOPSJON ADD CONSTRAINT FK_ADOPSJON_1 FOREIGN KEY ( behandling_grunnlag_id ) REFERENCES BEHANDLING_GRUNNLAG ( id );
CREATE SEQUENCE SEQ_ADOPSJON MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_ADOPSJON_1 ON ADOPSJON (behandling_grunnlag_id);

-- Tabell ADOPSJON_BARN
CREATE TABLE ADOPSJON_BARN (
  id              NUMBER(19) NOT NULL,
  foedselsdato    DATE NOT NULL,
  adopsjon_id     NUMBER(19) NOT NULL,
  soknad_adopsjon_barn_id NUMBER(19) NOT NULL,
  versjon         NUMBER(19) DEFAULT 0 NOT NULL,
  opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 CHAR),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_ADOPSJON_BARN PRIMARY KEY ( id )
);
ALTER TABLE ADOPSJON_BARN ADD CONSTRAINT FK_ADOPSJON_BARN_1 FOREIGN KEY ( adopsjon_id ) REFERENCES ADOPSJON ( id );
CREATE SEQUENCE SEQ_ADOPSJON_BARN MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;