-- Tabell SOEKNAD
ALTER TABLE SOEKNAD ADD omsorg_omsorgover_dato DATE NULL;
ALTER TABLE SOEKNAD ADD elektronisk_registrert VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
ALTER TABLE SOEKNAD ADD mottatt_dato DATE NULL;

-- Tabell OMSORGSOVERTAKELSE UTGÅR

-- Tabell VILKAR_TIL_VURDERING UTGÅR



