CREATE TABLE AKTOER_NORSK_IDENT_MAP (
    id              NUMBER(19) NOT NULL,
    aktoer_id       NUMBER(19) NOT NULL,
    norsk_ident     VARCHAR2(50 CHAR) NOT NULL,
    versjon         NUMBER(19) DEFAULT 0 NOT NULL,
    opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av       VARCHAR2(20 CHAR),
    endret_tid      TIMESTAMP(3),
    CONSTRAINT PK_AKTOER_NORSK_IDENT_MAP PRIMARY KEY (id)
);

CREATE INDEX IDX_AKTOER_NORSK_IDENT_MAP_1 ON AKTOER_NORSK_IDENT_MAP (aktoer_id);
CREATE INDEX IDX_AKTOER_NORSK_IDENT_MAP_2 ON AKTOER_NORSK_IDENT_MAP (norsk_ident);

ALTER TABLE AKTOER_NORSK_IDENT_MAP ADD CONSTRAINT UIDX_AKTOER_NORSK_IDENT_MAP_1 UNIQUE ( aktoer_id,norsk_ident );

CREATE SEQUENCE SEQ_AKTOER_NORSK_IDENT_MAP MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
