-- Tabell
CREATE TABLE FAGSAK_STATUS (
    kode   VARCHAR2(7 CHAR) NOT NULL,
    navn VARCHAR2(40 CHAR) NOT NULL,
    beskrivelse varchar2(4000 CHAR),
    opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av       VARCHAR2(20 CHAR),
    endret_tid      TIMESTAMP(3),
    CONSTRAINT PK_FAGSAK_STATUS PRIMARY KEY (kode)
);

INSERT INTO FAGSAK_STATUS (kode, navn) VALUES ('OPPR', 'Opprettet');
INSERT INTO FAGSAK_STATUS (kode, navn) VALUES ('UBEH', 'Under behandling');
INSERT INTO FAGSAK_STATUS (kode, navn) VALUES ('LOP', 'Løpende');
INSERT INTO FAGSAK_STATUS (kode, navn) VALUES ('AVSLU', 'Avsluttet');


-- Tabell
CREATE TABLE FAGSAK (
    id                     NUMBER(19, 0) NOT NULL,
    saksnummer             NUMBER(19, 0),
    fagsak_status VARCHAR2(7 char) NOT NULL,
    fagsak_relasjon_id      NUMBER(19) NOT NULL,
    bruker_id     NUMBER(19) NOT NULL,
    bruker_rolle varchar2(7 char) NOT NULL,
    versjon              NUMBER(19) DEFAULT 0 NOT NULL,
    opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av       VARCHAR2(20 CHAR),
    endret_tid      TIMESTAMP(3),
    CONSTRAINT PK_FAGSAK PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UIDX_FAGSAK_1 ON FAGSAK (SAKSNUMMER);

CREATE INDEX IDX_FAGSAK_1 ON FAGSAK(fagsak_status);
CREATE INDEX IDX_FAGSAK_2 ON FAGSAK(bruker_rolle);
CREATE INDEX IDX_FAGSAK_3 ON FAGSAK(bruker_id);
CREATE INDEX IDX_FAGSAK_4 ON FAGSAK(fagsak_relasjon_id);

ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_1 FOREIGN KEY (fagsak_relasjon_id) REFERENCES FAGSAK_RELASJON;
ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_2 FOREIGN KEY (fagsak_status) REFERENCES FAGSAK_STATUS;
ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_3 FOREIGN KEY (bruker_id) REFERENCES BRUKER;
ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_4 FOREIGN KEY (bruker_rolle) REFERENCES BRUKER_ROLLE_TYPE;

CREATE SEQUENCE SEQ_FAGSAK MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell
CREATE TABLE JOURNALDOKUMENT (
  id                NUMBER(19) NOT NULL,
  journalpost_id    NUMBER(19) NOT NULL,
  fagsak_id         NUMBER(19) NOT NULL,
  opprettet_av      VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid     TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av         VARCHAR2(20 CHAR),
  endret_tid        TIMESTAMP(3),
  CONSTRAINT  PK_JOURNALDOKUMENT PRIMARY KEY (id)
);
ALTER TABLE JOURNALDOKUMENT ADD CONSTRAINT FK_JOURNALDOKUMENT FOREIGN KEY (fagsak_id) REFERENCES fagsak (id);
CREATE SEQUENCE SEQ_JOURNALDOKUMENT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE UNIQUE INDEX UIDX_JOURNALDOKUMENT_1 ON JOURNALDOKUMENT (journalpost_id);
CREATE INDEX IDX_JOURNALDOKUMENT_1 ON JOURNALDOKUMENT(fagsak_id);
