-- fikser
delete from KODELISTE_RELASJON where KODE1 = 'ARBEID' AND KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';
delete from KODELISTE_RELASJON where KODE1 = 'MILITÆR_ELLER_SIVILTJENESTE' AND KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';

update KODELISTE set kode = 'FRILANSER_OPPDRAGSTAKER' where OFFISIELL_KODE = 'frilanserOppdragstakerHonorarPersonerMm' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'FORENKLET_OPPGJOERSORDNING' where OFFISIELL_KODE = 'forenkletOppgjoersordning' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'ORDINAERT_ARBEIDSFORHOLD' where OFFISIELL_KODE = 'ordinaertArbeidsforhold' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'MARITIMT_ARBEIDSFORHOLD' where OFFISIELL_KODE = 'maritimtArbeidsforhold' AND KODEVERK = 'ARBEID_TYPE';

update YRKESAKTIVITET set ARBEID_TYPE = 'FRILANSER_OPPDRAGSTAKER' where ARBEID_TYPE = 'frilanserOppdragstakerHonorarPersonerMm';
update YRKESAKTIVITET set ARBEID_TYPE = 'FORENKLET_OPPGJOERSORDNING' where ARBEID_TYPE = 'forenkletOppgjoersordning';
update YRKESAKTIVITET set ARBEID_TYPE = 'ORDINAERT_ARBEIDSFORHOLD' where ARBEID_TYPE = 'ordinaertArbeidsforhold';
update YRKESAKTIVITET set ARBEID_TYPE = 'MARITIMT_ARBEIDSFORHOLD' where ARBEID_TYPE = 'maritimtArbeidsforhold';
update YRKESAKTIVITET set ARBEID_TYPE = 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD' where ARBEID_TYPE = 'pensjonOgAndreTyperYtelserUtenAnsettelsesforhold';
ALTER TABLE YRKESAKTIVITET ADD CONSTRAINT FK_YRKESAKTIVITET_2 FOREIGN KEY (ARBEID_TYPE_KL, ARBEID_TYPE) REFERENCES KODELISTE (kodeverk, kode);

update KODELISTE set kode = 'MILITAER_ELLER_SIVILTJENESTE' where kode = 'MILITÆR_ELLER_SIVILTJENESTE' and KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'MILITAER_ELLER_SIVILTJENESTE' where kode = 'MILITÆR_ELLER_SIVILTJENESTE' and KODEVERK = 'OPPTJENING_AKTIVITET_TYPE';
update KODELISTE set kode = 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD' where OFFISIELL_KODE = 'pensjonOgAndreTyperYtelserUtenAnsettelsesforhold' and KODEVERK = 'ARBEID_TYPE';

INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'OPPTJENING_AKTIVITET_TYPE', 'ARBEID', 'ARBEID_TYPE', 'ORDINAERT_ARBEIDSFORHOLD', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'OPPTJENING_AKTIVITET_TYPE', 'MILITAER_ELLER_SIVILTJENESTE', 'ARBEID_TYPE', 'MILITAER_ELLER_SIVILTJENESTE', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));

INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'RELATERT_YTELSE_TYPE', 'SYKEPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'SYKEPENGER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'RELATERT_YTELSE_TYPE', 'FORELDREPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'FORELDREPENGER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'RELATERT_YTELSE_TYPE', 'ARBEIDSAVKLARINGSPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'AAP', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'RELATERT_YTELSE_TYPE', 'DAGPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'DAGPENGER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'RELATERT_YTELSE_TYPE', 'SVANGERSKAPSPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'SVANGERSKAPSPENGER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));

INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'ORDINAERT_ARBEIDSFORHOLD', 'OPPTJENING_AKTIVITET_TYPE', 'ARBEID', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'FORENKLET_OPPGJOERSORDNING', 'OPPTJENING_AKTIVITET_TYPE', 'ARBEID', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'MARITIMT_ARBEIDSFORHOLD', 'OPPTJENING_AKTIVITET_TYPE', 'ARBEID', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'MILITAER_ELLER_SIVILTJENESTE', 'OPPTJENING_AKTIVITET_TYPE', 'MILITAER_ELLER_SIVILTJENESTE', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'SELVNAER', 'OPPTJENING_AKTIVITET_TYPE', 'ARBEID', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'FRILANSER_OPPDRAGSTAKER', 'OPPTJENING_AKTIVITET_TYPE', 'FRILANS', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));

INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ANNEN_OPPTJENING_TYPE', 'MILITAER_SIVIL_TJENESTE', 'OPPTJENING_AKTIVITET_TYPE', 'MILITAER_ELLER_SIVILTJENESTE', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ANNEN_OPPTJENING_TYPE', 'VARTPENGER', 'OPPTJENING_AKTIVITET_TYPE', 'VARTPENGER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));

INSERT INTO KODELISTE(ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, BESKRIVELSE)
VALUES (SEQ_KODELISTE.nextval, 'OPPTJENING_AKTIVITET_TYPE', 'UTDANNINGSPERMISJON', 'UTDANNINGSPERMISJON', 'Utdanningspermisjon', 'Kode for utdanningspermisjon');
