ALTER TABLE GR_YTELSES_FORDELING
  ADD (perioder_utenomsorg_id NUMBER(19), perioder_aleneomsorg_id NUMBER(19));

-- Opprett tabeller
CREATE TABLE PERIODER_UTEN_OMSORG (
  id            NUMBER(19)                        NOT NULL,
  versjon       NUMBER(19) DEFAULT 0              NOT NULL,
  opprettet_av  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av     VARCHAR2(20 CHAR),
  endret_tid    TIMESTAMP(3),
  CONSTRAINT PK_PERIODER_UTEN_OMSORG PRIMARY KEY (id)
);

-- Opprett tabeller
CREATE TABLE PERIODER_ALENEOMSORG (
  id            NUMBER(19)                        NOT NULL,
  versjon       NUMBER(19) DEFAULT 0              NOT NULL,
  opprettet_av  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av     VARCHAR2(20 CHAR),
  endret_tid    TIMESTAMP(3),
  CONSTRAINT PK_PERIODER_ALENEOMSORG PRIMARY KEY (id)
);

ALTER TABLE GR_YTELSES_FORDELING
  ADD CONSTRAINT FK_GR_YTELSES_FORDELING_5 FOREIGN KEY (perioder_utenomsorg_id) REFERENCES PERIODER_UTEN_OMSORG;
ALTER TABLE GR_YTELSES_FORDELING
  ADD CONSTRAINT FK_GR_YTELSES_FORDELING_6 FOREIGN KEY (perioder_aleneomsorg_id) REFERENCES PERIODER_ALENEOMSORG;

CREATE SEQUENCE SEQ_PERIODER_UTEN_OMSORG
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_PERIODER_ALENEOMSORG
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE TABLE PERIODE_UTEN_OMSORG (
  id            NUMBER(19)                        NOT NULL,
  perioder_id   NUMBER(19)                        NOT NULL,
  fom           DATE                              NOT NULL,
  tom           DATE                              NOT NULL,
  opprettet_av  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av     VARCHAR2(20 CHAR),
  endret_tid    TIMESTAMP(3),
  CONSTRAINT PK_OMSORGSPERIODE PRIMARY KEY (id),
  CONSTRAINT FK_OMSORGSPERIODE_1 FOREIGN KEY (perioder_id) REFERENCES PERIODER_UTEN_OMSORG
);

CREATE SEQUENCE SEQ_PERIODE_UTEN_OMSORG
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE TABLE PERIODE_ALENEOMSORG (
  id            NUMBER(19)                        NOT NULL,
  perioder_id   NUMBER(19)                        NOT NULL,
  fom           DATE                              NOT NULL,
  tom           DATE                              NOT NULL,
  opprettet_av  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av     VARCHAR2(20 CHAR),
  endret_tid    TIMESTAMP(3),
  CONSTRAINT PK_PERIODE_ALENEOMSORG PRIMARY KEY (id),
  CONSTRAINT FK_PERIODE_ALENEOMSORG_1 FOREIGN KEY (perioder_id) REFERENCES PERIODER_ALENEOMSORG
);

CREATE SEQUENCE SEQ_PERIODE_ALENEOMSORG
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;
