-- Ny VedtakResultatType for Innsyn
UPDATE KODELISTE SET  OFFISIELL_KODE = 'F' WHERE KODE = '14DLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';

UPDATE KODELISTE SET  OFFISIELL_KODE = 'M' WHERE KODE = 'MNDLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';

UPDATE KODELISTE SET  OFFISIELL_KODE = 'Å' WHERE KODE = 'AARLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';


