-- KODEVERK
INSERT INTO KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
VALUES (seq_kodeliste.nextval, 'ANNEN_OPPTJENING_TYPE', 'ETTERLONN_ARBEIDSGIVER', null, 'Etterlønn fra Arbeidsgiver', NULL, to_date('2000-01-01', 'YYYY-MM-DD'));
UPDATE KODELISTE SET KODE='LONN_UTDANNING' WHERE KODE = 'LØNN_UNDER_UTDANNING' AND KODEVERK = 'ANNEN_OPPTJENING_TYPE';
UPDATE KODELISTE SET KODE='VENTELONN' WHERE KODE = 'VENTELØNN' AND KODEVERK = 'ANNEN_OPPTJENING_TYPE';
UPDATE KODELISTE SET KODE='MILITAER_SIVIL_TJENESTE' WHERE KODE = 'MILITÆR_ELLER_SIVILTJENESTE' AND KODEVERK = 'ANNEN_OPPTJENING_TYPE';
-- KODEVERK SLUTT
