CREATE TABLE VEDTAK_UTBETALING_DVH
(
  TRANS_ID           NUMBER(19)         NOT NULL,
  TRANS_TID          TIMESTAMP(3)       NOT NULL,
  XML_CLOB           CLOB               NOT NULL,
  FAGSAK_ID          NUMBER(19)         NOT NULL,
  BEHANDLING_ID      NUMBER(19)         NOT NULL,
  VEDTAK_ID          NUMBER(19)         NOT NULL,
  BEHANDLING_TYPE    VARCHAR(100)       NOT NULL,
  SOEKNAD_TYPE       VARCHAR(100)       NOT NULL,
  FAGSAK_TYPE        VARCHAR(100)       NOT NULL,
  VEDTAK_DATO     DATE               NOT NULL,
  FUNKSJONELL_TID    TIMESTAMP(3)       NOT NULL,
  ENDRET_AV          VARCHAR2(20 CHAR)
) ;
ALTER TABLE VEDTAK_UTBETALING_DVH ADD CONSTRAINT PK_VEDTAK_UTBETALING_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_VEDTAK_UTBETALING_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_VEDTAK_UTBETALING_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON VEDTAK_UTBETALING_DVH TO FPSAK_HIST_SKRIVE_ROLE;
