-- Tabell BEHANDLING_RELATERTE_YTELSER endring
ALTER TABLE BEHANDLING_REL_YTELSER ADD vedtak_tom TIMESTAMP(3);
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.vedtak_tom IS 'Siste dag ytelsesvedtaket gjelder';
