ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD ADD MORS_AKTIVITET VARCHAR2(100 CHAR);

ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD ADD KL_MORS_AKTIVITET  VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('MORS_AKTIVITET') VIRTUAL;

ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD ADD CONSTRAINT FK_UTTAK_RES_PER_SOKNAD_2 FOREIGN KEY (KL_MORS_AKTIVITET, MORS_AKTIVITET) REFERENCES KODELISTE (kodeverk, kode);

CREATE INDEX IDX_UTTAK_RESULTAT_SOKNAD_2 ON UTTAK_RESULTAT_PERIODE_SOKNAD (MORS_AKTIVITET);

COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.MORS_AKTIVITET IS 'Mors aktivitet i perioden.';

