UPDATE KODELISTE SET NAVN='Dagmamma i eget hjem/familiebarnehage' WHERE KODEVERK='VIRKSOMHET_TYPE' AND KODE='DAGMAMMA';
UPDATE KODELISTE SET NAVN='Jordbruk' WHERE KODEVERK='VIRKSOMHET_TYPE' AND KODE='JORDBRUK_SKOGBRUK';
