DROP SEQUENCE SEQ_UTTAK_RESULTAT_ARBFHOLD;
DROP SEQUENCE SEQ_UTTAK_POSTERING;
DROP TABLE UTTAK_POSTERING;
DROP TABLE GAMMEL_UTTAK_RESULTAT_PERIODE;
DROP TABLE UTTAK_RESULTAT_ARBFORHOLD;
DROP TABLE UTTAK_RESULTAT_PLAN;
ALTER TABLE GR_YTELSES_FORDELING DROP COLUMN PERIODER_ALENEOMSORG_ID;
ALTER TABLE GR_YTELSES_FORDELING DROP COLUMN PERIODER_UTENOMSORG_ID;
DROP TABLE PERIODE_ALENEOMSORG;
DROP TABLE PERIODE_UTEN_OMSORG;
DROP TABLE PERIODER_ALENEOMSORG;
DROP TABLE PERIODER_UTEN_OMSORG;

CREATE TABLE UTTAK_AKTIVITET (
  ID                           NUMBER(19, 0)                     NOT NULL,
  ARBFORHOLD_ID                VARCHAR2(200 CHAR),
  ARBFORHOLD_ORGNR             VARCHAR2(100 CHAR),
  UTTAK_ARBEID_TYPE            VARCHAR2(100 CHAR)                NOT NULL,
  KL_UTTAK_ARBEID_TYPE         VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('UTTAK_ARBEID_TYPE') VIRTUAL,
  VERSJON                      NUMBER(19, 0) DEFAULT 0           NOT NULL,
  OPPRETTET_AV                 VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID                TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV                    VARCHAR2(20 CHAR),
  ENDRET_TID                   TIMESTAMP(3),

  CONSTRAINT PK_UTTAK_AKTIVITET_1 PRIMARY KEY (ID),
  CONSTRAINT FK_UTTAK_AKTIVITET_01 FOREIGN KEY (UTTAK_ARBEID_TYPE, KL_UTTAK_ARBEID_TYPE) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE SEQUENCE SEQ_UTTAK_AKTIVITET MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_UTTAK_AKTIVITET_1 on UTTAK_AKTIVITET(UTTAK_ARBEID_TYPE);

COMMENT ON TABLE UTTAK_AKTIVITET IS 'Arbeid eller annen aktivitet som gir uttak';
COMMENT ON COLUMN UTTAK_AKTIVITET.ARBFORHOLD_ORGNR IS 'Arbeidsforhold-org.nr denne uttaksresultatperioden er knyttet til';
COMMENT ON COLUMN UTTAK_AKTIVITET.ARBFORHOLD_ID IS 'Arbeidsforhold-id denne uttaksresultatperioden er knyttet til';
COMMENT ON COLUMN UTTAK_AKTIVITET.UTTAK_ARBEID_TYPE IS 'Arbeidstype';

CREATE TABLE UTTAK_RESULTAT_PERIODE_SOKNAD (
ID                           NUMBER(19, 0)                     NOT NULL,
PERIODE_TYPE                 VARCHAR2(100 CHAR)                NOT NULL,
KL_PERIODE_TYPE              VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('UTTAK_PERIODE_TYPE') VIRTUAL,
GRADERING_ARBEIDSTIDSPROSENT NUMBER(5, 2),
SAMTIDIG_UTTAK               CHAR                              NOT NULL CHECK (SAMTIDIG_UTTAK IN ('J', 'N')),
MOTTATT_DATO                 TIMESTAMP(3),
VERSJON                      NUMBER(19, 0) DEFAULT 0           NOT NULL,
OPPRETTET_AV                 VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
OPPRETTET_TID                TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
ENDRET_AV                    VARCHAR2(20 CHAR),
ENDRET_TID                   TIMESTAMP(3),

CONSTRAINT PK_UTTAK_RES_PER_SOKNAD_1 PRIMARY KEY (ID),
CONSTRAINT FK_UTTAK_RES_PER_SOKNAD_01 FOREIGN KEY (PERIODE_TYPE, KL_PERIODE_TYPE) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE SEQUENCE SEQ_UTTAK_RES_PER_SOKNAD MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_UTTAK_RES_PER_SOKNAD_1 on UTTAK_RESULTAT_PERIODE_SOKNAD(PERIODE_TYPE);

COMMENT ON TABLE UTTAK_RESULTAT_PERIODE_SOKNAD IS 'Perioder fra søknaden';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.PERIODE_TYPE IS 'type periode i søknadsperioden';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.GRADERING_ARBEIDSTIDSPROSENT IS 'Arbeidstidsprosent hvis søkt om gradering';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.SAMTIDIG_UTTAK IS 'Samtidig uttak eller ikke';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.MOTTATT_DATO IS 'Mottatt dato for søknad';

CREATE TABLE UTTAK_RESULTAT_DOK_REGEL (
  ID                           NUMBER(19, 0)                     NOT NULL,
  UTTAK_RESULTAT_PERIODE_ID    NUMBER(19 ,0)                     NOT NULL,
  TIL_MANUELL_BEHANDLING       CHAR                              NOT NULL CHECK (TIL_MANUELL_BEHANDLING IN ('J', 'N')),
  MANUELL_BEHANDLING_AARSAK    VARCHAR2(100 CHAR)                NOT NULL,
  KL_MANUELL_BEHANDLING_AARSAK VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('MANUELL_BEHANDLING_AARSAK') VIRTUAL,
  REGEL_INPUT                  CLOB,
  REGEL_EVALUERING             CLOB,
  VERSJON                      NUMBER(19, 0) DEFAULT 0           NOT NULL,
  OPPRETTET_AV                 VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID                TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV                    VARCHAR2(20 CHAR),
  ENDRET_TID                   TIMESTAMP(3),

  CONSTRAINT PK_UTTAK_RESULTAT_DOK_REGEL_1 PRIMARY KEY (ID),
  CONSTRAINT FK_UTTAK_RESULTAT_DOK_REGEL_01 FOREIGN KEY (MANUELL_BEHANDLING_AARSAK, KL_MANUELL_BEHANDLING_AARSAK)
  REFERENCES KODELISTE (KODE, KODEVERK),
  CONSTRAINT FK_UTTAK_RESULTAT_DOK_REGEL_02 FOREIGN KEY (UTTAK_RESULTAT_PERIODE_ID)
  REFERENCES UTTAK_RESULTAT_PERIODE (ID)
);

CREATE SEQUENCE SEQ_UTTAK_RESULTAT_DOK_REGEL MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_UTTAK_RESULTAT_DOK_REGEL_1 on UTTAK_RESULTAT_DOK_REGEL(MANUELL_BEHANDLING_AARSAK);
CREATE INDEX IDX_UTTAK_RESULTAT_DOK_REGEL_2 on UTTAK_RESULTAT_DOK_REGEL(UTTAK_RESULTAT_PERIODE_ID);

COMMENT ON TABLE UTTAK_RESULTAT_DOK_REGEL IS 'Sporingsinformasjon ifbm kjøring av regler';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.TIL_MANUELL_BEHANDLING IS 'Om perioden er merket manuell behandling';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.MANUELL_BEHANDLING_AARSAK IS 'Årsak til manuell behandling';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.REGEL_EVALUERING IS 'Evaluering';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.REGEL_INPUT IS 'Regel input';

CREATE TABLE UTTAK_RESULTAT_PERIODE_AKT (
  ID                           NUMBER(19, 0)                     NOT NULL,
  UTTAK_RESULTAT_PERIODE_ID    NUMBER(19, 0)                     NOT NULL,
  UTTAK_AKTIVITET_ID           NUMBER(19, 0)                     NOT NULL,
  TREKKONTO                    VARCHAR2(100 CHAR)                NOT NULL,
  KL_TREKKONTO                 VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('STOENADSKONTOTYPE') VIRTUAL,
  TREKKDAGER                   NUMBER(3, 0)                      NOT NULL CHECK (TREKKDAGER >= 0),
  TREKKDAGER_FLERBARN_KVOTE    NUMBER(3, 0)                      NOT NULL CHECK (TREKKDAGER_FLERBARN_KVOTE >= 0),
  ARBEIDSTIDSPROSENT           NUMBER(5, 2)                      NOT NULL CHECK (ARBEIDSTIDSPROSENT >= 0),
  OVERSTYRT_UTBETALINGSPROSENT NUMBER(5, 2)                      CHECK (OVERSTYRT_UTBETALINGSPROSENT >= 0 AND OVERSTYRT_UTBETALINGSPROSENT <= 100),
  VERSJON                      NUMBER(19, 0) DEFAULT 0           NOT NULL,
  OPPRETTET_AV                 VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID                TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV                    VARCHAR2(20 CHAR),
  ENDRET_TID                   TIMESTAMP(3),

  CONSTRAINT PK_UTTAK_RES_PERIODE_AKT_1 PRIMARY KEY (ID),
  CONSTRAINT FK_UTTAK_RES_PERIODE_AKT_01 FOREIGN KEY (UTTAK_RESULTAT_PERIODE_ID)
  REFERENCES UTTAK_RESULTAT_PERIODE (ID),
  CONSTRAINT FK_UTTAK_RES_PERIODE_AKT_02 FOREIGN KEY (UTTAK_AKTIVITET_ID)
  REFERENCES UTTAK_AKTIVITET (ID),
  CONSTRAINT FK_UTTAK_RES_PERIODE_AKT_03 FOREIGN KEY (TREKKONTO, KL_TREKKONTO)
  REFERENCES KODELISTE (KODE, KODEVERK)
);

COMMENT ON TABLE UTTAK_RESULTAT_PERIODE_AKT IS 'Uttakresultatperiode for arbeidsforhold';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.UTTAK_RESULTAT_PERIODE_ID IS 'FK: UTTAK_RESULTAT|_PERIODE.';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.TREKKONTO IS 'Hvilken stønadskonto det skal trekkes fra.';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.TREKKDAGER IS 'Antall virkedager som skal trekkes. Kan avvike fra antall virkedager i perioden.';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.TREKKDAGER_FLERBARN_KVOTE IS 'Antall virkedager som skal trekkes fra flerbarnkvote. Kan avvike fra antall virkedager i perioden.';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.ARBEIDSTIDSPROSENT IS 'Hvor mange prosent bruker ønsker å arbeide i dette arbeidsforholdet.';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.OVERSTYRT_UTBETALINGSPROSENT IS 'Overstyrt utbetalingsprosent';

CREATE SEQUENCE SEQ_UTTAK_RESULTAT_PERIODE_AKT MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

ALTER TABLE UTTAK_RESULTAT_PERIODE DROP CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_02;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_06;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_07;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_08;

ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN ARBFORHOLD_ID;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN ARBFORHOLD_ORGNR;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN KL_STOENADSKONTOTYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN STOENADSKONTOTYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN TREKKDAGER;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN TREKKDAGER_FLERBARN_KVOTE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN PROSENT_ARBEID;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN PROSENT_UTBETALING;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN KL_UTTAK_PERIODE_TYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN UTTAK_PERIODE_TYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN KL_UTTAK_ARBEID_TYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN UTTAK_ARBEID_TYPE;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN GRADERING;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN REGEL_INPUT;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN REGEL_EVALUERING;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN KL_MANUELL_BEHANDLING_AARSAK;
ALTER TABLE UTTAK_RESULTAT_PERIODE DROP COLUMN MANUELL_BEHANDLING_AARSAK;
ALTER TABLE UTTAK_RESULTAT_PERIODE ADD SAMTIDIG_UTTAK CHAR DEFAULT 'N' NOT NULL CHECK (SAMTIDIG_UTTAK IN ('J', 'N'));
ALTER TABLE UTTAK_RESULTAT_PERIODE ADD GRADERING_INNVILGET CHAR DEFAULT 'J' NOT NULL CHECK (GRADERING_INNVILGET IN ('J', 'N'));
ALTER TABLE UTTAK_RESULTAT_PERIODE ADD PERIODE_SOKNAD_ID NUMBER(19,0) ;
ALTER TABLE UTTAK_RESULTAT_PERIODE ADD CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_02 FOREIGN KEY (PERIODE_SOKNAD_ID) REFERENCES UTTAK_RESULTAT_PERIODE_SOKNAD (ID);

COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.GRADERING_INNVILGET IS 'Om gradering ble innvilget';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.SAMTIDIG_UTTAK IS 'Uttaksperiode har samtidig uttak';


CREATE INDEX IDX_UTTAK_RES_PERIODE_AKT_1 on UTTAK_RESULTAT_PERIODE_AKT(UTTAK_RESULTAT_PERIODE_ID);
CREATE INDEX IDX_UTTAK_RES_PERIODE_AKT_2 on UTTAK_RESULTAT_PERIODE_AKT(UTTAK_AKTIVITET_ID);
CREATE INDEX IDX_UTTAK_RES_PERIODE_AKT_3 on UTTAK_RESULTAT_PERIODE_AKT(TREKKONTO);
CREATE INDEX IDX_UTTAK_RESULTAT_PERIODE_9 on UTTAK_RESULTAT_PERIODE(PERIODE_SOKNAD_ID);

