/*NORDEN, EØS*/
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1, KODE1, KODEVERK2, KODE2)
SELECT seq_kodeliste_relasjon.nextval, 'REGION', lr.REGION, 'LANDKODER', lr.LAND
FROM LAND_REGION lr;

DROP TABLE LAND_REGION;
