
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD VIRKSOMHET_ID NUMBER(19) NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD ARBEIDSFORHOLD_TYPE VARCHAR2(100 CHAR) DEFAULT '-' NOT NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD KL_ARBEIDSFORHOLD_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('OPPTJENING_AKTIVITET_TYPE') VIRTUAL;

ALTER TABLE BEREGNINGSRESULTAT_ANDEL add constraint FK_BEREGNINGSRESULTAT_ANDEL_2 foreign key (virksomhet_id) references VIRKSOMHET(id);

UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'FRILANS', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'Frilans';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'VARTPENGER', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'VARTPENGER';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'VENTELØNN', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'VENTELØNN';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'ETTERLØNN_ARBEIDSGIVER', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'ETTERLØNN';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'SLUTTPAKKE', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'SLUTTPAKKE';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'VIDERE_ETTERUTDANNING', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'VIDERE ETTERUTDANNING';
UPDATE BEREGNINGSRESULTAT_ANDEL SET ARBEIDSFORHOLD_TYPE = 'UTDANNINGSPERMISJON', ARBEIDSFORHOLD_ID = null WHERE ARBEIDSFORHOLD_ID = 'UTDANNINGSPERMISJON';

UPDATE BEREGNINGSRESULTAT_ANDEL
SET VIRKSOMHET_ID = (select v.id from virksomhet v where v.orgnr = ARBEIDSFORHOLD_ID)
WHERE ARBEIDSFORHOLD_ID IS NOT NULL;

ALTER TABLE BEREGNINGSRESULTAT_ANDEL DROP COLUMN ARBEIDSFORHOLD_ID;

ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD ARBEIDSFORHOLD_ID VARCHAR2(200 CHAR);

COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.VIRKSOMHET_ID IS 'Eventuell virksomhet som denne andelen er knyttet til';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.ARBEIDSFORHOLD_ID IS 'Arbeidsforhold-id denne andelen er knyttet til';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.ARBEIDSFORHOLD_TYPE IS 'Typekode for arbeidstakeraktivitet som ikke er tilknyttet noen virksomhet';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.KL_ARBEIDSFORHOLD_TYPE IS 'Kodeverksreferanse for arbeidsforhold-type';

CREATE INDEX IDX_BEREGNINGSRESULTAT_ANDEL_3 on BEREGNINGSRESULTAT_ANDEL(VIRKSOMHET_ID);
