ALTER TABLE OKO_OPPDRAG_ENHET_120 MODIFY dato_enhet_fom NOT NULL;
ALTER TABLE OKO_OPPDRAG_LINJE_150 MODIFY henvisning NOT NULL;

ALTER TABLE IAY_EGEN_NAERING MODIFY nyoppstartet NOT NULL;
ALTER TABLE IAY_EGEN_NAERING MODIFY varig_endring NOT NULL;

ALTER TABLE MEDLEMSKAP_PERIODER MODIFY er_medlem NOT NULL;
ALTER TABLE MEDLEMSKAP_OPPG_LAND MODIFY medlemskap_oppg_tilknyt_id NOT NULL;

ALTER TABLE SO_SOEKNAD MODIFY er_endringssoeknad NOT NULL;

ALTER TABLE YF_FORDELING_PERIODE MODIFY arbeidstaker NOT NULL;

ALTER TABLE VILKAR MODIFY manuelt_vurdert NOT NULL;
ALTER TABLE VILKAR MODIFY vilkar_resultat_id NOT NULL;

ALTER TABLE MEDLEMSKAP_OPPG_TILKNYT MODIFY opphold_naa NOT NULL;

ALTER TABLE KODELISTE MODIFY sprak NOT NULL;

ALTER TABLE UTGAAENDE_HENDELSE MODIFY opprettet_av NOT NULL;
ALTER TABLE UTGAAENDE_HENDELSE MODIFY opprettet_tid NOT NULL;

-- DokumentFelles
ALTER TABLE DOKUMENT_FELLES MODIFY NAVN_AVSENDER_ENHET NOT NULL;
ALTER TABLE DOKUMENT_FELLES MODIFY KONTAKT_TLF NOT NULL;
ALTER TABLE DOKUMENT_FELLES MODIFY DOKUMENT_DATO NOT NULL;

ALTER TABLE FH_ADOPSJON MODIFY familie_hendelse_id NOT NULL;
ALTER TABLE FH_TERMINBEKREFTELSE MODIFY FAMILIE_HENDELSE_ID NOT NULL;
ALTER TABLE FH_UIDENTIFISERT_BARN MODIFY familie_hendelse_id NOT NULL;
ALTER TABLE IAY_INNTEKT MODIFY aktoer_inntekt_id NOT NULL;

ALTER TABLE VURDERINGSPUNKT_DEF MODIFY BEHANDLING_STEG NOT NULL;

ALTER TABLE AKSJONSPUNKT MODIFY AKSJONSPUNKT_DEF NOT NULL;

-- FagsakRelasjon
DELETE FROM FAGSAK_RELASJON
WHERE FAGSAK_EN_ID IS NULL;

ALTER TABLE FAGSAK_RELASJON MODIFY FAGSAK_EN_ID NOT NULL;
