create table BR_FERIEPENGER (
  id                         NUMBER(19) NOT NULL,
  beregningsresultat_fp_id   NUMBER(19) NOT NULL,
  feriepenger_periode_fom    TIMESTAMP(3) NOT NULL,
  feriepenger_periode_tom    TIMESTAMP(3) NOT NULL,
  feriepenger_regel_input    CLOB NOT NULL,
  feriepenger_regel_sporing  CLOB NOT NULL,
  opprettet_av               VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid              TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                  VARCHAR2(20 CHAR),
  endret_tid                 TIMESTAMP(3),
  versjon                    NUMBER(19) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_BR_FERIEPENGER PRIMARY KEY (id)
);

CREATE SEQUENCE SEQ_BR_FERIEPENGER MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;
ALTER TABLE BR_FERIEPENGER ADD CONSTRAINT FK_BR_FERIEPENGER_1 FOREIGN KEY ( beregningsresultat_fp_id ) REFERENCES BEREGNINGSRESULTAT_FP ( ID ) ;
CREATE INDEX IDX_BR_FERIEPENGER_1 ON BR_FERIEPENGER(BEREGNINGSRESULTAT_FP_ID);

COMMENT ON TABLE BR_FERIEPENGER  IS 'Oversikt over ev feriepenger';
COMMENT ON COLUMN BR_FERIEPENGER.ID IS 'Primær nøkkel';
COMMENT ON COLUMN BR_FERIEPENGER.BEREGNINGSRESULTAT_FP_ID IS 'FK: BEREGNINGSRESULTAT_FP';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_PERIODE_FOM IS 'Første dag i brukers feriepengeperiode';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_PERIODE_TOM IS 'Siste dag i brukers feriepengeperiode	';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_REGEL_INPUT IS 'Input til regel (clob)';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_REGEL_SPORING IS 'Logg fra regel (clob)';

create table BR_FERIEPENGER_PR_AAR (
  id                           NUMBER(19) NOT NULL,
  BR_FERIEPENGER_id            NUMBER(19) NOT NULL,
  beregningsresultat_andel_id  NUMBER(19) NOT NULL,
  opptjeningsår                DATE NOT NULL,
  årsbeløp                     NUMBER(19) NOT NULL,
  opprettet_av                 VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid                TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                    VARCHAR2(20 CHAR),
  endret_tid                   TIMESTAMP(3),
  versjon                      NUMBER(19) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_BR_FERIEPENGER_PR_AAR PRIMARY KEY (id)
);

CREATE SEQUENCE SEQ_BR_FERIEPENGER_PR_AAR MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

ALTER TABLE BR_FERIEPENGER_PR_AAR ADD CONSTRAINT FK_BR_FERIEPENGER_PR_AAR_1 FOREIGN KEY ( BR_FERIEPENGER_id ) REFERENCES BR_FERIEPENGER ( id ) ;
ALTER TABLE BR_FERIEPENGER_PR_AAR ADD CONSTRAINT FK_BR_FERIEPENGER_PR_AAR_2 FOREIGN KEY ( beregningsresultat_andel_id ) REFERENCES BEREGNINGSRESULTAT_ANDEL ( ID ) ;
CREATE INDEX IDX_BR_FERIEPENGER_PR_AAR_1 ON BR_FERIEPENGER_PR_AAR(BR_FERIEPENGER_ID);
CREATE INDEX IDX_BR_FERIEPENGER_PR_AAR_2 ON BR_FERIEPENGER_PR_AAR(BEREGNINGSRESULTAT_ANDEL_ID);

COMMENT ON TABLE BR_FERIEPENGER_PR_AAR  IS 'Årsverdier av feriepenger knyttet til andel';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.ID IS 'Primær nøkkel';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.BR_FERIEPENGER_id IS 'FK: BR_FERIEPENGER';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.BEREGNINGSRESULTAT_ANDEL_ID IS 'FK: BEREGNINGSRESULTAT_ANDEL';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.OPPTJENINGSÅR IS '31/12 i opptjeningsåret, dvs året før feriepengene utbetales';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.ÅRSBELØP IS 'Årsbeløp som skal utbetales, avrundet';
