CREATE TABLE GR_SOEKNAD (
  id                            NUMBER(19)                        NOT NULL,
  behandling_id                 NUMBER(19)                        NOT NULL,
  soeknad_id   NUMBER(19)                        NOT NULL,
  aktiv                         VARCHAR2(1 CHAR) DEFAULT 'N'      NOT NULL,
  versjon                       NUMBER(19) DEFAULT 0              NOT NULL,
  opprettet_av                  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid                 TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                     VARCHAR2(20 CHAR),
  endret_tid                    TIMESTAMP(3),
  CONSTRAINT PK_GR_SOEKNAD PRIMARY KEY (id),
  CONSTRAINT FK_GR_SOEKNAD_1 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING,
  CONSTRAINT FK_GR_SOEKNAD_2 FOREIGN KEY (soeknad_id) REFERENCES SOEKNAD,
  CONSTRAINT CHK_GR_SOEKNAD CHECK (AKTIV IN ('J', 'N'))
);

CREATE UNIQUE INDEX UIDX_GR_SOEKNAD_01
  ON GR_SOEKNAD (
    (CASE WHEN AKTIV = 'J'
      THEN BEHANDLING_ID
     ELSE NULL END),
    (CASE WHEN AKTIV = 'J'
      THEN AKTIV
     ELSE NULL END)
  );

CREATE SEQUENCE SEQ_GR_SOEKNAD
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50
  NOCACHE
  NOCYCLE;

CREATE INDEX IDX_GR_SOEKNAD_1 ON GR_SOEKNAD(behandling_id);
CREATE INDEX IDX_GR_SOEKNAD_2 ON GR_SOEKNAD(soeknad_id);

COMMENT ON TABLE GR_SOEKNAD IS 'Grunnlag for søknaden';

ALTER TABLE SOEKNAD RENAME TO SO_SOEKNAD;

COMMENT ON COLUMN OPPLYSNING_ADRESSE.ADRESSELINJE1 IS 'Sanert, kan fjernes';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.ADRESSELINJE2 IS 'Sanert, kan fjernes';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.ADRESSELINJE3 IS 'Sanert, kan fjernes';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.MOTTAKER_NAVN IS 'Sanert, kan fjernes';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.POSTNUMMER IS 'Sanert, kan fjernes';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.POSTSTED IS 'Sanert, kan fjernes';
COMMENT ON COLUMN PERSONOPPLYSNING.NUMMER IS 'Sanert, kan fjernes';
