-- PKLIBELLE-843 endre datatype fra float/double til number

ALTER TABLE BG_PR_STATUS_OG_ANDEL DROP COLUMN MAKSIMAL_BRUKERS_ANDEL_PR_AAR;

ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE MODIFY (BRUTTO_PR_AAR NUMBER(19,2));
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE MODIFY (AVKORTET_PR_AAR NUMBER(19,2));
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE MODIFY (REDUSERT_PR_AAR NUMBER(19,2));

ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (BEREGNET_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (OVERSTYRT_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (BRUTTO_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (AVKORTET_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (REDUSERT_PR_AAR NUMBER(19,2));

ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (AVKORTET_BRUKERS_ANDEL_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (REDUSERT_BRUKERS_ANDEL_PR_AAR NUMBER(19,2));

ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (REFUSJONSKRAV_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (MAKSIMAL_REFUSJON_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (AVKORTET_REFUSJON_PR_AAR NUMBER(19,2));
ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (REDUSERT_REFUSJON_PR_AAR NUMBER(19,2));

ALTER TABLE BG_PR_STATUS_OG_ANDEL MODIFY (NATURALYTELSE_BORTFALT_PR_AAR NUMBER(19,2));

ALTER TABLE SAMMENLIGNINGSGRUNNLAG MODIFY (RAPPORTERT_PR_AAR NUMBER(19,2));
