COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_STATUS IS 'FK:AKSJONSPUNKT_STATUS Fremmednøkkel til tabellen som inneholder status på aksjonspunktene';
COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_DEF IS 'FK:AKSJONSPUNKT_DEF Fremmednøkkel til tabellen som inneholder definisjonene av aksjonspunktene';
COMMENT ON COLUMN AKSJONSPUNKT.SLETTES_VED_REGISTERINNHENTING IS 'Parameter som sier om aksjonspunktet slettes ved no.nav.foreldrepenger.domene.registerinnhenting';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.VURDERINGSPUNKT IS 'FK: VURDERINGSPUNKT_DEF Fremmednøkkel til tabellen som inneholder beskrivelsen av de ulike vurderingspunktene';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.VILKAR_TYPE IS 'FK: VILKAR_TYPE Fremmednøkkel til tabellen som forklarer i hvilket vilkår aksjonspunktet skal løses';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.AKSJONSPUNKT_TYPE IS 'FK: AKSJONSPUNKT_TYPE Fremmednøkkel til tabellen som forteller om aksjonspunktet kan løses automatisk, eller om det krever amnuell avklaring';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.SKJERMLENKE_TYPE IS 'FK: SKJERMLENKE_TYPE Fremmednøkkel til tabellen for skjermlenker';
COMMENT ON COLUMN BEHANDLING.FAGSAK_ID IS 'FK: FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_STATUS IS 'FK: BEHANDLING_STATUS Fremmednøkkel til tabellen som viser status på behandlinger';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_TYPE IS 'FK: BEHANDLING_TYPE Fremmedøkkel til oversikten over hvilken behandlingstyper som finnes';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG  Fremmednøkkel til tabellen som holder oversikt over siste innhenting av data fra registere';
COMMENT ON COLUMN BEHANDLING.STARTPUNKT_TYPE IS 'Fremmednøkkel til tabellen som forteller startpunktet slik det er gitt av forretningshendelsen';
COMMENT ON COLUMN BEHANDLING_ARSAK.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN BEHANDLING_ARSAK.BEHANDLING_ARSAK_TYPE IS 'FK: BEHANDLING_ARSAK_TYPE Fremmednøkkel til oversikten over hvilke årsaker en behandling kan begrunnes med';
COMMENT ON COLUMN BEHANDLING_ARSAK.ORIGINAL_BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandlingen denne raden i tabellen hører til';
COMMENT ON COLUMN BEHANDLING_ARSAK.BEROERT_BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel fro kobling til behandlingen til berørt sak';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN BEHANDLING_RESULTAT.INNGANGSVILKAR_RESULTAT_ID IS 'FK: INNGANGSVILKAR_RESULTAT Fremmednøkkel til tabellen som viser de avklarte inngangsvilkårene som er grunnlaget for behandlingsresultatet';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEREGNING_RESULTAT_ID IS 'FK: BEREGNING_RESULTAT Fremmednøkkel til tabellen som inneholder beregningsresultatet';
COMMENT ON COLUMN BEHANDLING_STEG_TILSTAND.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandlingen dette steget er tilknyttet';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.BEHANDLING_TYPE IS 'FK: BEHANDLING_TYPE Fremmednøkkel til kodeverket for behandlingstyper';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.BEHANDLING_STEG_TYPE IS 'FK: BEHANDLING_STEG_TYPE Fremmednøkkel til tabellen som viser krav til status for at steget skal kunne kjøres';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.SEKVENS_NR IS 'Forteller når i sekvensen av steg i en behandling dette steget skal kjøres';
COMMENT ON COLUMN BEHANDLING_VEDTAK.BEHANDLING_RESULTAT_ID IS 'FK:BEHANDLING_RESULTAT Fremmednøkkel til tabellen som viser behandlingsresultatet';
COMMENT ON COLUMN BEHANDLING_VEDTAK.VEDTAK_RESULTAT_TYPE IS 'FK:VEDTAK_RESULTAT_TYPE Fremmednøkkel til tabellen som viser innholdet i vedtaket';
COMMENT ON COLUMN BEREGNING.BEREGNING_RESULTAT_ID IS 'FK: BEREGNING_RESULTAT Fremmednøkkel til tabellen som inneholder beregningsresultatet';
COMMENT ON COLUMN BEREGNING.OVERSTYRT IS 'Flagg son viser om beregningen er overstyrt';
COMMENT ON COLUMN BEREGNING_RESULTAT.ORIGINAL_BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel til behandlingen denne raden i tabellen hører til';
COMMENT ON COLUMN BEREGNINGSGRUNNLAG_PERIODE.BEREGNINGSGRUNNLAG_ID IS 'Fremmednøkkel til tabell som knytter beregningsgrunnlagsperioden til et beregningsgrunnlag';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.BR_PERIODE_ID IS 'Fremmednøkkel til tabell som knytter beregningsresultatandelen til en beregningsgrunnlagsperiode';
COMMENT ON COLUMN BEREGNINGSRESULTAT_PERIODE.BEREGNINGSRESULTAT_FP_ID IS 'Fremmednøkkel til tabell som knytter beregningsresultperioden til beregningsresultatet';
COMMENT ON COLUMN BG_AKTIVITET_STATUS.BEREGNINGSGRUNNLAG_ID IS 'Fremmednøkkel til tabell som knytter beregningsgrunnlagsaktivitetstatusen til et beregningsgrunnlag';
COMMENT ON COLUMN BG_AKTIVITET_STATUS.KL_AKTIVITET_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.BG_PERIODE_ID IS 'Fremmednøkkel til tabell som knytter beregningsgrunnlagsandelen til en beregningsgrunnlagperiode';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.KL_AKTIVITET_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.KL_RELATERT_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.INNTEKTSKATEGORI IS 'FK:INNTEKTSKATEGORI Fremmednøkkel til tabell med oversikt over inntektskategorier';
COMMENT ON COLUMN BRUKER.BRUKER_KJOENN IS 'FK:BRUKER_KJOENN Fremmednøkkel til kodeverkstabellen som viser mulige kjønn for bruker og viser til brukerens kjønn';
COMMENT ON COLUMN BRUKER.SPRAK_KODE IS 'FK:SPRAAK_KODE Fremmednøkkel til kodeverkstabellen som viser språk som er støttet og viser til brukerens foretrukne språk';
COMMENT ON COLUMN DOKUMENT_DATA.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN DOKUMENT_FELLES.SPRAK_KODE IS 'FK:SPRAAK_KODE Brukers foretrukne språk som skal brukes i kommunikasjon med bruker';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på mottakers adresse';
COMMENT ON COLUMN DOKUMENT_FELLES.RETUR_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på returadresse';
COMMENT ON COLUMN DOKUMENT_FELLES.POST_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på postadresse';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATA_ID IS 'FK:DOKUMENT_DATA Fremmednøkkel til tabellen som Inneholder informasjon om hvilken dokumentmal som er bestillt og når brevet er bestillt';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKUMENT_FELLES_ID IS 'FK:DOKUMENT_FELLES';
COMMENT ON COLUMN ETTERKONTROLL_LOGG.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN FAGSAK.FAGSAK_STATUS IS 'FK:FAGSAK_STATUS Fremmednøkkel til kodeverkstabellen som inneholder oversikten over fagstatuser';
COMMENT ON COLUMN FAGSAK.BRUKER_ID IS 'FK:BRUKER Fremmednøkkel til brukertabellen';
COMMENT ON COLUMN FAGSAK.BRUKER_ROLLE IS 'FK:BRUKER_ROLLE_TYPE Fremmednøkkel til tabellen som viser brukerens rolle i fagsaken';
COMMENT ON COLUMN FAGSAK.YTELSE_TYPE IS 'Fremmednøkkel til kodeverkstabellen som inneholder oversikt over ytelser';
COMMENT ON COLUMN FAGSAK.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.FAGSAK_ID IS 'Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.PROSESS_TASK_ID IS 'Fremmednøkkel for knyttning til logging av prosesstask som ??';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.BEHANDLING_ID IS 'Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN FH_ADOPSJON.FAMILIE_HENDELSE_ID IS 'Fremmednøkkel som knytter adopsjonsinformasjonen til familiehendelse';
COMMENT ON COLUMN FH_ADOPSJON.KL_OMSORG_VILKAAR_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FH_FAMILIE_HENDELSE.KL_FAMILIE_HENDELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FH_TERMINBEKREFTELSE.FAMILIE_HENDELSE_ID IS 'Fremmednøkkel som knytter terminbekreftelsen til familiehendelse';
COMMENT ON COLUMN FH_UIDENTIFISERT_BARN.FAMILIE_HENDELSE_ID IS 'Fremmednøkkel som knytter fødselsdato for barn til familiehendelse';
COMMENT ON COLUMN FORRETNINGSHENDELSE_DEF.FORRETNINGSHENDELSE_TYPE IS 'FK: FORRETNINGSHENDELSE_TYPE Fremmednøkel for å finne beskrivelsen av forretningshendelsestypen';
COMMENT ON COLUMN FORRETNINGSHENDELSE_DEF.REVURDERINGSÅRSAK_TYPE IS 'FK: BEHANDLING_AARSAK Fremmednøkkel for å knytte forretningshendelsen til behandlingsårsak';
COMMENT ON COLUMN FORRETNINGSHENDELSE_DEF.STARTPUNKT_TYPE IS 'FK: STARTPUNKT_TYPE Fremmednøkkel som viser til oversikt over startpunkt slik det er gitt av forretningshendelsen.';
COMMENT ON COLUMN FORRETNINGSHENDELSE_DEF.KL_FORRETNINGSHENDELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN FORRETNINGSHENDELSE_DEF.KL_REVURDERINGSÅRSAK_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.INNTEKTSMELDINGER_ID IS 'Fremmednøkkel for kobling til inntektsmeldinger';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.OPPGITT_OPPTJENING_ID IS 'Fremmenøkkel for kobling til egen oppgitt opptjening';
COMMENT ON COLUMN GR_BEREGNINGSGRUNNLAG.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_BEREGNINGSGRUNNLAG.BEREGNINGSGRUNNLAG_ID IS 'FK:BEREGNINGSGRUNNLAG Fremmednøkkel til tabell som knytter beregningsgrunnlagforekomsten til behandling';
COMMENT ON COLUMN GR_MEDLEMSKAP.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_PERSONOPPLYSNING.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_SOEKNAD.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_VERGE.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_YTELSES_FORDELING.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN HISTORIKKINNSLAG.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKK_AKTOER_ID IS 'FK:HISTORIKK_AKTOER Fremmednøkkel til';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKKINNSLAG_TYPE IS 'Fremmednøkkel til beskrivelse av historikkinnslaget';
COMMENT ON COLUMN HISTORIKKINNSLAG.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN HISTORIKKINNSLAG.BRUKER_KJOENN IS 'FK:BRUKER_KJOENN Fremmednøkkel til kodeverkstabellen som viser mulige kjønn for bruker og viser til brukerens kjønn';
COMMENT ON COLUMN HISTORIKKINNSLAG_DEL.HISTORIKKINNSLAG_ID IS 'FK:HISTORIKKINNSLAG Fremmednøkkel til riktig innslag i historikktabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.HISTORIKKINNSLAG_ID IS 'FK:HISTORIKKINNSLAG Fremmednøkkel til riktig innslag i historikktabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_NAVN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_VERDI IS 'FK:KODELISTE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_ANNEN_AKTIVITET.KL_ARBEID_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_EGEN_NAERING.KL_VIRKSOMHET_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_EGEN_NAERING.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_INNTEKT.KL_KILDE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.KL_INNSENDINGSAARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_INNTEKTSPOST.INNTEKT_ID IS 'Fremmednøkkel til kodeverkstabellen for inntektsposttyper';
COMMENT ON COLUMN IAY_INNTEKTSPOST.KL_INNTEKTSPOST_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_INNTEKTSPOST.YTELSE_TYPE IS 'Fremmednøkkel til tabell for ytelsestyper';
COMMENT ON COLUMN IAY_INNTEKTSPOST.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_NATURAL_YTELSE.NATURAL_YTELSE_TYPE IS 'Fremmednøkkel til kodeverktabell for naturalytelsetype.';
COMMENT ON COLUMN IAY_NATURAL_YTELSE.KL_NATURAL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.ARBEID_TYPE IS 'Fremmednøkkel til tabell over arbeidstyper';
COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.KL_ARBEID_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_PERMISJON.BESKRIVELSE_TYPE IS 'Fremmednøkkel til tabell for beskrivelse av permisjonstyper';
COMMENT ON COLUMN IAY_PERMISJON.KL_BESKRIVELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.AKTOER_YTELSE_ID IS 'FK:AKTOER_YTELSE';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.KL_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.KL_KILDE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.TEMAUNDERKATEGORI IS 'Fremmednøkkel til kodeverktabellen for beskrivelser av underkategori fra Infotrygd';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.KL_TEMAUNDERKATEGORI IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_UTSETTELSE_PERIODE.UTSETTELSE_AARSAK_TYPE IS 'Fremmednøkkel til kodeverkstabellen som beskriver uttsettelsesårsaker';
COMMENT ON COLUMN IAY_UTSETTELSE_PERIODE.KL_UTSETTELSE_AARSAK_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.AKTOER_ARBEID_ID IS 'Fremmednøkkel for';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.ARBEIDSGIVER_VIRKSOMHET_ID IS 'Fremmednøkkel for';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.ARBEID_TYPE IS 'Fremmednøkkel til tabell over arbeidstyper';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.KL_ARBEID_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_YTELSE_ANVIST.YTELSE_ID IS 'FK:YTELSE Fremmednøkkel til kodeverktabellen over ytelser???';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.YTELSE_ID IS 'FK:YTELSE Fremmednøkkel til kodeverktabellen over ytelser???';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.ARBEIDSKATEGORI IS 'FK:ARBEIDSKATEGORI';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.KL_ARBEIDSKATEGORI IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_YTELSE_STOERRELSE.YTELSE_GRUNNLAG_ID IS 'FK:YTELSE_GRUNNLAG';
COMMENT ON COLUMN IAY_YTELSE_STOERRELSE.VIRKSOMHET_ID IS 'FK:VIRKSOMHET';
COMMENT ON COLUMN IAY_YTELSE_STOERRELSE.KL_HYPPIGHET IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN INNSYN.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN INNSYN.INNSYN_RESULTAT_TYPE IS 'FK:INNSYN_RESULTAT_TYPE Fremmednøkkel til kodeverkstabellen for innsynsresultat';
COMMENT ON COLUMN INNSYN.KL_INNSYN_RESULTAT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN INNSYN_DOKUMENT.INNSYN_ID IS 'FK:INNSYN Fremmednøkkel til';
COMMENT ON COLUMN JOURNALPOST.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN LAGRET_VEDTAK.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN LAGRET_VEDTAK.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN MEDLEMSKAP_OPPG_LAND.LAND IS 'FK:LANDKODER';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.MEDLEMSKAP_TYPE IS 'Fremmednøkkel for tabell over mulige medlemskapstyper';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.DEKNING_TYPE IS 'Fremmednøkkel';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KILDE_TYPE IS 'Fremmednøkkel til tabllen for beskrivelse av kilde for informasjonen om medlemskap';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.MEDLEMSKAP_REGISTRERT_ID IS 'FK:MEDLEMSKAP_REGISTRERT Fremmednøkkel til tabellen for registrert medlemskap fra MEDL';
COMMENT ON COLUMN MEDLEMSKAP_VURDERING.MEDLEMSPERIODE_MANUELL_VURD IS 'Fremmednøkkel til tabell som innholder de mulige valgene for manuell vurdering av medlemsperiodene';
COMMENT ON COLUMN MOTTATT_DOKUMENT.TYPE IS 'FK:DOKUMENT_TYPE Fremmednøkkel for kobling til dokumenttype';
COMMENT ON COLUMN MOTTATT_DOKUMENT.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN MOTTATT_DOKUMENT.FAGSAK_ID IS 'FK:FAGSAKORIGINAL_BEHANDLING_ID Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN MOTTATT_DOKUMENT.KL_DOKUMENT_TYPE_ID IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OKO_ATTESTANT_180.OPPDRAGS_LINJE_150_ID IS 'FK:OKO_OPPDRAG_LINJE_150 Fremmednøkkel for kopling til tabellen som holder detaljene for oppdraget til oppgjør';
COMMENT ON COLUMN OKO_GRAD_170.OPPDRAGS_LINJE_150_ID IS 'Fremmednøkkel for kopling til tabellen som holder detaljene for oppdraget til oppgjør';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.OPPDRAG110_ID IS 'FK:OKO_OPPDRAG_110 Fremmednøkkel for kopling til tabell som innholder detaljer om oppdragets art til oppgjør';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OPPDRAG110_ID IS 'FK:OKO_OPPDRAG_110 Fremmednøkkel for kopling til tabell som innholder detaljer om oppdragets art til oppgjør';
COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAGS_KONTROLL_ID IS 'FK:OPPDRAG_KONTROLL Fremmednøkkel som knytter oppdragets art til kvitteringsmeldingen fra økonomi';
COMMENT ON COLUMN OKO_OPPDRAG_110.AVSTEMMING115_ID IS 'FK:AVSTEMMING_115 Fremmednøkkel som knytter oppdragets art til avstemming';
COMMENT ON COLUMN OKO_REFUSJONSINFO_156.OPPDRAGS_LINJE_150_ID IS 'Fremmednøkkel for kopling til tabellen som holder detaljene for oppdraget til oppgjør';
COMMENT ON COLUMN OPPDRAG_KONTROLL.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN OPPDRAG_KONTROLL.PROSESS_TASK_ID IS 'FK:PROSESS_TASK Fremmednøkkel for knyttning til logging av prosesstask som ???';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_AARSAK IS 'FK:OPPGAVE_AARSAK Fremmednøkkel for kobling til kodeverkstabell for årsaken til at oppgaven er opprettet';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.LAND IS 'Informasjon om Land';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.KL_ADRESSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OPPTJENING.VILKAR_RESULTAT_ID IS 'FK:VILKAR_RESULTAT';
COMMENT ON COLUMN OPPTJENING_AKTIVITET.KL_AKTIVITET_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OPPTJENING_AKTIVITET.KL_KLASSIFISERING IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN OPPTJENING_AKTIVITET.KL_REFERANSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PERSONOPPLYSNING.VALGT_OPPLYSNING_ID IS 'FK:VALGT_OPPLYSNING Fremmednøkkel til tabell for valgte personopplysninger. Settes til initielle verdier fra TPS og senere til det saksbehandler har valgt ved endringer.';
COMMENT ON COLUMN PERSONOPPLYSNING.FORRIGE_TPS_OPPLYSNING_ID IS 'FK:VALGT_OPPLYSNING Fremmednøkkel til tabell for valgte personopplysninger. Settes til gamle verdier dersom det kommer endringer i TPS-verdiene';
COMMENT ON COLUMN PO_ADRESSE.ADRESSE_TYPE IS 'Fremmednøkkel til kodeverkstabell for oversikt over adressetyper';
COMMENT ON COLUMN PO_ADRESSE.KL_ADRESSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_PERSONOPPLYSNING.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_PERSONOPPLYSNING.KL_SIVILSTAND_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_PERSONOPPLYSNING.KL_REGION IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_PERSONSTATUS.KL_PERSONSTATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_RELASJON.KL_RELASJONSROLLE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PO_RELASJON.FRA_AKTOER_ID IS 'Hva betyr dette?';
COMMENT ON COLUMN PO_RELASJON.TIL_AKTOER_ID IS 'Hva betyr dette?';
COMMENT ON COLUMN PO_STATSBORGERSKAP.KL_STATSBORGERSKAP IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_MAKS_FORSOEK IS 'Maksimalt anntall forsøk på rekjøring om noe går galt';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_SEK_MELLOM_FORSOEK IS 'Ventetid i sekunder mellom hvert forsøk på rekjøring om noe har gått galt';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEILHANDTERING_ALGORITME IS 'FK:PROSESS_TASK_FEILHAND Fremmednøkkel til tabell som viser detaljer om hvordan en feilsituasjon skal håndteres';
COMMENT ON COLUMN RES_BEREGNINGSRESULTAT_FP.BEHANDLING_ID IS 'FK:BEHANDLING';
COMMENT ON COLUMN RES_BEREGNINGSRESULTAT_FP.BEREGNINGSRESULTAT_FP_ID IS 'FK:BEREGNINGSRESULTAT_FP';
COMMENT ON COLUMN SAMMENLIGNINGSGRUNNLAG.RAPPORTERT_PR_AAR IS 'Rapportert inntekt per år';
COMMENT ON COLUMN SATS.SATS_TYPE IS 'FK:SATS_TYPE Fremmednøkkel til tabell for beskrivelse av satstyper i beregning';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.INNSENDINGSVALG IS 'FK:INNSENDINGSVALG Fremmednøkkel til tabell over mulige innsendingsvalg';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.SOEKNAD_ID IS 'FK:SOEKNAD Fremmednøkkel som viser til søknaden';
COMMENT ON COLUMN SO_SOEKNAD.FAR_SOEKER_TYPE IS 'FK:FAR_SOEKER_TYPE';
COMMENT ON COLUMN SO_SOEKNAD.ANNEN_PART_ID IS 'FK:SOEKNAD_ANNEN_PART';
COMMENT ON COLUMN SO_SOEKNAD.MEDLEMSKAP_OPPG_TILKNYT_ID IS 'FK:MEDLEMSKAP_OPPG_TILKNYT';
COMMENT ON COLUMN SO_SOEKNAD.BRUKER_ROLLE IS 'FK:RELASJONSROLLE_TYPE';
COMMENT ON COLUMN STARTPUNKT_TYPE.BEHANDLING_STEG IS 'FK:BEHANDLNG_STEG_TYPE Fremmednøkkel til tabell som angir konkret behandlingssteg der behandlingen skal starte gitt startpunktet';
COMMENT ON COLUMN UTGAAENDE_HENDELSE.OUTPUT_FEED_KODE IS 'FK:OUTPUT_FEED Fremmednøkkel til Output Feed';
COMMENT ON COLUMN UTTAK_AKTIVITET.KL_UTTAK_ARBEID_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.KL_MANUELL_BEHANDLING_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.UTTAK_RESULTAT_PERIODER_ID IS 'FK:UTTAK_RESULTAT_PERIODER';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.KL_PERIODE_RESULTAT_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.KL_PERIODE_RESULTAT_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.KL_GRADERING_AVSLAG_AARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.KL_PERIODE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VALGT_OPPLYSNING.BRUKER_KJOENN IS 'FK:BRUKER_KJOENN Fremmednøkkel til kodeverkstabellen som viser mulige kjønn for bruker og viser til brukerens kjønn';
COMMENT ON COLUMN VERGE.BRUKER_ID IS 'FK:BRUKER Fremmednøkkel til brukertabellen';
COMMENT ON COLUMN VILKAR.VILKAR_RESULTAT_ID IS 'FK:INNGANGSVILKAR_RESULTAT Fremmednøkkel til tabellen som viser de avklarte inngangsvilkårene som er grunnlaget for behandlingsresultatet';
COMMENT ON COLUMN VILKAR.VILKAR_UTFALL IS 'FK:VILKAR_UTFALL_TYPE Fremmednøkkel til kodeverkstabell over mulige utfall av vilkårsvurderingen';
COMMENT ON COLUMN VILKAR.VILKAR_TYPE IS 'FK:VILKAR_TYPE';
COMMENT ON COLUMN VILKAR.VILKAR_UTFALL_MERKNAD IS 'FK:VILKAR_UTFALL_MERKNAD Fremmednøkkel til kodeverkstabell over merknader sm kan velges i saammenheng med vilkårsvurderingen';
COMMENT ON COLUMN VILKAR.OPPRINNELIG_VILKAR_UTFALL IS 'FK.KODELISTE Fremmednøkkel til tabell som viser opprinnelig (første) utfall dersom utfallet er overstyrt. Vil ikke endres ved påfølgende overstyringer.';
COMMENT ON COLUMN VILKAR.KL_AVSLAGSARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR_RESULTAT.VILKAR_RESULTAT IS 'FK: VILKAR_RESULTAT_TYPE Fremmednøkkeltil kodeverk for vilkårsresultattype';
COMMENT ON COLUMN VILKAR_RESULTAT.ORIGINAL_BEHANDLING_ID IS 'FK:BEHANDLING';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.BEHANDLING_STEG IS 'FK:BEHANDLING_STEG_TYPE Fremmednøkkel til tabellen som viser krav til status for at steget skal kunne kjøres';
COMMENT ON COLUMN VURDER_PAA_NYTT_AARSAK.AKSJONSPUNKT_ID IS 'FK:AKSJONSPUNKT Fremmednøkkel til aksjonspunktet som må vurderes på nytt';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.PERIODER_ID IS 'FK: YF_DOKUMENTASJON_PERIODER Fremmednøkkel til tabell som samler dokumentasjon for en periode';
COMMENT ON COLUMN YF_FORDELING_PERIODE.FORDELING_ID IS 'FK:YF_FORDELING Fremmednøkkel til tabell tabell som knytter grunnlag og perioder sammen';
COMMENT ON COLUMN YF_FORDELING_PERIODE.VIRKSOMHET_ID IS 'FK:VIRKSOMHET';
