-- Tabell IVERKSETTING_STATUS
CREATE TABLE IVERKSETTING_STATUS (
    kode varchar2(20 char) not null,
    navn varchar2(50 char) not null,
    beskrivelse varchar2(4000 char),
    opprettet_av    VARCHAR2(20 char) DEFAULT 'VL' NOT NULL,
    opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av       VARCHAR2(20 char),
    endret_tid      TIMESTAMP(3),
	CONSTRAINT PK_IVERKSETTING_STATUS PRIMARY KEY (kode)
);

INSERT INTO IVERKSETTING_STATUS (kode, navn) VALUES ('IKKE_IVERKSATT', 'Ikke iverksatt');
INSERT INTO IVERKSETTING_STATUS (kode, navn) VALUES ('UNDER_IVERKSETTING', 'Under iverksetting');
INSERT INTO IVERKSETTING_STATUS (kode, navn) VALUES ('IVERKSATT', 'Iverksatt');

-- Ny kolonne i BEHANDLING_VEDTAK
ALTER TABLE BEHANDLING_VEDTAK ADD iverksetting_status VARCHAR2(20 char) DEFAULT 'IKKE_IVERKSATT' NOT NULL;
ALTER TABLE BEHANDLING_VEDTAK ADD CONSTRAINT FK_IVERKSETTING_STATUS FOREIGN KEY (iverksetting_status) REFERENCES IVERKSETTING_STATUS;
