ALTER TABLE SOEKNAD DISABLE CONSTRAINT FK_SOEKNAD_2;
UPDATE SOEKNAD_GJELDER_TYPE SET KODE = 'ES_MOR' WHERE KODE = 'MORA';
UPDATE SOEKNAD_GJELDER_TYPE SET KODE = 'ES_FAR' WHERE KODE = 'FARA';
UPDATE SOEKNAD SET SOEKNAD_GJELDER = 'ES_MOR' WHERE SOEKNAD_GJELDER = 'MORA';
UPDATE SOEKNAD SET SOEKNAD_GJELDER = 'ES_FAR' WHERE SOEKNAD_GJELDER = 'FARA';
ALTER TABLE SOEKNAD MODIFY SOEKNAD_GJELDER VARCHAR2(20 CHAR) DEFAULT (null);
ALTER TABLE SOEKNAD ENABLE CONSTRAINT FK_SOEKNAD_2;