-- Endre navn på
INSERT INTO AKSJONSPUNKT_KATEGORI (kode, navn) VALUES ('APK-004', 'Avklar');
INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type) VALUES ('AVFAK.UT', 'Avklar fakta - Utgang', 'AVFAK', 'UT');

ALTER TABLE REGEL_MERKNAD_DEF DROP CONSTRAINT FK_REGEL_MERKNAD_DEF_1;

ALTER TABLE AKSJONSPUNKT_DEF ADD VILKAR_TYPE VARCHAR2(20 CHAR);
ALTER TABLE AKSJONSPUNKT_DEF ADD CONSTRAINT FK_AKSJONSPUNKT_DEF_3 FOREIGN KEY (VILKAR_TYPE) REFERENCES VILKAR_TYPE;

select * from VILKAR_TYPE;
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5001, NAVN = 'Avklar terminbekreftelse', VILKAR_TYPE = 'FP_VK_1' where KODE = 'FP_VK_1.AP_1';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5002, NAVN = 'Avklar fødsel' , VILKAR_TYPE = 'FP_VK_1' where KODE = 'FP_VK_1.AP_2';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5003, NAVN = 'Avklar antall barn' , VILKAR_TYPE = 'FP_VK_1' where KODE = 'FP_VK_1.AP_3';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5004, NAVN = 'Avklar adopsjonsdokumentasjon', VILKAR_TYPE = 'FP_VK_4' where KODE = 'FP_VK_4.AP_1';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5005, NAVN = 'Avklar om adopsjon gjelder ektefelles barn', VILKAR_TYPE = 'FP_VK_4' where KODE = 'FP_VK_4.AP_2';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5006, NAVN = 'Avklar om søker er mann adopterer alene', VILKAR_TYPE = 'FP_VK_4' where KODE = 'FP_VK_4.AP_3';
UPDATE AKSJONSPUNKT_DEF SET AKSJONSPUNKT_KATEGORI = 'APK-002', KODE = 5007, NAVN = 'Manuell vurdering av søknadsfristvilkåret', VILKAR_TYPE = 'FP_VK_3' where KODE = 'FP_VK_3.AP_1';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'AVFAK.UT', AKSJONSPUNKT_KATEGORI = 'APK-004', KODE = 5008, NAVN = 'Avklar fakta for omsorgs/foreldreansvarsvilkåret'  where KODE = 'AF.AP_1';
UPDATE AKSJONSPUNKT_DEF SET AKSJONSPUNKT_KATEGORI = 'APK-002', KODE = 5009, NAVN = 'Manuell vurdering av medlemskapsvilkåret', VILKAR_TYPE = 'FP_VK_2' where KODE = 'FP_VK_2.AP_1';

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, AKSJONSPUNKT_KATEGORI, VURDERINGSPUNKT, BESKRIVELSE) VALUES ('5010', 'Avklar tilleggsopplysninger', 'APK-004', 'AVFAK.UT', 'Avklar tilleggsopplysninger fra søknad');
INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, AKSJONSPUNKT_KATEGORI, VURDERINGSPUNKT, BESKRIVELSE) VALUES ('5011', 'Auto start ny avklaring', 'APK-004', 'AVFAK.UT', 'Aksjonspunkt som VL skal vente på');
INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, AKSJONSPUNKT_KATEGORI, VURDERINGSPUNKT, BESKRIVELSE) VALUES ('5012', 'Registrer papirsøknad', 'APK-001', 'INSAK.INN', 'Registrer ustrukturert papirsøknad og send inn som strukturert søknad');

-- Oppdater REGEL_MERKNAD_DEF sin mapping mot  AKSJONSPUNKT_DEF (REGEL_MERKNAD_DEF skal fjernes)
UPDATE REGEL_MERKNAD_DEF SET AKSJONSPUNKT_DEF = KODE;