--- DENNE FILEN BRUKES TIL Å SPORE HVA SOM ER UTESTÅENDE AV DOKUMENTASJON PÅ DATABASE NIVÅ
---
--- WARNING: DET SKAL IKKE LEGGES INN HACKS I DENNE FILEN FOR Å UNNGÅ TEST ELLER NOEN ANDRE STEDER. GIT FORTELLER OSS HVEM DU ER!!!
---
---                uuuuuuu
---             uu$$$$$$$$$$$uu
---          uu$$$$$$$$$$$$$$$$$uu
---         u$$$$$$$$$$$$$$$$$$$$$u
---        u$$$$$$$$$$$$$$$$$$$$$$$u
---       u$$$$$$$$$$$$$$$$$$$$$$$$$u
---       u$$$$$$$$$$$$$$$$$$$$$$$$$u
---       u$$$$$$"   "$$$"   "$$$$$$u
---       "$$$$"      u$u       $$$$"
---        $$$u       u$u       u$$$
---        $$$u      u$$$u      u$$$
---         "$$$$uu$$$   $$$uu$$$$"
---          "$$$$$$$"   "$$$$$$$"
---            u$$$$$$$u$$$$$$$u
---             u$"$"$"$"$"$"$u
---  uuu        $$u$ $ $ $ $u$$       uuu
--- u$$$$        $$$$$u$u$u$$$       u$$$$
---  $$$$$uu      "$$$$$$$$$"     uu$$$$$$
---u$$$$$$$$$$$uu    """""    uuuu$$$$$$$$$$
---$$$$"""$$$$$$$$$$uuu   uu$$$$$$$$$"""$$$"
--- """      ""$$$$$$$$$$$uu ""$"""
---           uuuu ""$$$$$$$$$$uuu
---  u$$$uuu$$$$$$$$$uu ""$$$$$$$$$$$uuu$$$
---  $$$$$$$$$$""""           ""$$$$$$$$$$$"
---   "$$$$$"                      ""$$$$""
---     $$$"                         $$$$"


-- MISSING TABLE COMMENTS

COMMENT ON TABLE FAGSAK_ARSAK_TYPE IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE FAGSAK_YTELSE_TYPE IS 'MISSING TABLE COMMENT';             
COMMENT ON TABLE FAGSAK_RELASJON IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE BRUKER_ROLLE_TYPE IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE BRUKER_KJOENN IS 'MISSING TABLE COMMENT';                  
COMMENT ON TABLE BRUKER IS 'MISSING TABLE COMMENT';                         
COMMENT ON TABLE BARN IS 'MISSING TABLE COMMENT';                           
COMMENT ON TABLE FAGSAK_STATUS IS 'MISSING TABLE COMMENT';                  
COMMENT ON TABLE FAGSAK IS 'MISSING TABLE COMMENT';                         
COMMENT ON TABLE JOURNALDOKUMENT IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE VURDERINGSPUNKT_DEF IS 'MISSING TABLE COMMENT';            
COMMENT ON TABLE BEHANDLING_TYPE IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE BEHANDLING_TYPE_STEG_SEKV IS 'MISSING TABLE COMMENT';      
COMMENT ON TABLE BEHANDLING IS 'MISSING TABLE COMMENT';                     
COMMENT ON TABLE OPPGAVE_AARSAK IS 'MISSING TABLE COMMENT';                 
COMMENT ON TABLE OPPGAVE_BEHANDLING_KOBLING IS 'MISSING TABLE COMMENT';     
COMMENT ON TABLE SOEKNAD IS 'MISSING TABLE COMMENT';                        
COMMENT ON TABLE FOEDSEL IS 'MISSING TABLE COMMENT';                        
COMMENT ON TABLE TERMINBEKREFTELSE IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE BEHANDLING_GRUNNLAG IS 'MISSING TABLE COMMENT';            
COMMENT ON TABLE VILKAR_TYPE IS 'MISSING TABLE COMMENT';                    
COMMENT ON TABLE VILKAR_UTFALL_TYPE IS 'MISSING TABLE COMMENT';             
COMMENT ON TABLE VILKAR_RESULTAT_TYPE IS 'MISSING TABLE COMMENT';           
COMMENT ON TABLE VILKAR_UTFALL_MERKNAD IS 'MISSING TABLE COMMENT';          
COMMENT ON TABLE INNGANGSVILKAR_RESULTAT IS 'MISSING TABLE COMMENT';        
COMMENT ON TABLE VILKAR IS 'MISSING TABLE COMMENT';                         
COMMENT ON TABLE BEREGNING_RESULTAT IS 'MISSING TABLE COMMENT';             
COMMENT ON TABLE BEREGNING IS 'MISSING TABLE COMMENT';                      
COMMENT ON TABLE BEHANDLING_RESULTAT IS 'MISSING TABLE COMMENT';            
COMMENT ON TABLE REGEL_MERKNAD_DEF IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE REGEL_MERKNAD IS 'MISSING TABLE COMMENT';                  
COMMENT ON TABLE AKTOER_NORSK_IDENT_MAP IS 'MISSING TABLE COMMENT';         
COMMENT ON TABLE PROSESS_TASK_FEILHAND IS 'MISSING TABLE COMMENT';          
COMMENT ON TABLE PROSESS_TASK_TYPE IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE SAKSOPPLYSNING IS 'MISSING TABLE COMMENT';                 
COMMENT ON TABLE SAKSOPPLYSNING_DOKUMENT IS 'MISSING TABLE COMMENT';        
COMMENT ON TABLE SAKSOPPLYSNING_KILDE IS 'MISSING TABLE COMMENT';           
COMMENT ON TABLE SAKSOPPLYSNING_TYPE IS 'MISSING TABLE COMMENT';            
COMMENT ON TABLE SOEKNAD_GJELDER_TYPE IS 'MISSING TABLE COMMENT';           
COMMENT ON TABLE SOEKNAD_TYPE IS 'MISSING TABLE COMMENT';                   
COMMENT ON TABLE FAR_SOEKER_TYPE IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE SOEKNAD_ADOPSJON_BARN IS 'MISSING TABLE COMMENT';          
COMMENT ON TABLE SPRAAK_KODE IS 'MISSING TABLE COMMENT';                    
COMMENT ON TABLE DOKUMENT_DATA IS 'MISSING TABLE COMMENT';                  
COMMENT ON TABLE DOKUMENT_FELLES IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE DOKUMENT_TYPE_DATA IS 'MISSING TABLE COMMENT';             
COMMENT ON TABLE VEDTAK_RESULTAT_TYPE IS 'MISSING TABLE COMMENT';           
COMMENT ON TABLE BEHANDLING_VEDTAK IS 'MISSING TABLE COMMENT';              
COMMENT ON TABLE LAGRET_VEDTAK IS 'MISSING TABLE COMMENT';   

-- Kjente Primary Keys
COMMENT ON COLUMN ADOPSJON.ID IS 'Primary Key';
COMMENT ON COLUMN ADOPSJON_BARN.ID IS 'Primary Key';
COMMENT ON COLUMN ADRESSE.ID IS 'Primary Key';
COMMENT ON COLUMN AKSJONSPUNKT.ID IS 'Primary Key';
COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.ID IS 'Primary Key';
COMMENT ON COLUMN BARN.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING_GRUNNLAG.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING_RESULTAT.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.ID IS 'Primary Key';
COMMENT ON COLUMN BEHANDLING_VEDTAK.ID IS 'Primary Key';
COMMENT ON COLUMN BEREGNING.ID IS 'Primary Key';
COMMENT ON COLUMN BEREGNING_RESULTAT.ID IS 'Primary Key';
COMMENT ON COLUMN BRUKER.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_DATA.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_FELLES.ID IS 'Primary Key';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.ID IS 'Primary Key';
COMMENT ON COLUMN FAGSAK.ID IS 'Primary Key';
COMMENT ON COLUMN FAGSAK_RELASJON.ID IS 'Primary Key';
COMMENT ON COLUMN FOEDSEL.ID IS 'Primary Key';
COMMENT ON COLUMN HISTORIKKINNSLAG.ID IS 'Primary Key';
COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.ID IS 'Primary Key';
COMMENT ON COLUMN INNGANGSVILKAR_RESULTAT.ID IS 'Primary Key';
COMMENT ON COLUMN JOURNALDOKUMENT.ID IS 'Primary Key';
COMMENT ON COLUMN LAGRET_VEDTAK.ID IS 'Primary Key';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.ID IS 'Primary Key';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.ID IS 'Primary Key';
COMMENT ON COLUMN PROSESS_TASK.ID IS 'Primary Key';
COMMENT ON COLUMN REGEL_MERKNAD.ID IS 'Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING.ID IS 'Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT.ID IS 'Primary Key';
COMMENT ON COLUMN SATS.ID IS 'Primary Key';
COMMENT ON COLUMN SOEKNAD.ID IS 'Primary Key';
COMMENT ON COLUMN SOEKNAD_ADOPSJON_BARN.ID IS 'Primary Key';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.ID IS 'Primary Key';
COMMENT ON COLUMN SOEKNAD_BARN.ID IS 'Primary Key';
COMMENT ON COLUMN TERMINBEKREFTELSE.ID IS 'Primary Key';
COMMENT ON COLUMN TILKNYTNING_NORGE.ID IS 'Primary Key';
COMMENT ON COLUMN UTLANDSOPPHOLD.ID IS 'Primary Key';
COMMENT ON COLUMN VEDLEGG.ID IS 'Primary Key';
COMMENT ON COLUMN VILKAR.ID IS 'Primary Key';

COMMENT ON COLUMN AKSJONSPUNKT_DEF.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN AKSJONSPUNKT_KATEGORI.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN AKSJONSPUNKT_STATUS.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN BEHANDLING_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN BRUKER_KJOENN.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN BRUKER_ROLLE_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN DOKUMENT_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN FAGSAK_ARSAK_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN FAGSAK_STATUS.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN FAGSAK_YTELSE_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN FAR_SOEKER_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN INNSENDINGSVALG.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN LAGRET_VEDTAK_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN LANDKODER.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN MOTTATT_STATUS.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN OPPGAVE_AARSAK.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN POSTSTED.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN PROSESS_TASK_FEILHAND.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN PROSESS_TASK_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN REGEL_MERKNAD_DEF.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING_KILDE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SAKSOPPLYSNING_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SATS_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SOEKNAD_GJELDER_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SOEKNAD_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN SPRAAK_KODE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VEDTAK_RESULTAT_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VILKAR_RESULTAT_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VILKAR_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VILKAR_UTFALL_MERKNAD.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VILKAR_UTFALL_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.KODE IS 'Kodeverk Primary Key';

-- Kjente kolonner
COMMENT ON COLUMN SATS.FOM IS 'Gyldig Fra-Og-Med';
COMMENT ON COLUMN SATS.TOM IS 'Gyldig Til-Og-Med';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN AKSJONSPUNKT_KATEGORI.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN AKSJONSPUNKT_STATUS.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN BEHANDLING_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN BRUKER_KJOENN.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN BRUKER_ROLLE_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN DOKUMENT_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN FAGSAK_ARSAK_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN FAGSAK_STATUS.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN FAGSAK_YTELSE_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN FAR_SOEKER_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN INNSENDINGSVALG.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN LAGRET_VEDTAK_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN LANDKODER.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN MOTTATT_STATUS.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN OPPGAVE_AARSAK.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN POSTSTED.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN PROSESS_TASK_FEILHAND.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN PROSESS_TASK_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN REGEL_MERKNAD_DEF.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SAKSOPPLYSNING_KILDE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SAKSOPPLYSNING_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SATS_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SOEKNAD_GJELDER_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SOEKNAD_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN SPRAAK_KODE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VEDTAK_RESULTAT_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VILKAR_RESULTAT_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VILKAR_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VILKAR_UTFALL_MERKNAD.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VILKAR_UTFALL_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.BESKRIVELSE IS 'Utdypende beskrivelse av koden';

-- Kjente Foreign keys
COMMENT ON COLUMN AKSJONSPUNKT_DEF.AKSJONSPUNKT_KATEGORI IS 'FK: AKSJONSPUNKT_KATEGORI';
COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_STATUS IS 'FK: AKSJONSPUNKT_STATUS';
COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_DEF IS 'FK: AKSJONSPUNKT_DEF';
COMMENT ON COLUMN REGEL_MERKNAD_DEF.AKSJONSPUNKT_DEF IS 'FK: AKSJONSPUNKT_DEF';
COMMENT ON COLUMN REGEL_MERKNAD.AKSJONSPUNKT_ID IS 'FK: AKSJONSPUNKT';
COMMENT ON COLUMN REGEL_MERKNAD.REGEL_MERKNAD_DEF IS 'FK: REGEL_MERKNAD_DEF';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEILHANDTERING_ALGORITME IS 'FK: PROSESS_TASK_FEILHAND';
COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING_DOKUMENT_ID IS 'FK: SAKSOPPLYSNING_DOKUMENT';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT.SAKSOPPLYSNING_DOK_TYPE IS 'FK: SAKSOPPLYSNING_DOKUMENT_TYPE';
COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING_KILDE IS 'FK: SAKSOPPLYSNING_KILDE';
COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING_TYPE IS 'FK: SAKSOPPLYSNING_TYPE';
COMMENT ON COLUMN SOEKNAD.SOEKNAD_GJELDER IS 'FK: SOEKNAD_GJELDER_TYPE';
COMMENT ON COLUMN SOEKNAD.SOEKNAD_TYPE IS 'FK: SOEKNAD_TYPE';
COMMENT ON COLUMN SOEKNAD.FAR_SOEKER_TYPE IS 'FK: FAR_SOEKER_TYPE';
COMMENT ON COLUMN ADOPSJON_BARN.ADOPSJON_ID IS 'FK: ADOPSJON';
COMMENT ON COLUMN DOKUMENT_FELLES.SPRAAK_KODE IS 'FK: SPRAAK_KODE';
COMMENT ON COLUMN BEHANDLING.SPRAAK_KODE IS 'FK: SPRAAK_KODE';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ADRESSE_ID IS 'FK: ADRESSE';
COMMENT ON COLUMN DOKUMENT_FELLES.RETUR_ADRESSE_ID IS 'FK: ADRESSE';
COMMENT ON COLUMN DOKUMENT_FELLES.POST_ADRESSE_ID IS 'FK: ADRESSE';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKUMENT_FELLES_ID IS 'FK: DOKUMENT_FELLES';
COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_FELLES_ID IS 'FK: DOKUMENT_FELLES';
COMMENT ON COLUMN BEHANDLING_VEDTAK.VEDTAK_RESULTAT_TYPE IS 'FK: VEDTAK_RESULTAT_TYPE';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKKINNSLAG_TYPE_ID IS 'FK: HISTORIKKINNSLAG_TYPE';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKK_AKTOER_ID IS 'FK: HISTORIKK_AKTOER';
COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.HISTORIKKINNSLAG_ID IS 'FK: HISTORIKKINNSLAG';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.TYPE IS 'FK: DOKUMENT_TYPE';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.STATUS IS 'FK: MOTTATT_STATUS';
COMMENT ON COLUMN VEDLEGG.INNSENDINGSVALG IS 'FK: INNSENDINGSVALG';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.UTENLANDSK_FNR_LAND IS 'FK: LANDKODER';
COMMENT ON COLUMN UTLANDSOPPHOLD.LAND IS 'FK: LANDKODER';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.TYPE IS 'FK: SOEKNAD_ANNEN_PART_TYPE';
COMMENT ON COLUMN SOEKNAD.ANNEN_PART_ID IS 'FK: SOEKNAD_ANNEN_PART';
COMMENT ON COLUMN SOEKNAD.TILKNYTNING_NORGE_ID IS 'FK: TILKNYTNING_NORGE';
COMMENT ON COLUMN UTLANDSOPPHOLD.TIDLIGERE_OPPHOLD_NORGE IS 'FK: TILKNYTNING_NORGE';
COMMENT ON COLUMN UTLANDSOPPHOLD.FREMTIDIG_OPPHOLD_NORGE IS 'FK: TILKNYTNING_NORGE';
COMMENT ON COLUMN FAGSAK_RELASJON.FAGSAK_ARSAK_TYPE IS 'FK: FAGSAK_ARSAK_TYPE';
COMMENT ON COLUMN FAGSAK_RELASJON.FAGSAK_YTELSE_TYPE IS 'FK: FAGSAK_YTELSE_TYPE';
COMMENT ON COLUMN BARN.FAGSAK_RELASJON_ID IS 'FK: FAGSAK_RELASJON';
COMMENT ON COLUMN FAGSAK.FAGSAK_RELASJON_ID IS 'FK: FAGSAK_RELASJON';
COMMENT ON COLUMN FAGSAK.BRUKER_ROLLE IS 'FK: BRUKER_ROLLE_TYPE';
COMMENT ON COLUMN BRUKER.BRUKER_KJOENN IS 'FK: BRUKER_KJOENN';
COMMENT ON COLUMN FAGSAK.BRUKER_ID IS 'FK: BRUKER';
COMMENT ON COLUMN FAGSAK.FAGSAK_STATUS IS 'FK: FAGSAK_STATUS';
COMMENT ON COLUMN JOURNALDOKUMENT.FAGSAK_ID IS 'FK: FAGSAK';
COMMENT ON COLUMN BEHANDLING.FAGSAK_ID IS 'FK: FAGSAK';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.BEHANDLING_STEG IS 'FK: BEHANDLING_STEG_TYPE';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.BEHANDLING_STEG_TYPE IS 'FK: BEHANDLING_STEG_TYPE';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_STEG IS 'FK: BEHANDLING_STEG_TYPE';
COMMENT ON COLUMN AKSJONSPUNKT_DEF.VURDERINGSPUNKT IS 'FK: VURDERINGSPUNKT_DEF';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_STATUS IS 'FK: BEHANDLING_STATUS';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.BEHANDLING_TYPE IS 'FK: BEHANDLING_TYPE';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_TYPE IS 'FK: BEHANDLING_TYPE';
COMMENT ON COLUMN DOKUMENT_DATA.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN INNGANGSVILKAR_RESULTAT.ORIGINAL_BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN BEREGNING_RESULTAT.ORIGINAL_BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN HISTORIKKINNSLAG.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN BEHANDLING_GRUNNLAG.ORIGINAL_BEHANDLING_ID IS 'FK: BEHANDLING';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_AARSAK IS 'FK: OPPGAVE_AARSAK';
COMMENT ON COLUMN VEDLEGG.SOEKNAD_ID IS 'FK: SOEKNAD';
COMMENT ON COLUMN SOEKNAD_BARN.SOEKNAD_ID IS 'FK: SOEKNAD';
COMMENT ON COLUMN SOEKNAD_ADOPSJON_BARN.SOEKNAD_ID IS 'FK: SOEKNAD';
COMMENT ON COLUMN MOTTATTE_DOKUMENT.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN ADOPSJON.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN SOEKNAD.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN TERMINBEKREFTELSE.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN FOEDSEL.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN BEHANDLING.BEHANDLING_GRUNNLAG_ID IS 'FK: BEHANDLING_GRUNNLAG';
COMMENT ON COLUMN VILKAR.VILKAR_TYPE IS 'FK: VILKAR_TYPE';
COMMENT ON COLUMN VILKAR.VILKAR_UTFALL IS 'FK: VILKAR_UTFALL_TYPE';
COMMENT ON COLUMN INNGANGSVILKAR_RESULTAT.VILKAR_RESULTAT IS 'FK: VILKAR_RESULTAT_TYPE';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEHANDLING_RESULTAT IS 'FK: VILKAR_RESULTAT_TYPE';
COMMENT ON COLUMN VILKAR.VILKAR_UTFALL_MERKNAD IS 'FK: VILKAR_UTFALL_MERKNAD';
COMMENT ON COLUMN VILKAR.INNGANGSVILKAR_RESULTAT_ID IS 'FK: INNGANGSVILKAR_RESULTAT';
COMMENT ON COLUMN BEHANDLING_RESULTAT.INNGANGSVILKAR_RESULTAT_ID IS 'FK: INNGANGSVILKAR_RESULTAT';
COMMENT ON COLUMN BEREGNING.BEREGNING_RESULTAT_ID IS 'FK: BEREGNING_RESULTAT';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEREGNING_RESULTAT_ID IS 'FK: BEREGNING_RESULTAT';
COMMENT ON COLUMN SATS.SATS_TYPE IS 'FK: SATS_TYPE';
COMMENT ON COLUMN AKSJONSPUNKT.BEHANDLING_RESULTAT_ID IS 'FK: BEHANDLING_RESULTAT';
COMMENT ON COLUMN BEHANDLING_VEDTAK.BEHANDLING_RESULTAT_ID IS 'FK: BEHANDLING_RESULTAT';

-- KJENTE MISSING COLUMN COMMENTS (MÅ FIKSES!)
COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.AKTOER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.NORSK_IDENT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BARN.AKTOER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BARN.NORSK_IDENT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BARN.FOEDSELDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEHANDLING.OPPRETTET_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEHANDLING.AVSLUTTET_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.SEKVENS_NR IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEHANDLING_VEDTAK.VEDTAKSDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEHANDLING_VEDTAK.ANSVARLIG_SAKSBEHANDLER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEREGNING.SATS_VERDI IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEREGNING.ANTALL_BARN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEREGNING.BEREGNET_TILKJENT_YTELSE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BEREGNING.BEREGNET_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BRUKER.AKTOER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN BRUKER.FOEDSELDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_DATA.JOURNAL_POST_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_MAL_NAVN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_DATA.FORHAANDSVIST_TID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_DATA.SENDT_TID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_SAKSBEHANDLER_NAVN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.AUTOMATISK_BEHANDLET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_NAVN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_NAVN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_GEO_ENHET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_NAVN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.NAVN_AVSENDER_ENHET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.NUMMER_AVSENDER_ENHET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.KONTAKT_TELEFON_NUMMER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKSYS_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FOEDSEL.FOEDSELSDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FOEDSEL.ANTALL_BARN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FOEDSEL.ANTALL_BARN_TPS_GJELDER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FOEDSEL.KILDE_SAKSBEHANDLER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FOEDSEL.KILDE_REF IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN LAGRET_VEDTAK.XML_CLOB IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.SAKS_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT_AV IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT_TID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_MAKS_FORSOEK IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_SEK_MELLOM_FORSOEK IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SAKSOPPLYSNING.FAGSAK_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SAKSOPPLYSNING.BEHANDLING_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SAKSOPPLYSNING.EKSTERN_REFERANSE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT.DOKUMENT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.SOEKNADSDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.FOEDSELSDATO_FRA_SOEKNAD IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.UTSTEDT_DATO_TERMINBEKREFTELSE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.TERMINDATO_FRA_SOEKNAD IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.ANTALL_BARN_FRA_SOEKNAD IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.KILDE_REF IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.TILLEGGSOPPLYSNINGER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.ADOP_OMSORGOVER_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.OMSORG_OMSORGOVER_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.ELEKTRONISK_REGISTRERT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD.MOTTATT_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_ADOPSJON_BARN.FOEDSELSDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN TERMINBEKREFTELSE.TERMINDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN TERMINBEKREFTELSE.UTSTEDT_DATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN TERMINBEKREFTELSE.ANTALL_BARN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN TERMINBEKREFTELSE.KILDE_REF IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN VURDERINGSPUNKT_DEF.VURDERINGSPUNKT_TYPE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_BARN.FOEDSELSDATO IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN ADOPSJON_BARN.SOKNAD_ADOPSJON_BARN_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN LAGRET_VEDTAK.BEHANDLING_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SATS.VERDI IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.UTENLANDSK_FNR IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.VERDI IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK_TYPE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.BEGRUNNELSE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKSYS_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN FAGSAK.SAKSNUMMER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.AKTOER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN LAGRET_VEDTAK.FAGSAK_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.AARSAK IS 'MISSING COLUMN COMMENT';