-- Tabell OPPDRAG_KONTROLL
CREATE TABLE OPPDRAG_KONTROLL (
    id                    NUMBER(19, 0) NOT NULL,
    behandling_id         NUMBER(19, 0) NOT NULL,
    saksnummer            NUMBER(19, 0) NOT NULL,
    venter_kvittering     VARCHAR2(1 CHAR) NOT NULL,
    prosess_task_id       NUMBER(19, 0) NOT NULL,
    alvorlighetsgrad      VARCHAR2(2 CHAR),
    beskr_melding         VARCHAR2(300 CHAR),
    versjon               NUMBER(19) DEFAULT 0 NOT NULL,
    opprettet_av          VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    opprettet_tid         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av             VARCHAR2(20 CHAR),
    endret_tid            TIMESTAMP(3),
    CONSTRAINT PK_OPPDRAG_KONTROLL PRIMARY KEY (id)
);

CREATE INDEX IDX_OPPDRAG_KONTROLL_1 ON OPPDRAG_KONTROLL(behandling_id);
CREATE INDEX IDX_OPPDRAG_KONTROLL_2 ON OPPDRAG_KONTROLL(saksnummer);
CREATE INDEX IDX_OPPDRAG_KONTROLL_3 ON OPPDRAG_KONTROLL(venter_kvittering);
CREATE INDEX IDX_OPPDRAG_KONTROLL_4 ON OPPDRAG_KONTROLL(prosess_task_id);

CREATE SEQUENCE SEQ_OPPDRAG_KONTROLL MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell OKO_AVSTEMMING_115
CREATE TABLE OKO_AVSTEMMING_115 (
  id                        NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  kode_komponent            VARCHAR2(10 CHAR) NOT NULL,
  nokkel_avstemming         TIMESTAMP(3) NOT NULL,
  tidspnkt_melding          TIMESTAMP(3) NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_OKO_AVSTEMMING_115 PRIMARY KEY ( id )
);

CREATE INDEX IDX_OKO_AVSTEMMING_115_1 ON OKO_AVSTEMMING_115(kode_komponent);
CREATE INDEX IDX_OKO_AVSTEMMING_115_2 ON OKO_AVSTEMMING_115(nokkel_avstemming);
CREATE INDEX IDX_OKO_AVSTEMMING_115_3 ON OKO_AVSTEMMING_115(tidspnkt_melding);

CREATE SEQUENCE SEQ_OKO_AVSTEMMING_115 MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- Tabell OKO_OPPDRAG_110
CREATE TABLE OKO_OPPDRAG_110 (
  id                        NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  kode_aksjon               VARCHAR2(7 CHAR) NOT NULL,
  kode_endring              VARCHAR2(10 CHAR) NOT NULL,
  kode_fagomrade            VARCHAR2(10 CHAR) NOT NULL,
  fagsystem_id              VARCHAR2(30 CHAR) NOT NULL,
  utbet_frekvens            VARCHAR2(10 CHAR) NOT NULL,
  oppdrag_gjelder_id        VARCHAR2(20 CHAR) NOT NULL,
  dato_Oppdrag_Gjelder_Fom  DATE NOT NULL,
  saksbeh_id                VARCHAR2(10 CHAR) NOT NULL,
  oppdrags_kontroll_id      NUMBER(19) NOT NULL,
  avstemming115_id          NUMBER(19) NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_OKO_OPPDRAG_110 PRIMARY KEY ( id )
);

ALTER TABLE OKO_OPPDRAG_110 ADD CONSTRAINT FK_OKO_OPPDRAG_110_1 FOREIGN KEY ( oppdrags_kontroll_id ) REFERENCES OPPDRAG_KONTROLL ( id );
ALTER TABLE OKO_OPPDRAG_110 ADD CONSTRAINT FK_OKO_OPPDRAG_110_2 FOREIGN KEY ( avstemming115_id ) REFERENCES OKO_AVSTEMMING_115 ( id );

CREATE INDEX IDX_OKO_OPPDRAG_110_1 ON OKO_OPPDRAG_110(oppdrags_kontroll_id);
CREATE INDEX IDX_OKO_OPPDRAG_110_2 ON OKO_OPPDRAG_110(fagsystem_id);
CREATE INDEX IDX_OKO_OPPDRAG_110_3 ON OKO_OPPDRAG_110(oppdrag_gjelder_id);

CREATE SEQUENCE SEQ_OKO_OPPDRAG_110 MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;


-- Tabell OKO_OPPDRAG_ENHET_120
CREATE TABLE OKO_OPPDRAG_ENHET_120 (
  id                        NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  type_enhet                VARCHAR2(20 CHAR) NOT NULL,
  enhet                     VARCHAR2(7 CHAR) NOT NULL,
  dato_enhet_fom            DATE,
  oppdrag110_id             NUMBER(19) NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_OKO_OPPDRAG_ENHET_120 PRIMARY KEY ( id )
);

ALTER TABLE OKO_OPPDRAG_ENHET_120 ADD CONSTRAINT FK_OKO_OPPDRAG_ENHET_120_1 FOREIGN KEY ( oppdrag110_id ) REFERENCES OKO_OPPDRAG_110 ( id );

CREATE INDEX IDX_OKO_OPPDRAG_ENHET_120_1 ON OKO_OPPDRAG_ENHET_120(type_enhet);
CREATE INDEX IDX_OKO_OPPDRAG_ENHET_120_2 ON OKO_OPPDRAG_ENHET_120(enhet);
CREATE INDEX IDX_OKO_OPPDRAG_ENHET_120_3 ON OKO_OPPDRAG_ENHET_120(oppdrag110_id);

CREATE SEQUENCE SEQ_OKO_OPPDRAG_ENHET_120 MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;


-- Tabell OKO_OPPDRAG_LINJE_150
CREATE TABLE OKO_OPPDRAG_LINJE_150 (
  id                        NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  kode_endring_linje        VARCHAR2(10 CHAR) NOT NULL,
  kode_status_linje         VARCHAR2(10 CHAR),
  dato_status_fom           DATE,
  vedtak_id                 VARCHAR2(10 CHAR),
  delytelse_id              VARCHAR2(30 CHAR),
  dato_vedtak_fom           DATE NOT NULL,
  dato_vedtak_tom           DATE,
  kode_klassifik            VARCHAR2(50 CHAR) NOT NULL,
  sats                      NUMBER(19) NOT NULL,
  fradrag_tillegg           VARCHAR2(7 CHAR) NOT NULL,
  type_sats                 VARCHAR2(10 CHAR) NOT NULL,
  bruk_kjore_plan           VARCHAR2(5 CHAR) NOT NULL,
  saksbeh_id                VARCHAR2(10 CHAR) NOT NULL,
  utbetales_til_id          VARCHAR2(20 CHAR) NOT NULL,
  henvisning                VARCHAR2(30 CHAR),
  ref_fagsystem_id          VARCHAR2(30 CHAR),
  ref_delytelse_id          VARCHAR2(30 CHAR),
  oppdrag110_id             NUMBER(19) NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_OKO_OPPDRAG_LINJE_150 PRIMARY KEY ( id )
);

ALTER TABLE OKO_OPPDRAG_LINJE_150 ADD CONSTRAINT FK_OKO_OPPDRAG_LINJE_150_1 FOREIGN KEY ( oppdrag110_id ) REFERENCES OKO_OPPDRAG_110 ( id );

CREATE INDEX IDX_OKO_OPPDRAG_LINJE_150_1 ON OKO_OPPDRAG_LINJE_150(vedtak_id);
CREATE INDEX IDX_OKO_OPPDRAG_LINJE_150_2 ON OKO_OPPDRAG_LINJE_150(delytelse_id);
CREATE INDEX IDX_OKO_OPPDRAG_LINJE_150_3 ON OKO_OPPDRAG_LINJE_150(saksbeh_id);
CREATE INDEX IDX_OKO_OPPDRAG_LINJE_150_4 ON OKO_OPPDRAG_LINJE_150(utbetales_til_id);
CREATE INDEX IDX_OKO_OPPDRAG_LINJE_150_5 ON OKO_OPPDRAG_LINJE_150(oppdrag110_id);

CREATE SEQUENCE SEQ_OKO_OPPDRAG_LINJE_150 MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;


-- Tabell OKO_ATTESTANT_180
CREATE TABLE OKO_ATTESTANT_180 (
  id                        NUMBER(19) NOT NULL,
  versjon                   NUMBER(19) DEFAULT 0 NOT NULL,
  attestant_id              VARCHAR2(10 CHAR) NOT NULL,
  oppdrags_linje_150_id     NUMBER(19) NOT NULL,
  opprettet_av              VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid             TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                 VARCHAR2(20 CHAR),
  endret_tid                TIMESTAMP(3),
  CONSTRAINT PK_OKO_ATTESTANT_180 PRIMARY KEY ( id )
);

ALTER TABLE OKO_ATTESTANT_180 ADD CONSTRAINT FK_OKO_ATTESTANT_180_1 FOREIGN KEY ( oppdrags_linje_150_id ) REFERENCES OKO_OPPDRAG_LINJE_150 ( id );

CREATE INDEX IDX_OKO_ATTESTANT_180_1 ON OKO_ATTESTANT_180(attestant_id);

CREATE SEQUENCE SEQ_OKO_ATTESTANT_180 MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- kjente PK og FKs
COMMENT ON COLUMN OKO_ATTESTANT_180.ID IS 'Primary Key';
COMMENT ON COLUMN OKO_AVSTEMMING_115.ID IS 'Primary Key';
COMMENT ON COLUMN OKO_OPPDRAG_110.ID IS 'Primary Key';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.ID IS 'Primary Key';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.ID IS 'Primary Key';
COMMENT ON COLUMN OPPDRAG_KONTROLL.ID IS 'Primary Key';

COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAGS_KONTROLL_ID IS 'FK: OPPDRAG_KONTROLL';
COMMENT ON COLUMN OKO_OPPDRAG_110.AVSTEMMING115_ID IS 'FK: AVSTEMMING_115';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.OPPDRAG110_ID IS 'FK: OKO_OPPDRAG_110';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OPPDRAG110_ID IS 'FK: OKO_OPPDRAG_110';
COMMENT ON COLUMN OKO_ATTESTANT_180.OPPDRAGS_LINJE_150_ID IS 'FK: OKO_OPPDRAG_LINJE_150';


--- TEAM LIBELLE:  HER MANGLER DOKUMENTASJON!!! FYLL INN ALLE MISSINGS
COMMENT ON TABLE OPPDRAG_KONTROLL IS 'MISSING TABLE COMMENT';   
COMMENT ON TABLE OKO_OPPDRAG_110 IS 'MISSING TABLE COMMENT';                
COMMENT ON TABLE OKO_OPPDRAG_ENHET_120 IS 'MISSING TABLE COMMENT';          
COMMENT ON TABLE OKO_AVSTEMMING_115 IS 'MISSING TABLE COMMENT';             
COMMENT ON TABLE OKO_OPPDRAG_LINJE_150 IS 'MISSING TABLE COMMENT';          
COMMENT ON TABLE OKO_ATTESTANT_180 IS 'MISSING TABLE COMMENT';

COMMENT ON COLUMN OPPDRAG_KONTROLL.SAKSNUMMER IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OPPDRAG_KONTROLL.VENTER_KVITTERING IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_ATTESTANT_180.ATTESTANT_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_AVSTEMMING_115.KODE_KOMPONENT IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_AVSTEMMING_115.NOKKEL_AVSTEMMING IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_AVSTEMMING_115.TIDSPNKT_MELDING IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_AKSJON IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_ENDRING IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_FAGOMRADE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.FAGSYSTEM_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.UTBET_FREKVENS IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAG_GJELDER_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_110.SAKSBEH_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.TYPE_ENHET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.ENHET IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.DATO_ENHET_FOM IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_ENDRING_LINJE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_STATUS_LINJE IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_STATUS_FOM IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.VEDTAK_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DELYTELSE_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_FOM IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_TOM IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_KLASSIFIK IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SATS IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.FRADRAG_TILLEGG IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.TYPE_SATS IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.BRUK_KJORE_PLAN IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SAKSBEH_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.UTBETALES_TIL_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_FAGSYSTEM_ID IS 'MISSING COLUMN COMMENT';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_DELYTELSE_ID IS 'MISSING COLUMN COMMENT';


