ALTER TABLE MOTTATTE_DOKUMENT DROP COLUMN BEHANDLING_GRUNNLAG_ID;
ALTER TABLE MOTTATTE_DOKUMENT DROP COLUMN STATUS;
ALTER TABLE MOTTATTE_DOKUMENT ADD (BEHANDLING_ID NUMBER(19) NOT NULL);

ALTER TABLE TILKNYTNING_NORGE DROP COLUMN TIDLIGERE_OPPHOLD_NORGE;
ALTER TABLE TILKNYTNING_NORGE DROP COLUMN FREMTIDIG_OPPHOLD_NORGE;

ALTER TABLE UTLANDSOPPHOLD DROP COLUMN TIDLIGERE_OPPHOLD_NORGE;
ALTER TABLE UTLANDSOPPHOLD DROP COLUMN FREMTIDIG_OPPHOLD_NORGE;
ALTER TABLE UTLANDSOPPHOLD ADD (TIDLIGERE_OPPHOLD VARCHAR2(1 CHAR) NOT NULL);
ALTER TABLE UTLANDSOPPHOLD ADD (OPPHOLD_NORGE NUMBER(19));
ALTER TABLE UTLANDSOPPHOLD ADD CONSTRAINT FK_UTLANDSOPPHOLD_1 FOREIGN KEY (OPPHOLD_NORGE) REFERENCES TILKNYTNING_NORGE;

INSERT INTO DOKUMENT_TYPE (kode, navn) VALUES ('SØKNAD', 'Søknad');
INSERT INTO DOKUMENT_TYPE (kode, navn) VALUES ('TERMINBEKREFTELSE', 'Terminbekreftelse');
INSERT INTO DOKUMENT_TYPE (kode, navn) VALUES ('ADOPSJONSPAPIRER', 'Adopsjonspapirer');

INSERT INTO MOTTATT_STATUS (kode, navn) VALUES ('MOTTATT', 'Mottatt');
INSERT INTO MOTTATT_STATUS (kode, navn) VALUES ('ETTERSPURT', 'Etterspurt');

INSERT INTO LANDKODER (kode, navn) VALUES ('NOR', 'Norge');
INSERT INTO LANDKODER (kode, navn) VALUES ('SWE', 'Sverige');
INSERT INTO LANDKODER (kode, navn) VALUES ('SYC', 'Seychellene');
INSERT INTO LANDKODER (kode, navn) VALUES ('USA', 'United States of America');

INSERT INTO SOEKNAD_ANNEN_PART_TYPE (kode, navn) VALUES ('MOR', 'Mor');
INSERT INTO SOEKNAD_ANNEN_PART_TYPE (kode, navn) VALUES ('MEDMOR', 'Medmor');
INSERT INTO SOEKNAD_ANNEN_PART_TYPE (kode, navn) VALUES ('FAR', 'Far');
INSERT INTO SOEKNAD_ANNEN_PART_TYPE (kode, navn) VALUES ('MEDFAR', 'Medfar');

INSERT INTO INNSENDINGSVALG (kode, navn) VALUES ('LASTET_OPP', 'Lastet opp');
INSERT INTO INNSENDINGSVALG (kode, navn) VALUES ('SEND_SENERE', 'Send senere');
INSERT INTO INNSENDINGSVALG (kode, navn) VALUES ('SENDES_IKKE', 'Sendes ikke');
