ALTER TABLE BG_PR_STATUS_OG_ANDEL
add andelsnr number(19,0);
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.andelsnr IS 'Nummer for å identifisere andel innanfor ein periode';

CREATE SEQUENCE SEQ_ANDELSNR MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

UPDATE BG_PR_STATUS_OG_ANDEL SET andelsnr = SEQ_ANDELSNR.NEXTVAL;

ALTER TABLE BG_PR_STATUS_OG_ANDEL modify andelsnr not null;
