ALTER TABLE BRUKER ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE BRUKER SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE BRUKER RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE BRUKER RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE BRUKER SET UNUSED(AKTOER_ID_OLD);
create unique index UIDX_BRUKER_1 ON BRUKER (AKTOER_ID);
------

ALTER TABLE SO_ANNEN_PART ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE SO_ANNEN_PART SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE SO_ANNEN_PART RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE SO_ANNEN_PART RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE SO_ANNEN_PART SET UNUSED(AKTOER_ID_OLD);
ALTER TABLE SO_ANNEN_PART RENAME COLUMN UTENLANDSK_FNR TO UTL_PERSON_IDENT;
ALTER TABLE SO_ANNEN_PART RENAME COLUMN UTENLANDSK_FNR_LAND TO UTL_PERSON_IDENT_LAND;
CREATE INDEX IDX_SO_ANNEN_PART_3 ON SO_ANNEN_PART(AKTOER_ID);
create index IDX_SO_ANNEN_PART_4 on SO_ANNEN_PART(UTL_PERSON_IDENT);

------
ALTER TABLE PO_STATSBORGERSKAP ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PO_STATSBORGERSKAP SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE PO_STATSBORGERSKAP RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE PO_STATSBORGERSKAP RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE PO_STATSBORGERSKAP SET UNUSED(AKTOER_ID_OLD);
create index IDX_PO_STATSBORGERSKAP_2 ON PO_STATSBORGERSKAP(AKTOER_ID);
------

ALTER TABLE PO_RELASJON ADD(FRA_AKTOER_ID_2 VARCHAR2(50 CHAR));
ALTER TABLE PO_RELASJON ADD(TIL_AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PO_RELASJON SET FRA_AKTOER_ID_2=FRA_AKTOER_ID;
UPDATE PO_RELASJON SET TIL_AKTOER_ID_2=TIL_AKTOER_ID;
COMMIT;
ALTER TABLE PO_RELASJON RENAME COLUMN FRA_AKTOER_ID TO FRA_AKTOER_ID_OLD;
ALTER TABLE PO_RELASJON RENAME COLUMN FRA_AKTOER_ID_2 TO FRA_AKTOER_ID;
ALTER TABLE PO_RELASJON SET UNUSED(FRA_AKTOER_ID_OLD);
ALTER TABLE PO_RELASJON RENAME COLUMN TIL_AKTOER_ID TO TIL_AKTOER_ID_OLD;
ALTER TABLE PO_RELASJON RENAME COLUMN TIL_AKTOER_ID_2 TO TIL_AKTOER_ID;
ALTER TABLE PO_RELASJON SET UNUSED(TIL_AKTOER_ID_OLD);
CREATE INDEX IDX_PO_RELASJON_2 ON PO_RELASJON(FRA_AKTOER_ID);
CREATE INDEX IDX_PO_RELASJON_3 ON PO_RELASJON(TIL_AKTOER_ID);

--------
ALTER TABLE PO_PERSONSTATUS ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PO_PERSONSTATUS SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE PO_PERSONSTATUS RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE PO_PERSONSTATUS RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE PO_PERSONSTATUS SET UNUSED(AKTOER_ID_OLD);
create index IDX_PO_PERSONSTATUS_2 ON PO_PERSONSTATUS(AKTOER_ID);
----------

ALTER TABLE PO_PERSONOPPLYSNING ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PO_PERSONOPPLYSNING SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE PO_PERSONOPPLYSNING RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE PO_PERSONOPPLYSNING RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE PO_PERSONOPPLYSNING SET UNUSED(AKTOER_ID_OLD);
create index IDX_PO_PERSONOPPLYSNING_2 ON PO_PERSONOPPLYSNING(AKTOER_ID);

---------
ALTER TABLE PO_ADRESSE ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PO_ADRESSE SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE PO_ADRESSE RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE PO_ADRESSE RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE PO_ADRESSE SET UNUSED(AKTOER_ID_OLD);
create index IDX_PO_ADRESSE_3 ON PO_ADRESSE(AKTOER_ID);

-----------

ALTER TABLE PERSONOPPLYSNING ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE PERSONOPPLYSNING SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE PERSONOPPLYSNING RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE PERSONOPPLYSNING RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE PERSONOPPLYSNING SET UNUSED(AKTOER_ID_OLD);
create index IDX_PERSONOPPLYSNING_12 ON PERSONOPPLYSNING(AKTOER_ID);
------------

ALTER TABLE IAY_AKTOER_INNTEKT ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE IAY_AKTOER_INNTEKT SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE IAY_AKTOER_INNTEKT RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE IAY_AKTOER_INNTEKT RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE IAY_AKTOER_INNTEKT SET UNUSED(AKTOER_ID_OLD);
create index IDX_IAY_AKTOER_INNTEKT_1 ON IAY_AKTOER_INNTEKT(AKTOER_ID);
---------

ALTER TABLE IAY_AKTOER_YTELSE ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE IAY_AKTOER_YTELSE SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE IAY_AKTOER_YTELSE RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE IAY_AKTOER_YTELSE RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE IAY_AKTOER_YTELSE SET UNUSED(AKTOER_ID_OLD);
create index IDX_IAY_AKTOER_YTELSE_1 ON IAY_AKTOER_YTELSE(AKTOER_ID);
----------
ALTER TABLE IAY_AKTOER_ARBEID ADD(AKTOER_ID_2 VARCHAR2(50 CHAR));
UPDATE IAY_AKTOER_ARBEID SET AKTOER_ID_2=AKTOER_ID;
COMMIT;
ALTER TABLE IAY_AKTOER_ARBEID RENAME COLUMN AKTOER_ID TO AKTOER_ID_OLD;
ALTER TABLE IAY_AKTOER_ARBEID RENAME COLUMN AKTOER_ID_2 TO AKTOER_ID;
ALTER TABLE IAY_AKTOER_ARBEID SET UNUSED(AKTOER_ID_OLD);
create index IDX_IAY_AKTOER_ARBEID_1 ON IAY_AKTOER_ARBEID(AKTOER_ID);


COMMENT ON COLUMN IAY_AKTOER_ARBEID.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN IAY_AKTOER_INNTEKT.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN IAY_AKTOER_YTELSE.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PERSONOPPLYSNING.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PO_ADRESSE.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PO_PERSONOPPLYSNING.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PO_STATSBORGERSKAP.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN SO_ANNEN_PART.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PO_PERSONSTATUS.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN UTGAAENDE_HENDELSE.AKTOER_ID IS 'Aktørid (fra NAV Aktørregister)';
COMMENT ON COLUMN PO_RELASJON.FRA_AKTOER_ID IS 'Aktørid (fra NAV Aktørregister) for fra-part i relasjon';
COMMENT ON COLUMN PO_RELASJON.TIL_AKTOER_ID IS 'Aktørid (fra NAV Aktørregister) for til-part i relasjon';
comment on column SO_ANNEN_PART.UTL_PERSON_IDENT is 'Utenlandsk person ident';
comment on column SO_ANNEN_PART.UTL_PERSON_IDENT_LAND is 'Utenlandsk person ident landkode (ISO 3-bokstav kode)';
