ALTER TABLE FAGSAK DROP CONSTRAINT FK_FAGSAK_1;
ALTER TABLE FAGSAK SET UNUSED(ARSAK_TYPE);
ALTER TABLE FAGSAK SET UNUSED(KL_ARSAK_TYPE);
DELETE FROM KODELISTE WHERE KODEVERK = 'FAGSAK_ARSAK';
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_MOTIV_TYPE';
