-- Ny tabell for relasjon mellom gjensidig utelukkende aksjonspunkter
CREATE TABLE AKSJONSPUNKT_UTELUKKENDE (
  ap1 VARCHAR2(50 char) NOT NULL,
  ap2 VARCHAR2(50 char) NOT NULL,
  opprettet_av    VARCHAR2(20 char) DEFAULT 'VL' NOT NULL,
  opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av       VARCHAR2(20 char),
  endret_tid      TIMESTAMP(3),
  CONSTRAINT PK_AP_UTELUKKENDE PRIMARY KEY (ap1, ap2)
);

ALTER TABLE AKSJONSPUNKT_UTELUKKENDE ADD CONSTRAINT FK_AP_UTELUKKENDE_1 FOREIGN KEY (ap1) REFERENCES AKSJONSPUNKT_DEF(kode);
ALTER TABLE AKSJONSPUNKT_UTELUKKENDE ADD CONSTRAINT FK_AP_UTELUKKENDE_2 FOREIGN KEY (ap2) REFERENCES AKSJONSPUNKT_DEF(kode);
CREATE INDEX IDX_AP_UTELUKKENDE_1 ON AKSJONSPUNKT_UTELUKKENDE(ap1);
CREATE INDEX IDX_AP_UTELUKKENDE_2 ON AKSJONSPUNKT_UTELUKKENDE(ap2);

COMMENT ON TABLE AKSJONSPUNKT_UTELUKKENDE IS 'Relasjon mellom aksjonspunktsdefinisjoner som er gjensidig utelukkende (dvs. kan ikke være i samme behandling samtidig)';
COMMENT ON COLUMN AKSJONSPUNKT_UTELUKKENDE.ap1 IS 'Aksjonspunkt 1';
COMMENT ON COLUMN AKSJONSPUNKT_UTELUKKENDE.ap2 IS 'Aksjonspunkt 2';

INSERT INTO AKSJONSPUNKT_UTELUKKENDE(ap1, ap2)
VALUES (5001, 5027);
