ALTER TABLE FAGSAK ADD(SAKSNUMMER_2 VARCHAR2(50 CHAR));
UPDATE FAGSAK SET SAKSNUMMER_2=SAKSNUMMER;
COMMIT;
ALTER TABLE FAGSAK RENAME COLUMN SAKSNUMMER TO SAKSNUMMER_OLD;
ALTER TABLE FAGSAK RENAME COLUMN SAKSNUMMER_2 TO SAKSNUMMER;
ALTER TABLE FAGSAK SET UNUSED(SAKSNUMMER_OLD);
create unique index UIDX_FAGSAK_1 ON FAGSAK (SAKSNUMMER);
COMMENT ON COLUMN FAGSAK.SAKSNUMMER IS 'Saksnummer (som GSAK har mottatt)';
------

ALTER TABLE OPPGAVE_BEHANDLING_KOBLING ADD(SAKSNUMMER_2 VARCHAR2(50 CHAR));
UPDATE OPPGAVE_BEHANDLING_KOBLING SET SAKSNUMMER_2=SAKS_ID;
COMMIT;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING RENAME COLUMN SAKS_ID TO SAKSNUMMER_OLD;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING RENAME COLUMN SAKSNUMMER_2 TO SAKSNUMMER;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING SET UNUSED(SAKSNUMMER_OLD);
create index IDX_OPPGAVE_BEHANDLING_KOBLI_7 ON OPPGAVE_BEHANDLING_KOBLING (SAKSNUMMER);
create unique index UIDX_OPPGAVE_BEHANDLING_KOBL_1 on OPPGAVE_BEHANDLING_KOBLING(BEHANDLING_ID, OPPGAVE_ID, OPPGAVE_AARSAK, SAKSNUMMER);
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.SAKSNUMMER IS 'Saksnummer (som GSAK har mottatt)';

-------

ALTER TABLE HISTORIKKINNSLAG_DOK_LINK RENAME COLUMN JOURNAL_POST_ID TO JOURNALPOST_ID;
alter table MOTTATT_DOKUMENT rename column journal_post_id to journalpost_id;
