UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1D"}' WHERE KODE = 'DAGLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1W"}' WHERE KODE = 'UKNLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P2W"}' WHERE KODE = '14DLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1M"}' WHERE KODE = 'MNDLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1Y"}' WHERE KODE = 'AARLG' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
