-- Manglende versjonsfelt
ALTER TABLE BEKREFTET_BARN add versjon NUMBER(19) DEFAULT 0 NOT NULL;
ALTER TABLE BEKREFTET_FORELDRE add versjon NUMBER(19) DEFAULT 0 NOT NULL;

-- FK til kodeverk
ALTER TABLE BEKREFTET_FORELDRE ADD CONSTRAINT FK_BEKREFTET_FORELDRE_2 FOREIGN KEY ( bruker_kjoenn ) REFERENCES bruker_kjoenn ( kode );



