ALTER TABLE SO_RETTIGHET ADD aleneomsorg VARCHAR2(1 CHAR) DEFAULT 'N';
ALTER TABLE SO_RETTIGHET DROP CONSTRAINT CHK_SO_RETTIGHET_01;
ALTER TABLE SO_RETTIGHET DROP CONSTRAINT CHK_SO_RETTIGHET_02;
ALTER TABLE SO_RETTIGHET MODIFY (omsorg_i_hele_perioden NULL);
ALTER TABLE SO_RETTIGHET MODIFY (annen_foreldre_rett NULL);
ALTER TABLE SO_RETTIGHET ADD CONSTRAINT CHK_SO_RETTIGHET_01 CHECK (omsorg_i_hele_perioden IS NULL OR aleneomsorg IN ('J', 'N'));
ALTER TABLE SO_RETTIGHET ADD CONSTRAINT CHK_SO_RETTIGHET_02 CHECK (annen_foreldre_rett IS NULL OR aleneomsorg IN ('J', 'N'));
ALTER TABLE SO_RETTIGHET ADD CONSTRAINT CHK_SO_RETTIGHET_03 CHECK (aleneomsorg IS NULL OR aleneomsorg IN ('J', 'N'));
