ALTER TABLE GR_ARBEID_INNTEKT
  ADD CONSTRAINT FK_GR_ARBEID_INNTEKT_2 FOREIGN KEY (INNTEKT_ARBEID_YTELSER_ID) REFERENCES INNTEKT_ARBEID_YTELSER;

ALTER TABLE AKTOER_ARBEID
  ADD CONSTRAINT FK_AKTOER_ARBEID_1 FOREIGN KEY (INNTEKT_ARBEID_YTELSER_ID) REFERENCES INNTEKT_ARBEID_YTELSER;

ALTER TABLE AKTOER_INNTEKT
  ADD CONSTRAINT FK_AKTOER_INNTEKT_1 FOREIGN KEY (INNTEKT_ARBEID_YTELSER_ID) REFERENCES INNTEKT_ARBEID_YTELSER;

ALTER TABLE YRKESAKTIVITET
  ADD CONSTRAINT FK_YRKESAKTIVITET_1 FOREIGN KEY (AKTOER_ARBEID_ID) REFERENCES AKTOER_ARBEID;

ALTER TABLE AKTIVITETS_AVTALE
  ADD CONSTRAINT FK_AKTIVITETS_AVTALE_1 FOREIGN KEY (YRKESAKTIVITET_ID) REFERENCES YRKESAKTIVITET;

ALTER TABLE RELATERTE_YTELSER
  ADD CONSTRAINT FK_RELATERTE_YTELSER_1 FOREIGN KEY (INNTEKT_ARBEID_YTELSER_ID) REFERENCES INNTEKT_ARBEID_YTELSER;

ALTER TABLE PERMISJON
  ADD CONSTRAINT FK_PERMISJON_1 FOREIGN KEY (YRKESAKTIVITET_ID) REFERENCES YRKESAKTIVITET;

