ALTER TABLE AKSJONSPUNKT
  ADD CONSTRAINT CHK_AKTIVT CHECK (aktivt = 'J' OR aktivt = 'N');

ALTER TABLE AKSJONSPUNKT
  ADD CONSTRAINT CHK_MANUELT_OPPRETTET CHECK (MANUELT_OPPRETTET = 'J' OR MANUELT_OPPRETTET = 'N');

