ALTER TABLE UTTAK_RESULTAT_PLAN ADD (
  BEHANDLING_RESULTAT_ID  NUMBER(19, 0),
  CONSTRAINT FK_UTTAK_RESULTAT_PLAN_1 FOREIGN KEY (BEHANDLING_RESULTAT_ID) REFERENCES BEHANDLING_RESULTAT(ID));

UPDATE UTTAK_RESULTAT_PLAN
SET BEHANDLING_RESULTAT_ID =
(SELECT DISTINCT ID FROM BEHANDLING_RESULTAT
WHERE BEHANDLING_RESULTAT.BEHANDLING_ID = UTTAK_RESULTAT_PLAN.BEHANDLING_ID);

ALTER TABLE UTTAK_RESULTAT_PLAN DROP CONSTRAINT FK_UTTAK_RESULTAT_PLAN;
ALTER TABLE UTTAK_RESULTAT_PLAN DROP COLUMN BEHANDLING_ID;
ALTER TABLE UTTAK_RESULTAT_PLAN MODIFY (BEHANDLING_RESULTAT_ID NUMBER(19, 0) NOT NULL);
