-- Rydde opp data som er relatert til adresse

UPDATE KODELISTE SET OFFISIELL_KODE='BOAD' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='BOSTEDSADRESSE';
UPDATE KODELISTE SET OFFISIELL_KODE='POST' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='POSTADRESSE';
UPDATE KODELISTE SET OFFISIELL_KODE='PUTL' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='POSTADRESSE_UTLAND';
UPDATE KODELISTE SET OFFISIELL_KODE='TIAD' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='MIDLERTIDIG_POSTADRESSE_NORGE';
UPDATE KODELISTE SET OFFISIELL_KODE='UTAD' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='MIDLERTIDIG_POSTADRESSE_UTLAND';
UPDATE KODELISTE SET OFFISIELL_KODE='UKJE' WHERE KODEVERK IN ('ADRESSE_TYPE') and KODE='UKJENT_ADRESSE';

ALTER TABLE OPPLYSNING_ADRESSE DROP CONSTRAINT FK_OPPLYSNING_ADRESSE_80;
ALTER TABLE OPPLYSNING_ADRESSE DROP COLUMN KL_OPPLYSNING_ADRESSE_TYPE;

ALTER TABLE OPPLYSNING_ADRESSE ADD KL_ADRESSE_TYPE VARCHAR2(100 CHAR) generated always as ('ADRESSE_TYPE') virtual;
ALTER TABLE OPPLYSNING_ADRESSE ADD CONSTRAINT FK_ADRESSE_80 FOREIGN KEY (ADRESSE_TYPE, KL_ADRESSE_TYPE) REFERENCES KODELISTE(kode, kodeverk);

DELETE FROM KODELISTE WHERE KODEVERK = 'OPPLYSNING_ADRESSE_TYPE';

DELETE FROM KODEVERK WHERE KODE IN ('OPPLYSNING_ADRESSE_TYPE','POSTADRESSE_TYPE');

