ALTER TABLE SO_FORDELING_PERIODE
ADD MORS_AKTIVITET  VARCHAR2(100 CHAR);
ALTER TABLE SO_FORDELING_PERIODE
  ADD kl_MORS_AKTIVITET  VARCHAR2(100 CHAR) AS ('MORS_AKTIVITET');

ALTER TABLE SO_FORDELING_PERIODE ADD CONSTRAINT FK_SO_FORDELING_PERIODE_3 FOREIGN KEY (kl_MORS_AKTIVITET, MORS_AKTIVITET) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON COLUMN SO_FORDELING_PERIODE.MORS_AKTIVITET IS 'Mors aktivitet i perioden.';

alter table SO_FORDELING_PERIODE drop CONSTRAINT CHK_SO_FORDELING_PERIODE_01;
alter table SO_FORDELING_PERIODE drop column arbeidsforhold_id;
