ALTER TABLE UTTAK_POSTERING ADD (
  UTTAK_RESULTAT_PLAN_ID  NUMBER(19, 0),
  CONSTRAINT FK_UTTAK_POSTERING_5 FOREIGN KEY (UTTAK_RESULTAT_PLAN_ID) REFERENCES UTTAK_RESULTAT_PLAN(ID));

UPDATE UTTAK_POSTERING
SET UTTAK_RESULTAT_PLAN_ID =
(SELECT DISTINCT UTTAK_RESULTAT_PLAN.ID
FROM UTTAK_RESULTAT_PLAN
INNER JOIN BEHANDLING_RESULTAT ON UTTAK_RESULTAT_PLAN.BEHANDLING_RESULTAT_ID = BEHANDLING_RESULTAT.ID
INNER JOIN BEHANDLING ON BEHANDLING_RESULTAT.BEHANDLING_ID = BEHANDLING.ID
WHERE BEHANDLING.ID = UTTAK_POSTERING.BEHANDLING_ID);

ALTER TABLE UTTAK_POSTERING DROP CONSTRAINT FK_UTTAK_POSTERING_3;
ALTER TABLE UTTAK_POSTERING DROP COLUMN BEHANDLING_ID;
ALTER TABLE UTTAK_POSTERING MODIFY (UTTAK_RESULTAT_PLAN_ID NUMBER(19, 0) NOT NULL);
