INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, OPPRETTET_AV, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT)
VALUES ('5051', 'Vurder perioder med opptjening', 'VURDER_OPPTJ.INN', 'Vurder perioder med opptjening', 'VL', 'FP_VK_23', 'N');
