ALTER TABLE UTTAK_RESULTAT_PERIODE ADD (
  KL_STOENADSKONTOTYPE               VARCHAR2(100)  AS ('STOENADSKONTOTYPE'),
  KL_AVKORTING_AARSAK_TYPE           VARCHAR2(100)  AS ('AVKORTING_AARSAK_TYPE'),
  KL_UTTAK_PERIODE_TYPE              VARCHAR2(100)  AS ('UTTAK_PERIODE_TYPE'),
  KL_PERIODE_RESULTAT_TYPE           VARCHAR2(100)  AS ('PERIODE_RESULTAT_TYPE'),
  CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_3 FOREIGN KEY (KL_STOENADSKONTOTYPE, STOENADSKONTOTYPE) REFERENCES KODELISTE(kodeverk, kode),
  CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_4 FOREIGN KEY (KL_AVKORTING_AARSAK_TYPE, AVKORTING_AARSAK_TYPE) REFERENCES KODELISTE(kodeverk, kode),
  CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_5 FOREIGN KEY (KL_UTTAK_PERIODE_TYPE, UTTAK_PERIODE_TYPE) REFERENCES KODELISTE(kodeverk, kode),
  CONSTRAINT FK_UTTAK_RESULTAT_PERIODE_6 FOREIGN KEY (KL_PERIODE_RESULTAT_TYPE, PERIODE_RESULTAT_TYPE) REFERENCES KODELISTE(kodeverk, kode)
);

/* UTTAK_POSTERINGER */
ALTER TABLE UTTAK_POSTERING ADD (
  KL_POSTERINGSTYPE            VARCHAR2(100) AS ('POSTERINGSTYPE'),
  CONSTRAINT FK_UTTAK_POSTERING_4 FOREIGN KEY (KL_POSTERINGSTYPE, POSTERINGSTYPE) REFERENCES KODELISTE(kodeverk, kode)
);
