ALTER TABLE BEHANDLING_DVH ADD RELATERT_TIL NUMBER(19);
ALTER TABLE BEHANDLING_DVH ADD FERDIG CHAR(1);
ALTER TABLE BEHANDLING_DVH ADD VEDTATT CHAR(1);
ALTER TABLE BEHANDLING_DVH ADD AVBRUTT CHAR(1);

COMMENT ON COLUMN BEHANDLING_DVH.RELATERT_TIL IS 'Behandling ID til forrige behandling';
COMMENT ON COLUMN BEHANDLING_DVH.FERDIG IS 'Angir om behandlingen er ferdig (fedig utbetalt eller fattet avslag)';
COMMENT ON COLUMN BEHANDLING_DVH.VEDTATT IS 'Angir om behandlingen har fått et positivt eller negativt vedtak';
COMMENT ON COLUMN BEHANDLING_DVH.AVBRUTT IS 'Angir om behandlingen har blitt avbrutt';

