ALTER TABLE aksjonspunkt_dvh
  ADD aksjonspunkt_def2 VARCHAR2(20 CHAR);
UPDATE aksjonspunkt_dvh
SET aksjonspunkt_def2 = aksjonspunkt_def;
COMMIT;
ALTER TABLE aksjonspunkt_dvh
  DROP COLUMN aksjonspunkt_def;
ALTER TABLE aksjonspunkt_dvh
  RENAME COLUMN aksjonspunkt_def2 TO aksjonspunkt_def;
ALTER TABLE AKSJONSPUNKT_DVH  
  MODIFY (AKSJONSPUNKT_DEF NOT NULL);

ALTER TABLE aksjonspunkt_dvh
  ADD TOTRINN_BEHANDLING2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE aksjonspunkt_dvh
SET TOTRINN_BEHANDLING2 = TOTRINN_BEHANDLING;
COMMIT;
ALTER TABLE aksjonspunkt_dvh
  DROP COLUMN TOTRINN_BEHANDLING;
ALTER TABLE aksjonspunkt_dvh
  RENAME COLUMN TOTRINN_BEHANDLING2 TO TOTRINN_BEHANDLING;


ALTER TABLE aksjonspunkt_dvh
  ADD TOTRINN_BEHANDLING_GODKJENT2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE aksjonspunkt_dvh
SET TOTRINN_BEHANDLING_GODKJENT2 = TOTRINN_BEHANDLING_GODKJENT;
COMMIT;
ALTER TABLE aksjonspunkt_dvh
  DROP COLUMN TOTRINN_BEHANDLING_GODKJENT;
ALTER TABLE aksjonspunkt_dvh
  RENAME COLUMN TOTRINN_BEHANDLING_GODKJENT2 TO TOTRINN_BEHANDLING_GODKJENT;


ALTER TABLE BEHANDLING_DVH
  ADD TOTRINNSBEHANDLING2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE BEHANDLING_DVH
SET TOTRINNSBEHANDLING2 = TOTRINNSBEHANDLING;
COMMIT;
ALTER TABLE BEHANDLING_DVH
  DROP COLUMN TOTRINNSBEHANDLING;
ALTER TABLE BEHANDLING_DVH
  RENAME COLUMN TOTRINNSBEHANDLING2 TO TOTRINNSBEHANDLING;

ALTER TABLE FAGSAK_DVH
  ADD BRUKER_AKTOER_ID2 VARCHAR2(20 CHAR);
UPDATE FAGSAK_DVH
SET BRUKER_AKTOER_ID2 = BRUKER_AKTOER_ID;
COMMIT;
ALTER TABLE FAGSAK_DVH
  DROP COLUMN BRUKER_AKTOER_ID;
ALTER TABLE FAGSAK_DVH
  RENAME COLUMN BRUKER_AKTOER_ID2 TO BRUKER_AKTOER_ID;
ALTER TABLE FAGSAK_DVH  
  MODIFY (BRUKER_AKTOER_ID NOT NULL); 
  
ALTER TABLE FAGSAK_DVH
  ADD EPS_AKTOER_ID2 VARCHAR2(20 CHAR);
UPDATE FAGSAK_DVH
SET EPS_AKTOER_ID2 = EPS_AKTOER_ID;
COMMIT;
ALTER TABLE FAGSAK_DVH
  DROP COLUMN EPS_AKTOER_ID;
ALTER TABLE FAGSAK_DVH
  RENAME COLUMN EPS_AKTOER_ID2 TO EPS_AKTOER_ID;

ALTER TABLE KONTROLL_DVH
  ADD LAST_FLAGG2 VARCHAR2(1 CHAR);
UPDATE KONTROLL_DVH
SET LAST_FLAGG2 = LAST_FLAGG;
COMMIT;
ALTER TABLE KONTROLL_DVH
  DROP COLUMN LAST_FLAGG;
ALTER TABLE KONTROLL_DVH
  RENAME COLUMN LAST_FLAGG2 TO LAST_FLAGG;
