#!/usr/bin/env groovy


def call(body) {
    try {
		env.LANG = "nb_NO.UTF-8"
		 
        stage ('Build') {
            sh 'mvn install -DskipTests' 
        }
		
	} catch (error) {
		throw error
	}
}

return this;