
RENAME BEHANDLING_AARSAK TO BEHANDLING_ARSAK;
RENAME SEQ_BEHANDLING_AARSAK TO SEQ_BEHANDLING_ARSAK;
ALTER TABLE BEHANDLING_ARSAK RENAME CONSTRAINT PK_BEHANDLING_AARSAK TO PK_BEHANDLING_ARSAK;
ALTER TABLE BEHANDLING_ARSAK RENAME CONSTRAINT FK_BEHANDLING_AARSAK_1 TO FK_BEHANDLING_ARSAK_1;
ALTER INDEX PK_BEHANDLING_AARSAK RENAME TO PK_BEHANDLING_ARSAK;
ALTER INDEX IDX_BEHANDLING_AARSAK_1 RENAME TO IDX_BEHANDLING_ARSAK_1;
ALTER TABLE BEHANDLING_ARSAK RENAME COLUMN BEHANDLING_AARSAK_TYPE TO BEHANDLING_ARSAK_TYPE;

