-- BEHANDLING_REL_YTELSER Legg til FK til behandlingsgrunnlag

ALTER TABLE BEHANDLING_REL_YTELSER ADD BEHANDLING_GRUNNLAG_ID NUMBER(19,0);

UPDATE BEHANDLING_REL_YTELSER BRY SET BRY.BEHANDLING_GRUNNLAG_ID = (
    SELECT B.BEHANDLING_GRUNNLAG_ID FROM BEHANDLING B, BEHANDLING_GRUNNLAG BG
    WHERE BG.ID = B.BEHANDLING_GRUNNLAG_ID
    AND B.ID = BRY.BEHANDLING_ID
    );

ALTER TABLE BEHANDLING_REL_YTELSER MODIFY BEHANDLING_GRUNNLAG_ID NUMBER(19,0) NOT NULL;

ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_BEHANDLING_REL_YTELSER_87 FOREIGN KEY (BEHANDLING_GRUNNLAG_ID) REFERENCES BEHANDLING_GRUNNLAG;

ALTER TABLE BEHANDLING_REL_YTELSER DROP COLUMN BEHANDLING_ID CASCADE CONSTRAINTS;
