-- OPPDRAG_KONTROLL
update OPPDRAG_KONTROLL set VENTER_KVITTERING = 'J' where VENTER_KVITTERING='Y';
alter table OPPDRAG_KONTROLL add constraint CHK_VENTER_KVITTERING check (VENTER_KVITTERING in ('J', 'N'));
-- DOKUMENT_MAL_TYPE
update DOKUMENT_MAL_TYPE set GENERISK = 'J' where GENERISK='Y';
alter table DOKUMENT_MAL_TYPE add constraint CHK_GENERISK check (GENERISK in ('J', 'N'));
-- DOKUMENT_FELLES
update DOKUMENT_FELLES set AUTOMATISK_BEHANDLET = 'J' where AUTOMATISK_BEHANDLET='Y';
alter table DOKUMENT_FELLES add constraint CHK_AUTOMATISK_BEHANDLET check (AUTOMATISK_BEHANDLET in ('J', 'N'));
-- ADOPSJON
update ADOPSJON set EKTEFELLES_BARN = 'J' where EKTEFELLES_BARN='Y';
update ADOPSJON set ADOPTERER_ALENE = 'J' where ADOPTERER_ALENE='Y';
alter table ADOPSJON add constraint CHK_EKTEFELLES_BARN check (EKTEFELLES_BARN in ('J', 'N'));
alter table ADOPSJON add constraint CHK_ADOPTERER_ALENE check (ADOPTERER_ALENE in ('J', 'N'));
-- BEKREFTET_BARN
update BEKREFTET_BARN set BEKREFTET_VIA_TPS = 'J' where BEKREFTET_VIA_TPS='Y';
alter table BEKREFTET_BARN add constraint CHK_BEKREFTET_VIA_TPS check (BEKREFTET_VIA_TPS in ('J', 'N'));
-- BEKREFTET_FORELDRE
update BEKREFTET_FORELDRE set BEKREFTET_VIA_TPS = 'J' where BEKREFTET_VIA_TPS='Y';
alter table BEKREFTET_FORELDRE add constraint CHK_BEKREFTET_VIA_TPS2 check (BEKREFTET_VIA_TPS in ('J', 'N'));
