-- start sette opp nav offisielle kodeverk og knytte mot eget.
update KODELISTE set offisiell_kode = kode where kodeverk in ('POSTSTED', 'LANDKODER', 'PERSONSTATUS', 'SPRAAK_KODE', 'BRUKER_KJOENN');

update kodeverk set kodeverk_eier='Kodeverkforvaltning', kodeverk_eier_ref ='http://nav.no/kodeverk/Kodeverk/Postnummer', kodeverk_eier_ver='6', kodeverk_eier_navn='Postnummer' where kode='POSTSTED';
update kodeverk set kodeverk_eier='Kodeverkforvaltning', kodeverk_eier_ref ='http://nav.no/kodeverk/Kodeverk/Landkoder', kodeverk_eier_ver='2', kodeverk_eier_navn='Landkoder', beskrivelse='NAV kopi av ISO 3166-1-alpha-3 3-bokstav landkoder' where kode='LANDKODER';

update kodeverk set kodeverk_eier='Kodeverkforvaltning', kodeverk_eier_ref ='http://nav.no/kodeverk/Kodeverk/Personstatuser', kodeverk_eier_ver='1', kodeverk_eier_navn='Personstatuser' where kode='PERSONSTATUS';
update kodeverk set kodeverk_synk_nye='N', kodeverk_eier='Kodeverkforvaltning', kodeverk_eier_ref ='http://nav.no/kodeverk/Kodeverk/Spr_c3_a5k', kodeverk_eier_ver='1', kodeverk_eier_navn='Språk', beskrivelse='NAV kopi av ISO 639-1 2-bokstavsspråk kode i store bokstaver' where kode='SPRAAK_KODE';

update kodeverk set kodeverk_synk_nye='N', kodeverk_eier='Kodeverkforvaltning', kodeverk_eier_ref ='http://nav.no/kodeverk/Kodeverk/Kj_c3_b8nnstyper', kodeverk_eier_ver='1', kodeverk_eier_navn='Kjønnstyper' where kode='BRUKER_KJOENN';

--korrigeringer
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'AKSJONSPUNKT_KATEGORI', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'AKSJONSPUNKT_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'BEHANDLING_AARSAK', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'BEHANDLING_STEG_STATUS', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'BRUKER_KJOENN', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'BRUKER_ROLLE_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'DOKUMENT_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'FAGSAK_ARSAK', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'FAGSAK_YTELSE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'FAR_SOEKER_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'FORELDRE_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'HISTORIKK_AKTOER', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'LAGRET_VEDTAK_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'LANDKODER', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'MEDLEMSKAP_DEKNING', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'MEDLEMSKAP_KILDE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'MEDLEMSKAP_MANUELL_VURD', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'MEDLEMSKAP_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'OMSORGSOVERTAKELSE_VILKAR', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'OPPGAVE_AARSAK', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'PERIODE_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'PERSONSTATUS_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'REGION', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'RELATERT_YTELSE_RESULTAT', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'RELATERT_YTELSE_SAKSTYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'SOEKNAD_ANNEN_PART', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'SPRAAK_KODE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'VILKAR_RESULTAT_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'VILKAR_UTFALL_MERKNAD', to_date('2000-01-01', 'YYYY-MM-DD'));
insert into KODELISTE (id, kode, navn, beskrivelse,kodeverk, gyldig_fom) values (seq_kodeliste.nextval, '-', 'Ikke definert', 'Ikke definert', 'VILKAR_UTFALL_TYPE', to_date('2000-01-01', 'YYYY-MM-DD'));


update AKSJONSPUNKT_DEF set AKSJONSPUNKT_KATEGORI='-' where AKSJONSPUNKT_KATEGORI is null;
update AKSJONSPUNKT_DEF set AKSJONSPUNKT_TYPE='-' where AKSJONSPUNKT_TYPE is null;
update BEHANDLING_REL_YTELSER set RELATERT_YTELSE_RESULTAT='-' where RELATERT_YTELSE_RESULTAT is null;
update BEHANDLING_REL_YTELSER set RELATERT_YTELSE_SAKSTYPE='-' where RELATERT_YTELSE_SAKSTYPE is null;

update BEKREFTET_FORELDRE set BRUKER_KJOENN='-' where BRUKER_KJOENN is null;
update BEKREFTET_FORELDRE set FORELDRETYPE='-' where FORELDRETYPE is null;
update BEKREFTET_FORELDRE set OVERSTYRT_PERSONSTATUS_TYPE='-' where OVERSTYRT_PERSONSTATUS_TYPE is null;
update BEKREFTET_FORELDRE set PERSONSTATUSTYPE='-' where PERSONSTATUSTYPE is null;
update BEKREFTET_FORELDRE set REGION='-' where REGION is null;
update BRUKER set BRUKER_KJOENN='-' where BRUKER_KJOENN is null;
update BRUKER set SPRAAK_KODE='-' where SPRAAK_KODE is null;
update DOKUMENT_FELLES set SPRAAK_KODE='-' where SPRAAK_KODE is null;
update HISTORIKKINNSLAG set HISTORIKK_AKTOER_ID='-' where HISTORIKK_AKTOER_ID is null;
update INNGANGSVILKAR_RESULTAT set VILKAR_RESULTAT='-' where VILKAR_RESULTAT is null;

update LAGRET_VEDTAK set LAGRET_VEDTAK_TYPE='-' where LAGRET_VEDTAK_TYPE is null;
update LAND_REGION set LANDKODE='-' where LANDKODE is null;
update LAND_REGION set REGION='-' where REGION is null;
update MEDLEMSKAP set MEDLEMSPERIODE_MANUELL_VURD='-' where MEDLEMSPERIODE_MANUELL_VURD is null;
update MEDLEMSKAP_PERIODER set DEKNINGTYPE='-' where DEKNINGTYPE is null;
update MEDLEMSKAP_PERIODER set KILDETYPE='-' where KILDETYPE is null;
update MEDLEMSKAP_PERIODER set LOVVALGSLAND='-' where LOVVALGSLAND is null;
update MEDLEMSKAP_PERIODER set MEDLEMSKAPTYPE='-' where MEDLEMSKAPTYPE is null;
update MEDLEMSKAP_PERIODER set STUDIELAND='-' where STUDIELAND is null;

update OMSORGSOVERTAKELSE set VILKAARSTYPE='-' where VILKAARSTYPE is null;
update OPPGAVE_BEHANDLING_KOBLING set OPPGAVE_AARSAK='-' where OPPGAVE_AARSAK is null;
update SATS set SATS_TYPE='-' where SATS_TYPE is null;
update SOEKNAD set FAR_SOEKER_TYPE='-' where FAR_SOEKER_TYPE is null;
update SOEKNAD_ANNEN_PART set TYPE='-' where TYPE is null;
update SOEKNAD_ANNEN_PART set UTENLANDSK_FNR_LAND='-' where UTENLANDSK_FNR_LAND is null;
update SOEKNAD_VEDLEGG set INNSENDINGSVALG='-' where INNSENDINGSVALG is null;
update STATSBORGERSKAP set LANDKODE='-' where LANDKODE is null;
update TILKNYTNING_HJEMLAND set PERIODETYPE='-' where PERIODETYPE is null;
update UTLANDSOPPHOLD set LAND='-' where LAND is null;
update VILKAR set VILKAR_UTFALL='-' where VILKAR_UTFALL is null;
update VILKAR set VILKAR_UTFALL_MERKNAD='-' where VILKAR_UTFALL_MERKNAD is null;

alter table BEHANDLING_STEG_TILSTAND modify (behandling_steg_status NOT NULL);
alter table MEDLEMSKAP modify (medlemsperiode_manuell_vurd NOT NULL);
alter table MEDLEMSKAP_PERIODER modify (lovvalgsland NOT NULL);
alter table MEDLEMSKAP_PERIODER modify (studieland NOT NULL);
alter table MEDLEMSKAP_PERIODER modify (medlemskapType NOT NULL);
alter table MEDLEMSKAP_PERIODER modify (dekningType NOT NULL);
alter table MEDLEMSKAP_PERIODER modify (kildeType NOT NULL);
alter table OMSORGSOVERTAKELSE modify (vilkaarstype NOT NULL);
alter table SOEKNAD modify (far_soeker_type NOT NULL);
alter table SOEKNAD_ANNEN_PART modify (utenlandsk_fnr_land NOT NULL);
alter table TILKNYTNING_HJEMLAND modify (periodetype NOT NULL);
alter table BEHANDLING_REL_YTELSER modify (relatert_ytelse_sakstype NOT NULL);
alter table BEHANDLING_REL_YTELSER modify (relatert_ytelse_resultat NOT NULL);
alter table VILKAR modify (vilkar_utfall NOT NULL);
alter table VILKAR modify (vilkar_utfall_merknad NOT NULL);
ALTER TABLE MEDLEMSKAP_PERIODER modify (KL_MEDLEMSKAP_DEKNING not null);
ALTER TABLE MEDLEMSKAP_PERIODER modify (KL_LANDKODER not null);
ALTER TABLE VILKAR modify (KL_VILKAR_UTFALL_MERKNAD not null);
ALTER TABLE SOEKNAD_ANNEN_PART modify (KL_LANDKODER not null);
ALTER TABLE BEKREFTET_FORELDRE modify (FORELDRETYPE not null);
ALTER TABLE BEKREFTET_FORELDRE modify (KL_FORELDRE_TYPE not null);
ALTER TABLE MOTTATTE_DOKUMENT modify (KL_DOKUMENT_TYPE not null);
ALTER TABLE BEHANDLING_GRUNNLAG modify (KL_RELATERTE_YTELSER_STATUS not null);
ALTER TABLE LAND_REGION modify (KL_REGION not null);
ALTER TABLE AKSJONSPUNKT_DEF modify (KL_AKSJONSPUNKT_KATEGORI not null);
ALTER TABLE STATSBORGERSKAP modify (KL_LANDKODER not null);
ALTER TABLE KONFIG_VERDI_KODE modify (KL_KONFIG_VERDI_GRUPPE not null);
ALTER TABLE FAGSAK modify (KL_FAGSAK_STATUS not null);
ALTER TABLE AKSJONSPUNKT modify (AKSJONSPUNKT_STATUS not null);
ALTER TABLE AKSJONSPUNKT modify (KL_AKSJONSPUNKT_STATUS not null);
ALTER TABLE SOEKNAD_VEDLEGG modify (KL_INNSENDINGSVALG not null);
ALTER TABLE LAND_REGION modify (KL_LANDKODER not null);
ALTER TABLE UTLANDSOPPHOLD modify (KL_LANDKODER not null);
ALTER TABLE BEHANDLING modify (KL_BEHANDLING_STATUS not null);
ALTER TABLE MEDLEMSKAP modify (KL_MEDLEMSKAP_MANUELL_VURD not null);
ALTER TABLE BEKREFTET_FORELDRE modify (REGION not null);
ALTER TABLE BEKREFTET_FORELDRE modify (KL_REGION not null);
ALTER TABLE MEDLEMSKAP_PERIODER modify (KL_MEDLEMSKAP_TYPE not null);
ALTER TABLE BEHANDLING_STEG_TILSTAND modify (KL_BEHANDLING_STEG_STATUS not null);
ALTER TABLE INNGANGSVILKAR_RESULTAT modify (KL_VILKAR_RESULTAT_TYPE not null);
ALTER TABLE BEHANDLING_VEDTAK modify (KL_IVERKSETTING_STATUS not null);
ALTER TABLE BEHANDLING_REL_YTELSER modify (KL_RELATERT_YTELSE_TYPE not null);
ALTER TABLE HISTORIKKINNSLAG modify (KL_HISTORIKK_AKTOER not null);
ALTER TABLE DOKUMENT_MAL_TYPE modify (KL_DOKUMENT_MAL_RESTRIKSJON not null);
ALTER TABLE SOEKNAD_ANNEN_PART modify (KL_SOEKNAD_ANNEN_PART not null);
ALTER TABLE BEHANDLING_RESULTAT modify (KL_BEHANDLING_RESULTAT_TYPE not null);
ALTER TABLE BEHANDLING_REL_YTELSER modify (KL_RELATERT_YTELSE_RESULTAT not null);
ALTER TABLE FAGSAK_RELASJON modify (KL_FAGSAK_YTELSE not null);
ALTER TABLE OMSORGSOVERTAKELSE modify (KL_OMSORGSOVERTAKELSE_VILKAR not null);
ALTER TABLE AKSJONSPUNKT_DEF modify (AKSJONSPUNKT_TYPE not null);
ALTER TABLE AKSJONSPUNKT_DEF modify (KL_AKSJONSPUNKT_TYPE not null);
ALTER TABLE KONFIG_VERDI_KODE modify (KL_KONFIG_VERDI_TYPE not null);
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING modify (KL_OPPGAVE_AARSAK not null);
ALTER TABLE FAGSAK_RELASJON modify (KL_FAGSAK_ARSAK not null);
ALTER TABLE BEHANDLING_REL_YTELSER modify (RELATERT_YTELSE_TILSTAND not null);
ALTER TABLE BEHANDLING_REL_YTELSER modify (KL_RELATERT_YTELSE_TILSTAND not null);
ALTER TABLE MEDLEMSKAP_PERIODER modify (KL_MEDLEMSKAP_KILDE not null);
ALTER TABLE SOEKNAD modify (KL_FAR_SOEKER_TYPE not null);
ALTER TABLE BEHANDLING_VEDTAK modify (KL_VEDTAK_RESULTAT_TYPE not null);
ALTER TABLE BEHANDLING_REL_YTELSER modify (KL_RELATERT_YTELSE_SAKSTYPE not null);
ALTER TABLE FAGSAK modify (KL_BRUKER_ROLLE_TYPE not null);
ALTER TABLE SATS modify (KL_SATS_TYPE not null);
ALTER TABLE BEKREFTET_FORELDRE modify (KL_BRUKER_KJOENN not null);
ALTER TABLE BRUKER modify (KL_BRUKER_KJOENN not null);
ALTER TABLE BRUKER modify (KL_SPRAAK_KODE not null);
ALTER TABLE DOKUMENT_FELLES modify (KL_SPRAAK_KODE not null);
ALTER TABLE VILKAR modify (KL_VILKAR_UTFALL_TYPE not null);
ALTER TABLE TILKNYTNING_HJEMLAND modify (KL_PERIODE_TYPE not null);
ALTER TABLE BEKREFTET_FORELDRE modify (PERSONSTATUSTYPE not null);
ALTER TABLE BEKREFTET_FORELDRE modify (KL_PERSONSTATUS_TYPE not null);
ALTER TABLE BEKREFTET_FORELDRE MODIFY (OVERSTYRT_PERSONSTATUS_TYPE NOT NULL);
