-- Endre navn: Innhent saksopplysninger ->  Innhent Registeropplysninger
ALTER TABLE VURDERINGSPUNKT_DEF DISABLE CONSTRAINT FK_VURDERINGSPUNKT_DEF_1;
ALTER TABLE AKSJONSPUNKT_DEF DISABLE CONSTRAINT FK_AKSJONSPUNKT_DEF_2;
ALTER TABLE BEHANDLING_TYPE_STEG_SEKV DISABLE CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_01;
ALTER TABLE AKSJONSPUNKT DISABLE CONSTRAINT FK_AKSJONSPUNKT_1;

UPDATE BEHANDLING_STEG_TYPE SET KODE = 'INREG' WHERE KODE = 'INSAK';

UPDATE VURDERINGSPUNKT_DEF SET BEHANDLING_STEG = 'INREG', KODE = 'INREG.INN'  WHERE BEHANDLING_STEG = 'INSAK' AND KODE = 'INSAK.INN';
UPDATE VURDERINGSPUNKT_DEF SET BEHANDLING_STEG = 'INREG', KODE = 'INREG.UT'  WHERE BEHANDLING_STEG = 'INSAK' AND KODE = 'INSAK.UT';

UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'INREG.INN' where VURDERINGSPUNKT = 'INSAK.INN';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'INREG.UT' where VURDERINGSPUNKT = 'INSAK.UT';

UPDATE AKSJONSPUNKT SET BEHANDLING_STEG_FUNNET = 'INREG' WHERE BEHANDLING_STEG_FUNNET = 'INSAK';

UPDATE BEHANDLING_TYPE_STEG_SEKV SET BEHANDLING_STEG_TYPE = 'INREG' WHERE BEHANDLING_STEG_TYPE = 'INSAK';

ALTER TABLE VURDERINGSPUNKT_DEF ENABLE CONSTRAINT FK_VURDERINGSPUNKT_DEF_1;
ALTER TABLE AKSJONSPUNKT_DEF ENABLE CONSTRAINT FK_AKSJONSPUNKT_DEF_2;
ALTER TABLE BEHANDLING_TYPE_STEG_SEKV ENABLE CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_01;
ALTER TABLE AKSJONSPUNKT ENABLE CONSTRAINT FK_AKSJONSPUNKT_1;

-- Introdusere nytt steg: Registrer søknad
INSERT INTO BEHANDLING_STEG_TYPE(kode, navn, behandling_status_def, beskrivelse)
VALUES ('REGSØK', 'Registrer søknad', 'UTRED', 'Registrering av papirsøknad');

INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('REGSØK.INN', 'Registrer søknad - Inngang', 'REGSØK', 'INN');
INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('REGSØK.UT', 'Registrer søknad - Utgang', 'REGSØK', 'UT');

-- Introdusere nytt steg: Innhent søknadsopplysninger
INSERT INTO BEHANDLING_STEG_TYPE(kode, navn, behandling_status_def, beskrivelse)
VALUES ('INSØK', 'Innhent søknadsopplysninger', 'UTRED', 'Innhenting av søknadsopplysninger');

INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('INSØK.INN', 'Innhent søknadsopplysninger - Inngang', 'INSØK', 'INN');
INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('INSØK.UT', 'Innhent søknadsopplysninger - Utgang', 'INSØK', 'UT');

UPDATE BEHANDLING_TYPE_STEG_SEKV SET sekvens_nr = sekvens_nr + 2 WHERE sekvens_nr >= 1;
INSERT INTO BEHANDLING_TYPE_STEG_SEKV (id, behandling_type, behandling_steg_type, sekvens_nr)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-002', 'REGSØK', 1);
INSERT INTO BEHANDLING_TYPE_STEG_SEKV (id, behandling_type, behandling_steg_type, sekvens_nr)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-002', 'INSØK', 2);

-- Flytting av aksjonspunkter fra mottak -> nytt steg

-- Nye aksjonspunkter

