-- pkmantis-188
ALTER TABLE HISTORIKKINNSLAG MODIFY behandling_id NUMBER(19) NULL;
ALTER TABLE HISTORIKKINNSLAG ADD fagsak_id NUMBER(19) NOT NULL;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_3 FOREIGN KEY (fagsak_id) REFERENCES FAGSAK;

-- refaktoring - sett kjoenn i tabell
ALTER TABLE HISTORIKKINNSLAG ADD bruker_kjoenn    VARCHAR2(100 CHAR) NOT NULL;
ALTER TABLE HISTORIKKINNSLAG ADD kl_bruker_kjoenn VARCHAR2(100 CHAR) AS ('BRUKER_KJOENN') NOT NULL;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_4  FOREIGN KEY (kl_bruker_kjoenn, bruker_kjoenn) REFERENCES KODELISTE (kodeverk, kode);
CREATE INDEX IDX_HISTORIKKINNSLAG_02 ON HISTORIKKINNSLAG(bruker_kjoenn);


-- opprydding navnestandard
ALTER TABLE HISTORIKKINNSLAG_DOK_LINK RENAME COLUMN tag TO link_tekst;



