-- AKSJONSPUNKT
update AKSJONSPUNKT set TOTRINNSBEHANDLING = 'J' where TOTRINNSBEHANDLING='Y';
update AKSJONSPUNKT set TOTRINNSBEHANDLING_GODKJENT = 'J' where TOTRINNSBEHANDLING_GODKJENT='Y';
alter table AKSJONSPUNKT add constraint CHK_TOTRINNSBEHANDLING check (TOTRINNSBEHANDLING in ('J', 'N'));
alter table AKSJONSPUNKT add constraint CHK_TOTRINNSBEHANDLING_GODKJ check (TOTRINNSBEHANDLING_GODKJENT in ('J', 'N'));
-- AKSJONSPUNKT_DEF
update AKSJONSPUNKT_DEF set ALLTID_TOTRINNSBEHANDLING = 'J' where ALLTID_TOTRINNSBEHANDLING='Y';
alter table AKSJONSPUNKT_DEF add constraint CHK_ALLTID_TOTRINNSBEH check (ALLTID_TOTRINNSBEHANDLING in ('J', 'N'));
-- OPPGAVE_BEHANDLING_KOBLING
update OPPGAVE_BEHANDLING_KOBLING set FERDIGSTILT = 'J' where FERDIGSTILT='Y';
alter table OPPGAVE_BEHANDLING_KOBLING add constraint CHK_FERDIGSTILT check (FERDIGSTILT in ('J', 'N'));
-- MEDLEMSKAP
update MEDLEMSKAP set OPPHOLDSRETT_VURDERING = 'J' where OPPHOLDSRETT_VURDERING='Y';
update MEDLEMSKAP set LOVLIG_OPPHOLD_VURDERING = 'J' where LOVLIG_OPPHOLD_VURDERING='Y';
update MEDLEMSKAP set BOSATT_VURDERING = 'J' where BOSATT_VURDERING='Y';
update MEDLEMSKAP set ER_EOS_BORGER = 'J' where ER_EOS_BORGER='Y';
alter table MEDLEMSKAP add constraint CHK_OPPHOLDSRETT_VURDERING check (OPPHOLDSRETT_VURDERING in ('J', 'N'));
alter table MEDLEMSKAP add constraint CHK_LOVLIG_OPPHOLD_VURDERING check (LOVLIG_OPPHOLD_VURDERING in ('J', 'N'));
alter table MEDLEMSKAP add constraint CHK_BOSATT_VURDERING check (BOSATT_VURDERING in ('J', 'N'));
alter table MEDLEMSKAP add constraint CHK_ER_EOS_BORGER check (ER_EOS_BORGER in ('J', 'N'));
-- VILKAR
update VILKAR set MANUELT_VURDERT = 'J' where MANUELT_VURDERT='Y';
alter table VILKAR add constraint CHK_MANUELT_VURDERT check (MANUELT_VURDERT in ('J', 'N'));
-- BEHANDLING_REL_YTELSER
update BEHANDLING_REL_YTELSER set SOEKER = 'J' where SOEKER='Y';
alter table BEHANDLING_REL_YTELSER add constraint CHK_SOEKER check (SOEKER in ('J', 'N'));
