update AKSJONSPUNKT_DEF set VURDERINGSPUNKT = 'REGSØK.UT', BESKRIVELSE = 'Registrer ustrukturert papirsøknad'
WHERE KODE = '5012';

update AKSJONSPUNKT_DEF set VURDERINGSPUNKT = 'INREG.UT' WHERE KODE = '5024';


update AKSJONSPUNKT_DEF set VURDERINGSPUNKT = 'INREG.UT' WHERE KODE = '5024';

update AKSJONSPUNKT_DEF set VURDERINGSPUNKT = 'INSØK.UT' WHERE KODE = '7003';
