ALTER TABLE DOKUMENT_DATA DROP CONSTRAINT FK_DOKUMENT_DATA_1;
ALTER TABLE DOKUMENT_DATA DROP COLUMN DOKUMENT_FELLES_ID;

ALTER TABLE DOKUMENT_FELLES ADD DOKUMENT_DATA_ID NUMBER(19) NOT NULL;
ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_4 FOREIGN KEY ( dokument_data_id ) REFERENCES DOKUMENT_DATA ( id );

ALTER TABLE DOKUMENT_FELLES ADD JOURNALPOST_ID NUMBER(19) NULL;

comment on column DOKUMENT_FELLES.JOURNALPOST_ID is 'Referanse til journalposten i Joark.';

ALTER TABLE DOKUMENT_DATA DROP COLUMN JOURNAL_POST_ID;
