INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, AKSJONSPUNKT_KATEGORI, VILKAR_TYPE, VURDERINGSPUNKT, ALLTID_TOTRINNSBEHANDLING, BESKRIVELSE, AKSJONSPUNKT_TYPE)
VALUES ('5033', 'Vurdere annen ytelse før vedtak', 'APK-002', NULL , 'FORVEDSTEG.INN', 'N', 'Det finnes en åpen oppgave av type "Vurder annen ytelse før vedtak"', 'MANU');

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, AKSJONSPUNKT_KATEGORI, VILKAR_TYPE, VURDERINGSPUNKT, ALLTID_TOTRINNSBEHANDLING, BESKRIVELSE, AKSJONSPUNKT_TYPE)
VALUES ('5034', 'Vurdere dokument før vedtak', 'APK-002', NULL , 'FORVEDSTEG.INN', 'N', 'Det finnes en åpen oppgave av type "Vurder dokument før vedtak"', 'MANU');
