-- Tabell DOKUMENT_MAL_TYPE
ALTER TABLE DOKUMENT_MAL_TYPE ADD DOKSYS_KODE VARCHAR2(20 CHAR) default 'INGEN' NOT NULL;

UPDATE DOKUMENT_MAL_TYPE SET DOKSYS_KODE = KODE;

UPDATE DOKUMENT_MAL_TYPE SET KODE = 'POSVED' WHERE KODE = '000048';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'INNHEN' WHERE KODE = '000049';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'HENLEG' WHERE KODE = '000050';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'AVSLAG' WHERE KODE = '000051';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'UENDRE' WHERE KODE = '000052';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'FORLEN' WHERE KODE = '000056';
UPDATE DOKUMENT_MAL_TYPE SET KODE = 'REVURD' WHERE KODE = '000058';

INSERT INTO DOKUMENT_MAL_TYPE (kode, navn, DOKUMENT_MAL_RESTRIKSJON, generisk, DOKSYS_KODE)
VALUES ('FORLME', 'Forlenget saksbehandlingstid - medlem', 'ÅPEN_BEHANDLING', 'Y', '000056');
