ALTER TABLE MEDLEMSKAP_PERIODER RENAME COLUMN lovvalgsland TO lovvalg_land;
ALTER TABLE MEDLEMSKAP_PERIODER RENAME COLUMN studieland TO studie_land;
ALTER TABLE MEDLEMSKAP_PERIODER RENAME COLUMN medlemskapType TO medlemskap_type;
ALTER TABLE MEDLEMSKAP_PERIODER RENAME COLUMN dekningType TO dekning_type;
ALTER TABLE MEDLEMSKAP_PERIODER RENAME COLUMN kildeType TO kilde_type;
