-- Endrer navn på kolonner
ALTER TABLE BEHANDLING_REL_YTELSER RENAME COLUMN IVERKSETTELSESDATO TO IVERKSETTELSE_DATO;
ALTER TABLE BEHANDLING_REL_YTELSER RENAME COLUMN OPPHOERFOMDATO TO OPPHOER_FOM;
ALTER TABLE BEHANDLING_REL_YTELSER RENAME COLUMN REGISTRERINGSDATO TO REGISTRERING_DATO;
ALTER TABLE BEHANDLING_REL_YTELSER RENAME COLUMN VEDTAKDATO  TO VEDTAK_DATO;
ALTER TABLE BEHANDLING_RESULTAT RENAME COLUMN AVSLAGSARSAK_FRITEKST TO AVSLAG_ARSAK_FRITEKST;
ALTER TABLE BEHANDLING_VEDTAK RENAME COLUMN VEDTAKSDATO TO VEDTAK_DATO;
ALTER TABLE DOKUMENT_ADRESSE RENAME COLUMN MOTTAKERNAVN TO MOTTAKER_NAVN;
ALTER TABLE DOKUMENT_ADRESSE RENAME COLUMN POST_NUMMER TO POSTNUMMER;
ALTER TABLE DOKUMENT_FELLES RENAME COLUMN KONTAKT_TELEFON_NUMMER TO KONTAKT_TLF;
ALTER TABLE DOKUMENT_FELLES RENAME COLUMN SPRAAK_KODE TO SPRAK_KODE;

-- Endrer navn på tabell
ALTER TABLE VURDER_PAA_NYTT_AARSAK_TYPE RENAME TO VURDER_ARSAK;

-- Fjerne ident kolonne fra tabell BEHANDLING_REL_YTELSER
ALTER TABLE BEHANDLING_REL_YTELSER DROP COLUMN IDENT;
