INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, VILKAR_TYPE, SKJERMLENKE_TYPE)
VALUES ('5053', 'Avklar fortsatt medlemskap.', 'VURDERMV.INN', 'Avklar fortsatt medlemskap.', 'N', 'MANU', 'FP_VK_2', 'FAKTA_OM_MEDLEMSKAP');
