INSERT INTO VURDERINGSPUNKT_DEF (kode, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, navn)
VALUES ('KOFAKUT.UT', 'KOFAKUT', 'UT', 'Kontroller fakta for uttak - Utgang');

INSERT INTO VURDERINGSPUNKT_DEF (kode, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, navn)
VALUES ('KOFAKUT.INN', 'KOFAKUT', 'INN', 'Kontroller fakta for uttak - Utgang');

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT)
VALUES ('5070', 'Avklar fakta uttak', 'KOFAKUT.UT', 'Registrer ustrukturert papirsøknad foreldrepenger', '-', 'N');
