ALTER TABLE INNTEKTSGRUNNLAG_MOCK MODIFY bruttoinntekt DECIMAL(19,2);
ALTER TABLE INNTEKTSGRUNNLAG_MOCK MODIFY refusjonskrav DECIMAL(19,2);
ALTER TABLE INNTEKTSGRUNNLAG_MOCK MODIFY naturalytelse DECIMAL(19,2);
