INSERT INTO KODELISTE (id, kode, navn, beskrivelse, gyldig_fom, kodeverk) VALUES (seq_kodeliste.nextval, 'FAKTA_OM_OMSORG_OG_FORELDREANSVAR', 'Fakta om omsorg og foreldreansvar', 'Fakta om omsorg og foreldreansvar', to_date('2000-01-01', 'YYYY-MM-DD'), 'SKJERMLENKE_TYPE');
UPDATE KODELISTE SET KODE = 'PUNKT_FOR_FORELDREANSVAR' WHERE KODE = 'FORELDREANSVAR' AND KODEVERK = 'SKJERMLENKE_TYPE';
UPDATE AKSJONSPUNKT_DEF SET SKJERMLENKE_TYPE = 'PUNKT_FOR_FORELDREANSVAR' WHERE SKJERMLENKE_TYPE = 'FORELDREANSVAR';
