ALTER TABLE MOTTATT_DOKUMENT ADD FORSENDELSE_ID RAW(16);
ALTER TABLE MOTTATT_DOKUMENT ADD CONSTRAINT CHK_UNIQUE_FORS_MOTT_DOK UNIQUE (FORSENDELSE_ID);
COMMENT ON COLUMN MOTTATT_DOKUMENT.FORSENDELSE_ID IS 'Unik ID for forsendelsen';
