UPDATE AKSJONSPUNKT_DEF SET SKJERMLENKE_TYPE = 'PUNKT_FOR_MEDLEMSKAP' WHERE KODE = '5010';
UPDATE AKSJONSPUNKT_DEF SET SKJERMLENKE_TYPE = 'FAKTA_FOR_OMSORG' WHERE KODE = '5060';
UPDATE AKSJONSPUNKT_DEF SET SKJERMLENKE_TYPE = 'FAKTA_FOR_OMSORG' WHERE KODE = '5061';
