UPDATE KODELISTE
SET KODE = 'ADOPSJONSVILKARET'
WHERE KODEVERK = 'HISTORIKK_ENDRET_FELT_TYPE' and KODE = 'ADOPSJON';

UPDATE KODELISTE
SET KODE = 'FODSELSVILKARET'
WHERE KODEVERK = 'HISTORIKK_ENDRET_FELT_TYPE' and KODE = 'FODSEL';

UPDATE KODELISTE
SET KODE = 'FORELDREANSVARSVILKARET'
WHERE KODEVERK = 'HISTORIKK_ENDRET_FELT_TYPE' and KODE = 'FORELDREANSVAR';

INSERT INTO KODELISTE (id, kode, navn, beskrivelse, gyldig_fom, kodeverk) VALUES (seq_kodeliste.nextval, 'SOKNADSFRISTVILKARET', 'Søknadsfristvilkåret', 'Søknadsfristvilkåret', to_date('2000-01-01', 'YYYY-MM-DD'), 'HISTORIKK_ENDRET_FELT_TYPE');
