ALTER TABLE DOKUMENT_FELLES
  ADD SAKSPART_PERSON_STATUS VARCHAR2(20 CHAR) DEFAULT 'ANNET' NOT NULL;

COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_PERSON_STATUS IS 'Gjeldende personstatus fra TPS når dokumentet produseres';
