ALTER TABLE UTSETTELSE_PERIODE DROP (UTSETTELSE_PERIODE_TYPE, KL_UTSETTELSE_PERIODE_TYPE) CASCADE CONSTRAINTS;

DELETE FROM KODELISTE WHERE KODEVERK = 'UTSETTELSE_PERIODE_TYPE';
DELETE FROM KODEVERK WHERE KODE = 'UTSETTELSE_PERIODE_TYPE';
