-- Tabell OPPTJENING_MOCK Endring
DROP INDEX IDX_OPPTJENING_MOCK_01;
ALTER TABLE OPPTJENING_MOCK DROP COLUMN fnr;
UPDATE OPPTJENING_MOCK SET aktor_id = 0 WHERE aktor_id IS NULL;
ALTER TABLE OPPTJENING_MOCK MODIFY (aktor_id NOT NULL);
CREATE INDEX IDX_OPPTJENING_MOCK_03 ON OPPTJENING_MOCK (aktor_id);

-- Tabell AKTIVITETER_MOCK Endring
DROP INDEX IDX_AKTIVITETER_MOCK_01;
ALTER TABLE AKTIVITETER_MOCK DROP COLUMN fnr;
UPDATE AKTIVITETER_MOCK SET aktor_id = 0 WHERE aktor_id IS NULL;
ALTER TABLE AKTIVITETER_MOCK MODIFY (aktor_id NOT NULL);
CREATE INDEX IDX_AKTIVITETER_MOCK_03 ON AKTIVITETER_MOCK (aktor_id);

-- Tabell INNTEKTSGRUNNLAG_MOCK Endring
DROP INDEX IDX_INNTEKTSGRUNNLAG_MOCK_01;
ALTER TABLE INNTEKTSGRUNNLAG_MOCK DROP COLUMN fnr;
UPDATE INNTEKTSGRUNNLAG_MOCK SET aktor_id = 0 WHERE aktor_id IS NULL;
ALTER TABLE INNTEKTSGRUNNLAG_MOCK MODIFY (aktor_id NOT NULL);

