-- NAV har ikke noe offisielt kodeverk for Fagsystem.
-- Det er derfor ikke riktig at 'Gsak' eier disse kodeverksverdier. Setter alle disse konstantene som eid av VL.
UPDATE KODEVERK SET
  kodeverk_eier = 'VL',
  kodeverk_eier_ref = null,
  beskrivelse = 'Konstanter for NAVs fagsystemer. Det finnes intet offisielt kodeverk for fagsystem-navn, men det eksisterer likevel entydige fagsystemnavn'
WHERE KODE = 'FAGSYSTEM';

-- Definerer andre fagsystemer som brukes i VL.
insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'JOARK', 'AS36', 'Joark', 'Joark', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'TPS', 'FS03', 'TPS', 'TPS', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'MEDL', 'FS18', 'MEDL', 'MEDL', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'INNTEKT', 'FS28', 'INNTEKT', 'INNTEKT', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'GSAK', 'FS19', 'GSAK', 'GSAK', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'BISYS', 'BID', 'BID', 'BID', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'SKANNING', 'MOT', 'MOT', 'MOT', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'ØKONOMI', 'OKO', 'OKO', 'OKO', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'BIDRAGINNKREVING', 'BII', 'BII', 'BII', to_date('2017-11-19', 'YYYY-MM-DD'));

insert into KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
values(seq_kodeliste.nextval, 'FAGSYSTEM', 'ØVRIG', 'OVR', 'ØVRIG', 'ØVRIG', to_date('2017-11-19', 'YYYY-MM-DD'));

-- FAGSYSTEM-kodeliste overtar SAKSOPPLYSNING_KILDE
ALTER TABLE SAKSOPPLYSNING DROP CONSTRAINT FK_SAKSOPPLYSNING_2;
ALTER TABLE BEHANDLING_REL_YTELSER DROP CONSTRAINT FK_SAKSOPPLYSNING_KILDE;
DROP TABLE SAKSOPPLYSNING_KILDE;

ALTER TABLE SAKSOPPLYSNING ADD (KL_FAGSYSTEM VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAGSYSTEM') VIRTUAL  NOT NULL);
ALTER TABLE BEHANDLING_REL_YTELSER ADD (KL_FAGSYSTEM VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAGSYSTEM') VIRTUAL  NOT NULL);
COMMENT ON COLUMN SAKSOPPLYSNING.KL_FAGSYSTEM IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_REL_YTELSER.KL_FAGSYSTEM IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

-- Skal ikke bruke offisielle koder i internlageret
ALTER TABLE SAKSOPPLYSNING MODIFY (SAKSOPPLYSNING_KILDE VARCHAR2(16 CHAR));

UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'ARENA'            WHERE SAKSOPPLYSNING_KILDE = 'AO01';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'GRISEN'           WHERE SAKSOPPLYSNING_KILDE = 'AO11';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'GOSYS'            WHERE SAKSOPPLYSNING_KILDE = 'FS22';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'INFOTRYGD'        WHERE SAKSOPPLYSNING_KILDE = 'IT01';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'HJE_HEL_ORT'      WHERE SAKSOPPLYSNING_KILDE = 'OEBS';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'PESYS' 	          WHERE SAKSOPPLYSNING_KILDE = 'PP01';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'VENTELONN'        WHERE SAKSOPPLYSNING_KILDE = 'V2';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'UNNTAK'           WHERE SAKSOPPLYSNING_KILDE = 'UFM';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'FPSAK'            WHERE SAKSOPPLYSNING_KILDE = 'FS36';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'JOARK'            WHERE SAKSOPPLYSNING_KILDE = 'AS36';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'TPS' 		          WHERE SAKSOPPLYSNING_KILDE = 'FS03';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'MEDL' 	          WHERE SAKSOPPLYSNING_KILDE = 'FS18';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'INNTEKT'          WHERE SAKSOPPLYSNING_KILDE = 'FS28';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'GSAK'             WHERE SAKSOPPLYSNING_KILDE = 'FS19';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'BISYS'            WHERE SAKSOPPLYSNING_KILDE = 'BID';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'SKANNING'         WHERE SAKSOPPLYSNING_KILDE = 'MOT';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'ØKONOMI'          WHERE SAKSOPPLYSNING_KILDE = 'OKO';
UPDATE SAKSOPPLYSNING SET SAKSOPPLYSNING_KILDE = 'BIDRAGINNKREVING' WHERE SAKSOPPLYSNING_KILDE = 'BII';


-- Skal ikke bruke offisielle koder i internlageret
ALTER TABLE BEHANDLING_REL_YTELSER MODIFY (SAKSOPPLYSNING_KILDE VARCHAR2(16 CHAR));

UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'ARENA'            WHERE SAKSOPPLYSNING_KILDE = 'AO01';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'GRISEN'           WHERE SAKSOPPLYSNING_KILDE = 'AO11';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'GOSYS'            WHERE SAKSOPPLYSNING_KILDE = 'FS22';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'INFOTRYGD'        WHERE SAKSOPPLYSNING_KILDE = 'IT01';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'HJE_HEL_ORT'      WHERE SAKSOPPLYSNING_KILDE = 'OEBS';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'PESYS' 	          WHERE SAKSOPPLYSNING_KILDE = 'PP01';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'VENTELONN'        WHERE SAKSOPPLYSNING_KILDE = 'V2';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'UNNTAK'           WHERE SAKSOPPLYSNING_KILDE = 'UFM';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'FPSAK'            WHERE SAKSOPPLYSNING_KILDE = 'FS36';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'JOARK'            WHERE SAKSOPPLYSNING_KILDE = 'AS36';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'TPS' 		          WHERE SAKSOPPLYSNING_KILDE = 'FS03';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'MEDL' 	          WHERE SAKSOPPLYSNING_KILDE = 'FS18';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'INNTEKT'          WHERE SAKSOPPLYSNING_KILDE = 'FS28';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'GSAK'             WHERE SAKSOPPLYSNING_KILDE = 'FS19';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'BISYS'            WHERE SAKSOPPLYSNING_KILDE = 'BID';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'SKANNING'         WHERE SAKSOPPLYSNING_KILDE = 'MOT';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'ØKONOMI'          WHERE SAKSOPPLYSNING_KILDE = 'OKO';
UPDATE BEHANDLING_REL_YTELSER SET SAKSOPPLYSNING_KILDE = 'BIDRAGINNKREVING' WHERE SAKSOPPLYSNING_KILDE = 'BII';

ALTER TABLE SAKSOPPLYSNING ADD CONSTRAINT FK_SAKSOPPLYSNING_4 FOREIGN KEY ("SAKSOPPLYSNING_KILDE", "KL_FAGSYSTEM") REFERENCES KODELISTE ("KODE", "KODEVERK") ENABLE;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_BEHANDLING_REL_YTELSER_88 FOREIGN KEY ("SAKSOPPLYSNING_KILDE", "KL_FAGSYSTEM") REFERENCES KODELISTE ("KODE", "KODEVERK") ENABLE;
