ALTER TABLE BEREGNINGSGRUNNLAG
  DROP CONSTRAINT CHK_UNIQUE_BEHANDLING_ID;

ALTER TABLE BEREGNINGSGRUNNLAG
  DROP COLUMN BEHANDLING_ID;

-- Tabell BeregningsgrunnlagKobling
CREATE TABLE GR_BEREGNINGSGRUNNLAG (
  id                            NUMBER(19)                        NOT NULL,
  behandling_id                 NUMBER(19)                        NOT NULL,
  beregningsgrunnlag_id         NUMBER(19)                        NOT NULL,
  versjon                       NUMBER(19) DEFAULT 0              NOT NULL,
  opprettet_av                  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid                 TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                     VARCHAR2(20 CHAR),
  endret_tid                    TIMESTAMP(3),
  CONSTRAINT PK_GR_BEREGNINGSGRUNNLAG PRIMARY KEY (id),
  CONSTRAINT FK_GR_BEREGNINGSGRUNNLAG_1 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING,
  CONSTRAINT FK_GR_BEREGNINGSGRUNNLAG_2 FOREIGN KEY (beregningsgrunnlag_id) REFERENCES BEREGNINGSGRUNNLAG
);

CREATE SEQUENCE SEQ_GR_BEREGNINGSGRUNNLAG MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE GR_BEREGNINGSGRUNNLAG IS 'Tabell som kobler et beregningsgrunnlag til behandling';
COMMENT ON COLUMN GR_BEREGNINGSGRUNNLAG.ID IS 'Primary Key';
COMMENT ON COLUMN GR_BEREGNINGSGRUNNLAG.behandling_id IS 'FK: BEHANDLING';
COMMENT ON COLUMN GR_BEREGNINGSGRUNNLAG.beregningsgrunnlag_id IS 'FK: BEREGNINGSGRUNNLAG';
