-- Tabell OPPTJENING_MOCK Endring
ALTER TABLE OPPTJENING_MOCK MODIFY (fnr NULL);
ALTER TABLE OPPTJENING_MOCK ADD (aktor_id NUMBER(19, 0));

-- Tabell AKTIVITETER_MOCK Endring
ALTER TABLE AKTIVITETER_MOCK MODIFY (fnr NULL);
ALTER TABLE AKTIVITETER_MOCK ADD (aktor_id NUMBER(19, 0));
ALTER TABLE AKTIVITETER_MOCK ADD (arbeidsforhold_id NUMBER(19, 0));
