-- endre BEHANDLING_STEG_TYPE kode fra VURDERBV til VURDERSRB

INSERT INTO BEHANDLING_STEG_TYPE(KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
values ('VURDERSRB', 'Vurder søkers relasjon til barnet', 'UTRED', 'Vurder Søkers relasjon til barnet');

UPDATE BEHANDLING_TYPE_STEG_SEKV SET BEHANDLING_STEG_TYPE = 'VURDERSRB' WHERE BEHANDLING_STEG_TYPE='VURDERBV';

UPDATE BEHANDLING_STEG_TILSTAND SET BEHANDLING_STEG ='VURDERSRB' WHERE BEHANDLING_STEG='VURDERBV';
UPDATE AKSJONSPUNKT SET BEHANDLING_STEG_FUNNET ='VURDERSRB' WHERE BEHANDLING_STEG_FUNNET='VURDERBV';

INSERT INTO VURDERINGSPUNKT_DEF (KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN)
values ('VURDERSRB.INN', 'VURDERSRB', 'INN', 'Vurder Søkers relasjon til barnet - Inngang');

INSERT INTO VURDERINGSPUNKT_DEF (KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN)
VALUES ('VURDERSRB.UT', 'VURDERSRB', 'UT', 'Vurder Søkers relasjon til barnet - Utgang');

UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'VURDERSRB.INN' WHERE VURDERINGSPUNKT='VURDERBV.INN';
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'VURDERSRB.UT' WHERE VURDERINGSPUNKT='VURDERBV.UT';

DELETE FROM VURDERINGSPUNKT_DEF WHERE BEHANDLING_STEG = 'VURDERBV';
delete from behandling_type_steg_sekv where behandling_steg_type='VURDERBV';
delete from BEHANDLING_STEG_TYPE where kode='VURDERBV';

