--legg til
ALTER TABLE AKSJONSPUNKT ADD behandling_id number(19);
ALTER TABLE AKSJONSPUNKT DROP CONSTRAINT FK_AKSJONSPUNKT_2;

--migrer data
MERGE INTO AKSJONSPUNKT A
USING (SELECT * FROM BEHANDLING_RESULTAT) BR
ON (A.BEHANDLING_RESULTAT_ID = BR.ID)
WHEN MATCHED THEN UPDATE SET A.behandling_id = BR.BEHANDLING_ID;

-- oppdatere
ALTER TABLE AKSJONSPUNKT MODIFY (behandling_id not null);
ALTER TABLE AKSJONSPUNKT DROP COLUMN BEHANDLING_RESULTAT_ID;
ALTER TABLE AKSJONSPUNKT ADD CONSTRAINT FK_AKSJONSPUNKT_2 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING;