ALTER TABLE BEHANDLING_TYPE_STEG_SEKV ADD (FAGSAK_YTELSE_TYPE VARCHAR(100 CHAR));
UPDATE BEHANDLING_TYPE_STEG_SEKV SET FAGSAK_YTELSE_TYPE ='ES';
ALTER TABLE BEHANDLING_TYPE_STEG_SEKV MODIFY (FAGSAK_YTELSE_TYPE NOT NULL);

ALTER TABLE BEHANDLING_TYPE_STEG_SEKV ADD KL_FAGSAK_YTELSE varchar2(100 char) AS ('FAGSAK_YTELSE') NOT NULL;

ALTER TABLE BEHANDLING_TYPE_STEG_SEKV ADD CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_82 FOREIGN KEY (FAGSAK_YTELSE_TYPE, KL_FAGSAK_YTELSE) REFERENCES KODELISTE (KODE, KODEVERK);

COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.FAGSAK_YTELSE_TYPE IS 'Fagsak ytelse dette steget er definert for';

DROP INDEX UIDX_BEH_STEG_TYPE_SEKV_1;

INSERT INTO BEHANDLING_TYPE_STEG_SEKV(ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
SELECT SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, 'FP'
FROM BEHANDLING_TYPE_STEG_SEKV WHERE FAGSAK_YTELSE_TYPE = 'ES'
AND BEHANDLING_STEG_TYPE NOT IN ('VURDERSFV')
;

CREATE INDEX UIDX_BEH_STEG_TYPE_SEKV_1 ON BEHANDLING_TYPE_STEG_SEKV (BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, FAGSAK_YTELSE_TYPE);


INSERT INTO BEHANDLING_STEG_TYPE(KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
VALUES ('VURDER_OPPTJ', 'Vurder opptjeningsvilkåret', 'UTRED', 'Vurder opptjeningsvilkåret');

INSERT INTO BEHANDLING_STEG_TYPE(KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
values ('FORS_BERGRUNN', 'Foreslå beregningsgrunnlag', 'UTRED', 'Foreslå beregningsgrunnlag for Foreldrepenger');

INSERT INTO BEHANDLING_STEG_TYPE(KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
values ('FAST_BERGRUNN', 'Fastsett beregningsgrunnlag', 'UTRED', 'Fastsett beregningsgrunnlag for Foreldrepenger');

INSERT INTO BEHANDLING_STEG_TYPE(KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
values ('VURDER_UTTAK', 'Vurder uttaksvilkår', 'UTRED', 'Vurder uttaksvilkåret');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-002', 'VURDER_OPPTJ', 80, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-004', 'VURDER_OPPTJ', 80, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-002', 'FORS_BERGRUNN', 100, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-004', 'FORS_BERGRUNN', 100, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-002', 'FAST_BERGRUNN', 110, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-004', 'FAST_BERGRUNN', 110, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-002', 'VURDER_UTTAK', 120, 'FP');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR, FAGSAK_YTELSE_TYPE)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.NEXTVAL, 'BT-004', 'VURDER_UTTAK', 120, 'FP');

UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 25  WHERE BEHANDLING_STEG_TYPE='REGSØK';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 30 WHERE BEHANDLING_STEG_TYPE='INSØK';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 40  WHERE BEHANDLING_STEG_TYPE='INREG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 50  WHERE BEHANDLING_STEG_TYPE='KOFAK';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 55  WHERE BEHANDLING_STEG_TYPE='VURDEROP';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 70  WHERE BEHANDLING_STEG_TYPE='VURDERMV';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 60  WHERE BEHANDLING_STEG_TYPE='VURDERBV';

UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 160  WHERE BEHANDLING_STEG_TYPE='BERYT';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 170  WHERE BEHANDLING_STEG_TYPE='FORVEDSTEG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 180  WHERE BEHANDLING_STEG_TYPE='FVEDSTEG';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 190  WHERE BEHANDLING_STEG_TYPE='IVEDSTEG';

UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 90  WHERE BEHANDLING_STEG_TYPE='VURDERSFV';

UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 140 WHERE BEHANDLING_STEG_TYPE='KLAGEUI';
UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 145 WHERE BEHANDLING_STEG_TYPE='KLAGEOI';


UPDATE BEHANDLING_TYPE_STEG_SEKV SET SEKVENS_NR = 95  WHERE BEHANDLING_STEG_TYPE='VURDERSAMLET';

