DELETE FROM behandling_type_steg_sekv WHERE behandling_steg_type='VURDERSRB';
DELETE FROM AKSJONSPUNKT_DEF WHERE vurderingspunkt IN (SELECT kode FROM VURDERINGSPUNKT_DEF WHERE BEHANDLING_STEG = 'VURDERSRB');
DELETE FROM VURDERINGSPUNKT_DEF WHERE BEHANDLING_STEG = 'VURDERSRB';
DELETE FROM STARTPUNKT_TYPE WHERE BEHANDLING_STEG = 'VURDERSRB';
DELETE FROM BEHANDLING_STEG_TYPE WHERE kode = 'VURDERSRB';
