drop sequence SEQ_DOKUMENT_ADRESSE;
drop sequence SEQ_SOEKNAD_ANNEN_PART;
drop sequence SEQ_FAMILIERELASJON;
drop sequence SEQ_OPPLYSNING_ADRESSE;
drop sequence SEQ_PERSONOPPLYSNING;
drop sequence SEQ_VALGT_OPPLYSNING;
drop sequence SEQ_BEHANDLING_REL_YTELSER;