DROP TABLE oppgave_behandling_kobling CASCADE;

ALTER TABLE MEDLEMSKAP_VILKAR_PERIODER
  ADD VILKAR_UTFALL_MERKNAD varchar(100) default '-';
ALTER TABLE MEDLEMSKAP_VILKAR_PERIODER
  ADD KL_VILKAR_UTFALL_MERKNAD varchar(100) DEFAULT ('VILKAR_UTFALL_MERKNAD');
ALTER TABLE MEDLEMSKAP_VILKAR_PERIODER
  ADD CONSTRAINT FK_MEDLEMSKAP_VILKAR_PERIODE_3 FOREIGN KEY (KL_VILKAR_UTFALL_MERKNAD, VILKAR_UTFALL_MERKNAD) REFERENCES KODELISTE (kodeverk, kode);

CREATE INDEX IDX_MEDLEMSKAP_V_P_2 ON MEDLEMSKAP_VILKAR_PERIODER (VILKAR_UTFALL_MERKNAD);
COMMENT ON COLUMN MEDLEMSKAP_VILKAR_PERIODER.VILKAR_UTFALL_MERKNAD IS 'Kode for vilkår utfall merknad';
