DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_KATEGORI';
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_KATEGORI';
DELETE FROM KODEVERK WHERE KODE  = 'VILKAR_KATEGORI';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SOKNAD_TYPE_TILLEGG';
DELETE FROM KODELISTE WHERE KODEVERK = 'SOKNAD_TYPE_TILLEGG';
DELETE FROM KODEVERK WHERE KODE  = 'SOKNAD_TYPE_TILLEGG';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'POSTERINGSTYPE';
DELETE FROM KODELISTE WHERE KODEVERK = 'POSTERINGSTYPE';
DELETE FROM KODEVERK WHERE KODE  = 'POSTERINGSTYPE';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='LANDGRUPPER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'LANDGRUPPER';
DELETE FROM KODELISTE WHERE KODEVERK = 'LANDGRUPPER';
DELETE FROM KODEVERK WHERE KODE  = 'LANDGRUPPER';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'TYPE_FISKE';
DELETE FROM KODELISTE WHERE KODEVERK = 'TYPE_FISKE';
DELETE FROM KODEVERK WHERE KODE  = 'TYPE_FISKE';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'DOKUMENT_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK = 'DOKUMENT_TYPE';
DELETE FROM KODEVERK WHERE KODE  = 'DOKUMENT_TYPE';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SOEKNAD_ANNEN_PART';
DELETE FROM KODELISTE WHERE KODEVERK = 'SOEKNAD_ANNEN_PART';
DELETE FROM KODEVERK WHERE KODE  = 'SOEKNAD_ANNEN_PART';


DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1 = 'KOMMUNER' OR KODEVERK2='KOMMUNER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'KOMMUNER';
DELETE FROM KODELISTE WHERE KODEVERK = 'KOMMUNER';
DELETE FROM KODEVERK WHERE KODE  = 'KOMMUNER';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1 = 'FYLKER' OR KODEVERK2='FYLKER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FYLKER';
DELETE FROM KODELISTE WHERE KODEVERK = 'FYLKER';
DELETE FROM KODEVERK WHERE KODE  = 'FYLKER';
