ALTER TABLE SO_SOEKNAD DROP medlemskap_oppg_tilknyt_id;
ALTER TABLE SO_SOEKNAD DROP fordeling_id;
ALTER TABLE SO_SOEKNAD DROP rettighet_id;
ALTER TABLE SO_SOEKNAD DROP DEKNINGSGRAD_ID;

ALTER TABLE SO_SOEKNAD ADD SYKEFRAVAER_ID BIGINT;
ALTER TABLE SO_SOEKNAD ADD ARBEIDSGIVER_AKTOR_ID VARCHAR(100);
ALTER TABLE SO_SOEKNAD ADD ARBEIDSGIVER_VIRKSOMHET_ID BIGINT;
ALTER TABLE SO_SOEKNAD ADD SOEKNAD_REFERANSE VARCHAR(100) NOT NULL;
ALTER TABLE SO_SOEKNAD ADD SYKEMELDING_REFERANSE VARCHAR(100) NOT NULL;


ALTER TABLE SO_SOEKNAD
  ADD CONSTRAINT FK_SO_SOEKNAD_01 FOREIGN KEY (ARBEIDSGIVER_VIRKSOMHET_ID) REFERENCES VIRKSOMHET;
ALTER TABLE SO_SOEKNAD
  ADD CONSTRAINT FK_SO_SOEKNAD_02 FOREIGN KEY (SYKEFRAVAER_ID) REFERENCES SF_SYKEFRAVAER;

COMMENT ON COLUMN SO_SOEKNAD.ARBEIDSGIVER_AKTOR_ID IS 'Arbeidsgivers aktørId hvis personlig foretak';
COMMENT ON COLUMN SO_SOEKNAD.SOEKNAD_REFERANSE IS 'Ekstern referanse for søknaden';
COMMENT ON COLUMN SO_SOEKNAD.SYKEMELDING_REFERANSE IS 'Ekstern referanse for sykemeldingen';

CREATE INDEX IDX_SO_SOEKNAD_01 ON SO_SOEKNAD (SYKEFRAVAER_ID);
CREATE INDEX IDX_SO_SOEKNAD_02 ON SO_SOEKNAD (ARBEIDSGIVER_VIRKSOMHET_ID);

INSERT INTO KODELISTE (id, kode, beskrivelse, gyldig_fom, kodeverk)
VALUES (nextval('seq_kodeliste'), 'PAPIRSYKEMELDING', 'Papirsykemelding', to_date('2000-01-01', 'YYYY-MM-DD'),
        'SYKEFRAVÆR_PERIODE_TYPE');
INSERT INTO KODELISTE_NAVN_I18N (id, KL_KODE, KL_KODEVERK, SPRAK, NAVN)
VALUES (nextval('SEQ_KODELISTE_NAVN_I18N'), 'PAPIRSYKEMELDING', 'SYKEFRAVÆR_PERIODE_TYPE', 'NB', 'Papirsykemelding');

INSERT INTO KODELISTE (id, kode, beskrivelse, gyldig_fom, kodeverk)
VALUES (nextval('seq_kodeliste'), 'PERMISJON', 'Permisjon', to_date('2000-01-01', 'YYYY-MM-DD'),
        'SYKEFRAVÆR_PERIODE_TYPE');
INSERT INTO KODELISTE_NAVN_I18N (id, KL_KODE, KL_KODEVERK, SPRAK, NAVN)
VALUES (nextval('SEQ_KODELISTE_NAVN_I18N'), 'PERMISJON', 'SYKEFRAVÆR_PERIODE_TYPE', 'NB', 'Permisjon');
INSERT INTO KODELISTE (id, kode, beskrivelse, gyldig_fom, kodeverk)
VALUES (nextval('seq_kodeliste'), 'UTENLANDSOPPHOLD', 'Utenlandsopphold', to_date('2000-01-01', 'YYYY-MM-DD'),
        'SYKEFRAVÆR_PERIODE_TYPE');

INSERT INTO KODELISTE_NAVN_I18N (id, KL_KODE, KL_KODEVERK, SPRAK, NAVN)
VALUES (nextval('SEQ_KODELISTE_NAVN_I18N'), 'UTENLANDSOPPHOLD', 'SYKEFRAVÆR_PERIODE_TYPE', 'NB', 'Utenlandsopphold');
INSERT INTO KODELISTE (id, kode, beskrivelse, gyldig_fom, kodeverk)
VALUES (nextval('seq_kodeliste'), 'UTDANNING', 'Utdanning', to_date('2000-01-01', 'YYYY-MM-DD'),
        'SYKEFRAVÆR_PERIODE_TYPE');
INSERT INTO KODELISTE_NAVN_I18N (id, KL_KODE, KL_KODEVERK, SPRAK, NAVN)
VALUES (nextval('SEQ_KODELISTE_NAVN_I18N'), 'UTDANNING', 'SYKEFRAVÆR_PERIODE_TYPE', 'NB', 'Utdanning');
INSERT INTO KODELISTE (id, kode, beskrivelse, gyldig_fom, kodeverk)
VALUES (nextval('seq_kodeliste'), 'FERIE', 'Ferie', to_date('2000-01-01', 'YYYY-MM-DD'),
        'SYKEFRAVÆR_PERIODE_TYPE');
INSERT INTO KODELISTE_NAVN_I18N (id, KL_KODE, KL_KODEVERK, SPRAK, NAVN)
VALUES (nextval('SEQ_KODELISTE_NAVN_I18N'), 'FERIE', 'SYKEFRAVÆR_PERIODE_TYPE', 'NB', 'Ferie');
