DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_AARSAK' and kode1 in ('RE-MF', ' RE-MFIP', ' RE-AVAB', ' RE-PRSSL', ' RE-RGLF', ' RE-LOV', ' BERØRT-BEHANDLING', ' RE-FRDLING', ' RE-SRTB', ' RE-HENDELSE-FØDSEL');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_AARSAK' and kode2 in ('RE-MF', ' RE-MFIP', ' RE-AVAB', ' RE-PRSSL', ' RE-RGLF', ' RE-LOV', ' BERØRT-BEHANDLING', ' RE-FRDLING', ' RE-SRTB', ' RE-HENDELSE-FØDSEL');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_AARSAK' AND KL_KODE in ('RE-MF', ' RE-MFIP', ' RE-AVAB', ' RE-PRSSL', ' RE-RGLF', ' RE-LOV', ' BERØRT-BEHANDLING', ' RE-FRDLING', ' RE-SRTB', ' RE-HENDELSE-FØDSEL');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_AARSAK' and kode in ('RE-MF', ' RE-MFIP', ' RE-AVAB', ' RE-PRSSL', ' RE-RGLF', ' RE-LOV', ' BERØRT-BEHANDLING', ' RE-FRDLING', ' RE-SRTB', ' RE-HENDELSE-FØDSEL');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RETTEN_TIL' ;
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RETTEN_TIL' ;
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RETTEN_TIL' ;
DELETE FROM KODELISTE WHERE KODEVERK = 'RETTEN_TIL';
DELETE FROM KODEVERK WHERE KODE='RETTEN_TIL';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VEDTAKSBREV' ;
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VEDTAKSBREV' ;
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VEDTAKSBREV' ;
DELETE FROM KODELISTE WHERE KODEVERK = 'VEDTAKSBREV';
DELETE FROM KODEVERK WHERE KODE = 'VEDTAKSBREV';

alter table fagsak drop column til_infotrygd;

alter table behandling_resultat drop avslag_arsak, drop avslag_arsak_fritekst,drop  kl_avslagsarsak, drop retten_til, drop kl_retten_til, drop vedtaksbrev, drop kl_vedtaksbrev, drop overskrift, drop fritekstbrev;
 