ALTER TABLE IAY_INNTEKTSMELDING
  ADD COLUMN journalpost_id VARCHAR(100);

UPDATE IAY_INNTEKTSMELDING im
SET journalpost_id = (SELECT DISTINCT md.JOURNALPOST_ID FROM MOTTATT_DOKUMENT md WHERE md.id = im.MOTTATT_DOKUMENT_ID)
WHERE journalpost_id IS NULL;

ALTER TABLE IAY_INNTEKTSMELDING
  DROP MOTTATT_DOKUMENT_ID;

ALTER TABLE IAY_INNTEKTSMELDING
  ALTER COLUMN journalpost_id SET NOT NULL;

COMMENT ON COLUMN IAY_INNTEKTSMELDING.journalpost_id IS 'JournalpostIden som inntektsmeldingen er journalført på.';

DROP TABLE MOTTATT_DOKUMENT CASCADE;
