--------------------------------------------------------
--  DDL for Table PROSESS_TASK
--------------------------------------------------------

  CREATE TABLE PROSESS_TASK
   (	ID bigint NOT NULL,
	TASK_TYPE VARCHAR(200),
	PRIORITET NUMERIC(3,0) DEFAULT 0,
	STATUS VARCHAR(20) DEFAULT 'KLAR',
	TASK_PARAMETERE VARCHAR(4000),
	TASK_PAYLOAD TEXT,
	TASK_GRUPPE VARCHAR(250),
	TASK_SEKVENS VARCHAR(100) DEFAULT '1',
	NESTE_KJOERING_ETTER TIMESTAMP (0) DEFAULT LOCALTIMESTAMP,
	FEILEDE_FORSOEK NUMERIC(5,0) DEFAULT 0,
	BLOKKERT_AV bigint NULL,
	SISTE_KJOERING_TS TIMESTAMP (6),
	SISTE_KJOERING_FEIL_KODE VARCHAR(50),
	SISTE_KJOERING_FEIL_TEKST TEXT,
	SISTE_KJOERING_SERVER VARCHAR(1000),
	VERSJON bigint DEFAULT 0,
	OPPRETTET_AV                   VARCHAR(1000) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID                  TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL
   )  /* ENABLE ROW MOVEMENT // TODO: Partisjonering */ ;

   COMMENT ON COLUMN PROSESS_TASK.ID IS 'Primary Key';
   COMMENT ON COLUMN PROSESS_TASK.TASK_TYPE IS 'navn på task. Brukes til å matche riktig implementasjon';
   COMMENT ON COLUMN PROSESS_TASK.PRIORITET IS 'prioritet på task.  Høyere tall har høyere prioritet';
   COMMENT ON COLUMN PROSESS_TASK.STATUS IS 'status på task: KLAR, NYTT_FORSOEK, FEILET, VENTER_SVAR, FERDIG, VETO';
   COMMENT ON COLUMN PROSESS_TASK.TASK_PARAMETERE IS 'parametere angitt for en task';
   COMMENT ON COLUMN PROSESS_TASK.TASK_PAYLOAD IS 'inputdata for en task';
   COMMENT ON COLUMN PROSESS_TASK.TASK_GRUPPE IS 'angir en unik id som grupperer flere ';
   COMMENT ON COLUMN PROSESS_TASK.TASK_SEKVENS IS 'angir rekkefølge på task innenfor en gruppe ';
   COMMENT ON COLUMN PROSESS_TASK.NESTE_KJOERING_ETTER IS 'tasken skal ikke kjøeres før tidspunkt er passert';
   COMMENT ON COLUMN PROSESS_TASK.FEILEDE_FORSOEK IS 'antall feilede forsøk';
   COMMENT ON COLUMN PROSESS_TASK.SISTE_KJOERING_TS IS 'siste gang tasken ble forsøkt kjørt';
   COMMENT ON COLUMN PROSESS_TASK.SISTE_KJOERING_FEIL_KODE IS 'siste feilkode tasken fikk';
   COMMENT ON COLUMN PROSESS_TASK.SISTE_KJOERING_FEIL_TEKST IS 'siste feil tasken fikk';
   COMMENT ON COLUMN PROSESS_TASK.SISTE_KJOERING_SERVER IS 'navn på node som sist kjørte en task (server@pid)';
   COMMENT ON COLUMN PROSESS_TASK.VERSJON IS 'angir versjon for optimistisk låsing';
   COMMENT ON COLUMN PROSESS_TASK.BLOKKERT_AV IS 'Id til ProsessTask som blokkerer kjøring av denne (når status=VETO)';
   
   COMMENT ON TABLE PROSESS_TASK  IS 'Inneholder tasks som skal kjøres i bakgrunnen';
--------------------------------------------------------
--  DDL for Table PROSESS_TASK_FEILHAND
--------------------------------------------------------

  CREATE TABLE PROSESS_TASK_FEILHAND
   (	KODE VARCHAR(50)  NOT NULL,
	NAVN VARCHAR(1000),
	BESKRIVELSE VARCHAR(4000),
	OPPRETTET_AV VARCHAR(1000) DEFAULT 'VL',
	OPPRETTET_TID TIMESTAMP (3) DEFAULT LOCALTIMESTAMP,
	ENDRET_AV VARCHAR(1000),
	ENDRET_TID TIMESTAMP (3),
	INPUT_VARIABEL1 DOUBLE PRECISION,
	INPUT_VARIABEL2 DOUBLE PRECISION
   ) ;

   COMMENT ON COLUMN PROSESS_TASK_FEILHAND.KODE IS 'Kodeverk Primary Key';
   COMMENT ON COLUMN PROSESS_TASK_FEILHAND.NAVN IS 'Lesbart navn på type feilhåndtering brukt i prosesstask';
   COMMENT ON COLUMN PROSESS_TASK_FEILHAND.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
   COMMENT ON TABLE PROSESS_TASK_FEILHAND  IS 'Kodetabell for feilhåndterings-metoder. For eksempel antall ganger å prøve på nytt og til hvilke tidspunkt';

--------------------------------------------------------
--  DDL for Table PROSESS_TASK_TYPE
--------------------------------------------------------

  CREATE TABLE PROSESS_TASK_TYPE
   (	KODE VARCHAR(50)  NOT NULL,
	NAVN VARCHAR(1000),
	FEIL_MAKS_FORSOEK NUMERIC(10,0) DEFAULT 1,
	FEIL_SEK_MELLOM_FORSOEK NUMERIC(10,0) DEFAULT 30,
	FEILHANDTERING_ALGORITME VARCHAR(1000) DEFAULT 'DEFAULT',
	BESKRIVELSE VARCHAR(4000),
	OPPRETTET_AV VARCHAR(1000) DEFAULT 'VL',
	OPPRETTET_TID TIMESTAMP (3) DEFAULT LOCALTIMESTAMP,
	ENDRET_AV VARCHAR(1000),
	ENDRET_TID TIMESTAMP (3)
   ) ;

   COMMENT ON COLUMN PROSESS_TASK_TYPE.KODE IS 'Kodeverk Primary Key';
   COMMENT ON COLUMN PROSESS_TASK_TYPE.NAVN IS 'Lesbart navn på prosesstasktype';
   COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_MAKS_FORSOEK IS 'MISSING COLUMN COMMENT';
   COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_SEK_MELLOM_FORSOEK IS 'MISSING COLUMN COMMENT';
   COMMENT ON COLUMN PROSESS_TASK_TYPE.FEILHANDTERING_ALGORITME IS 'FK: PROSESS_TASK_FEILHAND';
   COMMENT ON COLUMN PROSESS_TASK_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
   COMMENT ON TABLE PROSESS_TASK_TYPE  IS 'Kodetabell for typer prosesser med beskrivelse og informasjon om hvilken feilhåndteringen som skal benyttes';

--------------------------------------------------------------------
-- EKSEMPEL DEFINISJONER PÅ FEILHÅNDTERINGSALGORITMER
--------------------------------------------------------------------
Insert into PROSESS_TASK_FEILHAND (KODE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,INPUT_VARIABEL1,INPUT_VARIABEL2) values ('DEFAULT','Eksponentiell back-off med tak',null,'VL',LOCALTIMESTAMP,null,null,null,null);

--------------------------------------------------------------------
-- EKSEMPEL DEFINISJONER AV PROSESS TASKS
--------------------------------------------------------------------
-- Insert into PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,FEILHANDTERING_ALGORITME,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID) values ('integrasjon.gsak.opprettOppgave','Oppretter Oppgave i GSak','1','30','DEFAULT',null,'VL',to_timestamp('10.11.2017 14.09.26,189000000','DD.MM.RRRR HH24.MI.SSXFF'),null,null);
-- Insert into PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,FEILHANDTERING_ALGORITME,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID) values ('fordeling.hentFraJoark','Henter metadata og xml fra Joark','3','30','TIL_GSAK_BACKOFF',null,'VL',to_timestamp('10.11.2017 14.09.26,189000000','DD.MM.RRRR HH24.MI.SSXFF'),null,null);
-- Insert into PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,FEILHANDTERING_ALGORITME,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID) values ('fordeling.hentOgVurderVLSak','Forsøker å finne matchende sak I repo','3','30','DEFAULT',null,'VL',to_timestamp('10.11.2017 14.09.26,190000000','DD.MM.RRRR HH24.MI.SSXFF'),null,null);


CREATE INDEX IDX_PROSESS_TASK_2 ON PROSESS_TASK (TASK_TYPE);
CREATE INDEX IDX_PROSESS_TASK_3 ON PROSESS_TASK (NESTE_KJOERING_ETTER) ;
CREATE INDEX IDX_PROSESS_TASK_5 ON PROSESS_TASK (TASK_GRUPPE) ;
CREATE INDEX IDX_PROSESS_TASK_1 ON PROSESS_TASK (STATUS) ;
CREATE INDEX IDX_PROSESS_TASK_6 ON PROSESS_TASK (BLOKKERT_AV) ;

/*CREATE UNIQUE INDEX PK_PROSESS_TASK ON PROSESS_TASK (ID) ; // konflikt med primary key nedenfor*/
/*CREATE UNIQUE INDEX PK_PROSESS_TASK_FEILHAND ON PROSESS_TASK_FEILHAND (KODE) ; // konflikt med primary key nedenfor*/
/*CREATE UNIQUE INDEX PK_PROSESS_TASK_TYPE ON PROSESS_TASK_TYPE (KODE) ; // konflikt med primary key nedenfor*/
CREATE INDEX IDX_PROSESS_TASK_TYPE_1 ON PROSESS_TASK_TYPE (FEILHANDTERING_ALGORITME) ;

--------------------------------------------------------
--  Constraints for Table PROSESS_TASK
--------------------------------------------------------

  ALTER TABLE PROSESS_TASK ADD CONSTRAINT PK_PROSESS_TASK PRIMARY KEY (ID) ;
  ALTER TABLE PROSESS_TASK ADD CONSTRAINT CHK_PROSESS_TASK_STATUS CHECK (STATUS IN ('KLAR', 'FEILET', 'VENTER_SVAR', 'SUSPENDERT', 'VETO', 'FERDIG')) ;
  ALTER TABLE PROSESS_TASK ALTER COLUMN VERSJON SET NOT NULL;
  ALTER TABLE PROSESS_TASK ALTER COLUMN TASK_SEKVENS SET NOT NULL ;
  ALTER TABLE PROSESS_TASK ALTER COLUMN STATUS SET NOT NULL;
  ALTER TABLE PROSESS_TASK ALTER COLUMN PRIORITET SET NOT NULL;
  ALTER TABLE PROSESS_TASK ALTER COLUMN TASK_TYPE SET NOT NULL;
  ALTER TABLE PROSESS_TASK ALTER COLUMN ID SET NOT NULL;

--------------------------------------------------------
--  Constraints for Table PROSESS_TASK_FEILHAND
--------------------------------------------------------

  ALTER TABLE PROSESS_TASK_FEILHAND ADD CONSTRAINT PK_PROSESS_TASK_FEILHAND PRIMARY KEY (KODE) ;
  ALTER TABLE PROSESS_TASK_FEILHAND ALTER COLUMN OPPRETTET_TID SET NOT NULL;
  ALTER TABLE PROSESS_TASK_FEILHAND ALTER COLUMN OPPRETTET_AV SET NOT NULL;
  ALTER TABLE PROSESS_TASK_FEILHAND ALTER COLUMN NAVN SET NOT NULL;
  ALTER TABLE PROSESS_TASK_FEILHAND ALTER COLUMN KODE SET NOT NULL;

--------------------------------------------------------
--  Constraints for Table PROSESS_TASK_TYPE
--------------------------------------------------------

  ALTER TABLE PROSESS_TASK_TYPE ADD CONSTRAINT PK_PROSESS_TASK_TYPE PRIMARY KEY (KODE) ;
  ALTER TABLE PROSESS_TASK_TYPE ALTER COLUMN OPPRETTET_TID SET NOT NULL;
  ALTER TABLE PROSESS_TASK_TYPE ALTER COLUMN OPPRETTET_AV SET NOT NULL;
  ALTER TABLE PROSESS_TASK_TYPE ALTER COLUMN FEIL_SEK_MELLOM_FORSOEK SET NOT NULL;
  ALTER TABLE PROSESS_TASK_TYPE ALTER COLUMN FEIL_MAKS_FORSOEK SET NOT NULL;
  ALTER TABLE PROSESS_TASK_TYPE ALTER COLUMN KODE SET NOT NULL;

--------------------------------------------------------
--  Ref Constraints for Table PROSESS_TASK
--------------------------------------------------------

  ALTER TABLE PROSESS_TASK ADD CONSTRAINT FK_PROSESS_TASK_1 FOREIGN KEY (TASK_TYPE)
	  REFERENCES PROSESS_TASK_TYPE (KODE) ;

--------------------------------------------------------
--  Ref Constraints for Table PROSESS_TASK_TYPE
--------------------------------------------------------

  ALTER TABLE PROSESS_TASK_TYPE ADD CONSTRAINT FK_PROSESS_TASK_TYPE_1 FOREIGN KEY (FEILHANDTERING_ALGORITME)
	  REFERENCES PROSESS_TASK_FEILHAND (KODE) ;


CREATE SEQUENCE SEQ_PROSESS_TASK  MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;
CREATE SEQUENCE SEQ_PROSESS_TASK_GRUPPE MINVALUE 10000000 START WITH 10000000 INCREMENT BY 1000000 NO CYCLE;