ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD AKTIVITET_STATUS VARCHAR2(100 char);
update BEREGNINGSRESULTAT_ANDEL set AKTIVITET_STATUS = '-';
comment on column BEREGNINGSRESULTAT_ANDEL.AKTIVITET_STATUS is 'Aktivitetstatus for andelen';
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD KL_AKTIVITET_STATUS VARCHAR2(100 char) AS ('AKTIVITET_STATUS');
comment on column BEREGNINGSRESULTAT_ANDEL.KL_AKTIVITET_STATUS is 'Aktivitetstatus kodeverk';
ALTER TABLE BEREGNINGSRESULTAT_ANDEL MODIFY KL_AKTIVITET_STATUS NOT NULL;

CREATE INDEX IDX_BEREGNINGSRESULTAT_ANDEL_2 ON BEREGNINGSRESULTAT_ANDEL(AKTIVITET_STATUS);
