update STARTPUNKT_TYPE SET RANGERING = 1 WHERE KODE = 'INNGANGSVILKÅR_OPPL';
update STARTPUNKT_TYPE SET RANGERING = 3 WHERE KODE = 'INNGANGSVILKÅR_MEDL';
update STARTPUNKT_TYPE SET RANGERING = 5 WHERE KODE = 'BEREGNING';
update STARTPUNKT_TYPE SET RANGERING = 6 WHERE KODE = 'UTTAKSVILKÅR';

insert into STARTPUNKT_TYPE (KODE, NAVN, BEHANDLING_STEG, RANGERING, BESKRIVELSE) values ('SØKERS_RELASJON_TIL_BARNET', 'Søkers relasjon til barnet', 'VURDERSRB', 2, 'Startpunkt søkers relasjon til barnet');
insert into STARTPUNKT_TYPE (KODE, NAVN, BEHANDLING_STEG, RANGERING, BESKRIVELSE) values ('OPPTJENING', 'Opptjening', 'VURDER_OPPTJ_PERIODE', 4, 'Startpunkt opptjening');


