INSERT INTO KODEVERK (kode, navn, beskrivelse, kodeverk_eier) VALUES ('FAGSYSTEM_UNDERKATEGORI', 'Kodeverk for mer spesifik kategorisering av kilde', 'Kodeverk for mer spesifik kategorisering av kilde','VL');

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'FAGSYSTEM_UNDERKATEGORI', 'INFOTRYGD_SAK', 'Sakdatabasen i Infotrygd', 'Er registrert som en sak Sakdatabasen i Infotrygd', 'NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'FAGSYSTEM_UNDERKATEGORI', 'INFOTRYGD_VEDTAK', 'Vedtak i Infotrygd', 'Er registrert som et vedtak i vedtaksdatabasen i Infotrygd', 'NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'FAGSYSTEM_UNDERKATEGORI', '-', 'Udefinert', 'Udefinert.', 'NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));

ALTER TABLE IAY_RELATERT_YTELSE ADD FAGSYSTEM_UNDERKATEGORI VARCHAR2(100 CHAR);

ALTER TABLE IAY_RELATERT_YTELSE ADD KL_FAGSYSTEM_UNDERKATEGORI VARCHAR2(100 CHAR) AS ('FAGSYSTEM_UNDERKATEGORI');

UPDATE IAY_RELATERT_YTELSE SET FAGSYSTEM_UNDERKATEGORI = '-';

CREATE INDEX IDX_IAY_RELATERT_YTELSE_10 ON IAY_RELATERT_YTELSE(FAGSYSTEM_UNDERKATEGORI);

ALTER TABLE IAY_RELATERT_YTELSE ADD constraint FK_YTELSE_6 foreign key (FAGSYSTEM_UNDERKATEGORI, KL_FAGSYSTEM_UNDERKATEGORI) references KODELISTE(kode, kodeverk);

COMMENT ON COLUMN IAY_RELATERT_YTELSE.FAGSYSTEM_UNDERKATEGORI IS 'Underkategori for der fagsystem ikke er nok.';

COMMENT ON COLUMN IAY_RELATERT_YTELSE.KL_FAGSYSTEM_UNDERKATEGORI IS 'Kodeverkreferanse for fagsystemUnderkategori';

