-- korreksjon av navn og definisjoner i database

alter table BEHANDLING_RESULTAT drop constraint FK_BEHANDLING_RESULTAT_6;
ALTER TABLE BEHANDLING_RESULTAT DROP COLUMN KL_AVSLAGSARSAK;
alter table BEHANDLING_RESULTAT add KL_AVSLAGSARSAK varchar2(100 char) as ('AVSLAGSARSAK');
ALTER TABLE BEHANDLING_RESULTAT ADD CONSTRAINT FK_BEHANDLING_RESULTAT_6 FOREIGN KEY (AVSLAG_ARSAK,KL_AVSLAGSARSAK) REFERENCES KODELISTE(KODE, KODEVERK);

alter table FAGSAK drop constraint FK_FAGSAK_1;
ALTER TABLE FAGSAK DROP COLUMN KL_ARSAK_TYPE;
alter table FAGSAK add KL_ARSAK_TYPE varchar2(100 char) as ('FAGSAK_ARSAK');
ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_1 FOREIGN KEY (ARSAK_TYPE,KL_ARSAK_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);

alter table FAGSAK drop constraint FK_FAGSAK_2;
ALTER TABLE FAGSAK DROP COLUMN KL_YTELSE_TYPE;
ALTER TABLE FAGSAK ADD KL_YTELSE_TYPE VARCHAR2(100 CHAR) AS ('FAGSAK_YTELSE');
alter table FAGSAK add constraint FK_FAGSAK_2 foreign key (YTELSE_TYPE,KL_YTELSE_TYPE) references KODELISTE(KODE, KODEVERK);

alter table FORRETNINGSHENDELSE_DEF drop constraint FK_FORRETNINGSHENDELSE_DEF_1;
alter table FORRETNINGSHENDELSE_DEF drop column KL_FORRETNINGSHENDELSE_TYPE;
alter table FORRETNINGSHENDELSE_DEF add KL_FORRETNINGSHENDELSE_TYPE varchar2(100 char) as ('FORRETNINGSHENDELSE_TYPE');
ALTER TABLE FORRETNINGSHENDELSE_DEF ADD CONSTRAINT FK_FORRETNINGSHENDELSE_DEF_1 FOREIGN KEY (FORRETNINGSHENDELSE_TYPE,KL_FORRETNINGSHENDELSE_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);

alter table FORRETNINGSHENDELSE_DEF drop constraint FK_FORRETNINGSHENDELSE_DEF_2;
alter table FORRETNINGSHENDELSE_DEF drop column "KL_REVURDERINGSÅRSAK_TYPE";
alter table FORRETNINGSHENDELSE_DEF add "KL_REVURDERINGSÅRSAK_TYPE" varchar2(100 char) as ('BEHANDLING_AARSAK');
ALTER TABLE FORRETNINGSHENDELSE_DEF ADD CONSTRAINT FK_FORRETNINGSHENDELSE_DEF_2 FOREIGN KEY ("REVURDERINGSÅRSAK_TYPE","KL_REVURDERINGSÅRSAK_TYPE") REFERENCES KODELISTE(KODE, KODEVERK);

alter table IAY_ANNEN_AKTIVITET drop constraint FK_ANNEN_AKTIVITET_2;
ALTER TABLE IAY_ANNEN_AKTIVITET DROP COLUMN KL_ARBEID_TYPE;
alter table IAY_ANNEN_AKTIVITET add KL_ARBEID_TYPE varchar2(100 char) as ('ARBEID_TYPE');
ALTER TABLE IAY_ANNEN_AKTIVITET ADD CONSTRAINT FK_ANNEN_AKTIVITET_2 FOREIGN KEY (ARBEID_TYPE,KL_ARBEID_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);

alter table IAY_EGEN_NAERING drop constraint FK_EGEN_NAERING_3;
alter table IAY_EGEN_NAERING drop column KL_VIRKSOMHET_TYPE;
alter table IAY_EGEN_NAERING add KL_VIRKSOMHET_TYPE varchar2(100 char) as ('VIRKSOMHET_TYPE');
ALTER TABLE IAY_EGEN_NAERING ADD CONSTRAINT FK_EGEN_NAERING_3 FOREIGN KEY (VIRKSOMHET_TYPE,KL_VIRKSOMHET_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);


alter table IAY_EGEN_NAERING drop constraint FK_EGEN_NAERING_3;
alter table IAY_EGEN_NAERING drop column KL_VIRKSOMHET_TYPE;
alter table IAY_EGEN_NAERING add KL_VIRKSOMHET_TYPE varchar2(100 char) as ('VIRKSOMHET_TYPE');
ALTER TABLE IAY_EGEN_NAERING ADD CONSTRAINT FK_EGEN_NAERING_3 FOREIGN KEY (VIRKSOMHET_TYPE,KL_VIRKSOMHET_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);

ALTER TABLE IAY_EGEN_NAERING DROP COLUMN KL_LANDKODER;
alter table IAY_EGEN_NAERING add KL_LANDKODER varchar2(100 char) as ('LANDKODER');
ALTER TABLE IAY_EGEN_NAERING ADD CONSTRAINT FK_EGEN_NAERING_4 FOREIGN KEY (LAND, KL_LANDKODER) REFERENCES KODELISTE(KODE, KODEVERK);

alter table VILKAR drop constraint FK_VILKAR_5;
alter table VILKAR drop column KL_AVSLAGSARSAK;
alter table VILKAR add KL_AVSLAGSARSAK varchar2(100 char) as ('AVSLAGSARSAK');
ALTER TABLE VILKAR ADD CONSTRAINT FK_VILKAR_5 FOREIGN KEY (AVSLAG_KODE,KL_AVSLAGSARSAK) REFERENCES KODELISTE(KODE, KODEVERK);

alter table YF_DOKUMENTASJON_PERIODE drop constraint FK_YF_DOKUMENTASJON_PERIODE_2;
alter table YF_DOKUMENTASJON_PERIODE drop column KL_DOKUMENTASJON_TYPE;
alter table YF_DOKUMENTASJON_PERIODE add KL_DOKUMENTASJON_TYPE varchar2(100 char) as ('UTTAK_DOKUMENTASJON_TYPE');
alter table YF_DOKUMENTASJON_PERIODE add constraint FK_YF_DOKUMENTASJON_PERIODE_2 foreign key (DOKUMENTASJON_TYPE,KL_DOKUMENTASJON_TYPE) references KODELISTE(KODE, KODEVERK);

alter table YF_DOKUMENTASJON_PERIODE drop constraint FK_YF_DOKUMENTASJON_PERIODE_3;
alter table YF_DOKUMENTASJON_PERIODE drop column KL_DOKUMENTASJON_KLASSE;
alter table YF_DOKUMENTASJON_PERIODE add KL_DOKUMENTASJON_KLASSE varchar2(100 char) as ('UTTAK_DOKUMENTASJON_KLASSE');
ALTER TABLE YF_DOKUMENTASJON_PERIODE ADD CONSTRAINT FK_YF_DOKUMENTASJON_PERIODE_3 FOREIGN KEY (DOKUMENTASJON_KLASSE,KL_DOKUMENTASJON_KLASSE) REFERENCES KODELISTE(KODE, KODEVERK);

alter table YF_DOKUMENTASJON_PERIODER drop constraint FK_YF_DOKUMENTASJON_PERIODER_1;
alter table YF_DOKUMENTASJON_PERIODER drop column KL_DOKUMENTASJON_KLASSE;
alter table YF_DOKUMENTASJON_PERIODER add KL_DOKUMENTASJON_KLASSE varchar2(100 char) as ('UTTAK_DOKUMENTASJON_KLASSE');
alter table YF_DOKUMENTASJON_PERIODER add constraint FK_YF_DOKUMENTASJON_PERIODER_1 foreign key (DOKUMENTASJON_KLASSE,KL_DOKUMENTASJON_KLASSE) references KODELISTE(KODE, KODEVERK);

alter index CHK_UNIQUE_BEH_AD rename to IDX_AKSJONSPUNKT_1;

ALTER TABLE IAY_YRKESAKTIVITET RENAME COLUMN ARBEID_TYPE_KL TO KL_ARBEID_TYPE;
ALTER TABLE BG_PR_STATUS_OG_ANDEL RENAME COLUMN AKTIVITET_STATUS_KL TO KL_AKTIVITET_STATUS;
ALTER TABLE BG_PR_STATUS_OG_ANDEL RENAME COLUMN RELATERT_YTELSE_TYPE_KL TO KL_RELATERT_YTELSE_TYPE;
ALTER TABLE BG_AKTIVITET_STATUS RENAME COLUMN AKTIVITET_STATUS_KL TO KL_AKTIVITET_STATUS;

