ALTER TABLE IAY_YRKESAKTIVITET ADD NAVN_ARBEIDSGIVER_UTLAND VARCHAR2(100 CHAR);

INSERT INTO KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom, ekstra_data)
VALUES (seq_kodeliste.nextval, 'ARBEID_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', null, 'Arbeid i utlandet', NULL, to_date('2000-01-01', 'YYYY-MM-DD'), '{ "gui": "true" }');

INSERT INTO KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
VALUES (seq_kodeliste.nextval, 'OPPTJENING_AKTIVITET_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', null, 'Arbeid i utlandet', NULL, to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'ARBEID_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', 'OPPTJENING_AKTIVITET_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'OPPTJENING_AKTIVITET_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', 'ARBEID_TYPE', 'UTENLANDSK_ARBEIDSFORHOLD', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));


COMMENT ON COLUMN IAY_YRKESAKTIVITET.NAVN_ARBEIDSGIVER_UTLAND IS 'Navn på utenlandske arbeidsgiver';
