COMMENT ON TABLE YF_DOKUMENTASJON_PERIODER IS 'Brukes for å samle rader fra YF_DOKUMENTASJON_PERIODE som settes samtidig';
COMMENT ON TABLE YF_DOKUMENTASJON_PERIODE IS 'Dokumentasjonsperiode. Brukes for å dokumentere fakta/vurderinger for søknadsperioder';
COMMENT ON TABLE UTTAK_RESULTAT_PERIODER IS 'Brukes for å samle rader fra UTTAK_RESULTAT_PERIODE som hører sammen';
COMMENT ON TABLE UTTAK_RESULTAT IS 'Peker på UTTAK_RESULTAT_PERIODER for å angi hvilke perioder som er aktive';

COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.PROSENT_UTBETALING IS 'Hvor stor andel av maksimal utbetaling for arbeidsforholdet som innvilges.';
COMMENT ON COLUMN UTTAK_POSTERING.ARBEIDSFORHOLD_ID IS 'Arbeidsforholdid';
COMMENT ON COLUMN UTTAK_POSTERING.GRADERING_PROSENT IS 'Arbeidsprosent';

COMMENT ON COLUMN STOENADSKONTO.KL_STOENADSKONTOTYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN GAMMEL_UTTAK_RESULTAT_PERIODE.VIRKEDAGER_BRUKT IS 'Antall virkedager i perioden';

COMMENT ON COLUMN YF_FORDELING_PERIODE.ID IS 'Primary key';
COMMENT ON COLUMN YF_FORDELING_PERIODE.FORDELING_ID IS 'FK: YF_FORDELING';
COMMENT ON COLUMN YF_FORDELING_PERIODE.FOM IS 'Fra-og-med dato for perioden';
COMMENT ON COLUMN YF_FORDELING_PERIODE.TOM IS 'Til-og-med dato for perioden';
COMMENT ON COLUMN YF_FORDELING_PERIODE.PERIODE_TYPE IS 'Hva det er søkt om (må sees i sammenheng med AARSAK-type ifbm utsettelse)';
COMMENT ON COLUMN YF_FORDELING_PERIODE.KL_PERIODE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN YF_FORDELING_PERIODE.AARSAK_TYPE IS 'Brukes ved søknad om utsettelse, opplyser årsak til dette';
COMMENT ON COLUMN YF_FORDELING_PERIODE.KL_AARSAK_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN YF_FORDELING_PERIODE.ARBEIDSPROSENT IS 'Hvor mye søker har tenkt å arbeide i perioden. Brukes ved gradert uttak.';
COMMENT ON COLUMN YF_FORDELING_PERIODE.MORS_AKTIVITET IS 'Hva mor skal gjøre i perioden (brukes ifbm aktivitetskrav)';
COMMENT ON COLUMN YF_FORDELING_PERIODE.KL_MORS_AKTIVITET IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN YF_FORDELING_PERIODE.BEGRUNNELSE IS 'Saksbehandlers begrunnelse. Brukes når saksbehandler dokumenterer/endrer perioder';

COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODER.DOKUMENTASJON_KLASSE IS 'Brukes av hibernate for å lage riktig java-klasse';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODER.KL_DOKUMENTASJON_KLASSE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.ID IS 'Primary key';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.PERIODER_ID IS 'FK: YF_DOKUMENTASJON_PERIODER';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.FOM IS 'Fra-og-med dato for perioden';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.TOM IS 'Tra-og-med dato for perioden';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.DOKUMENTASJON_TYPE IS 'Hvilken type dokumentasjon det er snakk om';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.KL_DOKUMENTASJON_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.DOKUMENTASJON_KLASSE IS 'Brukes av hibernate for å lage riktig java-klasse';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODE.KL_DOKUMENTASJON_KLASSE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

