insert into KODELISTE (ID, KODE, NAVN, BESKRIVELSE, KODEVERK) values
(seq_kodeliste.nextval, 'KØET-BEHANDLING', 'KØET-BEHANDLING', 'Markerer en køet behandling"', 'BEHANDLING_AARSAK');
insert into KODELISTE (ID, KODE, NAVN, BESKRIVELSE, KODEVERK) values
(seq_kodeliste.nextval, 'BERØRT-BEHANDLING', 'BERØRT-BEHANDLING', 'Markerer en berørt behandling (som har prioritert over køet behandling)"', 'BEHANDLING_AARSAK');

INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, VURDERINGSPUNKT, FRIST_PERIODE, BESKRIVELSE, OPPRETTET_AV, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, SKJERMLENKE_TYPE, AKSJONSPUNKT_TYPE)
VALUES ('7011', 'Autokøet behandling', 'INSØK.UT', null, 'Autokøet behandling', 'VL', '-', 'N', '-', 'AUTO');

INSERT INTO VURDERINGSPUNKT_DEF(KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN, BESKRIVELSE)
values ('IVEDSTEG.UT', 'IVEDSTEG', 'UT', 'Iverksett Vedtak - Utgang', 'Vurderingspunkt ved utgang til Behandling Steg - Iverksett Vedtak');

INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, VURDERINGSPUNKT, FRIST_PERIODE, BESKRIVELSE, OPPRETTET_AV, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, SKJERMLENKE_TYPE, TILBAKEHOPP_VED_GJENOPPTAKELSE, AKSJONSPUNKT_TYPE)
VALUES ('7012', 'Iverksettende behandling', 'IVEDSTEG.UT', null, 'Iverksettende behandling', 'VL', '-', 'N', '-', 'J', 'AUTO');

INSERT INTO PROSESS_TASK_TYPE (KODE, NAVN, FEIL_MAKS_FORSOEK, FEIL_SEK_MELLOM_FORSOEK, FEILHANDTERING_ALGORITME, BESKRIVELSE)
  values ('iverksetteVedtak.startBerørtBehandling', 'Vurder neste oppgave i behandlingskøen.', 3, 60, 'DEFAULT',
  'Vurder neste oppgave i behandlingskøen.');

ALTER TABLE BEHANDLING_ARSAK ADD beroert_behandling_id NUMBER(19);
ALTER TABLE BEHANDLING_ARSAK ADD CONSTRAINT FK_BEHANDLING_ARSAK_3 FOREIGN KEY (beroert_behandling_id) REFERENCES BEHANDLING;
create index IDX_BEHANDLING_ARSAK_8 on BEHANDLING_ARSAK(BEROERT_BEHANDLING_ID);
COMMENT ON COLUMN BEHANDLING_ARSAK.beroert_behandling_id IS 'FK: BEHANDLING';
