UPDATE AKSJONSPUNKT_DEF set AKSJONSPUNKT_TYPE = 'AUTO' where KODE IN ('7013');

UPDATE SOEKNAD s
SET s.BRUKER_ROLLE=(SELECT f.BRUKER_ROLLE FROM FAGSAK f
  INNER JOIN BEHANDLING b ON f.ID = b.FAGSAK_ID
  INNER JOIN GR_FAMILIE_HENDELSE fh ON b.ID = fh.BEHANDLING_ID
WHERE fh.ID=s.FAMILIE_HENDELSE_ID)
WHERE s.BRUKER_ROLLE='-' AND EXISTS(SELECT f.BRUKER_ROLLE FROM FAGSAK f
  INNER JOIN BEHANDLING b ON f.ID = b.FAGSAK_ID
  INNER JOIN GR_FAMILIE_HENDELSE fh ON b.ID = fh.BEHANDLING_ID
WHERE fh.ID=s.FAMILIE_HENDELSE_ID);
