ALTER TABLE YF_FORDELING_PERIODE ADD VIRKSOMHET_ID NUMBER(19);
ALTER TABLE YF_FORDELING_PERIODE ADD ARBEIDSTAKER VARCHAR2(1 CHAR) DEFAULT 'N';

ALTER TABLE YF_FORDELING_PERIODE add CONSTRAINT FK_YF_FORDELING_PERIODE_1 FOREIGN KEY (VIRKSOMHET_ID) REFERENCES VIRKSOMHET (ID);

COMMENT ON COLUMN YF_FORDELING_PERIODE.VIRKSOMHET_ID IS 'FK: VIRKSOMHET';
COMMENT ON COLUMN YF_FORDELING_PERIODE.ARBEIDSTAKER IS 'Er arbeidstype arbeidstaker.';
