ALTER TABLE FAGSAK
DROP CONSTRAINT FK_FAGSAK_81;

ALTER TABLE FAGSAK
MODIFY (KL_BRUKER_ROLLE_TYPE NULL);

ALTER TABLE FAGSAK
DROP COLUMN KL_BRUKER_ROLLE_TYPE;

ALTER TABLE FAGSAK
ADD (KL_RELASJONSROLLE_TYPE VARCHAR2(100 CHAR) AS ('RELASJONSROLLE_TYPE'));

COMMENT ON COLUMN FAGSAK.KL_RELASJONSROLLE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

ALTER TABLE FAGSAK
MODIFY (KL_RELASJONSROLLE_TYPE NOT NULL);

DELETE FROM KODELISTE
WHERE KODEVERK='BRUKER_ROLLE_TYPE';

INSERT INTO KODELISTE (id, kodeverk, kode, offisiell_kode, navn, beskrivelse, gyldig_fom)
VALUES(seq_kodeliste.nextval, 'RELASJONSROLLE_TYPE', '-', null, 'Ikke definert', 'Ikke definert', to_date('2000-01-01', 'YYYY-MM-DD'));

ALTER TABLE FAGSAK
ADD CONSTRAINT FK_FAGSAK_81
FOREIGN KEY (BRUKER_ROLLE, KL_RELASJONSROLLE_TYPE) REFERENCES KODELISTE(KODE, KODEVERK);
