-- Kolbing mellom søknad og behandling
INSERT INTO GR_SOEKNAD (id, behandling_id, soeknad_id, aktiv)
  SELECT SEQ_GR_SOEKNAD.nextval, b.id, sos.id, 'J' FROM SO_SOEKNAD sos
  inner join BEHANDLING b on b.BEHANDLING_GRUNNLAG_ID = sos.BEHANDLING_GRUNNLAG_ID
  where sos.BEHANDLING_GRUNNLAG_ID is not null;

alter table SO_SOEKNAD drop COLUMN BEHANDLING_GRUNNLAG_ID;

ALTER TABLE BEHANDLING DROP CONSTRAINT FK_BEHANDLING_6;
ALTER TABLE BEHANDLING_GRUNNLAG DROP CONSTRAINT FK_BEHANDLING_GRUNNLAG_1;
ALTER TABLE BEHANDLING_GRUNNLAG DROP CONSTRAINT FK_BEHANDLING_GRUNNLAG_80;
DROP TABLE BEHANDLING_GRUNNLAG;

alter table BEHANDLING drop COLUMN BEHANDLING_GRUNNLAG_ID;
