drop table FH_ADOPSJON cascade constraints purge;
drop table FH_UIDENTIFISERT_BARN cascade constraints  purge;
drop table FH_TERMINBEKREFTELSE cascade constraints purge;
drop table GR_FAMILIE_HENDELSE cascade constraints purge;

drop table SO_ANNEN_PART cascade constraints purge;

ALTER TABLE SO_SOEKNAD DROP (FOEDSELSDATO_FRA_SOEKNAD, UTSTEDT_DATO_TERMINBEKREFTELSE, TERMINDATO_FRA_SOEKNAD, ANTALL_BARN_FRA_SOEKNAD, ADOP_OMSORGOVER_DATO, ANNEN_PART_ID, NAVN_PAA_TERMINBEKREFTELSE, FAMILIE_HENDELSE_ID);
ALTER TABLE GR_PERSONOPPLYSNING DROP (SO_ANNEN_PART_ID);

DROP SEQUENCE SEQ_ADOPSJON;
DROP SEQUENCE SEQ_ADOPSJON_BARN;
DROP SEQUENCE SEQ_SOEKNAD_ADOPSJON_BARN;
DROP SEQUENCE SEQ_FOEDSEL;
DROP SEQUENCE SEQ_TERMINBEKREFTELSE;
DROP SEQUENCE SEQ_OMSORGSOVERTAKELSE;
DROP SEQUENCE SEQ_UIDENTIFISERT_BARN;
DROP SEQUENCE SEQ_FAMILIE_HENDELSE;
DROP SEQUENCE SEQ_GR_FAMILIE_HENDELSE;
