drop table KLAGE_VURDERING_RESULTAT cascade constraints purge;
drop sequence SEQ_KLAGE_VURDERING_RESULTAT;

drop table INNSYN cascade constraints purge;
drop sequence SEQ_INNSYN;

drop table INNSYN_DOKUMENT cascade constraints purge;
drop sequence SEQ_INNSYN_DOKUMENT;

alter table so_soeknad drop constraint FK_SOEKNAD_80;
alter table so_soeknad drop column kl_far_soeker_type;
alter table so_soeknad drop column far_soeker_type;

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK like 'KLAGE%';
DELETE FROM KODELISTE WHERE KODEVERK like 'KLAGE%';
DELETE FROM KODEVERK WHERE KODE  like 'KLAGE%';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK like 'INNSYN%';
DELETE FROM KODELISTE WHERE KODEVERK like 'INNSYN%';
DELETE FROM KODEVERK WHERE KODE  like 'INNSYN%';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_RESULTAT_TYPE' AND (KL_KODE LIKE '%INNSYN%' OR KL_KODE LIKE '%KLAGE%');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_RESULTAT_TYPE' AND ( KODE LIKE '%INNSYN%' OR KODE LIKE '%INNSYN%');

delete from aksjonspunkt_def where vurderingspunkt like 'KLAGE%' OR vurderingspunkt LIKE '%INNSYN%';
DELETE from behandling_type_steg_sekv where behandling_type in('BT-003', 'BT-005', 'BT-006');
delete from vurderingspunkt_def where (kode like 'KLAGE%' OR kode like '%INNSYN%');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_TYPE' and kl_kode in('BT-003', 'BT-005', 'BT-006');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_TYPE' and kode in('BT-003', 'BT-005', 'BT-006');


DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODE = 'VEDTAK_I_KLAGEBEHANDLING';
DELETE FROM KODELISTE WHERE KODE = 'VEDTAK_I_KLAGEBEHANDLING';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODE = 'VEDTAK_I_INNSYNBEHANDLING';
DELETE FROM KODELISTE WHERE KODE = 'VEDTAK_I_INNSYNBEHANDLING';


DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SKJERMLENKE_TYPE' and kl_kode in ('KLAGE_BEH_NFP', 'KLAGE_BEH_NK');
DELETE FROM KODELISTE WHERE KODEVERK = 'SKJERMLENKE_TYPE' and kode in ('KLAGE_BEH_NFP', 'KLAGE_BEH_NK');

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FAR_SOEKER_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK = 'FAR_SOEKER_TYPE';
DELETE FROM KODEVERK WHERE KODE  = 'FAR_SOEKER_TYPE';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SOEKNAD_ANNEN_PART';
DELETE FROM KODELISTE WHERE KODEVERK = 'SOEKNAD_ANNEN_PART';
DELETE FROM KODEVERK WHERE KODE  = 'SOEKNAD_ANNEN_PART';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FORELDRE_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK = 'FORELDRE_TYPE';
DELETE FROM KODEVERK WHERE KODE  = 'FORELDRE_TYPE';

