DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VURDER_AARSAK' and kode1 NOT IN ('FEIL_FAKTA', 'ANNET', 'FEIL_LOV', 'FEIL_REGEL', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VURDER_AARSAK' and kode2 NOT IN ('FEIL_FAKTA', 'ANNET', 'FEIL_LOV', 'FEIL_REGEL', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VURDER_AARSAK' AND KL_KODE NOT IN ('FEIL_FAKTA', 'ANNET', 'FEIL_LOV', 'FEIL_REGEL', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'VURDER_AARSAK' and kode NOT IN ('FEIL_FAKTA', 'ANNET', 'FEIL_LOV', 'FEIL_REGEL', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VILKAR_UTFALL_TYPE' and kode1 NOT IN ('IKKE_VURDERT', '-', 'IKKE_OPPFYLT', 'OPPFYLT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VILKAR_UTFALL_TYPE' and kode2 NOT IN ('IKKE_VURDERT', '-', 'IKKE_OPPFYLT', 'OPPFYLT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_UTFALL_TYPE' AND KL_KODE NOT IN ('IKKE_VURDERT', '-', 'IKKE_OPPFYLT', 'OPPFYLT');
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_UTFALL_TYPE' and kode NOT IN ('IKKE_VURDERT', '-', 'IKKE_OPPFYLT', 'OPPFYLT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='LAGRET_VEDTAK_TYPE' and kode1 NOT IN ('FODSEL', 'ADOPSJON', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='LAGRET_VEDTAK_TYPE' and kode2 NOT IN ('FODSEL', 'ADOPSJON', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'LAGRET_VEDTAK_TYPE' AND KL_KODE NOT IN ('FODSEL', 'ADOPSJON', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'LAGRET_VEDTAK_TYPE' and kode NOT IN ('FODSEL', 'ADOPSJON', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VERGE_TYPE' and kode1 NOT IN ('BARN', '-', 'FBARN', 'VOKSEN');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VERGE_TYPE' and kode2 NOT IN ('BARN', '-', 'FBARN', 'VOKSEN');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VERGE_TYPE' AND KL_KODE NOT IN ('BARN', '-', 'FBARN', 'VOKSEN');
DELETE FROM KODELISTE WHERE KODEVERK = 'VERGE_TYPE' and kode NOT IN ('BARN', '-', 'FBARN', 'VOKSEN');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTS_FORMAAL' and kode1 NOT IN ('FORMAAL_FORELDREPENGER', 'FORMAAL_PGI', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTS_FORMAAL' and kode2 NOT IN ('FORMAAL_FORELDREPENGER', 'FORMAAL_PGI', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTS_FORMAAL' AND KL_KODE NOT IN ('FORMAAL_FORELDREPENGER', 'FORMAAL_PGI', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTS_FORMAAL' and kode NOT IN ('FORMAAL_FORELDREPENGER', 'FORMAAL_PGI', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BG_HJEMMEL' and kode1 NOT IN ('F_14_7_8_30', 'F_14_7', 'F_14_7_8_49', 'F_14_7_8_47', '-', 'F_14_7_8_43', 'F_14_7_8_42', 'F_14_7_8_38', 'F_14_7_8_40', 'F_14_7_8_41', 'F_14_7_8_35');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BG_HJEMMEL' and kode2 NOT IN ('F_14_7_8_30', 'F_14_7', 'F_14_7_8_49', 'F_14_7_8_47', '-', 'F_14_7_8_43', 'F_14_7_8_42', 'F_14_7_8_38', 'F_14_7_8_40', 'F_14_7_8_41', 'F_14_7_8_35');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BG_HJEMMEL' AND KL_KODE NOT IN ('F_14_7_8_30', 'F_14_7', 'F_14_7_8_49', 'F_14_7_8_47', '-', 'F_14_7_8_43', 'F_14_7_8_42', 'F_14_7_8_38', 'F_14_7_8_40', 'F_14_7_8_41', 'F_14_7_8_35');
DELETE FROM KODELISTE WHERE KODEVERK = 'BG_HJEMMEL' and kode NOT IN ('F_14_7_8_30', 'F_14_7', 'F_14_7_8_49', 'F_14_7_8_47', '-', 'F_14_7_8_43', 'F_14_7_8_42', 'F_14_7_8_38', 'F_14_7_8_40', 'F_14_7_8_41', 'F_14_7_8_35');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='SOEKNAD_ANNEN_PART' and kode1 NOT IN ('MOR', '-', 'MEDFAR', 'MEDMOR', 'FAR');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='SOEKNAD_ANNEN_PART' and kode2 NOT IN ('MOR', '-', 'MEDFAR', 'MEDMOR', 'FAR');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SOEKNAD_ANNEN_PART' AND KL_KODE NOT IN ('MOR', '-', 'MEDFAR', 'MEDMOR', 'FAR');
DELETE FROM KODELISTE WHERE KODEVERK = 'SOEKNAD_ANNEN_PART' and kode NOT IN ('MOR', '-', 'MEDFAR', 'MEDMOR', 'FAR');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_STATUS' and kode1 NOT IN ('OPPRE', 'UTRED', 'AVSLU', 'FVED', 'IVED');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_STATUS' and kode2 NOT IN ('OPPRE', 'UTRED', 'AVSLU', 'FVED', 'IVED');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_STATUS' AND KL_KODE NOT IN ('OPPRE', 'UTRED', 'AVSLU', 'FVED', 'IVED');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_STATUS' and kode NOT IN ('OPPRE', 'UTRED', 'AVSLU', 'FVED', 'IVED');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='AKSJONSPUNKT_TYPE' and kode1 NOT IN ('OVST', '-', 'AUTO', 'SAOV', 'MANU');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='AKSJONSPUNKT_TYPE' and kode2 NOT IN ('OVST', '-', 'AUTO', 'SAOV', 'MANU');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'AKSJONSPUNKT_TYPE' AND KL_KODE NOT IN ('OVST', '-', 'AUTO', 'SAOV', 'MANU');
DELETE FROM KODELISTE WHERE KODEVERK = 'AKSJONSPUNKT_TYPE' and kode NOT IN ('OVST', '-', 'AUTO', 'SAOV', 'MANU');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_TILSTAND' and kode1 NOT IN ('ÅPEN', 'AVSLUTTET', 'LØPENDE', 'IKKESTARTET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_TILSTAND' and kode2 NOT IN ('ÅPEN', 'AVSLUTTET', 'LØPENDE', 'IKKESTARTET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_TILSTAND' AND KL_KODE NOT IN ('ÅPEN', 'AVSLUTTET', 'LØPENDE', 'IKKESTARTET');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_TILSTAND' and kode NOT IN ('ÅPEN', 'AVSLUTTET', 'LØPENDE', 'IKKESTARTET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTSPOST_TYPE' and kode1 NOT IN ('NÆRING_FISKE_FANGST_FAMBARNEHAGE', '-', 'LØNN', 'YTELSE', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTSPOST_TYPE' and kode2 NOT IN ('NÆRING_FISKE_FANGST_FAMBARNEHAGE', '-', 'LØNN', 'YTELSE', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTSPOST_TYPE' AND KL_KODE NOT IN ('NÆRING_FISKE_FANGST_FAMBARNEHAGE', '-', 'LØNN', 'YTELSE', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTSPOST_TYPE' and kode NOT IN ('NÆRING_FISKE_FANGST_FAMBARNEHAGE', '-', 'LØNN', 'YTELSE', 'SELVSTENDIG_NÆRINGSDRIVENDE');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_RESULTAT_TYPE' and kode1 NOT IN ('HENLAGT_SØKNAD_TRUKKET', 'AVSLÅTT', 'INGEN_ENDRING', 'OPPHØR', 'HENLAGT_BRUKER_DØD', 'MERGET_OG_HENLAGT', 'IKKE_FASTSATT', 'INNVILGET', 'MANGLER_BEREGNINGSREGLER', 'HENLAGT_SØKNAD_MANGLER', 'HENLAGT_FEILOPPRETTET', 'FORELDREPENGER_ENDRET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_RESULTAT_TYPE' and kode2 NOT IN ('HENLAGT_SØKNAD_TRUKKET', 'AVSLÅTT', 'INGEN_ENDRING', 'OPPHØR', 'HENLAGT_BRUKER_DØD', 'MERGET_OG_HENLAGT', 'IKKE_FASTSATT', 'INNVILGET', 'MANGLER_BEREGNINGSREGLER', 'HENLAGT_SØKNAD_MANGLER', 'HENLAGT_FEILOPPRETTET', 'FORELDREPENGER_ENDRET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_RESULTAT_TYPE' AND KL_KODE NOT IN ('HENLAGT_SØKNAD_TRUKKET', 'AVSLÅTT', 'INGEN_ENDRING', 'OPPHØR', 'HENLAGT_BRUKER_DØD', 'MERGET_OG_HENLAGT', 'IKKE_FASTSATT', 'INNVILGET', 'MANGLER_BEREGNINGSREGLER', 'HENLAGT_SØKNAD_MANGLER', 'HENLAGT_FEILOPPRETTET', 'FORELDREPENGER_ENDRET');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_RESULTAT_TYPE' and kode NOT IN ('HENLAGT_SØKNAD_TRUKKET', 'AVSLÅTT', 'INGEN_ENDRING', 'OPPHØR', 'HENLAGT_BRUKER_DØD', 'MERGET_OG_HENLAGT', 'IKKE_FASTSATT', 'INNVILGET', 'MANGLER_BEREGNINGSREGLER', 'HENLAGT_SØKNAD_MANGLER', 'HENLAGT_FEILOPPRETTET', 'FORELDREPENGER_ENDRET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='DOKUMENT_MAL_RESTRIKSJON' and kode1 NOT IN ('ÅPEN_BEHANDLING', 'INGEN', 'ÅPEN_BEHANDLING_IKKE_SENDT', 'REVURDERING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='DOKUMENT_MAL_RESTRIKSJON' and kode2 NOT IN ('ÅPEN_BEHANDLING', 'INGEN', 'ÅPEN_BEHANDLING_IKKE_SENDT', 'REVURDERING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'DOKUMENT_MAL_RESTRIKSJON' AND KL_KODE NOT IN ('ÅPEN_BEHANDLING', 'INGEN', 'ÅPEN_BEHANDLING_IKKE_SENDT', 'REVURDERING');
DELETE FROM KODELISTE WHERE KODEVERK = 'DOKUMENT_MAL_RESTRIKSJON' and kode NOT IN ('ÅPEN_BEHANDLING', 'INGEN', 'ÅPEN_BEHANDLING_IKKE_SENDT', 'REVURDERING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MEDLEMSKAP_DEKNING' and kode1 NOT IN ('FTL_2_9_1_c', 'FTL_2_9_1_b', 'FTL_2_6', 'OPPHOR', 'IHT_AVTALE', '-', 'UNNTATT', 'FTL_2_9_1_a', 'FTL_2_7_b', 'FTL_2_7_a', 'FTL_2_9_2_c', 'FULL', 'FTL_2_9_2_a');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MEDLEMSKAP_DEKNING' and kode2 NOT IN ('FTL_2_9_1_c', 'FTL_2_9_1_b', 'FTL_2_6', 'OPPHOR', 'IHT_AVTALE', '-', 'UNNTATT', 'FTL_2_9_1_a', 'FTL_2_7_b', 'FTL_2_7_a', 'FTL_2_9_2_c', 'FULL', 'FTL_2_9_2_a');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'MEDLEMSKAP_DEKNING' AND KL_KODE NOT IN ('FTL_2_9_1_c', 'FTL_2_9_1_b', 'FTL_2_6', 'OPPHOR', 'IHT_AVTALE', '-', 'UNNTATT', 'FTL_2_9_1_a', 'FTL_2_7_b', 'FTL_2_7_a', 'FTL_2_9_2_c', 'FULL', 'FTL_2_9_2_a');
DELETE FROM KODELISTE WHERE KODEVERK = 'MEDLEMSKAP_DEKNING' and kode NOT IN ('FTL_2_9_1_c', 'FTL_2_9_1_b', 'FTL_2_6', 'OPPHOR', 'IHT_AVTALE', '-', 'UNNTATT', 'FTL_2_9_1_a', 'FTL_2_7_b', 'FTL_2_7_a', 'FTL_2_9_2_c', 'FULL', 'FTL_2_9_2_a');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='REGION' and kode1 NOT IN ('EOS', '-', 'NORDEN', 'ANNET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='REGION' and kode2 NOT IN ('EOS', '-', 'NORDEN', 'ANNET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'REGION' AND KL_KODE NOT IN ('EOS', '-', 'NORDEN', 'ANNET');
DELETE FROM KODELISTE WHERE KODEVERK = 'REGION' and kode NOT IN ('EOS', '-', 'NORDEN', 'ANNET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='IVERKSETTING_STATUS' and kode1 NOT IN ('-', 'IKKE_IVERKSATT', 'UNDER_IVERKSETTING', 'IVERKSATT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='IVERKSETTING_STATUS' and kode2 NOT IN ('-', 'IKKE_IVERKSATT', 'UNDER_IVERKSETTING', 'IVERKSATT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'IVERKSETTING_STATUS' AND KL_KODE NOT IN ('-', 'IKKE_IVERKSATT', 'UNDER_IVERKSETTING', 'IVERKSATT');
DELETE FROM KODELISTE WHERE KODEVERK = 'IVERKSETTING_STATUS' and kode NOT IN ('-', 'IKKE_IVERKSATT', 'UNDER_IVERKSETTING', 'IVERKSATT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEREGNINGSGRUNNLAG_TILSTAND' and kode1 NOT IN ('FASTSATT_INN', 'KOFAKBER_UT', 'FASTSATT', 'OPPRETTET', '-', 'FORESLÅTT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEREGNINGSGRUNNLAG_TILSTAND' and kode2 NOT IN ('FASTSATT_INN', 'KOFAKBER_UT', 'FASTSATT', 'OPPRETTET', '-', 'FORESLÅTT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEREGNINGSGRUNNLAG_TILSTAND' AND KL_KODE NOT IN ('FASTSATT_INN', 'KOFAKBER_UT', 'FASTSATT', 'OPPRETTET', '-', 'FORESLÅTT');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEREGNINGSGRUNNLAG_TILSTAND' and kode NOT IN ('FASTSATT_INN', 'KOFAKBER_UT', 'FASTSATT', 'OPPRETTET', '-', 'FORESLÅTT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='DOKUMENT_GRUPPE' and kode1 NOT IN ('KLAGE', 'ENDRINGSSØKNAD', 'INNTEKTSMELDING', 'VEDLEGG', '-', 'SØKNAD');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='DOKUMENT_GRUPPE' and kode2 NOT IN ('KLAGE', 'ENDRINGSSØKNAD', 'INNTEKTSMELDING', 'VEDLEGG', '-', 'SØKNAD');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'DOKUMENT_GRUPPE' AND KL_KODE NOT IN ('KLAGE', 'ENDRINGSSØKNAD', 'INNTEKTSMELDING', 'VEDLEGG', '-', 'SØKNAD');
DELETE FROM KODELISTE WHERE KODEVERK = 'DOKUMENT_GRUPPE' and kode NOT IN ('KLAGE', 'ENDRINGSSØKNAD', 'INNTEKTSMELDING', 'VEDLEGG', '-', 'SØKNAD');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='PERMISJONSBESKRIVELSE_TYPE' and kode1 NOT IN ('UTDANNINGSPERMISJON', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='PERMISJONSBESKRIVELSE_TYPE' and kode2 NOT IN ('UTDANNINGSPERMISJON', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'PERMISJONSBESKRIVELSE_TYPE' AND KL_KODE NOT IN ('UTDANNINGSPERMISJON', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'PERMISJONSBESKRIVELSE_TYPE' and kode NOT IN ('UTDANNINGSPERMISJON', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSAK_STATUS' and kode1 NOT IN ('LOP', 'AVSLU', 'UBEH', 'OPPR');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='FAGSAK_STATUS' and kode2 NOT IN ('LOP', 'AVSLU', 'UBEH', 'OPPR');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FAGSAK_STATUS' AND KL_KODE NOT IN ('LOP', 'AVSLU', 'UBEH', 'OPPR');
DELETE FROM KODELISTE WHERE KODEVERK = 'FAGSAK_STATUS' and kode NOT IN ('LOP', 'AVSLU', 'UBEH', 'OPPR');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='KONSEKVENS_FOR_YTELSEN' and kode1 NOT IN ('ENDRING_I_UTTAK', 'INGEN_ENDRING', 'ENDRING_I_FORDELING_AV_YTELSEN', '-', 'FORELDREPENGER_OPPHØRER', 'ENDRING_I_BEREGNING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='KONSEKVENS_FOR_YTELSEN' and kode2 NOT IN ('ENDRING_I_UTTAK', 'INGEN_ENDRING', 'ENDRING_I_FORDELING_AV_YTELSEN', '-', 'FORELDREPENGER_OPPHØRER', 'ENDRING_I_BEREGNING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'KONSEKVENS_FOR_YTELSEN' AND KL_KODE NOT IN ('ENDRING_I_UTTAK', 'INGEN_ENDRING', 'ENDRING_I_FORDELING_AV_YTELSEN', '-', 'FORELDREPENGER_OPPHØRER', 'ENDRING_I_BEREGNING');
DELETE FROM KODELISTE WHERE KODEVERK = 'KONSEKVENS_FOR_YTELSEN' and kode NOT IN ('ENDRING_I_UTTAK', 'INGEN_ENDRING', 'ENDRING_I_FORDELING_AV_YTELSEN', '-', 'FORELDREPENGER_OPPHØRER', 'ENDRING_I_BEREGNING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='PERSONSTATUS_TYPE' and kode1 NOT IN ('FOSV', 'UTAN', 'UREG', 'UTPE', 'ADNR', '-', 'BOSA', 'UFUL', 'UTVA', 'DØD', 'ABNR', 'FØDR');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='PERSONSTATUS_TYPE' and kode2 NOT IN ('FOSV', 'UTAN', 'UREG', 'UTPE', 'ADNR', '-', 'BOSA', 'UFUL', 'UTVA', 'DØD', 'ABNR', 'FØDR');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'PERSONSTATUS_TYPE' AND KL_KODE NOT IN ('FOSV', 'UTAN', 'UREG', 'UTPE', 'ADNR', '-', 'BOSA', 'UFUL', 'UTVA', 'DØD', 'ABNR', 'FØDR');
DELETE FROM KODELISTE WHERE KODEVERK = 'PERSONSTATUS_TYPE' and kode NOT IN ('FOSV', 'UTAN', 'UREG', 'UTPE', 'ADNR', '-', 'BOSA', 'UFUL', 'UTVA', 'DØD', 'ABNR', 'FØDR');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKKINNSLAG_TYPE' and kode1 NOT IN ('MANGELFULL_SØKNAD', 'BEH_VENT', 'BEH_MAN_GJEN', 'BEH_OPPDATERT_NYE_OPPL', 'KØET_BEH_GJEN', 'BEH_AVBRUTT_VUR', 'SPOLT_TILBAKE', 'BEH_STARTET_PÅ_NYTT', 'FORSLAG_VEDTAK', 'FORSLAG_VEDTAK_UTEN_TOTRINN', 'SAK_RETUR', 'AVBRUTT_BEH', 'KLAGE_BEH_NK', 'OVERSTYRT', 'OPPTJENING', 'FASTSATT_UTTAK_SPLITT', 'OVST_UTTAK', 'VRS_REV_IKKE_SNDT', 'VEDTAK_FATTET', 'OVST_UTTAK_SPLITT', 'REVURD_OPPR', 'IVERKSETTELSE_VENT', 'BYTT_ENHET', '-', 'REGISTRER_OM_VERGE', 'UENDRET_UTFALL', 'BEH_STARTET', 'KLAGE_BEH_NFP', 'BREV_SENT', 'BREV_BESTILT', 'INNSYN_OPPR', 'FAKTA_ENDRET', 'REGISTRER_PAPIRSØK', 'VEDLEGG_MOTTATT', 'FASTSATT_UTTAK', 'NYE_REGOPPLYSNINGER', 'KLAGEBEH_STARTET', 'BEH_GJEN', 'BEH_KØET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKKINNSLAG_TYPE' and kode2 NOT IN ('MANGELFULL_SØKNAD', 'BEH_VENT', 'BEH_MAN_GJEN', 'BEH_OPPDATERT_NYE_OPPL', 'KØET_BEH_GJEN', 'BEH_AVBRUTT_VUR', 'SPOLT_TILBAKE', 'BEH_STARTET_PÅ_NYTT', 'FORSLAG_VEDTAK', 'FORSLAG_VEDTAK_UTEN_TOTRINN', 'SAK_RETUR', 'AVBRUTT_BEH', 'KLAGE_BEH_NK', 'OVERSTYRT', 'OPPTJENING', 'FASTSATT_UTTAK_SPLITT', 'OVST_UTTAK', 'VRS_REV_IKKE_SNDT', 'VEDTAK_FATTET', 'OVST_UTTAK_SPLITT', 'REVURD_OPPR', 'IVERKSETTELSE_VENT', 'BYTT_ENHET', '-', 'REGISTRER_OM_VERGE', 'UENDRET_UTFALL', 'BEH_STARTET', 'KLAGE_BEH_NFP', 'BREV_SENT', 'BREV_BESTILT', 'INNSYN_OPPR', 'FAKTA_ENDRET', 'REGISTRER_PAPIRSØK', 'VEDLEGG_MOTTATT', 'FASTSATT_UTTAK', 'NYE_REGOPPLYSNINGER', 'KLAGEBEH_STARTET', 'BEH_GJEN', 'BEH_KØET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKKINNSLAG_TYPE' AND KL_KODE NOT IN ('MANGELFULL_SØKNAD', 'BEH_VENT', 'BEH_MAN_GJEN', 'BEH_OPPDATERT_NYE_OPPL', 'KØET_BEH_GJEN', 'BEH_AVBRUTT_VUR', 'SPOLT_TILBAKE', 'BEH_STARTET_PÅ_NYTT', 'FORSLAG_VEDTAK', 'FORSLAG_VEDTAK_UTEN_TOTRINN', 'SAK_RETUR', 'AVBRUTT_BEH', 'KLAGE_BEH_NK', 'OVERSTYRT', 'OPPTJENING', 'FASTSATT_UTTAK_SPLITT', 'OVST_UTTAK', 'VRS_REV_IKKE_SNDT', 'VEDTAK_FATTET', 'OVST_UTTAK_SPLITT', 'REVURD_OPPR', 'IVERKSETTELSE_VENT', 'BYTT_ENHET', '-', 'REGISTRER_OM_VERGE', 'UENDRET_UTFALL', 'BEH_STARTET', 'KLAGE_BEH_NFP', 'BREV_SENT', 'BREV_BESTILT', 'INNSYN_OPPR', 'FAKTA_ENDRET', 'REGISTRER_PAPIRSØK', 'VEDLEGG_MOTTATT', 'FASTSATT_UTTAK', 'NYE_REGOPPLYSNINGER', 'KLAGEBEH_STARTET', 'BEH_GJEN', 'BEH_KØET');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKKINNSLAG_TYPE' and kode NOT IN ('MANGELFULL_SØKNAD', 'BEH_VENT', 'BEH_MAN_GJEN', 'BEH_OPPDATERT_NYE_OPPL', 'KØET_BEH_GJEN', 'BEH_AVBRUTT_VUR', 'SPOLT_TILBAKE', 'BEH_STARTET_PÅ_NYTT', 'FORSLAG_VEDTAK', 'FORSLAG_VEDTAK_UTEN_TOTRINN', 'SAK_RETUR', 'AVBRUTT_BEH', 'KLAGE_BEH_NK', 'OVERSTYRT', 'OPPTJENING', 'FASTSATT_UTTAK_SPLITT', 'OVST_UTTAK', 'VRS_REV_IKKE_SNDT', 'VEDTAK_FATTET', 'OVST_UTTAK_SPLITT', 'REVURD_OPPR', 'IVERKSETTELSE_VENT', 'BYTT_ENHET', '-', 'REGISTRER_OM_VERGE', 'UENDRET_UTFALL', 'BEH_STARTET', 'KLAGE_BEH_NFP', 'BREV_SENT', 'BREV_BESTILT', 'INNSYN_OPPR', 'FAKTA_ENDRET', 'REGISTRER_PAPIRSØK', 'VEDLEGG_MOTTATT', 'FASTSATT_UTTAK', 'NYE_REGOPPLYSNINGER', 'KLAGEBEH_STARTET', 'BEH_GJEN', 'BEH_KØET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='SKJERMLENKE_TYPE' and kode1 NOT IN ('PUNKT_FOR_OPPTJENING', 'FAKTA_OM_VERGE', 'FAKTA_OM_OPPTJENING', 'VEDTAK', 'SOEKNADSFRIST', 'UTTAK', 'KONTROLL_AV_SAKSOPPLYSNINGER', 'FAKTA_FOR_OPPTJENING', 'FAKTA_OM_ARBEIDSFORHOLD', 'BEREGNING_FORELDREPENGER', 'FAKTA_OM_BEREGNING', 'OPPLYSNINGSPLIKT', 'FAKTA_OM_MEDLEMSKAP', 'FAKTA_OM_UTTAK', '-', 'PUNKT_FOR_MEDLEMSKAP');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='SKJERMLENKE_TYPE' and kode2 NOT IN ('PUNKT_FOR_OPPTJENING', 'FAKTA_OM_VERGE', 'FAKTA_OM_OPPTJENING', 'VEDTAK', 'SOEKNADSFRIST', 'UTTAK', 'KONTROLL_AV_SAKSOPPLYSNINGER', 'FAKTA_FOR_OPPTJENING', 'FAKTA_OM_ARBEIDSFORHOLD', 'BEREGNING_FORELDREPENGER', 'FAKTA_OM_BEREGNING', 'OPPLYSNINGSPLIKT', 'FAKTA_OM_MEDLEMSKAP', 'FAKTA_OM_UTTAK', '-', 'PUNKT_FOR_MEDLEMSKAP');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SKJERMLENKE_TYPE' AND KL_KODE NOT IN ('PUNKT_FOR_OPPTJENING', 'FAKTA_OM_VERGE', 'FAKTA_OM_OPPTJENING', 'VEDTAK', 'SOEKNADSFRIST', 'UTTAK', 'KONTROLL_AV_SAKSOPPLYSNINGER', 'FAKTA_FOR_OPPTJENING', 'FAKTA_OM_ARBEIDSFORHOLD', 'BEREGNING_FORELDREPENGER', 'FAKTA_OM_BEREGNING', 'OPPLYSNINGSPLIKT', 'FAKTA_OM_MEDLEMSKAP', 'FAKTA_OM_UTTAK', '-', 'KLAGE_BEH_NFP', 'PUNKT_FOR_MEDLEMSKAP', 'KLAGE_BEH_NK');
DELETE FROM KODELISTE WHERE KODEVERK = 'SKJERMLENKE_TYPE' and kode NOT IN ('PUNKT_FOR_OPPTJENING', 'FAKTA_OM_VERGE', 'FAKTA_OM_OPPTJENING', 'VEDTAK', 'SOEKNADSFRIST', 'UTTAK', 'KONTROLL_AV_SAKSOPPLYSNINGER', 'FAKTA_FOR_OPPTJENING', 'FAKTA_OM_ARBEIDSFORHOLD', 'BEREGNING_FORELDREPENGER', 'FAKTA_OM_BEREGNING', 'OPPLYSNINGSPLIKT', 'FAKTA_OM_MEDLEMSKAP', 'FAKTA_OM_UTTAK', '-', 'KLAGE_BEH_NFP', 'PUNKT_FOR_MEDLEMSKAP', 'KLAGE_BEH_NK');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_STEG_STATUS' and kode1 NOT IN ('STARTET', 'TILBAKEFØRT', 'FREMOVERFØRT', 'UTFØRT', 'VENTER', 'INNGANG', 'AVBRUTT', 'UTGANG', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_STEG_STATUS' and kode2 NOT IN ('STARTET', 'TILBAKEFØRT', 'FREMOVERFØRT', 'UTFØRT', 'VENTER', 'INNGANG', 'AVBRUTT', 'UTGANG', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_STEG_STATUS' AND KL_KODE NOT IN ('STARTET', 'TILBAKEFØRT', 'FREMOVERFØRT', 'UTFØRT', 'VENTER', 'INNGANG', 'AVBRUTT', 'UTGANG', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_STEG_STATUS' and kode NOT IN ('STARTET', 'TILBAKEFØRT', 'FREMOVERFØRT', 'UTFØRT', 'VENTER', 'INNGANG', 'AVBRUTT', 'UTGANG', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='NATURAL_YTELSE_TYPE' and kode1 NOT IN ('AKSJER_UNDERKURS', 'BESOEKSREISER_HJEM', 'KOST_DOEGN', 'KOSTBESPARELSE_HJEM', 'RENTEFORDEL_LAAN', 'BEDRIFTSBARNEHAGE', 'ELEKTRISK_KOMMUNIKASJON', 'FORSIKRINGER', 'LOSJI', 'TILSKUDD_BARNEHAGE', 'FRI_TRANSPORT', 'ANNET', 'YRKESBIL_KILOMETER', 'OPSJONER', '-', 'YRKESBIL_LISTEPRIS', 'BIL', 'KOST_DAGER', 'BOLIG', 'UTENLANDSK_PENSJONSORDNING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='NATURAL_YTELSE_TYPE' and kode2 NOT IN ('AKSJER_UNDERKURS', 'BESOEKSREISER_HJEM', 'KOST_DOEGN', 'KOSTBESPARELSE_HJEM', 'RENTEFORDEL_LAAN', 'BEDRIFTSBARNEHAGE', 'ELEKTRISK_KOMMUNIKASJON', 'FORSIKRINGER', 'LOSJI', 'TILSKUDD_BARNEHAGE', 'FRI_TRANSPORT', 'ANNET', 'YRKESBIL_KILOMETER', 'OPSJONER', '-', 'YRKESBIL_LISTEPRIS', 'BIL', 'KOST_DAGER', 'BOLIG', 'UTENLANDSK_PENSJONSORDNING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'NATURAL_YTELSE_TYPE' AND KL_KODE NOT IN ('AKSJER_UNDERKURS', 'BESOEKSREISER_HJEM', 'KOST_DOEGN', 'KOSTBESPARELSE_HJEM', 'RENTEFORDEL_LAAN', 'BEDRIFTSBARNEHAGE', 'ELEKTRISK_KOMMUNIKASJON', 'FORSIKRINGER', 'LOSJI', 'TILSKUDD_BARNEHAGE', 'FRI_TRANSPORT', 'ANNET', 'YRKESBIL_KILOMETER', 'OPSJONER', '-', 'YRKESBIL_LISTEPRIS', 'BIL', 'KOST_DAGER', 'BOLIG', 'UTENLANDSK_PENSJONSORDNING');
DELETE FROM KODELISTE WHERE KODEVERK = 'NATURAL_YTELSE_TYPE' and kode NOT IN ('AKSJER_UNDERKURS', 'BESOEKSREISER_HJEM', 'KOST_DOEGN', 'KOSTBESPARELSE_HJEM', 'RENTEFORDEL_LAAN', 'BEDRIFTSBARNEHAGE', 'ELEKTRISK_KOMMUNIKASJON', 'FORSIKRINGER', 'LOSJI', 'TILSKUDD_BARNEHAGE', 'FRI_TRANSPORT', 'ANNET', 'YRKESBIL_KILOMETER', 'OPSJONER', '-', 'YRKESBIL_LISTEPRIS', 'BIL', 'KOST_DAGER', 'BOLIG', 'UTENLANDSK_PENSJONSORDNING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VEDTAK_RESULTAT_TYPE' and kode1 NOT IN ('-', 'DELVIS_INNVILGET', 'AVSLAG', 'OPPHØR', 'INNVILGET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VEDTAK_RESULTAT_TYPE' and kode2 NOT IN ('-', 'DELVIS_INNVILGET', 'AVSLAG', 'OPPHØR', 'INNVILGET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VEDTAK_RESULTAT_TYPE' AND KL_KODE NOT IN ('-', 'DELVIS_INNVILGET', 'AVSLAG', 'OPPHØR', 'INNVILGET');
DELETE FROM KODELISTE WHERE KODEVERK = 'VEDTAK_RESULTAT_TYPE' and kode NOT IN ('-', 'DELVIS_INNVILGET', 'AVSLAG', 'OPPHØR', 'INNVILGET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPLYSNINGSKILDE' and kode1 NOT IN ('SAKSBEH', 'UDEFINERT', 'TPS');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPLYSNINGSKILDE' and kode2 NOT IN ('SAKSBEH', 'UDEFINERT', 'TPS');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OPPLYSNINGSKILDE' AND KL_KODE NOT IN ('SAKSBEH', 'UDEFINERT', 'TPS');
DELETE FROM KODELISTE WHERE KODEVERK = 'OPPLYSNINGSKILDE' and kode NOT IN ('SAKSBEH', 'UDEFINERT', 'TPS');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='PERIODE_RESULTAT_AARSAK' and kode1 NOT IN ('-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='PERIODE_RESULTAT_AARSAK' and kode2 NOT IN ('-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'PERIODE_RESULTAT_AARSAK' AND KL_KODE NOT IN ('-');
DELETE FROM KODELISTE WHERE KODEVERK = 'PERIODE_RESULTAT_AARSAK' and kode NOT IN ('-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='REVURDERING_VARSLING_AARSAK' and kode1 NOT IN ('ANNET', 'JOBBFULLTID', 'IKKEOPPTJENT', 'IKKEOPPHOLD', 'AKTIVITET', 'BARNIKKEREG', 'JOBBUTLAND', 'UTVANDRET', 'JOBB6MND');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='REVURDERING_VARSLING_AARSAK' and kode2 NOT IN ('ANNET', 'JOBBFULLTID', 'IKKEOPPTJENT', 'IKKEOPPHOLD', 'AKTIVITET', 'BARNIKKEREG', 'JOBBUTLAND', 'UTVANDRET', 'JOBB6MND');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'REVURDERING_VARSLING_AARSAK' AND KL_KODE NOT IN ('ANNET', 'JOBBFULLTID', 'IKKEOPPTJENT', 'IKKEOPPHOLD', 'AKTIVITET', 'BARNIKKEREG', 'JOBBUTLAND', 'UTVANDRET', 'JOBB6MND');
DELETE FROM KODELISTE WHERE KODEVERK = 'REVURDERING_VARSLING_AARSAK' and kode NOT IN ('ANNET', 'JOBBFULLTID', 'IKKEOPPTJENT', 'IKKEOPPHOLD', 'AKTIVITET', 'BARNIKKEREG', 'JOBBUTLAND', 'UTVANDRET', 'JOBB6MND');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='ARBEID_TYPE' and kode1 NOT IN ('VARTPENGER', 'FORENKLET_OPPGJØRSORDNING', 'LØNN_UNDER_UTDANNING', 'VENTELØNN_VARTPENGER', 'ETTERLØNN_ARBEIDSGIVER', 'MILITÆR_ELLER_SIVILTJENESTE', 'ORDINÆRT_ARBEIDSFORHOLD', 'ETTERLØNN_SLUTTPAKKE', 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD', 'NÆRING', '-', 'FRILANSER', 'MARITIMT_ARBEIDSFORHOLD', 'FRILANSER_OPPDRAGSTAKER', 'SLUTTPAKKE', 'VENTELØNN', 'UTENLANDSK_ARBEIDSFORHOLD');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='ARBEID_TYPE' and kode2 NOT IN ('VARTPENGER', 'FORENKLET_OPPGJØRSORDNING', 'LØNN_UNDER_UTDANNING', 'VENTELØNN_VARTPENGER', 'ETTERLØNN_ARBEIDSGIVER', 'MILITÆR_ELLER_SIVILTJENESTE', 'ORDINÆRT_ARBEIDSFORHOLD', 'ETTERLØNN_SLUTTPAKKE', 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD', 'NÆRING', '-', 'FRILANSER', 'MARITIMT_ARBEIDSFORHOLD', 'FRILANSER_OPPDRAGSTAKER', 'SLUTTPAKKE', 'VENTELØNN', 'UTENLANDSK_ARBEIDSFORHOLD');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'ARBEID_TYPE' AND KL_KODE NOT IN ('VARTPENGER', 'FORENKLET_OPPGJØRSORDNING', 'LØNN_UNDER_UTDANNING', 'VENTELØNN_VARTPENGER', 'ETTERLØNN_ARBEIDSGIVER', 'MILITÆR_ELLER_SIVILTJENESTE', 'ORDINÆRT_ARBEIDSFORHOLD', 'ETTERLØNN_SLUTTPAKKE', 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD', 'NÆRING', '-', 'FRILANSER', 'MARITIMT_ARBEIDSFORHOLD', 'FRILANSER_OPPDRAGSTAKER', 'SLUTTPAKKE', 'VENTELØNN', 'UTENLANDSK_ARBEIDSFORHOLD');
DELETE FROM KODELISTE WHERE KODEVERK = 'ARBEID_TYPE' and kode NOT IN ('VARTPENGER', 'FORENKLET_OPPGJØRSORDNING', 'LØNN_UNDER_UTDANNING', 'VENTELØNN_VARTPENGER', 'ETTERLØNN_ARBEIDSGIVER', 'MILITÆR_ELLER_SIVILTJENESTE', 'ORDINÆRT_ARBEIDSFORHOLD', 'ETTERLØNN_SLUTTPAKKE', 'PENSJON_OG_ANDRE_TYPER_YTELSER_UTEN_ANSETTELSESFORHOLD', 'NÆRING', '-', 'FRILANSER', 'MARITIMT_ARBEIDSFORHOLD', 'FRILANSER_OPPDRAGSTAKER', 'SLUTTPAKKE', 'VENTELØNN', 'UTENLANDSK_ARBEIDSFORHOLD');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKT_PERIODE_TYPE' and kode1 NOT IN ('UKNLG', 'PREMGR', '-', 'MNDLG', 'AARLG', 'DAGLG', '14DLG', 'INNFS');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKT_PERIODE_TYPE' and kode2 NOT IN ('UKNLG', 'PREMGR', '-', 'MNDLG', 'AARLG', 'DAGLG', '14DLG', 'INNFS');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKT_PERIODE_TYPE' AND KL_KODE NOT IN ('UKNLG', 'PREMGR', '-', 'MNDLG', 'AARLG', 'DAGLG', '14DLG', 'INNFS');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKT_PERIODE_TYPE' and kode NOT IN ('UKNLG', 'PREMGR', '-', 'MNDLG', 'AARLG', 'DAGLG', '14DLG', 'INNFS');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTTAK_UTSETTELSE_TYPE' and kode1 NOT IN ('ARBEID', 'SYKDOM_SKADE', '-', 'SØKER_INNLAGT', 'FERIE', 'BARN_INNLAGT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTTAK_UTSETTELSE_TYPE' and kode2 NOT IN ('ARBEID', 'SYKDOM_SKADE', '-', 'SØKER_INNLAGT', 'FERIE', 'BARN_INNLAGT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'UTTAK_UTSETTELSE_TYPE' AND KL_KODE NOT IN ('ARBEID', 'SYKDOM_SKADE', '-', 'SØKER_INNLAGT', 'FERIE', 'BARN_INNLAGT');
DELETE FROM KODELISTE WHERE KODEVERK = 'UTTAK_UTSETTELSE_TYPE' and kode NOT IN ('ARBEID', 'SYKDOM_SKADE', '-', 'SØKER_INNLAGT', 'FERIE', 'BARN_INNLAGT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MEDLEMSKAP_KILDE' and kode1 NOT IN ('APPBRK', 'E500', 'AVGSYS', 'FS22', 'PP01', 'TP', 'ANNEN', 'MEDL', '-', 'LAANEKASSEN', 'INFOTR', 'TPS');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MEDLEMSKAP_KILDE' and kode2 NOT IN ('APPBRK', 'E500', 'AVGSYS', 'FS22', 'PP01', 'TP', 'ANNEN', 'MEDL', '-', 'LAANEKASSEN', 'INFOTR', 'TPS');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'MEDLEMSKAP_KILDE' AND KL_KODE NOT IN ('APPBRK', 'E500', 'AVGSYS', 'FS22', 'PP01', 'TP', 'ANNEN', 'MEDL', '-', 'LAANEKASSEN', 'INFOTR', 'TPS');
DELETE FROM KODELISTE WHERE KODEVERK = 'MEDLEMSKAP_KILDE' and kode NOT IN ('APPBRK', 'E500', 'AVGSYS', 'FS22', 'PP01', 'TP', 'ANNEN', 'MEDL', '-', 'LAANEKASSEN', 'INFOTR', 'TPS');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VILKAR_TYPE' and kode1 NOT IN ('FP_VK_3', 'FP_VK_41', 'FP_VK_23', 'FP_VK_2', 'FP_VK_34', 'FP_VK_21', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VILKAR_TYPE' and kode2 NOT IN ('FP_VK_3', 'FP_VK_41', 'FP_VK_23', 'FP_VK_2', 'FP_VK_34', 'FP_VK_21', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_TYPE' AND KL_KODE NOT IN ('FP_VK_3', 'FP_VK_41', 'FP_VK_23', 'FP_VK_2', 'FP_VK_34', 'FP_VK_21', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_TYPE' and kode NOT IN ('FP_VK_3', 'FP_VK_41', 'FP_VK_23', 'FP_VK_2', 'FP_VK_34', 'FP_VK_21', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='AVSLAGSARSAK' and kode1 NOT IN ('1041', '1019', '1021', '1020', '1035', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='AVSLAGSARSAK' and kode2 NOT IN ('1041', '1019', '1021', '1020', '1035', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'AVSLAGSARSAK' AND KL_KODE NOT IN ('1041', '1019', '1021', '1020', '1035', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'AVSLAGSARSAK' and kode NOT IN ('1041', '1019', '1021', '1020', '1035', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_AARSAK' and kode1 NOT IN ('RE-TILST-YT-INNVIL', 'RE-PRSSL', 'RE-MFIP', 'RE-INNTK', 'RE-ANNET', 'RE-TILST-YT-OPPH', 'RE-FEFAKTA', 'RE-FRDLING', 'RE-AVAB', 'RE-DØD', 'RE-RGLF', 'RE-END-INNTEKTSMELD', 'RE-BER-GRUN', 'RE-REGISTEROPPL', 'RE-MF', 'RE-END-FRA-BRUKER', 'BERØRT-BEHANDLING', '-', 'RE-LOV', 'RE-FRIST', 'RE-HENDELSE-FØDSEL', 'RE-ENDR-BER-GRUN', 'RE-YTELSE', 'RE-MDL', 'RE-OPTJ', 'KØET-BEHANDLING', 'RE-SRTB');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_AARSAK' and kode2 NOT IN ('RE-TILST-YT-INNVIL', 'RE-PRSSL', 'RE-MFIP', 'RE-INNTK', 'RE-ANNET', 'RE-TILST-YT-OPPH', 'RE-FEFAKTA', 'RE-FRDLING', 'RE-AVAB', 'RE-DØD', 'RE-RGLF', 'RE-END-INNTEKTSMELD', 'RE-BER-GRUN', 'RE-REGISTEROPPL', 'RE-MF', 'RE-END-FRA-BRUKER', 'BERØRT-BEHANDLING', '-', 'RE-LOV', 'RE-FRIST', 'RE-HENDELSE-FØDSEL', 'RE-ENDR-BER-GRUN', 'RE-YTELSE', 'RE-MDL', 'RE-OPTJ', 'KØET-BEHANDLING', 'RE-SRTB');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_AARSAK' AND KL_KODE NOT IN ('RE-TILST-YT-INNVIL', 'RE-PRSSL', 'RE-MFIP', 'RE-INNTK', 'RE-ANNET', 'RE-TILST-YT-OPPH', 'RE-FEFAKTA', 'RE-FRDLING', 'RE-AVAB', 'RE-DØD', 'RE-RGLF', 'RE-END-INNTEKTSMELD', 'RE-BER-GRUN', 'RE-REGISTEROPPL', 'RE-MF', 'RE-END-FRA-BRUKER', 'BERØRT-BEHANDLING', '-', 'RE-LOV', 'RE-FRIST', 'RE-HENDELSE-FØDSEL', 'RE-ENDR-BER-GRUN', 'RE-YTELSE', 'RE-MDL', 'RE-OPTJ', 'KØET-BEHANDLING', 'RE-SRTB');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_AARSAK' and kode NOT IN ('RE-TILST-YT-INNVIL', 'RE-PRSSL', 'RE-MFIP', 'RE-INNTK', 'RE-ANNET', 'RE-TILST-YT-OPPH', 'RE-FEFAKTA', 'RE-FRDLING', 'RE-AVAB', 'RE-DØD', 'RE-RGLF', 'RE-END-INNTEKTSMELD', 'RE-BER-GRUN', 'RE-REGISTEROPPL', 'RE-MF', 'RE-END-FRA-BRUKER', 'BERØRT-BEHANDLING', '-', 'RE-LOV', 'RE-FRIST', 'RE-HENDELSE-FØDSEL', 'RE-ENDR-BER-GRUN', 'RE-YTELSE', 'RE-MDL', 'RE-OPTJ', 'KØET-BEHANDLING', 'RE-SRTB');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VEDTAKSBREV' and kode1 NOT IN ('FRITEKST', '-', 'AUTOMATISK', 'INGEN');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VEDTAKSBREV' and kode2 NOT IN ('FRITEKST', '-', 'AUTOMATISK', 'INGEN');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VEDTAKSBREV' AND KL_KODE NOT IN ('FRITEKST', '-', 'AUTOMATISK', 'INGEN');
DELETE FROM KODELISTE WHERE KODEVERK = 'VEDTAKSBREV' and kode NOT IN ('FRITEKST', '-', 'AUTOMATISK', 'INGEN');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPTJENING_AKTIVITET_TYPE' and kode1 NOT IN ('PLEIEPENGER', 'FORELDREPENGER', 'AAP', 'NÆRING', 'SLUTTPAKKE', 'ETTERLØNN_SLUTTPAKKE', 'VENTELØNN_VARTPENGER', 'VENTELØNN', 'VIDERE_ETTERUTDANNING', 'UTENLANDSK_ARBEIDSFORHOLD', 'SVANGERSKAPSPENGER', 'OPPLÆRINGSPENGER', 'FRILANS', 'MILITÆR_ELLER_SIVILTJENESTE', 'ARBEID', 'OMSORGSPENGER', 'UTDANNINGSPERMISJON', '-', 'DAGPENGER', 'VARTPENGER', 'SYKEPENGER', 'ETTERLØNN_ARBEIDSGIVER');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPTJENING_AKTIVITET_TYPE' and kode2 NOT IN ('PLEIEPENGER', 'FORELDREPENGER', 'AAP', 'NÆRING', 'SLUTTPAKKE', 'ETTERLØNN_SLUTTPAKKE', 'VENTELØNN_VARTPENGER', 'VENTELØNN', 'VIDERE_ETTERUTDANNING', 'UTENLANDSK_ARBEIDSFORHOLD', 'SVANGERSKAPSPENGER', 'OPPLÆRINGSPENGER', 'FRILANS', 'MILITÆR_ELLER_SIVILTJENESTE', 'ARBEID', 'OMSORGSPENGER', 'UTDANNINGSPERMISJON', '-', 'DAGPENGER', 'VARTPENGER', 'SYKEPENGER', 'ETTERLØNN_ARBEIDSGIVER');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OPPTJENING_AKTIVITET_TYPE' AND KL_KODE NOT IN ('PLEIEPENGER', 'FORELDREPENGER', 'AAP', 'NÆRING', 'SLUTTPAKKE', 'ETTERLØNN_SLUTTPAKKE', 'VENTELØNN_VARTPENGER', 'VENTELØNN', 'VIDERE_ETTERUTDANNING', 'UTENLANDSK_ARBEIDSFORHOLD', 'SVANGERSKAPSPENGER', 'OPPLÆRINGSPENGER', 'FRILANS', 'MILITÆR_ELLER_SIVILTJENESTE', 'ARBEID', 'OMSORGSPENGER', 'UTDANNINGSPERMISJON', '-', 'DAGPENGER', 'VARTPENGER', 'SYKEPENGER', 'ETTERLØNN_ARBEIDSGIVER');
DELETE FROM KODELISTE WHERE KODEVERK = 'OPPTJENING_AKTIVITET_TYPE' and kode NOT IN ('PLEIEPENGER', 'FORELDREPENGER', 'AAP', 'NÆRING', 'SLUTTPAKKE', 'ETTERLØNN_SLUTTPAKKE', 'VENTELØNN_VARTPENGER', 'VENTELØNN', 'VIDERE_ETTERUTDANNING', 'UTENLANDSK_ARBEIDSFORHOLD', 'SVANGERSKAPSPENGER', 'OPPLÆRINGSPENGER', 'FRILANS', 'MILITÆR_ELLER_SIVILTJENESTE', 'ARBEID', 'OMSORGSPENGER', 'UTDANNINGSPERMISJON', '-', 'DAGPENGER', 'VARTPENGER', 'SYKEPENGER', 'ETTERLØNN_ARBEIDSGIVER');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RETTEN_TIL' and kode1 NOT IN ('-', 'HAR_RETT_TIL_FP', 'HAR_IKKE_RETT_TIL_FP');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RETTEN_TIL' and kode2 NOT IN ('-', 'HAR_RETT_TIL_FP', 'HAR_IKKE_RETT_TIL_FP');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RETTEN_TIL' AND KL_KODE NOT IN ('-', 'HAR_RETT_TIL_FP', 'HAR_IKKE_RETT_TIL_FP');
DELETE FROM KODELISTE WHERE KODEVERK = 'RETTEN_TIL' and kode NOT IN ('-', 'HAR_RETT_TIL_FP', 'HAR_IKKE_RETT_TIL_FP');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='REAKTIVERING_STATUS' and kode1 NOT IN ('AKTIV', 'SLETTET', 'INAKTIV');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='REAKTIVERING_STATUS' and kode2 NOT IN ('AKTIV', 'SLETTET', 'INAKTIV');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'REAKTIVERING_STATUS' AND KL_KODE NOT IN ('AKTIV', 'SLETTET', 'INAKTIV');
DELETE FROM KODELISTE WHERE KODEVERK = 'REAKTIVERING_STATUS' and kode NOT IN ('AKTIV', 'SLETTET', 'INAKTIV');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_BEGRUNNELSE_TYPE' and kode1 NOT IN ('BEH_STARTET_PA_NYTT', 'SAKSBEH_START_PA_NYTT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_BEGRUNNELSE_TYPE' and kode2 NOT IN ('BEH_STARTET_PA_NYTT', 'SAKSBEH_START_PA_NYTT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_BEGRUNNELSE_TYPE' AND KL_KODE NOT IN ('BEH_STARTET_PA_NYTT', 'SAKSBEH_START_PA_NYTT');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_BEGRUNNELSE_TYPE' and kode NOT IN ('BEH_STARTET_PA_NYTT', 'SAKSBEH_START_PA_NYTT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_AVKLART_SOEKNADSPERIODE_TYPE' and kode1 NOT IN ('UTSETTELSE_ARBEID');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_AVKLART_SOEKNADSPERIODE_TYPE' and kode2 NOT IN ('UTSETTELSE_ARBEID');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_AVKLART_SOEKNADSPERIODE_TYPE' AND KL_KODE NOT IN ('UTSETTELSE_ARBEID');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_AVKLART_SOEKNADSPERIODE_TYPE' and kode NOT IN ('UTSETTELSE_ARBEID');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSAK_YTELSE' and kode1 NOT IN ('-', 'FP');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='FAGSAK_YTELSE' and kode2 NOT IN ('-', 'FP');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FAGSAK_YTELSE' AND KL_KODE NOT IN ('-', 'FP');
DELETE FROM KODELISTE WHERE KODEVERK = 'FAGSAK_YTELSE' and kode NOT IN ('-', 'FP');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_SAKSTYPE' and kode1 NOT IN ('S', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_SAKSTYPE' and kode2 NOT IN ('S', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_SAKSTYPE' AND KL_KODE NOT IN ('S', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_SAKSTYPE' and kode NOT IN ('S', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_TEMA' and kode1 NOT IN ('AAP', 'BS', 'EF', 'SP', 'FA', 'DAG');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_TEMA' and kode2 NOT IN ('AAP', 'BS', 'EF', 'SP', 'FA', 'DAG');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_TEMA' AND KL_KODE NOT IN ('AAP', 'BS', 'EF', 'SP', 'FA', 'DAG');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_TEMA' and kode NOT IN ('AAP', 'BS', 'EF', 'SP', 'FA', 'DAG');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MEDLEMSKAP_MANUELL_VURD' and kode1 NOT IN ('OPPHOR_PGA_ENDRING_I_TPS', '-', 'UNNTAK', 'MEDLEM', 'IKKE_RELEVANT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MEDLEMSKAP_MANUELL_VURD' and kode2 NOT IN ('OPPHOR_PGA_ENDRING_I_TPS', '-', 'UNNTAK', 'MEDLEM', 'IKKE_RELEVANT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'MEDLEMSKAP_MANUELL_VURD' AND KL_KODE NOT IN ('OPPHOR_PGA_ENDRING_I_TPS', '-', 'UNNTAK', 'MEDLEM', 'IKKE_RELEVANT');
DELETE FROM KODELISTE WHERE KODEVERK = 'MEDLEMSKAP_MANUELL_VURD' and kode NOT IN ('OPPHOR_PGA_ENDRING_I_TPS', '-', 'UNNTAK', 'MEDLEM', 'IKKE_RELEVANT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='ARBEID_TYPE_KODE' and kode1 NOT IN ('-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='ARBEID_TYPE_KODE' and kode2 NOT IN ('-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'ARBEID_TYPE_KODE' AND KL_KODE NOT IN ('-');
DELETE FROM KODELISTE WHERE KODEVERK = 'ARBEID_TYPE_KODE' and kode NOT IN ('-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MEDLEMSKAP_TYPE' and kode1 NOT IN ('AVKLARES', 'FORELOPIG', 'ENDELIG', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MEDLEMSKAP_TYPE' and kode2 NOT IN ('AVKLARES', 'FORELOPIG', 'ENDELIG', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'MEDLEMSKAP_TYPE' AND KL_KODE NOT IN ('AVKLARES', 'FORELOPIG', 'ENDELIG', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'MEDLEMSKAP_TYPE' and kode NOT IN ('AVKLARES', 'FORELOPIG', 'ENDELIG', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPTJENING_AKTIVITET_KLASSIFISERING' and kode1 NOT IN ('-', 'ANTATT_GODKJENT', 'MELLOMLIGGENDE_PERIODE', 'BEKREFTET_AVVIST', 'BEKREFTET_GODKJENT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPTJENING_AKTIVITET_KLASSIFISERING' and kode2 NOT IN ('-', 'ANTATT_GODKJENT', 'MELLOMLIGGENDE_PERIODE', 'BEKREFTET_AVVIST', 'BEKREFTET_GODKJENT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OPPTJENING_AKTIVITET_KLASSIFISERING' AND KL_KODE NOT IN ('-', 'ANTATT_GODKJENT', 'MELLOMLIGGENDE_PERIODE', 'BEKREFTET_AVVIST', 'BEKREFTET_GODKJENT');
DELETE FROM KODELISTE WHERE KODEVERK = 'OPPTJENING_AKTIVITET_KLASSIFISERING' and kode NOT IN ('-', 'ANTATT_GODKJENT', 'MELLOMLIGGENDE_PERIODE', 'BEKREFTET_AVVIST', 'BEKREFTET_GODKJENT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='TYPE_FISKE' and kode1 NOT IN ('BLAD_A', '-', 'LOTT', 'HYRE', 'BLAD_B');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='TYPE_FISKE' and kode2 NOT IN ('BLAD_A', '-', 'LOTT', 'HYRE', 'BLAD_B');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'TYPE_FISKE' AND KL_KODE NOT IN ('BLAD_A', '-', 'LOTT', 'HYRE', 'BLAD_B');
DELETE FROM KODELISTE WHERE KODEVERK = 'TYPE_FISKE' and kode NOT IN ('BLAD_A', '-', 'LOTT', 'HYRE', 'BLAD_B');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTTAK_PERIODE_VURDERING_TYPE' and kode1 NOT IN ('PERIODE_OK', 'PERIODE_KAN_IKKE_AVKLARES', 'PERIODE_IKKE_VURDERT', 'PERIODE_OK_ENDRET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTTAK_PERIODE_VURDERING_TYPE' and kode2 NOT IN ('PERIODE_OK', 'PERIODE_KAN_IKKE_AVKLARES', 'PERIODE_IKKE_VURDERT', 'PERIODE_OK_ENDRET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'UTTAK_PERIODE_VURDERING_TYPE' AND KL_KODE NOT IN ('PERIODE_OK', 'PERIODE_KAN_IKKE_AVKLARES', 'PERIODE_IKKE_VURDERT', 'PERIODE_OK_ENDRET');
DELETE FROM KODELISTE WHERE KODEVERK = 'UTTAK_PERIODE_VURDERING_TYPE' and kode NOT IN ('PERIODE_OK', 'PERIODE_KAN_IKKE_AVKLARES', 'PERIODE_IKKE_VURDERT', 'PERIODE_OK_ENDRET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='PERIODE_RESULTAT_TYPE' and kode1 NOT IN ('AVSLÅTT', 'MANUELL_BEHANDLING', 'INNVILGET', 'IKKE_FASTSATT', 'GYLDIG_UTSETTELSE', 'UGYLDIG_UTSETTELSE');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='PERIODE_RESULTAT_TYPE' and kode2 NOT IN ('AVSLÅTT', 'MANUELL_BEHANDLING', 'INNVILGET', 'IKKE_FASTSATT', 'GYLDIG_UTSETTELSE', 'UGYLDIG_UTSETTELSE');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'PERIODE_RESULTAT_TYPE' AND KL_KODE NOT IN ('AVSLÅTT', 'MANUELL_BEHANDLING', 'INNVILGET', 'IKKE_FASTSATT', 'GYLDIG_UTSETTELSE', 'UGYLDIG_UTSETTELSE');
DELETE FROM KODELISTE WHERE KODEVERK = 'PERIODE_RESULTAT_TYPE' and kode NOT IN ('AVSLÅTT', 'MANUELL_BEHANDLING', 'INNVILGET', 'IKKE_FASTSATT', 'GYLDIG_UTSETTELSE', 'UGYLDIG_UTSETTELSE');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNSENDINGSVALG' and kode1 NOT IN ('VEDLEGG_SENDES_AV_ANDRE', 'LASTET_OPP', 'SENDES_IKKE', 'IKKE_VALGT', 'SEND_SENERE', 'VEDLEGG_ALLEREDE_SENDT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNSENDINGSVALG' and kode2 NOT IN ('VEDLEGG_SENDES_AV_ANDRE', 'LASTET_OPP', 'SENDES_IKKE', 'IKKE_VALGT', 'SEND_SENERE', 'VEDLEGG_ALLEREDE_SENDT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNSENDINGSVALG' AND KL_KODE NOT IN ('VEDLEGG_SENDES_AV_ANDRE', 'LASTET_OPP', 'SENDES_IKKE', 'IKKE_VALGT', 'SEND_SENERE', 'VEDLEGG_ALLEREDE_SENDT');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNSENDINGSVALG' and kode NOT IN ('VEDLEGG_SENDES_AV_ANDRE', 'LASTET_OPP', 'SENDES_IKKE', 'IKKE_VALGT', 'SEND_SENERE', 'VEDLEGG_ALLEREDE_SENDT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_STATUS' and kode1 NOT IN ('REGIS', 'L', 'RT', 'GODKJ', 'MOTAT', 'OPPRE', 'IP', 'UB', 'UK', 'AVSLU', 'VD', 'I', 'ST', 'VI', 'SG', 'IVERK', 'A', 'VT', 'INNST');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_STATUS' and kode2 NOT IN ('REGIS', 'L', 'RT', 'GODKJ', 'MOTAT', 'OPPRE', 'IP', 'UB', 'UK', 'AVSLU', 'VD', 'I', 'ST', 'VI', 'SG', 'IVERK', 'A', 'VT', 'INNST');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_STATUS' AND KL_KODE NOT IN ('REGIS', 'L', 'RT', 'GODKJ', 'MOTAT', 'OPPRE', 'IP', 'UB', 'UK', 'AVSLU', 'VD', 'I', 'ST', 'VI', 'SG', 'IVERK', 'A', 'VT', 'INNST');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_STATUS' and kode NOT IN ('REGIS', 'L', 'RT', 'GODKJ', 'MOTAT', 'OPPRE', 'IP', 'UB', 'UK', 'AVSLU', 'VD', 'I', 'ST', 'VI', 'SG', 'IVERK', 'A', 'VT', 'INNST');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_ENDRET_FELT_VERDI_TYPE' and kode1 NOT IN ('DOKUMENTERT', 'OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT', 'IKKE_ALENEOMSORG', 'IKKE_RELEVANT_PERIODE', 'VARIG_ENDRET_NAERING', 'VILKAR_OPPFYLT', 'NYOPPSTARTET', 'IKKE_NY_I_ARBEIDSLIVET', 'EKTEFELLES_BARN', 'IKKE_EKTEFELLES_BARN', 'IKKE_DOKUMENTERT', 'FORELDREANSVAR_4_TITTEL', 'ADOPTERER_ALENE', 'HENLEGG_BEHANDLING', 'IKKE_OPPHOLDSRETT', 'TIDSBEGRENSET_ARBEIDSFORHOLD', 'HAR_GYLDIG_GRUNN', 'LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT_IKKE', 'OMSORGSVILKARET_TITTEL', 'ADOPTERER_IKKE_ALENE', 'ALENEOMSORG', 'FORELDREANSVAR_2_TITTEL', 'INGEN_VARIG_ENDRING_NAERING', 'NY_I_ARBEIDSLIVET', 'VILKAR_IKKE_OPPFYLT', 'FASTSETT_RESULTAT_UTSETTELSE_AVKLARES', 'FORTSETT_BEHANDLING', 'OPPFYLT', 'FASTSETT_RESULTAT_PERIODEN_AVKLARES_IKKE', 'IKKE_LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT', 'BOSATT_I_NORGE', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT_IKKE', '-', 'HAR_IKKE_GYLDIG_GRUNN', 'IKKE_NYOPPSTARTET', 'IKKE_TIDSBEGRENSET_ARBEIDSFORHOLD', 'FASTSETT_RESULTAT_ENDRE_SOEKNADSPERIODEN', 'IKKE_BOSATT_I_NORGE', 'OPPHOLDSRETT', 'IKKE_OPPFYLT', 'PERIODE_UNNTAK', 'PERIODE_MEDLEM', 'IKKE_OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_GRADERING_AVKLARES');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_ENDRET_FELT_VERDI_TYPE' and kode2 NOT IN ('DOKUMENTERT', 'OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT', 'IKKE_ALENEOMSORG', 'IKKE_RELEVANT_PERIODE', 'VARIG_ENDRET_NAERING', 'VILKAR_OPPFYLT', 'NYOPPSTARTET', 'IKKE_NY_I_ARBEIDSLIVET', 'EKTEFELLES_BARN', 'IKKE_EKTEFELLES_BARN', 'IKKE_DOKUMENTERT', 'FORELDREANSVAR_4_TITTEL', 'ADOPTERER_ALENE', 'HENLEGG_BEHANDLING', 'IKKE_OPPHOLDSRETT', 'TIDSBEGRENSET_ARBEIDSFORHOLD', 'HAR_GYLDIG_GRUNN', 'LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT_IKKE', 'OMSORGSVILKARET_TITTEL', 'ADOPTERER_IKKE_ALENE', 'ALENEOMSORG', 'FORELDREANSVAR_2_TITTEL', 'INGEN_VARIG_ENDRING_NAERING', 'NY_I_ARBEIDSLIVET', 'VILKAR_IKKE_OPPFYLT', 'FASTSETT_RESULTAT_UTSETTELSE_AVKLARES', 'FORTSETT_BEHANDLING', 'OPPFYLT', 'FASTSETT_RESULTAT_PERIODEN_AVKLARES_IKKE', 'IKKE_LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT', 'BOSATT_I_NORGE', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT_IKKE', '-', 'HAR_IKKE_GYLDIG_GRUNN', 'IKKE_NYOPPSTARTET', 'IKKE_TIDSBEGRENSET_ARBEIDSFORHOLD', 'FASTSETT_RESULTAT_ENDRE_SOEKNADSPERIODEN', 'IKKE_BOSATT_I_NORGE', 'OPPHOLDSRETT', 'IKKE_OPPFYLT', 'PERIODE_UNNTAK', 'PERIODE_MEDLEM', 'IKKE_OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_GRADERING_AVKLARES');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_ENDRET_FELT_VERDI_TYPE' AND KL_KODE NOT IN ('DOKUMENTERT', 'OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT', 'IKKE_ALENEOMSORG', 'IKKE_RELEVANT_PERIODE', 'VARIG_ENDRET_NAERING', 'VILKAR_OPPFYLT', 'NYOPPSTARTET', 'IKKE_NY_I_ARBEIDSLIVET', 'EKTEFELLES_BARN', 'IKKE_EKTEFELLES_BARN', 'IKKE_DOKUMENTERT', 'FORELDREANSVAR_4_TITTEL', 'ADOPTERER_ALENE', 'HENLEGG_BEHANDLING', 'IKKE_OPPHOLDSRETT', 'TIDSBEGRENSET_ARBEIDSFORHOLD', 'HAR_GYLDIG_GRUNN', 'LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT_IKKE', 'OMSORGSVILKARET_TITTEL', 'ADOPTERER_IKKE_ALENE', 'ALENEOMSORG', 'FORELDREANSVAR_2_TITTEL', 'INGEN_VARIG_ENDRING_NAERING', 'NY_I_ARBEIDSLIVET', 'VILKAR_IKKE_OPPFYLT', 'FASTSETT_RESULTAT_UTSETTELSE_AVKLARES', 'FORTSETT_BEHANDLING', 'OPPFYLT', 'FASTSETT_RESULTAT_PERIODEN_AVKLARES_IKKE', 'IKKE_LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT', 'BOSATT_I_NORGE', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT_IKKE', '-', 'HAR_IKKE_GYLDIG_GRUNN', 'IKKE_NYOPPSTARTET', 'IKKE_TIDSBEGRENSET_ARBEIDSFORHOLD', 'FASTSETT_RESULTAT_ENDRE_SOEKNADSPERIODEN', 'IKKE_BOSATT_I_NORGE', 'OPPHOLDSRETT', 'IKKE_OPPFYLT', 'PERIODE_UNNTAK', 'PERIODE_MEDLEM', 'IKKE_OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_GRADERING_AVKLARES');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_ENDRET_FELT_VERDI_TYPE' and kode NOT IN ('DOKUMENTERT', 'OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT', 'IKKE_ALENEOMSORG', 'IKKE_RELEVANT_PERIODE', 'VARIG_ENDRET_NAERING', 'VILKAR_OPPFYLT', 'NYOPPSTARTET', 'IKKE_NY_I_ARBEIDSLIVET', 'EKTEFELLES_BARN', 'IKKE_EKTEFELLES_BARN', 'IKKE_DOKUMENTERT', 'FORELDREANSVAR_4_TITTEL', 'ADOPTERER_ALENE', 'HENLEGG_BEHANDLING', 'IKKE_OPPHOLDSRETT', 'TIDSBEGRENSET_ARBEIDSFORHOLD', 'HAR_GYLDIG_GRUNN', 'LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_INNLEGGELSEN_DOKUMENTERT_IKKE', 'OMSORGSVILKARET_TITTEL', 'ADOPTERER_IKKE_ALENE', 'ALENEOMSORG', 'FORELDREANSVAR_2_TITTEL', 'INGEN_VARIG_ENDRING_NAERING', 'NY_I_ARBEIDSLIVET', 'VILKAR_IKKE_OPPFYLT', 'FASTSETT_RESULTAT_UTSETTELSE_AVKLARES', 'FORTSETT_BEHANDLING', 'OPPFYLT', 'FASTSETT_RESULTAT_PERIODEN_AVKLARES_IKKE', 'IKKE_LOVLIG_OPPHOLD', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT', 'BOSATT_I_NORGE', 'FASTSETT_RESULTAT_PERIODEN_SYKDOM_DOKUMENTERT_IKKE', '-', 'HAR_IKKE_GYLDIG_GRUNN', 'IKKE_NYOPPSTARTET', 'IKKE_TIDSBEGRENSET_ARBEIDSFORHOLD', 'FASTSETT_RESULTAT_ENDRE_SOEKNADSPERIODEN', 'IKKE_BOSATT_I_NORGE', 'OPPHOLDSRETT', 'IKKE_OPPFYLT', 'PERIODE_UNNTAK', 'PERIODE_MEDLEM', 'IKKE_OMSORG_FOR_BARNET', 'FASTSETT_RESULTAT_GRADERING_AVKLARES');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='ARBEIDSFORHOLD_HANDLING_TYPE' and kode1 NOT IN ('BRUK', 'NYTT_ARBEIDSFORHOLD', 'SLÅTT_SAMMEN_MED_ANNET', 'BRUK_UTEN_INNTEKTSMELDING', 'IKKE_BRUK', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='ARBEIDSFORHOLD_HANDLING_TYPE' and kode2 NOT IN ('BRUK', 'NYTT_ARBEIDSFORHOLD', 'SLÅTT_SAMMEN_MED_ANNET', 'BRUK_UTEN_INNTEKTSMELDING', 'IKKE_BRUK', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'ARBEIDSFORHOLD_HANDLING_TYPE' AND KL_KODE NOT IN ('BRUK', 'NYTT_ARBEIDSFORHOLD', 'SLÅTT_SAMMEN_MED_ANNET', 'BRUK_UTEN_INNTEKTSMELDING', 'IKKE_BRUK', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'ARBEIDSFORHOLD_HANDLING_TYPE' and kode NOT IN ('BRUK', 'NYTT_ARBEIDSFORHOLD', 'SLÅTT_SAMMEN_MED_ANNET', 'BRUK_UTEN_INNTEKTSMELDING', 'IKKE_BRUK', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTS_KILDE' and kode1 NOT IN ('INNTEKT_OPPTJENING', 'INNTEKT_SAMMENLIGNING', 'INNTEKT_BEREGNING', '-', 'SIGRUN');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTS_KILDE' and kode2 NOT IN ('INNTEKT_OPPTJENING', 'INNTEKT_SAMMENLIGNING', 'INNTEKT_BEREGNING', '-', 'SIGRUN');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTS_KILDE' AND KL_KODE NOT IN ('INNTEKT_OPPTJENING', 'INNTEKT_SAMMENLIGNING', 'INNTEKT_BEREGNING', '-', 'SIGRUN');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTS_KILDE' and kode NOT IN ('INNTEKT_OPPTJENING', 'INNTEKT_SAMMENLIGNING', 'INNTEKT_BEREGNING', '-', 'SIGRUN');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='PERIODE_AARSAK' and kode1 NOT IN ('GRADERING', 'ARBEIDSFORHOLD_AVSLUTTET', 'ENDRING_I_REFUSJONSKRAV', '-', 'NATURALYTELSE_BORTFALT', 'REFUSJON_OPPHØRER', 'NATURALYTELSE_TILKOMMER');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='PERIODE_AARSAK' and kode2 NOT IN ('GRADERING', 'ARBEIDSFORHOLD_AVSLUTTET', 'ENDRING_I_REFUSJONSKRAV', '-', 'NATURALYTELSE_BORTFALT', 'REFUSJON_OPPHØRER', 'NATURALYTELSE_TILKOMMER');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'PERIODE_AARSAK' AND KL_KODE NOT IN ('GRADERING', 'ARBEIDSFORHOLD_AVSLUTTET', 'ENDRING_I_REFUSJONSKRAV', '-', 'NATURALYTELSE_BORTFALT', 'REFUSJON_OPPHØRER', 'NATURALYTELSE_TILKOMMER');
DELETE FROM KODELISTE WHERE KODEVERK = 'PERIODE_AARSAK' and kode NOT IN ('GRADERING', 'ARBEIDSFORHOLD_AVSLUTTET', 'ENDRING_I_REFUSJONSKRAV', '-', 'NATURALYTELSE_BORTFALT', 'REFUSJON_OPPHØRER', 'NATURALYTELSE_TILKOMMER');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_RESULTAT' and kode1 NOT IN ('-', 'I');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_RESULTAT' and kode2 NOT IN ('-', 'I');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_RESULTAT' AND KL_KODE NOT IN ('-', 'I');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_RESULTAT' and kode NOT IN ('-', 'I');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='TEMA_UNDERKATEGORI' and kode1 NOT IN ('PI', 'OP', 'PN', 'SV', 'SU', 'FE', '-', 'PP', 'RT', 'SP', 'RS', 'OG', 'OM', 'AP', 'PB', 'FØ', 'AE', 'FU');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='TEMA_UNDERKATEGORI' and kode2 NOT IN ('PI', 'OP', 'PN', 'SV', 'SU', 'FE', '-', 'PP', 'RT', 'SP', 'RS', 'OG', 'OM', 'AP', 'PB', 'FØ', 'AE', 'FU');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'TEMA_UNDERKATEGORI' AND KL_KODE NOT IN ('PI', 'OP', 'PN', 'SV', 'SU', 'FE', '-', 'PP', 'RT', 'SP', 'RS', 'OG', 'OM', 'AP', 'PB', 'FØ', 'AE', 'FU');
DELETE FROM KODELISTE WHERE KODEVERK = 'TEMA_UNDERKATEGORI' and kode NOT IN ('PI', 'OP', 'PN', 'SV', 'SU', 'FE', '-', 'PP', 'RT', 'SP', 'RS', 'OG', 'OM', 'AP', 'PB', 'FØ', 'AE', 'FU');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VILKAR_RESULTAT_TYPE' and kode1 NOT IN ('IKKE_FASTSATT', 'AVSLAATT', '-', 'INNVILGET');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VILKAR_RESULTAT_TYPE' and kode2 NOT IN ('IKKE_FASTSATT', 'AVSLAATT', '-', 'INNVILGET');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_RESULTAT_TYPE' AND KL_KODE NOT IN ('IKKE_FASTSATT', 'AVSLAATT', '-', 'INNVILGET');
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_RESULTAT_TYPE' and kode NOT IN ('IKKE_FASTSATT', 'AVSLAATT', '-', 'INNVILGET');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTTAK_PERIODE_TYPE' and kode1 NOT IN ('FORELDREPENGER', 'FORELDREPENGER_FØR_FØDSEL', 'ANNET', '-', 'FEDREKVOTE', 'MØDREKVOTE', 'FELLESPERIODE');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTTAK_PERIODE_TYPE' and kode2 NOT IN ('FORELDREPENGER', 'FORELDREPENGER_FØR_FØDSEL', 'ANNET', '-', 'FEDREKVOTE', 'MØDREKVOTE', 'FELLESPERIODE');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'UTTAK_PERIODE_TYPE' AND KL_KODE NOT IN ('FORELDREPENGER', 'FORELDREPENGER_FØR_FØDSEL', 'ANNET', '-', 'FEDREKVOTE', 'MØDREKVOTE', 'FELLESPERIODE');
DELETE FROM KODELISTE WHERE KODEVERK = 'UTTAK_PERIODE_TYPE' and kode NOT IN ('FORELDREPENGER', 'FORELDREPENGER_FØR_FØDSEL', 'ANNET', '-', 'FEDREKVOTE', 'MØDREKVOTE', 'FELLESPERIODE');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RELATERT_YTELSE_TYPE' and kode1 NOT IN ('PÅRØRENDESYKDOM', '-', 'ENGANGSSTØNAD', 'SYKEPENGER', 'DAGPENGER', 'SVANGERSKAPSPENGER', 'FORELDREPENGER', 'ENSLIG_FORSØRGER', 'ARBEIDSAVKLARINGSPENGER');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='RELATERT_YTELSE_TYPE' and kode2 NOT IN ('PÅRØRENDESYKDOM', '-', 'ENGANGSSTØNAD', 'SYKEPENGER', 'DAGPENGER', 'SVANGERSKAPSPENGER', 'FORELDREPENGER', 'ENSLIG_FORSØRGER', 'ARBEIDSAVKLARINGSPENGER');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'RELATERT_YTELSE_TYPE' AND KL_KODE NOT IN ('PÅRØRENDESYKDOM', '-', 'ENGANGSSTØNAD', 'SYKEPENGER', 'DAGPENGER', 'SVANGERSKAPSPENGER', 'FORELDREPENGER', 'ENSLIG_FORSØRGER', 'ARBEIDSAVKLARINGSPENGER');
DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_TYPE' and kode NOT IN ('PÅRØRENDESYKDOM', '-', 'ENGANGSSTØNAD', 'SYKEPENGER', 'DAGPENGER', 'SVANGERSKAPSPENGER', 'FORELDREPENGER', 'ENSLIG_FORSØRGER', 'ARBEIDSAVKLARINGSPENGER');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTTAK_ARBEID_TYPE' and kode1 NOT IN ('ANNET', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'FRILANS', 'ORDINÆRT_ARBEID');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTTAK_ARBEID_TYPE' and kode2 NOT IN ('ANNET', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'FRILANS', 'ORDINÆRT_ARBEID');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'UTTAK_ARBEID_TYPE' AND KL_KODE NOT IN ('ANNET', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'FRILANS', 'ORDINÆRT_ARBEID');
DELETE FROM KODELISTE WHERE KODEVERK = 'UTTAK_ARBEID_TYPE' and kode NOT IN ('ANNET', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'FRILANS', 'ORDINÆRT_ARBEID');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VILKAR_UTFALL_MERKNAD' and kode1 NOT IN ('1035', '1006', '1005', '1020', '1021', '1002', '1001', '1004', '1003', '1022', '1027', '1028', '1029', '1024', '1023', '1026', '1025', '1051', '1041', '5007', '-', '7004', '7003', '7002', '7001');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VILKAR_UTFALL_MERKNAD' and kode2 NOT IN ('1035', '1006', '1005', '1020', '1021', '1002', '1001', '1004', '1003', '1022', '1027', '1028', '1029', '1024', '1023', '1026', '1025', '1051', '1041', '5007', '-', '7004', '7003', '7002', '7001');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_UTFALL_MERKNAD' AND KL_KODE NOT IN ('1035', '1006', '1005', '1020', '1021', '1002', '1001', '1004', '1003', '1022', '1027', '1028', '1029', '1024', '1023', '1026', '1025', '1051', '1041', '5007', '-', '7004', '7003', '7002', '7001');
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_UTFALL_MERKNAD' and kode NOT IN ('1035', '1006', '1005', '1020', '1021', '1002', '1001', '1004', '1003', '1022', '1027', '1028', '1029', '1024', '1023', '1026', '1025', '1051', '1041', '5007', '-', '7004', '7003', '7002', '7001');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='SYKEFRAVÆR_PERIODE_TYPE' and kode1 NOT IN ('EGENMELDING', 'SYKEMELDT', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='SYKEFRAVÆR_PERIODE_TYPE' and kode2 NOT IN ('EGENMELDING', 'SYKEMELDT', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SYKEFRAVÆR_PERIODE_TYPE' AND KL_KODE NOT IN ('EGENMELDING', 'SYKEMELDT', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'SYKEFRAVÆR_PERIODE_TYPE' and kode NOT IN ('EGENMELDING', 'SYKEMELDT', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='ARBEIDSKATEGORI' and kode1 NOT IN ('INAKTIV', 'ARBEIDSTAKER', 'DAGPENGER', '-', 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER', 'JORDBRUKER', 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER', 'DAGMAMMA', 'FISKER', 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'SJØMANN', 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER', 'UGYLDIG', 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER', 'FRILANSER');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='ARBEIDSKATEGORI' and kode2 NOT IN ('INAKTIV', 'ARBEIDSTAKER', 'DAGPENGER', '-', 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER', 'JORDBRUKER', 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER', 'DAGMAMMA', 'FISKER', 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'SJØMANN', 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER', 'UGYLDIG', 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER', 'FRILANSER');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'ARBEIDSKATEGORI' AND KL_KODE NOT IN ('INAKTIV', 'ARBEIDSTAKER', 'DAGPENGER', '-', 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER', 'JORDBRUKER', 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER', 'DAGMAMMA', 'FISKER', 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'SJØMANN', 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER', 'UGYLDIG', 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER', 'FRILANSER');
DELETE FROM KODELISTE WHERE KODEVERK = 'ARBEIDSKATEGORI' and kode NOT IN ('INAKTIV', 'ARBEIDSTAKER', 'DAGPENGER', '-', 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER', 'JORDBRUKER', 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER', 'DAGMAMMA', 'FISKER', 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE', 'SELVSTENDIG_NÆRINGSDRIVENDE', 'SJØMANN', 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER', 'UGYLDIG', 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER', 'FRILANSER');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='REFERANSE_TYPE' and kode1 NOT IN ('AKTØR_ID', 'ORG_NR', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='REFERANSE_TYPE' and kode2 NOT IN ('AKTØR_ID', 'ORG_NR', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'REFERANSE_TYPE' AND KL_KODE NOT IN ('AKTØR_ID', 'ORG_NR', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'REFERANSE_TYPE' and kode NOT IN ('AKTØR_ID', 'ORG_NR', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEREGNINGSGRUNNLAG_ANDELTYPE' and kode1 NOT IN ('FRILANS', '-', 'BRUKERS_ANDEL', 'EGEN_NÆRING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEREGNINGSGRUNNLAG_ANDELTYPE' and kode2 NOT IN ('FRILANS', '-', 'BRUKERS_ANDEL', 'EGEN_NÆRING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEREGNINGSGRUNNLAG_ANDELTYPE' AND KL_KODE NOT IN ('FRILANS', '-', 'BRUKERS_ANDEL', 'EGEN_NÆRING');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEREGNINGSGRUNNLAG_ANDELTYPE' and kode NOT IN ('FRILANS', '-', 'BRUKERS_ANDEL', 'EGEN_NÆRING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='GRADERING_AVSLAG_AARSAK' and kode1 NOT IN ('-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='GRADERING_AVSLAG_AARSAK' and kode2 NOT IN ('-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'GRADERING_AVSLAG_AARSAK' AND KL_KODE NOT IN ('-');
DELETE FROM KODELISTE WHERE KODEVERK = 'GRADERING_AVSLAG_AARSAK' and kode NOT IN ('-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTS_FILTER' and kode1 NOT IN ('-', 'OPPTJENINGSGRUNNLAG', 'BEREGNINGSGRUNNLAG', 'SAMMENLIGNINGSGRUNNLAG');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTS_FILTER' and kode2 NOT IN ('-', 'OPPTJENINGSGRUNNLAG', 'BEREGNINGSGRUNNLAG', 'SAMMENLIGNINGSGRUNNLAG');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTS_FILTER' AND KL_KODE NOT IN ('-', 'OPPTJENINGSGRUNNLAG', 'BEREGNINGSGRUNNLAG', 'SAMMENLIGNINGSGRUNNLAG');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTS_FILTER' and kode NOT IN ('-', 'OPPTJENINGSGRUNNLAG', 'BEREGNINGSGRUNNLAG', 'SAMMENLIGNINGSGRUNNLAG');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_ENDRET_FELT_TYPE' and kode1 NOT IN ('ENDRING_TIDSBEGRENSET_ARBEIDSFORHOLD', 'NAVN', 'ANDEL_ARBEID', 'AVKLART_PERIODE', 'MANDAT', 'FRILANSVIRKSOMHET', 'OVERSTYRT_VURDERING', 'BEHANDLING', 'NY_AKTIVITET', 'PERIODE_TOM', 'GYLDIG_MEDLEM_FOLKETRYGDEN', 'AKTIVITET', 'ENDRING_NAERING', 'FRILANS_INNTEKT', 'FNR', 'INNTEKT', 'FORDELING_FOR_NY_ANDEL', 'MOTTATT_DATO', 'AVKLARSAKSOPPLYSNINGER', 'FASTSETT_RESULTAT_PERIODEN', 'FORDELING_FOR_ANDEL', 'SELVSTENDIG_NAERINGSDRIVENDE', 'VILKAR_SOM_ANVENDES', 'BEHANDLENDE_ENHET', 'NY_FORDELING', 'TYPE_VERGE', 'DAGPENGER_INNTEKT', 'SOKNADSFRISTVILKARET', 'SOKERSOPPLYSNINGSPLIKT', 'INNTEKTSKATEGORI_FOR_ANDEL', 'OPPHOLDSRETT_IKKE_EOS', 'AKTIVITET_PERIODE', 'INNTEKT_FRA_ARBEIDSFORHOLD', 'LØNNSENDRING_I_PERIODEN', 'BRUTTO_NAERINGSINNTEKT', 'DOKUMENTASJON_FORELIGGER', 'ER_SOKER_BOSATT_I_NORGE', 'OVERSTYRT_BEREGNING', 'PERIODE_FOM', 'INNTEKTSKATEGORI', 'KONTAKTPERSON', 'NYTT_REFUSJONSKRAV', 'SOKNADSFRIST', 'OPPHOLDSRETT_EOS', 'STARTDATO_FRA_SOKNAD', 'SYKDOM', 'ARBEIDSFORHOLD', 'BRUKER_TVUNGEN', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_ENDRET_FELT_TYPE' and kode2 NOT IN ('ENDRING_TIDSBEGRENSET_ARBEIDSFORHOLD', 'NAVN', 'ANDEL_ARBEID', 'AVKLART_PERIODE', 'MANDAT', 'FRILANSVIRKSOMHET', 'OVERSTYRT_VURDERING', 'BEHANDLING', 'NY_AKTIVITET', 'PERIODE_TOM', 'GYLDIG_MEDLEM_FOLKETRYGDEN', 'AKTIVITET', 'ENDRING_NAERING', 'FRILANS_INNTEKT', 'FNR', 'INNTEKT', 'FORDELING_FOR_NY_ANDEL', 'MOTTATT_DATO', 'AVKLARSAKSOPPLYSNINGER', 'FASTSETT_RESULTAT_PERIODEN', 'FORDELING_FOR_ANDEL', 'SELVSTENDIG_NAERINGSDRIVENDE', 'VILKAR_SOM_ANVENDES', 'BEHANDLENDE_ENHET', 'NY_FORDELING', 'TYPE_VERGE', 'DAGPENGER_INNTEKT', 'SOKNADSFRISTVILKARET', 'SOKERSOPPLYSNINGSPLIKT', 'INNTEKTSKATEGORI_FOR_ANDEL', 'OPPHOLDSRETT_IKKE_EOS', 'AKTIVITET_PERIODE', 'INNTEKT_FRA_ARBEIDSFORHOLD', 'LØNNSENDRING_I_PERIODEN', 'BRUTTO_NAERINGSINNTEKT', 'DOKUMENTASJON_FORELIGGER', 'ER_SOKER_BOSATT_I_NORGE', 'OVERSTYRT_BEREGNING', 'PERIODE_FOM', 'INNTEKTSKATEGORI', 'KONTAKTPERSON', 'NYTT_REFUSJONSKRAV', 'SOKNADSFRIST', 'OPPHOLDSRETT_EOS', 'STARTDATO_FRA_SOKNAD', 'SYKDOM', 'ARBEIDSFORHOLD', 'BRUKER_TVUNGEN', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_ENDRET_FELT_TYPE' AND KL_KODE NOT IN ('ENDRING_TIDSBEGRENSET_ARBEIDSFORHOLD', 'NAVN', 'ANDEL_ARBEID', 'AVKLART_PERIODE', 'MANDAT', 'FRILANSVIRKSOMHET', 'OVERSTYRT_VURDERING', 'BEHANDLING', 'NY_AKTIVITET', 'PERIODE_TOM', 'GYLDIG_MEDLEM_FOLKETRYGDEN', 'AKTIVITET', 'ENDRING_NAERING', 'FRILANS_INNTEKT', 'FNR', 'INNTEKT', 'FORDELING_FOR_NY_ANDEL', 'MOTTATT_DATO', 'AVKLARSAKSOPPLYSNINGER', 'FASTSETT_RESULTAT_PERIODEN', 'FORDELING_FOR_ANDEL', 'SELVSTENDIG_NAERINGSDRIVENDE', 'VILKAR_SOM_ANVENDES', 'BEHANDLENDE_ENHET', 'NY_FORDELING', 'TYPE_VERGE', 'DAGPENGER_INNTEKT', 'SOKNADSFRISTVILKARET', 'SOKERSOPPLYSNINGSPLIKT', 'INNTEKTSKATEGORI_FOR_ANDEL', 'OPPHOLDSRETT_IKKE_EOS', 'AKTIVITET_PERIODE', 'INNTEKT_FRA_ARBEIDSFORHOLD', 'LØNNSENDRING_I_PERIODEN', 'BRUTTO_NAERINGSINNTEKT', 'DOKUMENTASJON_FORELIGGER', 'ER_SOKER_BOSATT_I_NORGE', 'OVERSTYRT_BEREGNING', 'PERIODE_FOM', 'INNTEKTSKATEGORI', 'KONTAKTPERSON', 'NYTT_REFUSJONSKRAV', 'SOKNADSFRIST', 'OPPHOLDSRETT_EOS', 'STARTDATO_FRA_SOKNAD', 'SYKDOM', 'ARBEIDSFORHOLD', 'BRUKER_TVUNGEN', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_ENDRET_FELT_TYPE' and kode NOT IN ('ENDRING_TIDSBEGRENSET_ARBEIDSFORHOLD', 'NAVN', 'ANDEL_ARBEID', 'AVKLART_PERIODE', 'MANDAT', 'FRILANSVIRKSOMHET', 'OVERSTYRT_VURDERING', 'BEHANDLING', 'NY_AKTIVITET', 'PERIODE_TOM', 'GYLDIG_MEDLEM_FOLKETRYGDEN', 'AKTIVITET', 'ENDRING_NAERING', 'FRILANS_INNTEKT', 'FNR', 'INNTEKT', 'FORDELING_FOR_NY_ANDEL', 'MOTTATT_DATO', 'AVKLARSAKSOPPLYSNINGER', 'FASTSETT_RESULTAT_PERIODEN', 'FORDELING_FOR_ANDEL', 'SELVSTENDIG_NAERINGSDRIVENDE', 'VILKAR_SOM_ANVENDES', 'BEHANDLENDE_ENHET', 'NY_FORDELING', 'TYPE_VERGE', 'DAGPENGER_INNTEKT', 'SOKNADSFRISTVILKARET', 'SOKERSOPPLYSNINGSPLIKT', 'INNTEKTSKATEGORI_FOR_ANDEL', 'OPPHOLDSRETT_IKKE_EOS', 'AKTIVITET_PERIODE', 'INNTEKT_FRA_ARBEIDSFORHOLD', 'LØNNSENDRING_I_PERIODEN', 'BRUTTO_NAERINGSINNTEKT', 'DOKUMENTASJON_FORELIGGER', 'ER_SOKER_BOSATT_I_NORGE', 'OVERSTYRT_BEREGNING', 'PERIODE_FOM', 'INNTEKTSKATEGORI', 'KONTAKTPERSON', 'NYTT_REFUSJONSKRAV', 'SOKNADSFRIST', 'OPPHOLDSRETT_EOS', 'STARTDATO_FRA_SOKNAD', 'SYKDOM', 'ARBEIDSFORHOLD', 'BRUKER_TVUNGEN', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VIRKSOMHET_TYPE' and kode1 NOT IN ('DAGMAMMA', 'FISKE', 'JORDBRUK_SKOGBRUK', 'ANNEN', 'FRILANSER', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VIRKSOMHET_TYPE' and kode2 NOT IN ('DAGMAMMA', 'FISKE', 'JORDBRUK_SKOGBRUK', 'ANNEN', 'FRILANSER', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VIRKSOMHET_TYPE' AND KL_KODE NOT IN ('DAGMAMMA', 'FISKE', 'JORDBRUK_SKOGBRUK', 'ANNEN', 'FRILANSER', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'VIRKSOMHET_TYPE' and kode NOT IN ('DAGMAMMA', 'FISKE', 'JORDBRUK_SKOGBRUK', 'ANNEN', 'FRILANSER', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPGAVE_AARSAK' and kode1 NOT IN ('-', 'REG_SOK_VL', 'GOD_VED_VL', 'VUR_VL', 'SETTVENT_STO', 'RV_VL', 'BEH_SAK_FOR', 'BEH_SAK_VL', 'VUR_KONS_YTE_FOR');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPGAVE_AARSAK' and kode2 NOT IN ('-', 'REG_SOK_VL', 'GOD_VED_VL', 'VUR_VL', 'SETTVENT_STO', 'RV_VL', 'BEH_SAK_FOR', 'BEH_SAK_VL', 'VUR_KONS_YTE_FOR');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OPPGAVE_AARSAK' AND KL_KODE NOT IN ('-', 'REG_SOK_VL', 'GOD_VED_VL', 'VUR_VL', 'SETTVENT_STO', 'RV_VL', 'BEH_SAK_FOR', 'BEH_SAK_VL', 'VUR_KONS_YTE_FOR');
DELETE FROM KODELISTE WHERE KODEVERK = 'OPPGAVE_AARSAK' and kode NOT IN ('-', 'REG_SOK_VL', 'GOD_VED_VL', 'VUR_VL', 'SETTVENT_STO', 'RV_VL', 'BEH_SAK_FOR', 'BEH_SAK_VL', 'VUR_KONS_YTE_FOR');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='IKKE_OPPFYLT_AARSAK' and kode1 NOT IN ('4020');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='IKKE_OPPFYLT_AARSAK' and kode2 NOT IN ('4020');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'IKKE_OPPFYLT_AARSAK' AND KL_KODE NOT IN ('4020');
DELETE FROM KODELISTE WHERE KODEVERK = 'IKKE_OPPFYLT_AARSAK' and kode NOT IN ('4020');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='AKTIVITET_STATUS' and kode1 NOT IN ('FL', 'AT', 'DP', 'AAP', 'MS', 'AT_SN', 'AT_FL', 'FL_SN', 'BA', 'AT_FL_SN', 'SN', '-', 'TY');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='AKTIVITET_STATUS' and kode2 NOT IN ('FL', 'AT', 'DP', 'AAP', 'MS', 'AT_SN', 'AT_FL', 'FL_SN', 'BA', 'AT_FL_SN', 'SN', '-', 'TY');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'AKTIVITET_STATUS' AND KL_KODE NOT IN ('FL', 'AT', 'DP', 'AAP', 'MS', 'AT_SN', 'AT_FL', 'FL_SN', 'BA', 'AT_FL_SN', 'SN', '-', 'TY');
DELETE FROM KODELISTE WHERE KODEVERK = 'AKTIVITET_STATUS' and kode NOT IN ('FL', 'AT', 'DP', 'AAP', 'MS', 'AT_SN', 'AT_FL', 'FL_SN', 'BA', 'AT_FL_SN', 'SN', '-', 'TY');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FORRETNINGSHENDELSE_TYPE' and kode1 NOT IN ('YTELSE_INNVILGET', 'YTELSE_ENDRET', 'YTELSE_OPPHØRT', 'YTELSE_ANNULERT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='FORRETNINGSHENDELSE_TYPE' and kode2 NOT IN ('YTELSE_INNVILGET', 'YTELSE_ENDRET', 'YTELSE_OPPHØRT', 'YTELSE_ANNULERT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FORRETNINGSHENDELSE_TYPE' AND KL_KODE NOT IN ('YTELSE_INNVILGET', 'YTELSE_ENDRET', 'YTELSE_OPPHØRT', 'YTELSE_ANNULERT');
DELETE FROM KODELISTE WHERE KODEVERK = 'FORRETNINGSHENDELSE_TYPE' and kode NOT IN ('YTELSE_INNVILGET', 'YTELSE_ENDRET', 'YTELSE_OPPHØRT', 'YTELSE_ANNULERT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='SATS_TYPE' and kode1 NOT IN ('GRUNNBELØP', 'GSNITT', 'ENGANG', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='SATS_TYPE' and kode2 NOT IN ('GRUNNBELØP', 'GSNITT', 'ENGANG', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SATS_TYPE' AND KL_KODE NOT IN ('GRUNNBELØP', 'GSNITT', 'ENGANG', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'SATS_TYPE' and kode NOT IN ('GRUNNBELØP', 'GSNITT', 'ENGANG', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAKTA_OM_BEREGNING_TILFELLE' and kode1 NOT IN ('VURDER_LØNNSENDRING', 'VURDER_NYOPPSTARTET_FL', '-', 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON', 'FASTSETT_ENDRET_BEREGNINGSGRUNNLAG', 'VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD', 'VURDER_SN_NY_I_ARBEIDSLIVET', 'TILSTØTENDE_YTELSE', 'FASTSETT_MAANEDSINNTEKT_FL', 'FASTSETT_MÅNEDSLØNN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='FAKTA_OM_BEREGNING_TILFELLE' and kode2 NOT IN ('VURDER_LØNNSENDRING', 'VURDER_NYOPPSTARTET_FL', '-', 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON', 'FASTSETT_ENDRET_BEREGNINGSGRUNNLAG', 'VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD', 'VURDER_SN_NY_I_ARBEIDSLIVET', 'TILSTØTENDE_YTELSE', 'FASTSETT_MAANEDSINNTEKT_FL', 'FASTSETT_MÅNEDSLØNN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FAKTA_OM_BEREGNING_TILFELLE' AND KL_KODE NOT IN ('VURDER_LØNNSENDRING', 'VURDER_NYOPPSTARTET_FL', '-', 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON', 'FASTSETT_ENDRET_BEREGNINGSGRUNNLAG', 'VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD', 'VURDER_SN_NY_I_ARBEIDSLIVET', 'TILSTØTENDE_YTELSE', 'FASTSETT_MAANEDSINNTEKT_FL', 'FASTSETT_MÅNEDSLØNN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING');
DELETE FROM KODELISTE WHERE KODEVERK = 'FAKTA_OM_BEREGNING_TILFELLE' and kode NOT IN ('VURDER_LØNNSENDRING', 'VURDER_NYOPPSTARTET_FL', '-', 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON', 'FASTSETT_ENDRET_BEREGNINGSGRUNNLAG', 'VURDER_TIDSBEGRENSET_ARBEIDSFORHOLD', 'VURDER_SN_NY_I_ARBEIDSLIVET', 'TILSTØTENDE_YTELSE', 'FASTSETT_MAANEDSINNTEKT_FL', 'FASTSETT_MÅNEDSLØNN_ARBEIDSTAKER_UTEN_INNTEKTSMELDING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='SOKNAD_TYPE_TILLEGG' and kode1 NOT IN ('OVERFORING_AV_KVOTER', 'GRADERING', 'UTSETTELSE', '-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='SOKNAD_TYPE_TILLEGG' and kode2 NOT IN ('OVERFORING_AV_KVOTER', 'GRADERING', 'UTSETTELSE', '-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'SOKNAD_TYPE_TILLEGG' AND KL_KODE NOT IN ('OVERFORING_AV_KVOTER', 'GRADERING', 'UTSETTELSE', '-');
DELETE FROM KODELISTE WHERE KODEVERK = 'SOKNAD_TYPE_TILLEGG' and kode NOT IN ('OVERFORING_AV_KVOTER', 'GRADERING', 'UTSETTELSE', '-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTSMELDING_INNSENDINGSAARSAK' and kode1 NOT IN ('-', 'NY', 'ENDRING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTSMELDING_INNSENDINGSAARSAK' and kode2 NOT IN ('-', 'NY', 'ENDRING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTSMELDING_INNSENDINGSAARSAK' AND KL_KODE NOT IN ('-', 'NY', 'ENDRING');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTSMELDING_INNSENDINGSAARSAK' and kode NOT IN ('-', 'NY', 'ENDRING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BREV_MOTTAKER' and kode1 NOT IN ('-', 'SOEKER', 'BEGGE', 'VERGE');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BREV_MOTTAKER' and kode2 NOT IN ('-', 'SOEKER', 'BEGGE', 'VERGE');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BREV_MOTTAKER' AND KL_KODE NOT IN ('-', 'SOEKER', 'BEGGE', 'VERGE');
DELETE FROM KODELISTE WHERE KODEVERK = 'BREV_MOTTAKER' and kode NOT IN ('-', 'SOEKER', 'BEGGE', 'VERGE');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='POSTERINGSTYPE' and kode1 NOT IN ('PERIODE', 'OVERFØRING');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='POSTERINGSTYPE' and kode2 NOT IN ('PERIODE', 'OVERFØRING');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'POSTERINGSTYPE' AND KL_KODE NOT IN ('PERIODE', 'OVERFØRING');
DELETE FROM KODELISTE WHERE KODEVERK = 'POSTERINGSTYPE' and kode NOT IN ('PERIODE', 'OVERFØRING');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='AKSJONSPUNKT_STATUS' and kode1 NOT IN ('AVBR', 'OPPR', 'UTFO');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='AKSJONSPUNKT_STATUS' and kode2 NOT IN ('AVBR', 'OPPR', 'UTFO');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'AKSJONSPUNKT_STATUS' AND KL_KODE NOT IN ('AVBR', 'OPPR', 'UTFO');
DELETE FROM KODELISTE WHERE KODEVERK = 'AKSJONSPUNKT_STATUS' and kode NOT IN ('AVBR', 'OPPR', 'UTFO');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKKINNSLAG_FELT_TYPE' and kode1 NOT IN ('AKSJONSPUNKT_KODE', '-', 'OPPLYSNINGER', 'HENDELSE', 'RESULTAT', 'AARSAK', 'ENDRET_FELT', 'SKJERMLENKE', 'BEGRUNNELSE', 'ANGÅR_TEMA', 'AKSJONSPUNKT_GODKJENT', 'AKSJONSPUNKT_BEGRUNNELSE', 'AVKLART_SOEKNADSPERIODE', 'GJELDENDE_FRA');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKKINNSLAG_FELT_TYPE' and kode2 NOT IN ('AKSJONSPUNKT_KODE', '-', 'OPPLYSNINGER', 'HENDELSE', 'RESULTAT', 'AARSAK', 'ENDRET_FELT', 'SKJERMLENKE', 'BEGRUNNELSE', 'ANGÅR_TEMA', 'AKSJONSPUNKT_GODKJENT', 'AKSJONSPUNKT_BEGRUNNELSE', 'AVKLART_SOEKNADSPERIODE', 'GJELDENDE_FRA');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKKINNSLAG_FELT_TYPE' AND KL_KODE NOT IN ('AKSJONSPUNKT_KODE', '-', 'OPPLYSNINGER', 'HENDELSE', 'RESULTAT', 'AARSAK', 'ENDRET_FELT', 'SKJERMLENKE', 'BEGRUNNELSE', 'ANGÅR_TEMA', 'AKSJONSPUNKT_GODKJENT', 'AKSJONSPUNKT_BEGRUNNELSE', 'AVKLART_SOEKNADSPERIODE', 'GJELDENDE_FRA');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKKINNSLAG_FELT_TYPE' and kode NOT IN ('AKSJONSPUNKT_KODE', '-', 'OPPLYSNINGER', 'HENDELSE', 'RESULTAT', 'AARSAK', 'ENDRET_FELT', 'SKJERMLENKE', 'BEGRUNNELSE', 'ANGÅR_TEMA', 'AKSJONSPUNKT_GODKJENT', 'AKSJONSPUNKT_BEGRUNNELSE', 'AVKLART_SOEKNADSPERIODE', 'GJELDENDE_FRA');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='DOKUMENT_TYPE' and kode1 NOT IN ('-');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='DOKUMENT_TYPE' and kode2 NOT IN ('-');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'DOKUMENT_TYPE' AND KL_KODE NOT IN ('-');
DELETE FROM KODELISTE WHERE KODEVERK = 'DOKUMENT_TYPE' and kode NOT IN ('-');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VENT_AARSAK' and kode1 NOT IN ('AVV_DOK', 'VENT_REGISTERINNHENTING', 'VENT_INFOTRYGD', 'OPPD_ÅPEN_BEH', 'VENT_INNTEKT_RAPPORTERINGSFRIST', 'VENT_ÅPEN_BEHANDLING', '-', 'FOR_TIDLIG_SOKNAD', 'SCANN', 'UTV_FRIST', 'VENT_TIDLIGERE_BEHANDLING', 'AVV_RESPONS_REVURDERING', 'VENT_OPPTJENING_OPPLYSNINGER', 'VENT_OPDT_INNTEKTSMELDING', 'AVV_FODSEL');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VENT_AARSAK' and kode2 NOT IN ('AVV_DOK', 'VENT_REGISTERINNHENTING', 'VENT_INFOTRYGD', 'OPPD_ÅPEN_BEH', 'VENT_INNTEKT_RAPPORTERINGSFRIST', 'VENT_ÅPEN_BEHANDLING', '-', 'FOR_TIDLIG_SOKNAD', 'SCANN', 'UTV_FRIST', 'VENT_TIDLIGERE_BEHANDLING', 'AVV_RESPONS_REVURDERING', 'VENT_OPPTJENING_OPPLYSNINGER', 'VENT_OPDT_INNTEKTSMELDING', 'AVV_FODSEL');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VENT_AARSAK' AND KL_KODE NOT IN ('AVV_DOK', 'VENT_REGISTERINNHENTING', 'VENT_INFOTRYGD', 'OPPD_ÅPEN_BEH', 'VENT_INNTEKT_RAPPORTERINGSFRIST', 'VENT_ÅPEN_BEHANDLING', '-', 'FOR_TIDLIG_SOKNAD', 'SCANN', 'UTV_FRIST', 'VENT_TIDLIGERE_BEHANDLING', 'AVV_RESPONS_REVURDERING', 'VENT_OPPTJENING_OPPLYSNINGER', 'VENT_OPDT_INNTEKTSMELDING', 'AVV_FODSEL');
DELETE FROM KODELISTE WHERE KODEVERK = 'VENT_AARSAK' and kode NOT IN ('AVV_DOK', 'VENT_REGISTERINNHENTING', 'VENT_INFOTRYGD', 'OPPD_ÅPEN_BEH', 'VENT_INNTEKT_RAPPORTERINGSFRIST', 'VENT_ÅPEN_BEHANDLING', '-', 'FOR_TIDLIG_SOKNAD', 'SCANN', 'UTV_FRIST', 'VENT_TIDLIGERE_BEHANDLING', 'AVV_RESPONS_REVURDERING', 'VENT_OPPTJENING_OPPLYSNINGER', 'VENT_OPDT_INNTEKTSMELDING', 'AVV_FODSEL');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='KONFIG_VERDI_TYPE' and kode1 NOT IN ('URI', 'DURATION', 'INTEGER', 'STRING', 'DATE', 'BOOLEAN', 'PERIOD');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='KONFIG_VERDI_TYPE' and kode2 NOT IN ('URI', 'DURATION', 'INTEGER', 'STRING', 'DATE', 'BOOLEAN', 'PERIOD');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'KONFIG_VERDI_TYPE' AND KL_KODE NOT IN ('URI', 'DURATION', 'INTEGER', 'STRING', 'DATE', 'BOOLEAN', 'PERIOD');
DELETE FROM KODELISTE WHERE KODEVERK = 'KONFIG_VERDI_TYPE' and kode NOT IN ('URI', 'DURATION', 'INTEGER', 'STRING', 'DATE', 'BOOLEAN', 'PERIOD');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSYSTEM_UNDERKATEGORI' and kode1 NOT IN ('INFOTRYGD_SAK', '-', 'INFOTRYGD_VEDTAK');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='FAGSYSTEM_UNDERKATEGORI' and kode2 NOT IN ('INFOTRYGD_SAK', '-', 'INFOTRYGD_VEDTAK');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'FAGSYSTEM_UNDERKATEGORI' AND KL_KODE NOT IN ('INFOTRYGD_SAK', '-', 'INFOTRYGD_VEDTAK');
DELETE FROM KODELISTE WHERE KODEVERK = 'FAGSYSTEM_UNDERKATEGORI' and kode NOT IN ('INFOTRYGD_SAK', '-', 'INFOTRYGD_VEDTAK');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_AKTOER' and kode1 NOT IN ('SBH', 'VL', 'ARBEIDSGIVER', '-', 'SOKER', 'BESL');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_AKTOER' and kode2 NOT IN ('SBH', 'VL', 'ARBEIDSGIVER', '-', 'SOKER', 'BESL');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_AKTOER' AND KL_KODE NOT IN ('SBH', 'VL', 'ARBEIDSGIVER', '-', 'SOKER', 'BESL');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_AKTOER' and kode NOT IN ('SBH', 'VL', 'ARBEIDSGIVER', '-', 'SOKER', 'BESL');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEHANDLING_TYPE' and kode1 NOT IN ('BT-002', '-', 'BT-004');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='BEHANDLING_TYPE' and kode2 NOT IN ('BT-002', '-', 'BT-004');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_TYPE' AND KL_KODE NOT IN ('BT-002', '-', 'BT-004');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_TYPE' and kode NOT IN ('BT-002', '-', 'BT-004');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='INNTEKTSKATEGORI' and kode1 NOT IN ('ARBEIDSTAKER_UTEN_FERIEPENGER', 'JORDBRUKER', 'ARBEIDSTAKER', 'SJØMANN', 'FISKER', 'DAGPENGER', 'FRILANSER', 'DAGMAMMA', '-', 'ARBEIDSAVKLARINGSPENGER', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='INNTEKTSKATEGORI' and kode2 NOT IN ('ARBEIDSTAKER_UTEN_FERIEPENGER', 'JORDBRUKER', 'ARBEIDSTAKER', 'SJØMANN', 'FISKER', 'DAGPENGER', 'FRILANSER', 'DAGMAMMA', '-', 'ARBEIDSAVKLARINGSPENGER', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNTEKTSKATEGORI' AND KL_KODE NOT IN ('ARBEIDSTAKER_UTEN_FERIEPENGER', 'JORDBRUKER', 'ARBEIDSTAKER', 'SJØMANN', 'FISKER', 'DAGPENGER', 'FRILANSER', 'DAGMAMMA', '-', 'ARBEIDSAVKLARINGSPENGER', 'SELVSTENDIG_NÆRINGSDRIVENDE');
DELETE FROM KODELISTE WHERE KODEVERK = 'INNTEKTSKATEGORI' and kode NOT IN ('ARBEIDSTAKER_UTEN_FERIEPENGER', 'JORDBRUKER', 'ARBEIDSTAKER', 'SJØMANN', 'FISKER', 'DAGPENGER', 'FRILANSER', 'DAGMAMMA', '-', 'ARBEIDSAVKLARINGSPENGER', 'SELVSTENDIG_NÆRINGSDRIVENDE');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HISTORIKK_RESULTAT_TYPE' and kode1 NOT IN ('BEREGNET_AARSINNTEKT');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='HISTORIKK_RESULTAT_TYPE' and kode2 NOT IN ('BEREGNET_AARSINNTEKT');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_RESULTAT_TYPE' AND KL_KODE NOT IN ('BEREGNET_AARSINNTEKT');
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_RESULTAT_TYPE' and kode NOT IN ('BEREGNET_AARSINNTEKT');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='KONFIG_VERDI_GRUPPE' and kode1 NOT IN ('INGEN');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='KONFIG_VERDI_GRUPPE' and kode2 NOT IN ('INGEN');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'KONFIG_VERDI_GRUPPE' AND KL_KODE NOT IN ('INGEN');
DELETE FROM KODELISTE WHERE KODEVERK = 'KONFIG_VERDI_GRUPPE' and kode NOT IN ('INGEN');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MANUELL_BEHANDLING_AARSAK' and kode1 NOT IN ('5017', '5005', '5021', '5003', '-', '5010', '5013', '5002', '5012', '5098', '5006', '5011', '5016', '5099', '5015', '5014');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MANUELL_BEHANDLING_AARSAK' and kode2 NOT IN ('5017', '5005', '5021', '5003', '-', '5010', '5013', '5002', '5012', '5098', '5006', '5011', '5016', '5099', '5015', '5014');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'MANUELL_BEHANDLING_AARSAK' AND KL_KODE NOT IN ('5017', '5005', '5021', '5003', '-', '5010', '5013', '5002', '5012', '5098', '5006', '5011', '5016', '5099', '5015', '5014');
DELETE FROM KODELISTE WHERE KODEVERK = 'MANUELL_BEHANDLING_AARSAK' and kode NOT IN ('5017', '5005', '5021', '5003', '-', '5010', '5013', '5002', '5012', '5098', '5006', '5011', '5016', '5099', '5015', '5014');

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='VILKAR_KATEGORI' and kode1 NOT IN ('-', 'BEREGNINGSVILKÅR', 'INNGANGSVILKÅR');
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='VILKAR_KATEGORI' and kode2 NOT IN ('-', 'BEREGNINGSVILKÅR', 'INNGANGSVILKÅR');
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'VILKAR_KATEGORI' AND KL_KODE NOT IN ('-', 'BEREGNINGSVILKÅR', 'INNGANGSVILKÅR');
DELETE FROM KODELISTE WHERE KODEVERK = 'VILKAR_KATEGORI' and kode NOT IN ('-', 'BEREGNINGSVILKÅR', 'INNGANGSVILKÅR');




DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'HISTORIKK_OPPLYSNING_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK = 'HISTORIKK_OPPLYSNING_TYPE';
DELETE FROM KODEVERK WHERE KODE  = 'HISTORIKK_OPPLYSNING_TYPE';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'INNVILGET_AARSAK';
DELETE FROM KODELISTE WHERE KODEVERK = 'INNVILGET_AARSAK';
DELETE FROM KODEVERK WHERE KODE  = 'INNVILGET_AARSAK';



DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='REVURDERING_VARSLING_AARSAK';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='REVURDERING_VARSLING_AARSAK';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'REVURDERING_VARSLING_AARSAK';
DELETE FROM KODELISTE WHERE KODEVERK = 'REVURDERING_VARSLING_AARSAK';
DELETE FORM KODEVERK WHERE KODE = 'REVURDERING_VARSLING_AARSAK';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='TEMA';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='TEMA';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'TEMA';
DELETE FROM KODELISTE WHERE KODEVERK = 'TEMA';
DELETE FROM KODEVERK WHERE KODE ='TEMA';
