UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT = 'INSØK.INN' WHERE KODE = '7013';

DELETE FROM BEHANDLING_TYPE_STEG_SEKV WHERE BEHANDLING_STEG_TYPE = 'REGSØK';
DELETE FROM AKSJONSPUNKT_DEF WHERE vurderingspunkt IN (SELECT kode FROM VURDERINGSPUNKT_DEF WHERE BEHANDLING_STEG = 'REGSØK');
DELETE FROM VURDERINGSPUNKT_DEF WHERE BEHANDLING_STEG = 'REGSØK';
DELETE FROM BEHANDLING_STEG_TYPE WHERE kode = 'REGSØK';
