//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 05:21:39 PM CEST 
//


package no.nav.foreldrepenger.no.nav.spmottak.meldinger.dokumentnotifikasjonv1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Forsendelsesinformasjon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Forsendelsesinformasjon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arkivId" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Identifikator"/>
 *         &lt;element name="arkivsystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tema" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Tema"/>
 *         &lt;element name="behandlingstema" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Behandlingstema" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Forsendelsesinformasjon", propOrder = {
    "arkivId",
    "arkivsystem",
    "tema",
    "behandlingstema"
})
public class Forsendelsesinformasjon {

    @XmlElement(required = true)
    protected String arkivId;
    @XmlElement(required = true)
    protected String arkivsystem;
    @XmlElement(required = true)
    protected Tema tema;
    protected Behandlingstema behandlingstema;

    /**
     * Gets the value of the arkivId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivId() {
        return arkivId;
    }

    /**
     * Sets the value of the arkivId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivId(String value) {
        this.arkivId = value;
    }

    /**
     * Gets the value of the arkivsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivsystem() {
        return arkivsystem;
    }

    /**
     * Sets the value of the arkivsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivsystem(String value) {
        this.arkivsystem = value;
    }

    /**
     * Gets the value of the tema property.
     * 
     * @return
     *     possible object is
     *     {@link Tema }
     *     
     */
    public Tema getTema() {
        return tema;
    }

    /**
     * Sets the value of the tema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tema }
     *     
     */
    public void setTema(Tema value) {
        this.tema = value;
    }

    /**
     * Gets the value of the behandlingstema property.
     * 
     * @return
     *     possible object is
     *     {@link Behandlingstema }
     *     
     */
    public Behandlingstema getBehandlingstema() {
        return behandlingstema;
    }

    /**
     * Sets the value of the behandlingstema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behandlingstema }
     *     
     */
    public void setBehandlingstema(Behandlingstema value) {
        this.behandlingstema = value;
    }

}
