CREATE TABLE FAGSAK_DVH
  (
  TRANS_ID           NUMBER(19)         NOT NULL,
  TRANS_TID          TIMESTAMP(3)       NOT NULL,
  FAGSAK_ID          NUMBER(19)         NOT NULL,
  BRUKER_ID          NUMBER(19)         NOT NULL,
  BRUKER_AKTOER_ID   NUMBER(19)         NOT NULL,
  EPS_BRUKER_ID      NUMBER(19),
  OPPRETTET_DATO     DATE               NOT NULL,
  FUNKSJONELL_TID    TIMESTAMP(3)       NOT NULL,
  SAKSNUMMER         NUMBER(19),
  ENDRET_AV          VARCHAR2(20 CHAR),
  FAGSAK_STATUS      VARCHAR2(100 CHAR) NOT NULL,
  FAGSAK_YTELSE      VARCHAR2(100 CHAR) NOT NULL,
  FAGSAK_AARSAK      VARCHAR2(100 CHAR) NOT NULL
  ) ;
ALTER TABLE FAGSAK_DVH ADD CONSTRAINT PK_FAGSAK_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_FAGSAK_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_FAGSAK_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON FAGSAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;


COMMENT ON TABLE FAGSAK_DVH  IS 'En transaksjonstabell med alle endringer på fagsaken.';
COMMENT ON COLUMN FAGSAK_DVH.TRANS_ID IS 'Primær nøkkel for fagsak transaksjoner';
COMMENT ON COLUMN FAGSAK_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN FAGSAK_DVH.ENDRET_AV IS 'Samme som opprettet_av eller endret_av i VL';
COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_ID IS 'Id til Fagsak';
COMMENT ON COLUMN FAGSAK_DVH.BRUKER_ID IS 'Bruker id til fagsaken';
COMMENT ON COLUMN FAGSAK_DVH.BRUKER_AKTOER_ID IS 'Aktørid til bruker';
COMMENT ON COLUMN FAGSAK_DVH.EPS_BRUKER_ID IS 'bruker ID for brukers ektefelle/partner/samboer';
COMMENT ON COLUMN FAGSAK_DVH.OPPRETTET_DATO IS 'Dato da fagsaken ble opprettet';
COMMENT ON COLUMN FAGSAK_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN FAGSAK_DVH.SAKSNUMMER IS 'Saksnummer som åpent for saksbehandler';
COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_STATUS IS 'Fagsaksstatus';
COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_YTELSE IS 'Fagssaksytelse';
COMMENT ON COLUMN FAGSAK_DVH.FAGSAK_AARSAK IS 'Fagssaksårsak';

CREATE TABLE BEHANDLING_DVH
  (
    TRANS_ID                    NUMBER(19) NOT NULL ,
    TRANS_TID                   TIMESTAMP(3) NOT NULL,
    BEHANDLING_ID               NUMBER(19) NOT NULL ,
    FAGSAK_ID                   NUMBER(19) NOT NULL ,  
    VEDTAK_ID                   NUMBER(19) ,
    OPPRETTET_DATO              DATE NOT NULL ,
    FUNKSJONELL_TID             TIMESTAMP(3) NOT NULL ,
    BEHANDLING_RESULTAT_TYPE    VARCHAR2(100 CHAR) ,
    BEHANDLING_TYPE             VARCHAR2(100 CHAR) NOT NULL ,
    BEHANDLING_STATUS           VARCHAR2(100 CHAR) NOT NULL ,
    BEHANDLENDE_ENHET           VARCHAR2(10 CHAR) ,
    UTLANDSTILSNITT             VARCHAR2(100 CHAR) ,
    ENDRET_AV                   VARCHAR2(20 CHAR)  ,
    ANSVARLIG_BESLUTTER         VARCHAR2(100 CHAR) ,
    ANSVARLIG_SAKSBEHANDLER     VARCHAR2(100 CHAR),
    TOTRINNSBEHANDLING          CHAR(1) DEFAULT 'N' not null check (TOTRINNSBEHANDLING IN ('J', 'N'))
  ) ;
ALTER TABLE BEHANDLING_DVH ADD CONSTRAINT PK_BEHANDLING_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_BEHANDLING_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_BEHANDLING_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON BEHANDLING_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON TABLE BEHANDLING_DVH  IS 'En transaksjonstabell med alle endringer på behandlingen.';
COMMENT ON COLUMN BEHANDLING_DVH.TRANS_ID IS 'Primær nøkkel for behandling transaksjoner';
COMMENT ON COLUMN BEHANDLING_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN BEHANDLING_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
COMMENT ON COLUMN BEHANDLING_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_ID IS 'Id til Behandling';
COMMENT ON COLUMN BEHANDLING_DVH.FAGSAK_ID IS 'Id til Fagsak';
COMMENT ON COLUMN BEHANDLING_DVH.OPPRETTET_DATO IS 'Dato da fagsaken ble opprettet';
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_RESULTAT_TYPE IS 'Behandlingsresultat type.';
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_TYPE IS 'Behandlingstype';
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_STATUS IS 'Behandlingsstatus';
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLENDE_ENHET IS 'Enheten som sitter på behandlinge på dette tidspunktet.';
COMMENT ON COLUMN BEHANDLING_DVH.UTLANDSTILSNITT IS 'Kodeverk: UTLAND, NASJONAL. ';
COMMENT ON COLUMN BEHANDLING_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlige saksbehandler.';
COMMENT ON COLUMN BEHANDLING_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Ansvarlig besluttningstager';


CREATE TABLE BEHANDLING_STEG_DVH
  (
    TRANS_ID                    NUMBER(19) NOT NULL ,
    TRANS_TID                   TIMESTAMP(3) NOT NULL,
    BEHANDLING_STEG_ID          NUMBER(19) ,  
    BEHANDLING_ID               NUMBER(19) NOT NULL,
    FUNKSJONELL_TID             TIMESTAMP(3) NOT NULL,
    ENDRET_AV                   VARCHAR2(20 CHAR) ,
    BEHANDLING_STEG_TYPE        VARCHAR2(20 CHAR) ,
    BEHANDLING_STEG_STATUS      VARCHAR2(100 CHAR) 
  ) ;
ALTER TABLE BEHANDLING_STEG_DVH ADD CONSTRAINT PK_BEHANDLING_STEG_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_BEHANDLING_STEG_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_BEHANDLING_STEG_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON BEHANDLING_STEG_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON TABLE BEHANDLING_STEG_DVH  IS 'En transaksjonstabell av alle endringer på behandlingen steg.';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.TRANS_ID IS 'Primær nøkkel for behandling steg transaksjoner';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_ID IS 'BEHANDLING_STEG_TILSTAND.ID';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_TYPE IS 'Steg type';
COMMENT ON COLUMN BEHANDLING_STEG_DVH.BEHANDLING_STEG_STATUS IS 'Steg status';


CREATE TABLE AKSJONSPUNKT_DVH
  (
    TRANS_ID                    NUMBER(19) NOT NULL ,
    BEHANDLING_STEG_ID          NUMBER(19) ,
    TRANS_TID                  TIMESTAMP(3) NOT NULL ,
    AKSJONSPUNKT_ID             NUMBER(19) NOT NULL ,
    BEHANDLING_ID               NUMBER(19) NOT NULL ,
    FUNKSJONELL_TID             TIMESTAMP(3) NOT NULL ,
    ENHET_KODE                  VARCHAR2(10 CHAR) ,
    BEHANDLENDE_ENHET_KODE      VARCHAR2(10 CHAR) ,
    ENDRET_AV                   VARCHAR2(20 CHAR) ,
    ANSVARLIG_BESLUTTER         VARCHAR2(100 CHAR) ,
    ANSVARLIG_SAKSBEHANDLER     VARCHAR2(100 CHAR) ,
    AKSJONSPUNKT_DEF            NUMBER(19) ,
    AKSJONSPUNKT_STATUS         VARCHAR2(100 CHAR) NOT NULL,
    TOTRINN_BEHANDLING          CHAR(1) DEFAULT 'N' not null check (TOTRINN_BEHANDLING IN ('J', 'N')),
    TOTRINN_BEHANDLING_GODKJENT CHAR(1) check (TOTRINN_BEHANDLING_GODKJENT IN ('J', 'N'))
  ) ;
ALTER TABLE AKSJONSPUNKT_DVH ADD CONSTRAINT PK_AKSJONSPUNKT_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_AKSJONSPUNKT_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_AKSJONSPUNKT_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON AKSJONSPUNKT_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON TABLE AKSJONSPUNKT_DVH  IS 'En transaksjonstabell med alle endringer på aksjonspunkt tilknytte en behandling.';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.TRANS_ID IS 'Primær nøkkel for aksjonspunkt transaksjoner';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.AKSJONSPUNKT_ID IS 'Id til aksjonspunkt';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.ENHET_KODE IS 'Enheten ansvarlig for aksjonspunktet.';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.BEHANDLENDE_ENHET_KODE IS 'Behandlende enhet.';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlig beslutningstager for aksjonspunktet.';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Saksbehandler ansvarlig for aksjonspunktet om det finnes. ';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.AKSJONSPUNKT_DEF IS 'Aksjonspunkt definisjon';
COMMENT ON COLUMN AKSJONSPUNKT_DVH.AKSJONSPUNKT_STATUS IS 'Aksjonspunkt status';

CREATE TABLE BEHANDLING_VEDTAK_DVH
  (
    TRANS_ID                    NUMBER(19) NOT NULL ,
    TRANS_TID                   TIMESTAMP(3) NOT NULL ,
    VEDTAK_ID                   NUMBER(19) NOT NULL ,
    BEHANDLING_ID               NUMBER(19) NOT NULL ,
    OPPRETTET_DATO              DATE NOT NULL,
    FUNKSJONELL_TID             TIMESTAMP(3) NOT NULL,
    VEDTAK_DATO                 DATE NOT NULL,
    IVERKSETTING_STATUS          VARCHAR2(100 CHAR) NOT NULL,
    GODKJENNENDE_ENHET          VARCHAR2(10 CHAR) ,
    ENDRET_AV                   VARCHAR2(20 CHAR) ,
    ANSVARLIG_BESLUTTER         VARCHAR2(100 CHAR) ,
    ANSVARLIG_SAKSBEHANDLER     VARCHAR2(100 CHAR)
  ) ;
ALTER TABLE BEHANDLING_VEDTAK_DVH ADD CONSTRAINT PK_BEHANDLING_VEDTAK_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_BEHANDLING_VEDTAK_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_BEHANDLING_VEDTAK_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON BEHANDLING_VEDTAK_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON TABLE BEHANDLING_VEDTAK_DVH  IS 'En transaksjonstabell med alle endringer på behandlingsvedtak.';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.TRANS_ID IS 'Primær nøkkel for behandling vedtak transaksjoner';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.BEHANDLING_ID IS 'Id til behandling';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.OPPRETTET_DATO IS 'Dato da vedtak ble opprettet';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.VEDTAK_DATO IS 'Datoen da vedtaket ble vedtatt.';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.IVERKSETTING_STATUS IS 'Iverksettingsstatus';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.GODKJENNENDE_ENHET IS 'Enheten som godkjener vedtaket. ';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ANSVARLIG_BESLUTTER IS 'Ansvarlig beslutningstager';
COMMENT ON COLUMN BEHANDLING_VEDTAK_DVH.ANSVARLIG_SAKSBEHANDLER IS 'Ansvarlig saksbehandler';

CREATE TABLE KONTROLL_DVH
  (
    ID                          NUMBER(19) NOT NULL ,
    FAGSAK_TRANS_ID_MAX         NUMBER(19) ,
    BEH_TRANS_ID_MAX            NUMBER(19) ,
    BEH_STEG_TRANS_ID_MAX       NUMBER(19) ,
    BEH_AKSJONS_TRANS_ID_MAX    NUMBER(19) ,
    BEH_VEDTAKS_TRANS_ID_MAX    NUMBER(19) ,
    LAST_FLAGG                  CHAR(1) DEFAULT 'N' not null check (LAST_FLAGG IN ('J', 'N'))
 ) ;
ALTER TABLE KONTROLL_DVH ADD CONSTRAINT PK_KONTROLL_DVH PRIMARY KEY ( ID ) ;

GRANT ALL ON KONTROLL_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON COLUMN KONTROLL_DVH.ID IS 'Meta-data tabell som forteller hva siste leste trans id for de forskjellig transaksjonstabellene som er blitt lest av DVH. ';
COMMENT ON COLUMN KONTROLL_DVH.FAGSAK_TRANS_ID_MAX IS 'Sist leste id fra fagsak_dvh';
COMMENT ON COLUMN KONTROLL_DVH.BEH_TRANS_ID_MAX IS 'Sist leste id fra behandling_dvh';
COMMENT ON COLUMN KONTROLL_DVH.BEH_STEG_TRANS_ID_MAX IS 'Sist leste id fra behandling_steg_dvh';
COMMENT ON COLUMN KONTROLL_DVH.BEH_AKSJONS_TRANS_ID_MAX IS 'Sist leste id fra aksjonspunkt_dvh';
COMMENT ON COLUMN KONTROLL_DVH.BEH_VEDTAKS_TRANS_ID_MAX IS 'Sist leste id fra behandlings_vedtak_dvh';
COMMENT ON COLUMN KONTROLL_DVH.LAST_FLAGG IS 'Et flagg som forteller om det har forekommet en oppdatering av historiske, tidliger leste transaksjoner. ';
