ALTER TABLE RELATERT_YTELSE_TYPE MODIFY kode VARCHAR2(30 CHAR);
ALTER TABLE BEHANDLING_REL_YTELSER MODIFY RELATERT_YTELSE_TYPE VARCHAR2(30 CHAR);

INSERT INTO RELATERT_YTELSE_TYPE(kode,navn) VALUES ('ARBEIDSAVKLARINGSPENGER','Arbeidsavklaringspenger');
INSERT INTO RELATERT_YTELSE_TYPE(kode,navn) VALUES ('DAGPENGER','Dagpenger');

INSERT INTO RELATERT_YTELSE_TEMA(kode,navn) VALUES ('AA','Arbeidsavklaringspenger');
INSERT INTO RELATERT_YTELSE_TEMA(kode,navn) VALUES ('DAGP','Dagpenger');

--Når tema er 'AA' Arbeidsavklaringspenger
INSERT INTO RELATERT_YTELSE_BEHANDLTEMA(kode,navn) VALUES ('AAP','Arbeidsavklaringspenger');

--Når tema er 'DAGP' Dagpenger
INSERT INTO RELATERT_YTELSE_BEHANDLTEMA(kode,navn) VALUES ('DAGO','Ordinære dagpenger');
INSERT INTO RELATERT_YTELSE_BEHANDLTEMA(kode,navn) VALUES ('PERM','Dagpenger under permitteringer');
INSERT INTO RELATERT_YTELSE_BEHANDLTEMA(kode,navn) VALUES ('FISK','Dagp. v/perm fra fiskeindustri');
INSERT INTO RELATERT_YTELSE_BEHANDLTEMA(kode,navn) VALUES ('LONN','Lønnsgarantimidler - dagpenger');

INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('AVSLU','Avsluttet');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('GODKJ','Godkjent');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('INNST','Innstilt');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('IVERK','Iverksatt');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('MOTAT','Mottatt');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('OPPRE','Opprettet');
INSERT INTO RELATERT_YTELSE_STATUS(kode,navn) VALUES ('REGIS','Registrert');
