-- Starte på nytt
DELETE FROM LAND_REGION;
DELETE FROM LANDKODER;

-- Samtlige gyldige 3 bokstav landkoder fra NAV kodeverk
INSERT INTO LANDKODER (kode, navn) VALUES ('??? ', 'UOPPGITT/UKJENT');
INSERT INTO LANDKODER (kode, navn) VALUES ('349', 'SPANSKE OMR. AFRIKA');
INSERT INTO LANDKODER (kode, navn) VALUES ('546', 'SIKKIM');
INSERT INTO LANDKODER (kode, navn) VALUES ('556', 'YEMEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('669', 'PANAMAKANALSONEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('ABW', 'ARUBA');
INSERT INTO LANDKODER (kode, navn) VALUES ('AFG', 'AFGHANISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('AGO', 'ANGOLA');
INSERT INTO LANDKODER (kode, navn) VALUES ('AIA', 'ANGUILLA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ALA', 'ÅLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('ALB', 'ALBANIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('AND', 'ANDORRA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ANT', 'DE NEDERLANDSKE ANTILLENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('ARE', 'DE ARABISKE EMIRATER');
INSERT INTO LANDKODER (kode, navn) VALUES ('ARG', 'ARGENTINA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ARM', 'ARMENIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ASM', 'AM. SAMOA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ATF', 'FRANSKE SYDTERRITORIER');
INSERT INTO LANDKODER (kode, navn) VALUES ('ATG', 'ANTIGUA OG BARBUDA');
INSERT INTO LANDKODER (kode, navn) VALUES ('AUS', 'AUSTRALIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('AUT', 'ØSTERRIKE');
INSERT INTO LANDKODER (kode, navn) VALUES ('AZE', 'AZERBAJDZJAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('BDI', 'BURUNDI');
INSERT INTO LANDKODER (kode, navn) VALUES ('BEL', 'BELGIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BEN', 'BENIN');
INSERT INTO LANDKODER (kode, navn) VALUES ('BES', 'BONAIRE, SINT EUSTATIUS, SABA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BFA', 'BURKINA FASO');
INSERT INTO LANDKODER (kode, navn) VALUES ('BGD', 'BANGLADESH');
INSERT INTO LANDKODER (kode, navn) VALUES ('BGR', 'BULGARIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BHR', 'BAHRAIN');
INSERT INTO LANDKODER (kode, navn) VALUES ('BHS', 'BAHAMAS');
INSERT INTO LANDKODER (kode, navn) VALUES ('BIH', 'BOSNIA-HERCEGOVINA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BLM', 'SAINT BARTHELEMY');
INSERT INTO LANDKODER (kode, navn) VALUES ('BLR', 'HVITERUSSLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('BLZ', 'BELIZE');
INSERT INTO LANDKODER (kode, navn) VALUES ('BMU', 'BERMUDA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BOL', 'BOLIVIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BRA', 'BRASIL');
INSERT INTO LANDKODER (kode, navn) VALUES ('BRB', 'BARBADOS');
INSERT INTO LANDKODER (kode, navn) VALUES ('BRN', 'BRUNEI');
INSERT INTO LANDKODER (kode, navn) VALUES ('BTN', 'BHUTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('BVT', 'BOUVETØYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('BWA', 'BOTSWANA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CAF', 'SENTRALAFRIKA. REP.');
INSERT INTO LANDKODER (kode, navn) VALUES ('CAN', 'CANADA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CCK', 'KOKOSØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('CHE', 'SVEITS');
INSERT INTO LANDKODER (kode, navn) VALUES ('CHL', 'CHILE');
INSERT INTO LANDKODER (kode, navn) VALUES ('CHN', 'REPUBLIKKEN KINA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CIV', 'ELFENBEINSKYSTEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('CMR', 'KAMERUN');
INSERT INTO LANDKODER (kode, navn) VALUES ('COD', 'KONGO, DEN DEMOKR. REPUBL');
INSERT INTO LANDKODER (kode, navn) VALUES ('COG', 'KONGO, REPUBLIKKEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('COK', 'COOKØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('COL', 'COLOMBIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('COM', 'KOMORENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('CPV', 'KAPP VERDE');
INSERT INTO LANDKODER (kode, navn) VALUES ('CRI', 'COSTA RICA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CSK', 'TSJEKKOSLOVAKIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CUB', 'CUBA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CUW', 'CURACAO');
INSERT INTO LANDKODER (kode, navn) VALUES ('CXR', 'CHRISTMASØYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('CYM', 'CAYMANØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('CYP', 'KYPROS');
INSERT INTO LANDKODER (kode, navn) VALUES ('CZE', 'DEN TSJEKKISKE REP.');
INSERT INTO LANDKODER (kode, navn) VALUES ('DDR', 'TYSKLAND (ØST)');
INSERT INTO LANDKODER (kode, navn) VALUES ('DEU', 'TYSKLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('DJI', 'DJIBOUTI');
INSERT INTO LANDKODER (kode, navn) VALUES ('DMA', 'DOMINICA');
INSERT INTO LANDKODER (kode, navn) VALUES ('DNK', 'DANMARK');
INSERT INTO LANDKODER (kode, navn) VALUES ('DOM', 'DEN DOMINIKANSKE REP');
INSERT INTO LANDKODER (kode, navn) VALUES ('DZA', 'ALGERIE');
INSERT INTO LANDKODER (kode, navn) VALUES ('ECU', 'ECUADOR');
INSERT INTO LANDKODER (kode, navn) VALUES ('EGY', 'EGYPT');
INSERT INTO LANDKODER (kode, navn) VALUES ('ERI', 'ERITREA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ESH', 'VEST-SAHARA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ESP', 'SPANIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('EST', 'ESTLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('ETH', 'ETIOPIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('FIN', 'FINLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('FJI', 'FIJI');
INSERT INTO LANDKODER (kode, navn) VALUES ('FLK', 'FALKLANDSØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('FRA', 'FRANKRIKE');
INSERT INTO LANDKODER (kode, navn) VALUES ('FRO', 'FÆRØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('FSM', 'MIKRONESIAFØD.');
INSERT INTO LANDKODER (kode, navn) VALUES ('GAB', 'GABON');
INSERT INTO LANDKODER (kode, navn) VALUES ('GBR', 'STORBRITANNIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GEO', 'GEORGIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GGY', 'GUERNSEY');
INSERT INTO LANDKODER (kode, navn) VALUES ('GHA', 'GHANA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GIB', 'GIBRALTAR');
INSERT INTO LANDKODER (kode, navn) VALUES ('GIN', 'GUINEA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GLP', 'GUADELOUPE');
INSERT INTO LANDKODER (kode, navn) VALUES ('GMB', 'GAMBIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GNB', 'GUINEA-BISSAU');
INSERT INTO LANDKODER (kode, navn) VALUES ('GNQ', 'EKVATORIAL-GUINEA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GRC', 'HELLAS');
INSERT INTO LANDKODER (kode, navn) VALUES ('GRD', 'GRENADA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GRL', 'GRØNLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('GTM', 'GUATEMALA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GUF', 'FRANSK GUYANA');
INSERT INTO LANDKODER (kode, navn) VALUES ('GUM', 'GUAM');
INSERT INTO LANDKODER (kode, navn) VALUES ('GUY', 'GUYANA');
INSERT INTO LANDKODER (kode, navn) VALUES ('HKG', 'HONGKONG');
INSERT INTO LANDKODER (kode, navn) VALUES ('HMD', 'HEARD OG MCDONALD ØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('HND', 'HONDURAS');
INSERT INTO LANDKODER (kode, navn) VALUES ('HRV', 'KROATIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('HTI', 'HAITI');
INSERT INTO LANDKODER (kode, navn) VALUES ('HUN', 'UNGARN');
INSERT INTO LANDKODER (kode, navn) VALUES ('IDN', 'INDONESIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('IMN', 'ISLE OF MAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('IND', 'INDIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('IOT', 'BRITISK-INDISKE HAV');
INSERT INTO LANDKODER (kode, navn) VALUES ('IRL', 'IRLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('IRN', 'IRAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('IRQ', 'IRAK');
INSERT INTO LANDKODER (kode, navn) VALUES ('ISL', 'ISLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('ISR', 'ISRAEL');
INSERT INTO LANDKODER (kode, navn) VALUES ('ITA', 'ITALIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('JAM', 'JAMAICA');
INSERT INTO LANDKODER (kode, navn) VALUES ('JEY', 'JERSEY');
INSERT INTO LANDKODER (kode, navn) VALUES ('JOR', 'JORDAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('JPN', 'JAPAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('KAZ', 'KAZAKHSTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('KEN', 'KENYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('KGZ', 'KIRGISISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('KHM', 'KAMBODSJA');
INSERT INTO LANDKODER (kode, navn) VALUES ('KIR', 'KIRIBATI');
INSERT INTO LANDKODER (kode, navn) VALUES ('KNA', 'ST.KITTS OG NEVIS');
INSERT INTO LANDKODER (kode, navn) VALUES ('KOR', 'SØR-KOREA');
INSERT INTO LANDKODER (kode, navn) VALUES ('KWT', 'KUWAIT');
INSERT INTO LANDKODER (kode, navn) VALUES ('LAO', 'LAOS');
INSERT INTO LANDKODER (kode, navn) VALUES ('LBN', 'LIBANON');
INSERT INTO LANDKODER (kode, navn) VALUES ('LBR', 'LIBERIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('LBY', 'LIBYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('LCA', 'ST. LUCIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('LIE', 'LIECHTENSTEIN');
INSERT INTO LANDKODER (kode, navn) VALUES ('LKA', 'SRI LANKA');
INSERT INTO LANDKODER (kode, navn) VALUES ('LSO', 'LESOTHO');
INSERT INTO LANDKODER (kode, navn) VALUES ('LTU', 'LITAUEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('LUX', 'LUXEMBOURG');
INSERT INTO LANDKODER (kode, navn) VALUES ('LVA', 'LATVIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MAC', 'MACAO');
INSERT INTO LANDKODER (kode, navn) VALUES ('MAF', 'SAINT MARTIN');
INSERT INTO LANDKODER (kode, navn) VALUES ('MAR', 'MAROKKO');
INSERT INTO LANDKODER (kode, navn) VALUES ('MCO', 'MONACO');
INSERT INTO LANDKODER (kode, navn) VALUES ('MDA', 'MOLDOVA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MDG', 'MADAGASKAR');
INSERT INTO LANDKODER (kode, navn) VALUES ('MDV', 'MALDIVENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('MEX', 'MEXICO');
INSERT INTO LANDKODER (kode, navn) VALUES ('MHL', 'MARSHALLØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('MKD', 'MAKEDONIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MLI', 'MALI');
INSERT INTO LANDKODER (kode, navn) VALUES ('MLT', 'MALTA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MMR', 'MYANMAR (BURMA)');
INSERT INTO LANDKODER (kode, navn) VALUES ('MNE', 'MONTENEGRO');
INSERT INTO LANDKODER (kode, navn) VALUES ('MNG', 'MONGOLIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MNP', 'NORD-MARIANENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('MOZ', 'MOSAMBIK');
INSERT INTO LANDKODER (kode, navn) VALUES ('MRT', 'MAURITANIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MSR', 'MONSERRAT');
INSERT INTO LANDKODER (kode, navn) VALUES ('MTQ', 'MARTINIQUE');
INSERT INTO LANDKODER (kode, navn) VALUES ('MUS', 'MAURITIUS');
INSERT INTO LANDKODER (kode, navn) VALUES ('MWI', 'MALAWI');
INSERT INTO LANDKODER (kode, navn) VALUES ('MYS', 'MALAYSIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('MYT', 'MAYOTTE');
INSERT INTO LANDKODER (kode, navn) VALUES ('NAM', 'NAMIBIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('NCL', 'NY-KALEDONIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('NER', 'NIGER');
INSERT INTO LANDKODER (kode, navn) VALUES ('NFK', 'NORFOLKØYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('NGA', 'NIGERIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('NIC', 'NICARAGUA');
INSERT INTO LANDKODER (kode, navn) VALUES ('NIU', 'NIUE');
INSERT INTO LANDKODER (kode, navn) VALUES ('NLD', 'NEDERLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('NOR', 'NORGE');
INSERT INTO LANDKODER (kode, navn) VALUES ('NPL', 'NEPAL');
INSERT INTO LANDKODER (kode, navn) VALUES ('NRU', 'NAURU');
INSERT INTO LANDKODER (kode, navn) VALUES ('NZL', 'NEW ZEALAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('OMN', 'OMAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('PAK', 'PAKISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('PAN', 'PANAMA');
INSERT INTO LANDKODER (kode, navn) VALUES ('PCN', 'PITCAIRN');
INSERT INTO LANDKODER (kode, navn) VALUES ('PER', 'PERU');
INSERT INTO LANDKODER (kode, navn) VALUES ('PHL', 'FILIPPINENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('PLW', 'PALAU');
INSERT INTO LANDKODER (kode, navn) VALUES ('PNG', 'PAPUA NY-GUINEA');
INSERT INTO LANDKODER (kode, navn) VALUES ('POL', 'POLEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('PRI', 'PUERTO RICO');
INSERT INTO LANDKODER (kode, navn) VALUES ('PRK', 'NORD-KOREA');
INSERT INTO LANDKODER (kode, navn) VALUES ('PRT', 'PORTUGAL');
INSERT INTO LANDKODER (kode, navn) VALUES ('PRY', 'PARAGUAY');
INSERT INTO LANDKODER (kode, navn) VALUES ('PSE', 'DET PALESTINSKE OMRÅDET');
INSERT INTO LANDKODER (kode, navn) VALUES ('PYF', 'FRANSK POLYNESIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('QAT', 'QATAR');
INSERT INTO LANDKODER (kode, navn) VALUES ('REU', 'REUNION');
INSERT INTO LANDKODER (kode, navn) VALUES ('ROU', 'ROMANIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('RUS', 'RUSSLAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('RWA', 'RWANDA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SAU', 'SAUDI-ARABIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SCG', 'SERBIA OG MONTENEGRO');
INSERT INTO LANDKODER (kode, navn) VALUES ('SDN', 'SUDAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('SEN', 'SENEGAL');
INSERT INTO LANDKODER (kode, navn) VALUES ('SGP', 'SINGAPORE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SGS', 'SØR-GEORGIA OG SØR-SANDWICHØYE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SHN', 'ST. HELENA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SJM', 'SVALBARD OG JAN MAYEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('SLB', 'SALOMONØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SLE', 'SIERRA LEONE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SLV', 'EL SALVADOR');
INSERT INTO LANDKODER (kode, navn) VALUES ('SMR', 'SAN MARINO');
INSERT INTO LANDKODER (kode, navn) VALUES ('SOM', 'SOMALIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SPM', 'ST-PIERRE OG MIQUELON');
INSERT INTO LANDKODER (kode, navn) VALUES ('SRB', 'SERBIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SSD', 'SØR-SUDAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('STP', 'SAO TOME OG PRINCIPE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SUN', 'SOVJETUNIONEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('SUR', 'SURINAM');
INSERT INTO LANDKODER (kode, navn) VALUES ('SVK', 'SLOVAKIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SVN', 'SLOVENIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('SWE', 'SVERIGE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SWZ', 'SWAZILAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('SXM', 'SINT MAARTEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('SYC', 'SEYCHELLENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('SYR', 'SYRIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('TCA', 'TURKS/CAICOSØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('TCD', 'TSJAD');
INSERT INTO LANDKODER (kode, navn) VALUES ('TGO', 'TOGO');
INSERT INTO LANDKODER (kode, navn) VALUES ('THA', 'THAILAND');
INSERT INTO LANDKODER (kode, navn) VALUES ('TJK', 'TADZJIKISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('TKL', 'TOKELAU');
INSERT INTO LANDKODER (kode, navn) VALUES ('TKM', 'TURKMENISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('TLS', 'ØST-TIMOR');
INSERT INTO LANDKODER (kode, navn) VALUES ('TON', 'TONGA');
INSERT INTO LANDKODER (kode, navn) VALUES ('TTO', 'TRINIDAD OG TOBAGO');
INSERT INTO LANDKODER (kode, navn) VALUES ('TUN', 'TUNISIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('TUR', 'TYRKIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('TUV', 'TUVALU');
INSERT INTO LANDKODER (kode, navn) VALUES ('TWN', 'TAIWAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('TZA', 'TANZANIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('UGA', 'UGANDA');
INSERT INTO LANDKODER (kode, navn) VALUES ('UKR', 'UKRAINA');
INSERT INTO LANDKODER (kode, navn) VALUES ('UMI', 'MINDRE STILLEHAVSØYER');
INSERT INTO LANDKODER (kode, navn) VALUES ('URY', 'URUGUAY');
INSERT INTO LANDKODER (kode, navn) VALUES ('USA', 'USA');
INSERT INTO LANDKODER (kode, navn) VALUES ('UZB', 'UZBEKISTAN');
INSERT INTO LANDKODER (kode, navn) VALUES ('VAT', 'VATIKANSTATEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('VCT', 'ST. VINCENT');
INSERT INTO LANDKODER (kode, navn) VALUES ('VEN', 'VENEZUELA');
INSERT INTO LANDKODER (kode, navn) VALUES ('VGB', 'JOMFRUØYENE BRIT.');
INSERT INTO LANDKODER (kode, navn) VALUES ('VIR', 'JOMFRUØYENE AM.');
INSERT INTO LANDKODER (kode, navn) VALUES ('VNM', 'VIETNAM');
INSERT INTO LANDKODER (kode, navn) VALUES ('VUT', 'VANUATU');
INSERT INTO LANDKODER (kode, navn) VALUES ('WAK', 'WAKØYA');
INSERT INTO LANDKODER (kode, navn) VALUES ('WLF', 'WALLIS/FUTUNAØYENE');
INSERT INTO LANDKODER (kode, navn) VALUES ('WSM', 'SAMOA');
INSERT INTO LANDKODER (kode, navn) VALUES ('XXK', 'KOSOVO');
INSERT INTO LANDKODER (kode, navn) VALUES ('XXX', 'STATSLØS');
INSERT INTO LANDKODER (kode, navn) VALUES ('YEM', 'JEMEN');
INSERT INTO LANDKODER (kode, navn) VALUES ('YUG', 'JUGOSLAVIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ZAF', 'SØR-AFRIKA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ZMB', 'ZAMBIA');
INSERT INTO LANDKODER (kode, navn) VALUES ('ZWE', 'ZIMBABWE');


-- Ref. www.norden.org:
-- Norden består av Danmark, Norge, Sverige, Finland og Island.
-- samt Færøyene, Grønland og Åland.

INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('NOR', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('SWE', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('DNK', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('FIN', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ISL', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('FRO', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('GRL', 'NORDEN');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ALA', 'NORDEN');

-- Ref. helsenorge.no/behandling-i-utlandet/eu-eos-landene:
-- Dette er EU/EØS-landene:​​
-- Belgia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('BEL', 'EOS');
-- Bulgaria
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('BGR', 'EOS');
-- Danmark
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('DNK', 'EOS');
-- Estland
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('EST', 'EOS');
-- Finland
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('FIN', 'EOS');
-- Frankrike
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('FRA', 'EOS');
-- Hellas
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('GRC', 'EOS');
-- Irland
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('IRL', 'EOS');
-- Island
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ISL', 'EOS');
-- Italia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ITA', 'EOS');
-- Kroatia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('HRV', 'EOS');
-- Kypros
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('CYP', 'EOS');
-- Latvia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('LVA', 'EOS');
-- Liechtenstein
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('LIE', 'EOS');
-- Litauen
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('LTU', 'EOS');
-- Luxembourg
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('LUX', 'EOS');
-- Malta
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('MLT', 'EOS');
-- Nederland
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('NLD', 'EOS');
-- Norge
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('NOR', 'EOS');
-- Polen
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('POL', 'EOS');
-- Portugal
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('PRT', 'EOS');
-- Romania
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ROU', 'EOS');
-- Slovakia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('SVK', 'EOS');
-- Slovenia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('SVN', 'EOS');
-- Spania
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ESP', 'EOS');
-- Storbritannia og Nord-Irland,
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('GBR', 'EOS');
-- Sverige
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('SWE', 'EOS');
-- Tsjekkia
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('CZE', 'EOS');
-- Tyskland
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('DEU', 'EOS');
-- Ungarn
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('HUN', 'EOS');
-- Østerrike
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('AUT', 'EOS');

INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('USA', 'ANNET');

-- Forøvrig er de nordisk områder også inkludert
-- ettersom disse er underlagt nordiske land som også er Eøs land
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('FRO', 'EOS');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('GRL', 'EOS');
INSERT INTO LAND_REGION(LANDKODE, REGION) VALUES ('ALA', 'EOS');
