-- Tabell
CREATE TABLE DOKUMENT_MAL_RESTRIKSJON (
    kode            VARCHAR2(20 CHAR) NOT NULL,
    navn            VARCHAR2(50 CHAR) NOT NULL,
    beskrivelse     VARCHAR2(2000 CHAR),
    opprettet_av    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    opprettet_tid   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    endret_av       VARCHAR2(20 CHAR),
    endret_tid      TIMESTAMP(3),
	CONSTRAINT PK_DOKUMENT_MAL_RESTRIKSJON PRIMARY KEY (KODE)
);

-- Comments
COMMENT ON TABLE DOKUMENT_MAL_RESTRIKSJON IS 'Angir restriksjon av dokument mal';

INSERT INTO DOKUMENT_MAL_RESTRIKSJON (kode, navn) VALUES ('INGEN', 'ingen');
INSERT INTO DOKUMENT_MAL_RESTRIKSJON (kode, navn) VALUES ('REVURDERING', 'Mal for revurdering');

alter table DOKUMENT_MAL_TYPE add DOKUMENT_MAL_RESTRIKSJON VARCHAR2(20 CHAR) default 'INGEN' NOT NULL;
alter table DOKUMENT_MAL_TYPE add constraint FK_DOKUMENT_MAL_RESTRIKSJON_1 FOREIGN KEY (DOKUMENT_MAL_RESTRIKSJON) REFERENCES DOKUMENT_MAL_RESTRIKSJON (KODE);

INSERT INTO DOKUMENT_MAL_TYPE (kode, navn, generisk) VALUES ('000052', 'Uendret utfall', 'N');
INSERT INTO DOKUMENT_MAL_TYPE (kode, navn, DOKUMENT_MAL_RESTRIKSJON, generisk) VALUES ('000058', 'Revurdering', 'REVURDERING', 'N');
