-- Legg til FK mot BEHANDLING fra MOTTATTE_DOKUMENT
ALTER TABLE MOTTATTE_DOKUMENT
  ADD CONSTRAINT FK_MOTTATTE_DOKUMENT_2
FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID);

-- Fjerner ubrukt tabell MOTTATT_STATUS
DROP TABLE MOTTATT_STATUS;
