INSERT INTO VILKAR_TYPE (kode, navn) VALUES ('FP_VK_34', 'Søkers opplysningsplikt');

--Endring i behandling_resultat tabell
alter table BEHANDLING_RESULTAT add (avslag_arsak VARCHAR2(20 CHAR));
alter table BEHANDLING_RESULTAT add (avslagsarsak_fritekst VARCHAR2(1500 CHAR));

ALTER TABLE BEHANDLING_RESULTAT ADD CONSTRAINT FK_BEHANDLING_RESULTAT_6 FOREIGN KEY (avslag_arsak) REFERENCES AVSLAGSARSAK;

COMMENT ON COLUMN BEHANDLING_RESULTAT.avslag_arsak IS 'Årsakskode for avslag. Foreign key til AVSLAGSARSAK.';
COMMENT ON COLUMN BEHANDLING_RESULTAT.avslagsarsak_fritekst IS 'Begrunnelse for avslag av søknad.';

-- Endring i VILKAR_TYPE tabell
alter table VILKAR_TYPE add (lov_referanse VARCHAR2(60 CHAR));

COMMENT ON COLUMN VILKAR_TYPE.lov_referanse IS 'Referanse til lovhjemmel for avslag av søknad.';

-- Introduserer nytt steg: Kontrollere søkers opplysningslikt

--TODO: Sjekker inn denne når alt testing er utført for søkers opplysningsplikt.

delete from BEHANDLING_TYPE_STEG_SEKV;
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','INSAK','1');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','KOFAK','2');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','VURDERBV','4');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','BERYT','7');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','FVEDSTEG','9');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','IVEDSTEG','10');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','VURDERSFV','6');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','FORVEDSTEG','8');
Insert into BEHANDLING_TYPE_STEG_SEKV (ID,BEHANDLING_TYPE,BEHANDLING_STEG_TYPE,SEKVENS_NR) values (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval,'BT-002','VURDERMV','5');

INSERT INTO BEHANDLING_STEG_TYPE(kode, navn, behandling_status_def, beskrivelse)
VALUES ('VURDEROP', 'Kontrollerer søkers opplysningsplikt', 'UTRED', 'Kontrollere søkers opplysningsplikt for å se til at søknaden er komplett');

INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('VURDEROP.INN', 'Kontrollerer søkers opplysningsplikt - Inngang', 'VURDEROP', 'INN');
INSERT INTO VURDERINGSPUNKT_DEF (kode, navn, behandling_steg, vurderingspunkt_type)
VALUES ('VURDEROP.UT', 'Kontrollerer søkers opplysningsplikt - Utgang', 'VURDEROP', 'UT');


INSERT INTO BEHANDLING_TYPE_STEG_SEKV (id, behandling_type, behandling_steg_type, sekvens_nr)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-002', 'VURDEROP', 3);

INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, AKSJONSPUNKT_KATEGORI, VILKAR_TYPE, VURDERINGSPUNKT, ALLTID_TOTRINNSBEHANDLING, BESKRIVELSE, AKSJONSPUNKT_TYPE)
VALUES ('5017', 'Kontroller søkers opplysningsplikt', 'APK-003', 'FP_VK_34', 'VURDEROP.UT', 'N', 'Kontroller søkers opplysningsplikt', 'MANU');

INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, AKSJONSPUNKT_KATEGORI, VILKAR_TYPE, VURDERINGSPUNKT, ALLTID_TOTRINNSBEHANDLING, BESKRIVELSE, AKSJONSPUNKT_TYPE)
VALUES ('5018', 'Foreslå vedtak uten totrinnskontroll', 'APK-003', NULL , 'FORVEDSTEG.UT', 'N', 'Foreslå vedtak uten totrinnskontroll', 'MANU');

INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, AKSJONSPUNKT_KATEGORI, VILKAR_TYPE, VURDERINGSPUNKT, ALLTID_TOTRINNSBEHANDLING, BESKRIVELSE, AKSJONSPUNKT_TYPE)
VALUES ('6002', 'Kontroller søkers opplysningsplikt', 'APK-003', 'FP_VK_34', 'VURDEROP.UT', 'N', 'Kontroller søkers opplysningsplikt', 'OVST');


INSERT INTO AVSLAGSARSAK(KODE, VILKAR_KODE, NAVN) VALUES ('1019', 'FP_VK_34', 'Manglende dokumentasjon');


