-- Tabell: MEDLEMSKAP_MANUELL_VURD_TYPE
CREATE TABLE MEDLEMSKAP_MANUELL_VURD_TYPE (
  kode                           VARCHAR2(20 CHAR) NOT NULL,
  navn                           VARCHAR2(50 CHAR) NOT NULL,
  beskrivelse                    VARCHAR2(2000 CHAR),
  opprettet_av                   VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid                  TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                      VARCHAR2(20 CHAR),
  endret_tid                     TIMESTAMP(3),
  CONSTRAINT MEDLEMSKAP_MANUELL_VURD_TYPE PRIMARY KEY (kode)
);

COMMENT ON TABLE MEDLEMSKAP_MANUELL_VURD_TYPE  IS 'Kodeverk for manuell vurdering av medlemsskapsperioder i folketrygden';
COMMENT ON COLUMN MEDLEMSKAP_MANUELL_VURD_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN MEDLEMSKAP_MANUELL_VURD_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';

INSERT INTO MEDLEMSKAP_MANUELL_VURD_TYPE(kode, navn) VALUES ('MEDLEM', 'Periode med medlemskap');
INSERT INTO MEDLEMSKAP_MANUELL_VURD_TYPE(kode, navn) VALUES ('UNNTAK', 'Periode med unntak fra medlemskap');
INSERT INTO MEDLEMSKAP_MANUELL_VURD_TYPE(kode, navn) VALUES ('IKKE_RELEVANT', 'Ikke relevant periode');


ALTER TABLE TILKNYTNING_HJEMLAND rename column oppholdSistePeriode TO OPPHOLD_SISTE_PERIODE;
ALTER TABLE TILKNYTNING_HJEMLAND rename column oppholdNestePeriode TO OPPHOLD_NESTE_PERIODE;

COMMENT ON COLUMN TILKNYTNING_HJEMLAND.opphold_siste_periode IS 'True dersom søker har oppholdt seg i Norge i siste periode.';
COMMENT ON COLUMN TILKNYTNING_HJEMLAND.opphold_neste_periode IS 'True dersom søker har oppholdt seg i Norge i neste periode.';
COMMENT ON COLUMN TILKNYTNING_HJEMLAND.periodetype IS 'Varighet av oppholdsperiode';

ALTER TABLE MEDLEMSKAP_DEKNING_TYPE MODIFY (NAVN VARCHAR2(100 CHAR));

DELETE FROM MEDLEMSKAP_DEKNING_TYPE;
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_6', 'Folketrygdloven § 2-6');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_7_a', 'Folketrygdloven § 2-7, 3.ledd bokstav a');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_7_b', 'Folketrygdloven § 2-7, 3. ledd bokstav b');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_9_1_a', 'Folketrygdloven § 2-9, 1.ledd bokstav a');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_9_1_b', 'Folketrygdloven § 2-9, 1.ledd bokstav b');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_9_1_c', 'Folketrygdloven § 2-9, 1.ledd bokstav c');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_9_2_a', 'Folketrygdloven § 2-9, annet ledd, jfr. 1.ledd bokstav a');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FTL_2_9_2_c', 'Folketrygdloven § 2-9, annet ledd, jf. 1. ledd bokstav c');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('FULL', 'Full');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('IHT_AVTALE', 'I henhold til avtale');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('OPPHOR', 'Opphør');
INSERT INTO MEDLEMSKAP_DEKNING_TYPE(kode, navn) VALUES ('UNNTATT', 'Unntatt');

-- Synkroniserer kildetyper med MEDL2
DELETE FROM MEDLEMSKAP_KILDE_TYPE;
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('E500', 'E-500');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('INFOTR', 'Infotrygd');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('AVGSYS', 'Avgiftsystemet');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('APPBRK', 'Applikasjonsbruker');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('PP01', 'Pensjon');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('FS22', 'Gosys');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('MEDL', 'MEDL');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('TPS', 'TPS');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('TP', 'TP');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('LAANEKASSEN', 'Laanekassen');
INSERT INTO MEDLEMSKAP_KILDE_TYPE(kode, navn) VALUES ('ANNEN', 'Annen');

ALTER TABLE BEKREFTET_FORELDRE ADD OVERSTYRT_PERSONSTATUS_TYPE VARCHAR2(20 CHAR);
ALTER TABLE BEKREFTET_FORELDRE ADD CONSTRAINT FK_BEKREFTET_FORELDRE_5 FOREIGN KEY (OVERSTYRT_PERSONSTATUS_TYPE) REFERENCES PERSONSTATUS_TYPE;
CREATE INDEX IDX_BEKREFTET_FORELDRE_4 ON BEKREFTET_FORELDRE(OVERSTYRT_PERSONSTATUS_TYPE);

ALTER TABLE MEDLEMSKAP ADD medlemsperiode_manuell_vurd VARCHAR2(20 CHAR);
ALTER TABLE MEDLEMSKAP rename column regionForSoker TO REGION_FOR_SOKER;
ALTER TABLE MEDLEMSKAP rename column oppholdsrettVurdering TO OPPHOLDSRETT_VURDERING;
ALTER TABLE MEDLEMSKAP rename column lovligOppholdVurdering TO LOVLIG_OPPHOLD_VURDERING;
ALTER TABLE MEDLEMSKAP rename column bosattVurdering TO BOSATT_VURDERING;

ALTER TABLE MEDLEMSKAP ADD CONSTRAINT FK_MEDLEMSKAP_3 FOREIGN KEY (MEDLEMSPERIODE_MANUELL_VURD) REFERENCES MEDLEMSKAP_MANUELL_VURD_TYPE;

DROP INDEX IDX_MEDLEMSKAP_2;
CREATE INDEX IDX_MEDLEMSKAP_2 ON MEDLEMSKAP(region_for_soker);

COMMENT ON COLUMN MEDLEMSKAP.REGION_FOR_SOKER IS 'Region for søker';
COMMENT ON COLUMN MEDLEMSKAP.OPPHOLDSRETT_VURDERING IS 'True hvis søker har oppholdsrett';
COMMENT ON COLUMN MEDLEMSKAP.LOVLIG_OPPHOLD_VURDERING IS 'True hvis søker har lovlig opphold';
COMMENT ON COLUMN MEDLEMSKAP.BOSATT_VURDERING IS 'True hvis søker er bosatt';

UPDATE AKSJONSPUNKT_DEF set VURDERINGSPUNKT = 'KOFAK.INN' WHERE kode = '5022';

-- Endrer relasjon til REGION til å ligge på BEKREFTET_FORELDRE
ALTER TABLE MEDLEMSKAP DROP CONSTRAINT FK_MEDLEMSKAP_2;
ALTER TABLE MEDLEMSKAP DROP COLUMN region_for_soker;

ALTER TABLE BEKREFTET_FORELDRE ADD region VARCHAR2(20 CHAR);
ALTER TABLE BEKREFTET_FORELDRE ADD CONSTRAINT FK_BEKREFTET_FORELDRE_6 FOREIGN KEY (REGION) REFERENCES REGION ENABLE;
CREATE INDEX IDX_BEKREFTET_FORELDRE_6 ON BEKREFTET_FORELDRE(region);

ALTER TABLE MEDLEMSKAP_PERIODER ADD er_medlem VARCHAR2(1 CHAR);
ALTER TABLE MEDLEMSKAP_PERIODER ADD lovvalgsland VARCHAR2(20 CHAR);
ALTER TABLE MEDLEMSKAP_PERIODER ADD studieland VARCHAR2(20 CHAR);
ALTER TABLE MEDLEMSKAP_PERIODER ADD CONSTRAINT FK_MEDLEMSKAP_PERIODER_5 FOREIGN KEY (lovvalgsland) REFERENCES LANDKODER;
ALTER TABLE MEDLEMSKAP_PERIODER ADD CONSTRAINT FK_MEDLEMSKAP_PERIODER_6 FOREIGN KEY (studieland) REFERENCES LANDKODER;
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.er_medlem IS 'True hvis periode med medlemskap';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.lovvalgsland IS 'Lovvalgsland';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.studieland IS 'Studieland';
