INSERT INTO AKSJONSPUNKT_DEF(KODE, NAVN, AKSJONSPUNKT_KATEGORI, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, ALLTID_TOTRINNSBEHANDLING, FRIST_PERIODE, AKSJONSPUNKT_TYPE)
VALUES ('7004', 'Vent på fødsel', 'APK-004', 'KOFAK.UT', 'Automatisk satt på vent i påvente av fødselsregistrering.', NULL , 'N', 'P3W', 'AUTO');
