UPDATE VILKAR_TYPE
SET NAVN = 'Foreldreansvarsvilkåret 1',
  BESKRIVELSE = 'Foreldreansvarsvilkåret §14-17 andre ledd'
WHERE KODE = 'FP_VK_8';

INSERT INTO VILKAR_TYPE(KODE, NAVN, BESKRIVELSE, OPPRETTET_AV)
VALUES ('FP_VK_9', 'Foreldreansvarsvilkåret 2', 'Foreldreansvarsvilkåret §14-17 fjerde ledd', 'VL');

UPDATE OMSORGSOVERTAKELSE_VILKAR_TYPE
SET KODE = 'FP_VK_5'
WHERE KODE = 'OMSORGSOVERTAKELSE';

UPDATE OMSORGSOVERTAKELSE_VILKAR_TYPE
SET KODE = 'FP_VK_8'
WHERE KODE = 'FORELDREANSVAR_1';

UPDATE OMSORGSOVERTAKELSE_VILKAR_TYPE
SET KODE = 'FP_VK_9'
WHERE KODE = 'FORELDREANSVAR_2';

