CREATE TABLE SAKSOPPLYSNING_METADATA
  (
    ID                      NUMBER (19) NOT NULL ,
    SAKSOPPLYSNING_ID       NUMBER (19) NOT NULL ,
    TAG                     VARCHAR2(50 CHAR) NOT NULL ,
    VALUE                   VARCHAR2(100 CHAR),
    OPPRETTET_AV            VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV               VARCHAR2(20 CHAR),
    ENDRET_TID              TIMESTAMP(3),
    CONSTRAINT SAKSOPPLYSNING_METADATA PRIMARY KEY (ID),
  CONSTRAINT FK_SAKSOPPLYSNING_ID FOREIGN KEY (SAKSOPPLYSNING_ID) REFERENCES SAKSOPPLYSNING(ID)
  );

CREATE SEQUENCE SEQ_SAKSOPPLYSNING_METADATA MINVALUE 1 START WITH 1 INCREMENT BY 50;
  -- 50 er viktig: må være lik Hibernate sin (default) verdi

CREATE INDEX IDX_SAKSOPPL_META_01 ON SAKSOPPLYSNING_METADATA(SAKSOPPLYSNING_ID);
