-- BEHANDLING
COMMENT ON TABLE BEHANDLING IS 'Behandling av fagsak';

-- BEHANDLING_GRUNNLAG
COMMENT ON TABLE BEHANDLING_GRUNNLAG IS 'Grunnlag for en behandling';

--SOEKNAD
COMMENT ON TABLE SOEKNAD IS 'Søknad om foreldrepenger';
COMMENT ON COLUMN SOEKNAD.soeknadsdato IS 'Søknadsdato';
COMMENT ON COLUMN SOEKNAD.foedselsdato_fra_soeknad IS 'Angitt fødselsdato';
COMMENT ON COLUMN SOEKNAD.utstedt_dato_terminbekreftelse IS 'Utstedt dato for terminbekreftelse';
COMMENT ON COLUMN SOEKNAD.termindato_fra_soeknad IS 'Termindato';
COMMENT ON COLUMN SOEKNAD.antall_barn_fra_soeknad IS 'Antall barn';
COMMENT ON COLUMN SOEKNAD.kilde_ref IS 'Kildereferanse';
COMMENT ON COLUMN SOEKNAD.tilleggsopplysninger IS 'Tilleggsopplysninger';
COMMENT ON COLUMN SOEKNAD.adop_omsorgover_dato IS 'Omsorgsovertagelsesdato ved adopsjon';
COMMENT ON COLUMN SOEKNAD.omsorg_omsorgover_dato IS 'Omsorgsovertagelsesdato';
COMMENT ON COLUMN SOEKNAD.elektronisk_registrert IS 'Elektronisk registrert søknad';
COMMENT ON COLUMN SOEKNAD.mottatt_dato IS 'Mottatt dato';

--SOEKNAD_ADOPSJON_BARN
COMMENT ON TABLE SOEKNAD_ADOPSJON_BARN IS 'Fødselsdatoene på barna ved adopsjon';
COMMENT ON COLUMN SOEKNAD_ADOPSJON_BARN.foedselsdato IS 'Fødselsdato for adoptert barn';
COMMENT ON COLUMN SOEKNAD_ADOPSJON_BARN.barn_nummer IS 'Barn nummer i et barnekull';

--SOEKNAD_BARN
COMMENT ON TABLE SOEKNAD_BARN IS 'Fødselsdatoene på barna';
COMMENT ON COLUMN SOEKNAD_BARN.foedselsdato IS 'Fødselsdato for barn';
COMMENT ON COLUMN SOEKNAD_BARN.barn_nummer IS 'Barn nummer i et barnekull';

-- SOEKNAD_ANNEN_PART
COMMENT ON TABLE SOEKNAD_ANNEN_PART IS 'Informasjon om annen part i en søknad';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.aktoer_id IS 'Aktør id';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.utenlandsk_fnr IS 'Utenlandsk fødselsnummer';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.utenlandsk_fnr_land IS 'Land for utenlandsk fødselsnummer';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.aarsak IS 'Årsak';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.begrunnelse IS 'Begrunnelse';
COMMENT ON COLUMN SOEKNAD_ANNEN_PART.type IS 'Mor eller far';

--SOEKNAD_VEDLEGG
COMMENT ON TABLE SOEKNAD_VEDLEGG IS 'Vedlegg til søknad, eks: terminbekreftelse';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.skjemanummer IS 'Skjemanummer på vedlegget';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.tilleggsinfo IS 'Fritekst relatert til vedlegg';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.er_paakrevd_i_soeknadsdialog IS 'Om vedlegget er påkrevd';

--TERMINBEKREFTELSE
COMMENT ON TABLE TERMINBEKREFTELSE IS 'Terminbekreftelse';
COMMENT ON COLUMN TERMINBEKREFTELSE.termindato IS 'Termindato';
COMMENT ON COLUMN TERMINBEKREFTELSE.utstedt_dato IS 'Utstedt dato';
COMMENT ON COLUMN TERMINBEKREFTELSE.antall_barn IS 'Antall barn';
COMMENT ON COLUMN TERMINBEKREFTELSE.kilde_ref IS 'Kildereferanse';

COMMENT ON TABLE PROSESS_TASK is 'Inneholder tasks som skal kjøres i bakgrunnen';
COMMENT ON COLUMN PROSESS_TASK.task_type is 'navn på task. Brukes til å matche riktig implementasjon';
COMMENT ON COLUMN PROSESS_TASK.prioritet is 'prioritet på task.  Høyere tall har høyere prioritet';
COMMENT ON COLUMN PROSESS_TASK.status is 'status på task: KLAR, NYTT_FORSOEK, FEILET, VENTER_SVAR, FERDIG';
COMMENT ON COLUMN PROSESS_TASK.neste_kjoering_etter is 'tasken skal ikke kjøeres før tidspunkt er passert';
COMMENT ON COLUMN PROSESS_TASK.feilede_forsoek is 'antall feilede forsøk';
COMMENT ON COLUMN PROSESS_TASK.siste_kjoering_ts is 'siste gang tasken ble forsøkt kjørt';
COMMENT ON COLUMN PROSESS_TASK.siste_kjoering_feil_kode is 'siste feilkode tasken fikk';
COMMENT ON COLUMN PROSESS_TASK.siste_kjoering_feil_tekst is 'siste feil tasken fikk';
COMMENT ON COLUMN PROSESS_TASK.siste_kjoering_server is 'navn på node som sist kjørte en task (server@pid)';
COMMENT ON COLUMN PROSESS_TASK.task_parametere is 'parametere angitt for en task';
comment on column PROSESS_TASK.task_payload is 'inputdata for en task';
COMMENT ON COLUMN PROSESS_TASK.task_sekvens is 'angir rekkefølge på task innenfor en gruppe ';
COMMENT ON COLUMN PROSESS_TASK.task_gruppe is 'angir en unik id som grupperer flere ';
COMMENT ON COLUMN PROSESS_TASK.versjon is 'angir versjon for optimistisk låsing';

-- COMMENT ON TABLE VEDTAK_RESULTAT_TYPE IS '';

-- COMMENT ON TABLE BEHANDLING_VEDTAK IS '';
-- COMMENT ON COLUMN BEHANDLING_VEDTAK.BEHANDLING_VEDTAK IS '';
-- COMMENT ON COLUMN BEHANDLING_VEDTAK.ANSVARLIG_SAKSBEHANDLER IS '';
-- COMMENT ON COLUMN BEHANDLING_VEDTAK.BEHANDLING_VEDTAK IS '';
-- COMMENT ON COLUMN BEHANDLING_VEDTAK.VEDTAKSDATO IS '';

-- COMMENT ON TABLE LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK_TYPE IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.XML_CLOB IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.BEHANDLING_ID IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN LAGRET_VEDTAK.FAGSAK_ID IS '';

-- COMMENT ON TABLE OPPDRAG_KONTROLL IS '';
-- COMMENT ON COLUMN OPPDRAG_KONTROLL.OPPDRAG_KONTROLL IS '';
-- COMMENT ON COLUMN OPPDRAG_KONTROLL.VENTER_KVITTERING IS '';
-- COMMENT ON COLUMN OPPDRAG_KONTROLL.OPPDRAG_KONTROLL IS '';
-- COMMENT ON COLUMN OPPDRAG_KONTROLL.SAKSNUMMER IS '';

-- COMMENT ON TABLE OKO_AVSTEMMING_115 IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.OKO_AVSTEMMING_115 IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.TIDSPNKT_MELDING IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.OKO_AVSTEMMING_115 IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.NOKKEL_AVSTEMMING IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.OKO_AVSTEMMING_115 IS '';
-- COMMENT ON COLUMN OKO_AVSTEMMING_115.KODE_KOMPONENT IS '';

-- COMMENT ON TABLE FAGSAK_ARSAK_TYPE IS '';

-- COMMENT ON TABLE FAGSAK_YTELSE_TYPE IS '';

-- COMMENT ON TABLE FAGSAK_RELASJON IS '';

-- COMMENT ON TABLE BRUKER_ROLLE_TYPE IS '';

-- COMMENT ON TABLE BRUKER_KJOENN IS '';

-- COMMENT ON TABLE BRUKER IS '';
-- COMMENT ON COLUMN BRUKER.BRUKER IS '';
-- COMMENT ON COLUMN BRUKER.FOEDSELDATO IS '';
-- COMMENT ON COLUMN BRUKER.BRUKER IS '';
-- COMMENT ON COLUMN BRUKER.AKTOER_ID IS '';

-- COMMENT ON TABLE BARN IS '';
-- COMMENT ON COLUMN BARN.FOEDSEL IS '';
-- COMMENT ON COLUMN BARN.ANTALL_BARN_TPS_GJELDER IS '';
-- COMMENT ON COLUMN BARN.FOEDSEL IS '';
-- COMMENT ON COLUMN BARN.ANTALL_BARN IS '';
-- COMMENT ON COLUMN BARN.BEREGNING IS '';
-- COMMENT ON COLUMN BARN.ANTALL_BARN IS '';
-- COMMENT ON COLUMN BARN.BARN IS '';
-- COMMENT ON COLUMN BARN.FOEDSELDATO IS '';
-- COMMENT ON COLUMN BARN.BARN IS '';
-- COMMENT ON COLUMN BARN.NORSK_IDENT IS '';
-- COMMENT ON COLUMN BARN.BARN IS '';
-- COMMENT ON COLUMN BARN.AKTOER_ID IS '';
-- COMMENT ON COLUMN BARN.ADOPSJON_BARN IS '';
-- COMMENT ON COLUMN BARN.SOKNAD_ADOPSJON_BARN_ID IS '';

-- COMMENT ON TABLE FAGSAK_STATUS IS '';

-- COMMENT ON TABLE FAGSAK IS '';
-- COMMENT ON COLUMN FAGSAK.SAKSOPPLYSNING IS '';
-- COMMENT ON COLUMN FAGSAK.FAGSAK_ID IS '';
-- COMMENT ON COLUMN FAGSAK.LAGRET_VEDTAK IS '';
-- COMMENT ON COLUMN FAGSAK.FAGSAK_ID IS '';
-- COMMENT ON COLUMN FAGSAK.FAGSAK IS '';
-- COMMENT ON COLUMN FAGSAK.SAKSNUMMER IS '';

-- COMMENT ON TABLE JOURNALDOKUMENT IS '';

-- COMMENT ON TABLE VURDERINGSPUNKT_DEF IS '';
-- COMMENT ON COLUMN VURDERINGSPUNKT_DEF.VURDERINGSPUNKT_DEF IS '';
-- COMMENT ON COLUMN VURDERINGSPUNKT_DEF.VURDERINGSPUNKT_TYPE IS '';

-- COMMENT ON TABLE BEHANDLING_TYPE IS '';
-- COMMENT ON COLUMN BEHANDLING_TYPE.BEHANDLING_TYPE_STEG_SEKV IS '';
-- COMMENT ON COLUMN BEHANDLING_TYPE.SEKVENS_NR IS '';

-- COMMENT ON TABLE BEHANDLING_TYPE_STEG_SEKV IS '';
-- COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.BEHANDLING_TYPE_STEG_SEKV IS '';
-- COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.SEKVENS_NR IS '';

-- COMMENT ON TABLE OPPGAVE_AARSAK IS '';

-- COMMENT ON TABLE OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT_TID IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT_AV IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.FERDIGSTILT IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.SAKS_ID IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_BEHANDLING_KOBLING IS '';
-- COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_ID IS '';

-- COMMENT ON TABLE FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.KILDE_REF IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.KILDE_SAKSBEHANDLER IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.ANTALL_BARN_TPS_GJELDER IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.ANTALL_BARN IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSEL IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSELSDATO IS '';
-- COMMENT ON COLUMN FOEDSEL.BRUKER IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSELDATO IS '';
-- COMMENT ON COLUMN FOEDSEL.BARN IS '';
-- COMMENT ON COLUMN FOEDSEL.FOEDSELDATO IS '';

-- COMMENT ON TABLE VILKAR_TYPE IS '';

-- COMMENT ON TABLE VILKAR_UTFALL_TYPE IS '';

-- COMMENT ON TABLE VILKAR_RESULTAT_TYPE IS '';

-- COMMENT ON TABLE VILKAR_UTFALL_MERKNAD IS '';

-- COMMENT ON TABLE INNGANGSVILKAR_RESULTAT IS '';

-- COMMENT ON TABLE VILKAR IS '';

-- COMMENT ON TABLE BEREGNING_RESULTAT IS '';

-- COMMENT ON TABLE BEREGNING IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNING IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNET_DATO IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNING IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNET_TILKJENT_YTELSE IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNING IS '';
-- COMMENT ON COLUMN BEREGNING.ANTALL_BARN IS '';
-- COMMENT ON COLUMN BEREGNING.BEREGNING IS '';
-- COMMENT ON COLUMN BEREGNING.SATS_VERDI IS '';

-- COMMENT ON TABLE BEHANDLING_RESULTAT IS '';

-- COMMENT ON TABLE AKTOER_NORSK_IDENT_MAP IS '';
-- COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.AKTOER_NORSK_IDENT_MAP IS '';
-- COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.NORSK_IDENT IS '';
-- COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.AKTOER_NORSK_IDENT_MAP IS '';
-- COMMENT ON COLUMN AKTOER_NORSK_IDENT_MAP.AKTOER_ID IS '';

-- COMMENT ON TABLE PROSESS_TASK_FEILHAND IS '';

-- COMMENT ON TABLE PROSESS_TASK_TYPE IS '';
-- COMMENT ON COLUMN PROSESS_TASK_TYPE.PROSESS_TASK_TYPE IS '';
-- COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_SEK_MELLOM_FORSOEK IS '';
-- COMMENT ON COLUMN PROSESS_TASK_TYPE.PROSESS_TASK_TYPE IS '';
-- COMMENT ON COLUMN PROSESS_TASK_TYPE.FEIL_MAKS_FORSOEK IS '';

-- COMMENT ON TABLE SAKSOPPLYSNING IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING_DOKUMENT IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.DOKUMENT IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.EKSTERN_REFERANSE IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.BEHANDLING_ID IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.SAKSOPPLYSNING IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING.FAGSAK_ID IS '';

-- COMMENT ON TABLE SAKSOPPLYSNING_DOKUMENT IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT.SAKSOPPLYSNING_DOKUMENT IS '';
-- COMMENT ON COLUMN SAKSOPPLYSNING_DOKUMENT.DOKUMENT IS '';

-- COMMENT ON TABLE SAKSOPPLYSNING_KILDE IS '';

-- COMMENT ON TABLE SAKSOPPLYSNING_TYPE IS '';

-- COMMENT ON TABLE SOEKNAD_GJELDER_TYPE IS '';

-- COMMENT ON TABLE SOEKNAD_TYPE IS '';

-- COMMENT ON TABLE FAR_SOEKER_TYPE IS '';

-- COMMENT ON TABLE SPRAAK_KODE IS '';

-- COMMENT ON TABLE DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.SENDT_TID IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.FORHAANDSVIST_TID IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_MAL_NAVN IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_ID IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_DATA.JOURNAL_POST_ID IS '';

-- COMMENT ON TABLE DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.KONTAKT_TELEFON_NUMMER IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.NUMMER_AVSENDER_ENHET IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.NAVN_AVSENDER_ENHET IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_NAVN IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ID IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_GEO_ENHET IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_NAVN IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_NAVN IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_ID IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.AUTOMATISK_BEHANDLET IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_SAKSBEHANDLER_NAVN IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_FELLES IS '';
-- COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS '';

-- COMMENT ON TABLE DOKUMENT_TYPE_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKUMENT_TYPE_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_TYPE_DATA.VERDI IS '';
-- COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKUMENT_TYPE_DATA IS '';
-- COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKSYS_ID IS '';

-- COMMENT ON TABLE OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.SAKSBEH_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAG_GJELDER_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.UTBET_FREKVENS IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.FAGSYSTEM_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_FAGOMRADE IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_ENDRING IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.OKO_OPPDRAG_110 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_110.KODE_AKSJON IS '';

-- COMMENT ON TABLE OKO_OPPDRAG_ENHET_120 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.OKO_OPPDRAG_ENHET_120 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.DATO_ENHET_FOM IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.OKO_OPPDRAG_ENHET_120 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.ENHET IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.OKO_OPPDRAG_ENHET_120 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.TYPE_ENHET IS '';

-- COMMENT ON TABLE OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_DELYTELSE_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_FAGSYSTEM_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.UTBETALES_TIL_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SAKSBEH_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.BRUK_KJORE_PLAN IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.TYPE_SATS IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.FRADRAG_TILLEGG IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SATS IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_KLASSIFIK IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_TOM IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_VEDTAK_FOM IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DELYTELSE_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.VEDTAK_ID IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DATO_STATUS_FOM IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_STATUS_LINJE IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.OKO_OPPDRAG_LINJE_150 IS '';
-- COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.KODE_ENDRING_LINJE IS '';

-- COMMENT ON TABLE OKO_ATTESTANT_180 IS '';
-- COMMENT ON COLUMN OKO_ATTESTANT_180.OKO_ATTESTANT_180 IS '';
-- COMMENT ON COLUMN OKO_ATTESTANT_180.ATTESTANT_ID IS '';
