-- Tabell BEHANDLING_RELATERTE_YTELSER
CREATE TABLE BEHANDLING_REL_YTELSER (
  id                                NUMBER(19) NOT NULL,
  behandling_id                     NUMBER(19) NOT NULL,
  soeker                            VARCHAR2(1 CHAR),
  relatert_ytelse_type              VARCHAR2(20 CHAR) NOT NULL,
  relatert_ytelse_tilstand          VARCHAR2(20 CHAR),
  saksopplysning_kilde              VARCHAR2(20 CHAR),
  ident                             VARCHAR2(20 CHAR) NOT NULL,
  saksnummer                        VARCHAR2(20 CHAR) NOT NULL,
  registreringsdato                 TIMESTAMP(3) NOT NULL,
  relatert_ytelse_tema              VARCHAR2(20 CHAR) NOT NULL,
  relatert_ytelse_behandl_tema      VARCHAR2(20 CHAR) NOT NULL,
  relatert_ytelse_sakstype          VARCHAR2(20 CHAR) NOT NULL,
  relatert_ytelse_status            VARCHAR2(20 CHAR) NOT NULL,
  relatert_ytelse_resultat          VARCHAR2(20 CHAR),
  vedtakDato                        TIMESTAMP(3),
  iverksettelsesDato                TIMESTAMP(3),
  opphoerFomDato                    TIMESTAMP(3),
  opprettet_av                      VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid                     TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av                         VARCHAR2(20 CHAR),
  endret_tid                        TIMESTAMP(3),
  CONSTRAINT PK_BEHANDLING_REL_YTELSER PRIMARY KEY ( id )
);

ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_BEHANDLING_REL_YTELSER_1 FOREIGN KEY ( behandling_id ) REFERENCES BEHANDLING ( id ) ;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_TYPE FOREIGN KEY (relatert_ytelse_type) REFERENCES RELATERT_YTELSE_TYPE;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_TILSTAND FOREIGN KEY (relatert_ytelse_tilstand) REFERENCES RELATERT_YTELSE_TILSTAND;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_SAKSOPPLYSNING_KILDE FOREIGN KEY (saksopplysning_kilde) REFERENCES SAKSOPPLYSNING_KILDE;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_TEMA FOREIGN KEY (relatert_ytelse_tema) REFERENCES RELATERT_YTELSE_TEMA;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_BEHANDLTEMA FOREIGN KEY (relatert_ytelse_behandl_tema) REFERENCES RELATERT_YTELSE_BEHANDLTEMA;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_SAKSTYPE FOREIGN KEY (relatert_ytelse_sakstype) REFERENCES RELATERT_YTELSE_SAKSTYPE;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_STATUS FOREIGN KEY (relatert_ytelse_status) REFERENCES RELATERT_YTELSE_STATUS;
ALTER TABLE BEHANDLING_REL_YTELSER ADD CONSTRAINT FK_RELATERT_YTELSE_RESULTAT FOREIGN KEY (relatert_ytelse_resultat) REFERENCES RELATERT_YTELSE_RESULTAT;

CREATE SEQUENCE SEQ_BEHANDLING_REL_YTELSER MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
