/*INSERT*/
INSERT INTO KODELISTE (id, kodeverk, kode, beskrivelse, gyldig_fom, EKSTRA_DATA) 
VALUES  (seq_kodeliste.nextval, 'VILKAR_TYPE', 'FP_VK_16','Adopsjonsvilkåret Foreldrepenger', 
to_date('2000-01-01', 'YYYY-MM-DD'),'{ "fagsakYtelseType" : { "FP" : { "kategori": "vilkår", "lovreferanse": "§ 14-5, 1. ledd" } } }');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn) 
VALUES  (seq_kodeliste.nextval, 'VILKAR_TYPE', 'FP_VK_16','NB', 'Adopsjonsvilkåret Foreldrepenger');

/*UPDATE*/
UPDATE KODELISTE_RELASJON SET KODE1 = 'FP_VK_16' WHERE KODE1 = 'FP_VK_16_1' OR KODE1 = 'FP_VK_16_3'; 
UPDATE AKSJONSPUNKT_DEF SET VILKAR_TYPE = 'FP_VK_16' WHERE VILKAR_TYPE = 'FP_VK_16_1' OR VILKAR_TYPE = 'FP_VK_16_3'; 

UPDATE VILKAR SET VILKAR_TYPE = 'FP_VK_16' WHERE VILKAR_TYPE = 'FP_VK_16_1' OR VILKAR_TYPE = 'FP_VK_16_3';

/*DELETE*/
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODE = 'FP_VK_16_3' AND KL_KODEVERK = 'VILKAR_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODE = 'FP_VK_16_1' AND KL_KODEVERK = 'VILKAR_TYPE';
DELETE FROM KODELISTE WHERE KODE = 'FP_VK_16_3' AND KODEVERK = 'VILKAR_TYPE';
DELETE FROM KODELISTE WHERE KODE = 'FP_VK_16_1' AND KODEVERK = 'VILKAR_TYPE';
