-- migrering script for samtidig uttak.
UPDATE YF_FORDELING_PERIODE SET SAMTIDIG_UTTAK = 'N'  WHERE SAMTIDIG_UTTAK = '0';
UPDATE YF_FORDELING_PERIODE SET SAMTIDIG_UTTAK = 'N'  WHERE SAMTIDIG_UTTAK IS NULL;
UPDATE YF_FORDELING_PERIODE SET SAMTIDIG_UTTAK = 'J'  WHERE SAMTIDIG_UTTAK = '1';

ALTER TABLE YF_FORDELING_PERIODE MODIFY SAMTIDIG_UTTAK NOT NULL;
ALTER TABLE YF_FORDELING_PERIODE add constraint CHK_SAMTIDIG_UTTAK check (SAMTIDIG_UTTAK in ('J', 'N'));
