ALTER TABLE OPPDRAG_KONTROLL ADD simulering VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;

ALTER TABLE OPPDRAG_KONTROLL ADD CONSTRAINT CHK_OPPDRAG_KONTROLL_01 CHECK (simulering IN ('J', 'N'));

COMMENT on column OPPDRAG_KONTROLL.simulering is 'Gjelder oppdragskontroll simulering?';
