alter table YF_FORDELING_PERIODE MODIFY FORDELING_PERIODE_KILDE DEFAULT 'SØKNAD' NOT NULL;
alter table YF_FORDELING_PERIODE MODIFY KL_FORDELING_PERIODE_KILDE NOT NULL;

comment on column YF_FORDELING_PERIODE.KL_FORDELING_PERIODE_KILDE is 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

update YF_FORDELING_PERIODE set FORDELING_PERIODE_KILDE = 'SØKNAD' where FORDELING_PERIODE_KILDE = '-';
update KODELISTE set GYLDIG_TOM = to_date('2018-10-03', 'YYYY-MM - DD') where kodeverk = 'FORDELING_PERIODE_KILDE' and kode = '-';
