--opprett totrinnsvurderinger hvis de ikke eksisterer allerede.
INSERT INTO TOTRINNSVURDERING (ID, BEHANDLING_ID, AKSJONSPUNKT_DEF, GODKJENT, BEGRUNNELSE, OPPRETTET_AV)
  SELECT
    SEQ_TOTRINNSVURDERING.nextval   AS ID,
    aks.BEHANDLING_ID               AS BEHANDLING_ID,
    aks.AKSJONSPUNKT_DEF            AS AKSJONSPUNKT_DEF,
    aks.TOTRINN_BEHANDLING_GODKJENT AS TOTRINN_BEHANDLING_GODKJENT,
    aks.BESLUTTERS_BEGRUNNELSE      AS BESLUTTERS_BEGRUNNELSE,
    'MIGRERING_VL'                  AS OPPRETTET_AV
  FROM AKSJONSPUNKT aks
    INNER JOIN BEHANDLING beh ON beh.ID = aks.BEHANDLING_ID
  WHERE
    beh.BEHANDLING_STATUS != 'AVSLU' AND
    beh.BEHANDLING_STATUS != 'IVED' AND
    beh.TOTRINNSBEHANDLING = 1 AND
    aks.TOTRINN_BEHANDLING = 'J' AND
    aks.TOTRINN_BEHANDLING_GODKJENT IS NOT NULL
    AND (SELECT count(*)
         FROM TOTRINNSVURDERING tot
         WHERE tot.BEHANDLING_ID = aks.BEHANDLING_ID
               AND tot.AKSJONSPUNKT_DEF = aks.AKSJONSPUNKT_DEF
               AND tot.AKTIV = 'J') = 0;

--migrer årsaker
INSERT INTO VURDER_AARSAK_TTVURDERING (ID, AARSAK_TYPE, TOTRINNSVURDERING_ID)
  SELECT
    SEQ_VURDER_AARSAK_TTVURDERING.NEXTVAL AS ID,
    AARSAK_TYPE,
    TOTRINNSVURDERING_ID
  FROM (SELECT
          arsak.AARSAK_TYPE AS AARSAK_TYPE,
          tot.ID            AS TOTRINNSVURDERING_ID
        FROM VURDER_PAA_NYTT_AARSAK arsak
          INNER JOIN AKSJONSPUNKT aks ON arsak.AKSJONSPUNKT_ID = aks.ID
          INNER JOIN BEHANDLING beh ON beh.ID = aks.BEHANDLING_ID
          INNER JOIN TOTRINNSVURDERING tot ON beh.ID = tot.BEHANDLING_ID
        WHERE beh.BEHANDLING_STATUS != 'AVSLU'
              AND beh.BEHANDLING_STATUS != 'IVED'
              AND tot.AKTIV = 'J'
              AND tot.BEHANDLING_ID = aks.BEHANDLING_ID
              AND tot.AKSJONSPUNKT_DEF = aks.AKSJONSPUNKT_DEF
              AND tot.OPPRETTET_AV = 'MIGRERING_VL'
  );

-- logisk sletting av kolonner fra aksjonspunkt tabell
ALTER TABLE AKSJONSPUNKT SET UNUSED (BESLUTTERS_BEGRUNNELSE, TOTRINN_BEHANDLING_GODKJENT);

-- slett vurder-på-nytt-aarsak tabell
DROP TABLE VURDER_PAA_NYTT_AARSAK CASCADE CONSTRAINTS;

-- slett sequence
DROP SEQUENCE SEQ_VURDER_PAA_NYTT_AARSAK;


