-- Retter skrivefeil i KODELISTE
UPDATE KODELISTE SET BESKRIVELSE = '§14-2: Opphør medlemskap' WHERE KODEVERK = 'IKKE_OPPFYLT_AARSAK' and KODE = '4087';

-- retter skrivefeil i KODELISTE_NAVN_I18N
UPDATE KODELISTE_NAVN_I18N SET NAVN = '§14-2: Opphør medlemskap' WHERE KL_KODEVERK = 'IKKE_OPPFYLT_AARSAK' and KL_KODE = '4087';
