DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OVERFOERING_AARSAK_TYPE' AND KL_KODE = 'IKKE_RETT_ANNEN_FORELDER';
DELETE FROM KODELISTE WHERE KODEVERK = 'OVERFOERING_AARSAK_TYPE' AND KODE = 'IKKE_RETT_ANNEN_FORELDER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'OVERFOERING_AARSAK_TYPE' AND KL_KODE = 'ALENEOMSORG';
DELETE FROM KODELISTE WHERE KODEVERK = 'OVERFOERING_AARSAK_TYPE' AND KODE = 'ALENEOMSORG';
