INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'VIRKSOMHET_TYPE', 'FISKE', 'INNTEKTSKATEGORI', 'FISKER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'VIRKSOMHET_TYPE', 'FRILANSER', 'INNTEKTSKATEGORI', 'FRILANSER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'VIRKSOMHET_TYPE', 'JORDBRUK_SKOGBRUK', 'INNTEKTSKATEGORI', 'JORDBRUKER', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
INSERT INTO KODELISTE_RELASJON(ID, KODEVERK1, KODE1, KODEVERK2, KODE2, GYLDIG_FOM, GYLDIG_TOM)
values(seq_kodeliste_relasjon.nextval, 'VIRKSOMHET_TYPE', 'DAGMAMMA', 'INNTEKTSKATEGORI', 'DAGMAMMA', to_date('01.01.2000', 'DD.MM.YYYY'), to_date('31.12.9999', 'DD.MM.YYYY'));
