ALTER TABLE MOTTATT_DOKUMENT ADD DOKUMENT_KATEGORI varchar2(100 char);
update mottatt_dokument set dokument_kategori='-';
update mottatt_dokument set dokument_kategori='SOKN' where type='SØKNAD_ENGANGSSTØNAD_FØDSEL';
update mottatt_dokument set dokument_kategori='SOKN' where type='SØKNAD_ENGANGSSTØNAD_ADOPSJON';
update mottatt_dokument set dokument_kategori='KLGA' where type='KLAGE_DOKUMENT';
ALTER TABLE MOTTATT_DOKUMENT MODIFY DOKUMENT_KATEGORI NOT NULL;

ALTER TABLE MOTTATT_DOKUMENT ADD KL_DOKUMENT_KATEGORI varchar2(100 char) AS ('DOKUMENT_KATEGORI');
ALTER TABLE MOTTATT_DOKUMENT
  ADD CONSTRAINT FK_MOTTATT_DOKUMENT_03 FOREIGN KEY (KL_DOKUMENT_KATEGORI, DOKUMENT_KATEGORI) REFERENCES KODELISTE (kodeverk, kode);

CREATE INDEX IDX_MOTTATT_DOKUMENT_2 ON MOTTATT_DOKUMENT(DOKUMENT_KATEGORI);

COMMENT ON COLUMN MOTTATT_DOKUMENT.DOKUMENT_KATEGORI IS 'Dokumentkategori';
COMMENT ON COLUMN MOTTATT_DOKUMENT.KL_DOKUMENT_KATEGORI IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

