DELETE FROM KODELISTE
where KODEVERK = 'OPPGAVE_AARSAK' and KODE = 'BEH_SAK';

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'VENT_AARSAK', 'VENT_INNTEKT_RAPPORTERINGSFRIST', 'NB', 'Inntekt rapporteringsfrist');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'HISTORIKKINNSLAG_TYPE', 'BEH_OPPDATERT_NYE_OPPL', 'NB', 'Behandlingen oppdatert med nye opplysninger');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'HISTORIKKINNSLAG_TYPE', 'SPOLT_TILBAKE', 'NB', 'Behandlingen er flyttet');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'HISTORIKK_ENDRET_FELT_TYPE', 'DAGPENGER_INNTEKT', 'NB', 'Dagpenger');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'FAKTA_OM_BEREGNING_TILFELLE', 'VURDER_AT_OG_FL_I_SAMME_ORGANISASJON', 'NB', 'Vurder om bruker er arbeidstaker og frilanser i samme organisasjon');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'FAKTA_OM_BEREGNING_TILFELLE', 'FASTSETT_BESTEBEREGNING_FØDENDE_KVINNE', 'NB', 'Fastsett besteberegning fødende kvinne');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'RELATERT_YTELSE_STATUS', 'xx', 'NB', 'Ingen verdi');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'BEHANDLING_TYPE', '-', 'NB', 'Udefinert');

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'KONFIG_VERDI_TYPE', 'DATE', 'NB', 'Dato');
