DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_AARSAK' AND KL_KODE='RE-KLAG';

-- Migrere RE-KLAG til RE-KLAG-U-INNTK
UPDATE BEHANDLING_ARSAK set BEHANDLING_ARSAK_TYPE='RE-KLAG-U-INNTK' WHERE BEHANDLING_ARSAK_TYPE='RE-KLAG';
UPDATE HISTORIKKINNSLAG_FELT set TIL_VERDI_KODE='RE-KLAG-U-INNTK' WHERE TIL_VERDI_KODE='RE-KLAG';

DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_AARSAK' AND KODE='RE-KLAG';
