UPDATE UTTAK_RESULTAT_PERIODE SET GRADERING_AVSLAG_AARSAK = '4504' WHERE GRADERING_AVSLAG_AARSAK = '4519';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'GRADERING_AVSLAG_AARSAK' AND KL_KODE = '4519';
DELETE FROM KODELISTE WHERE KODEVERK = 'GRADERING_AVSLAG_AARSAK' AND KODE = '4519';
