UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Selvstendig næringsdrivende - Jordbruker'
where KL_KODEVERK = 'INNTEKTSKATEGORI'
  and KL_KODE = 'JORDBRUKER';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Selvstendig næringsdrivende (fisker)'
where KL_KODEVERK = 'INNTEKTSKATEGORI'
  and KL_KODE = 'FISKER';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Selvstendig næringsdrivende (dagmamma)'
where KL_KODEVERK = 'INNTEKTSKATEGORI'
  and KL_KODE = 'DAGMAMMA';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Dagpenger'
where KL_KODEVERK = 'RELATERT_YTELSE_TYPE'
  and KL_KODE = 'DAGPENGER';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Dagpenger'
where KL_KODEVERK = 'INNTEKTSKATEGORI'
  and KL_KODE = 'DAGPENGER';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Dagpenger'
where KL_KODEVERK = 'OPPTJENING_AKTIVITET_TYPE'
  and KL_KODE = 'DAGPENGER';

UPDATE KODELISTE_NAVN_I18N
set NAVN = 'Arbeidstaker - Sjømann'
where KL_KODEVERK = 'INNTEKTSKATEGORI'
  and KL_KODE = 'SJØMANN';
