ALTER TABLE GR_ARBEID_INNTEKT DROP COLUMN IAY_REGISTER_ETTER_ID;
ALTER TABLE GR_ARBEID_INNTEKT DROP COLUMN IAY_SAKSBEHANDLET_ETTER_ID;

ALTER TABLE GR_ARBEID_INNTEKT RENAME COLUMN IAY_REGISTER_FØR_ID TO REGISTER_ID;
ALTER TABLE GR_ARBEID_INNTEKT RENAME COLUMN IAY_SAKSBEHANDLET_FØR_ID TO SAKSBEHANDLET_ID;
