ALTER TABLE TOTRINNRESULTATGRUNNLAG DROP CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_5;

ALTER TABLE TOTRINNRESULTATGRUNNLAG ADD CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_5 FOREIGN KEY ( beregningsgrunnlag_id ) REFERENCES BEREGNINGSGRUNNLAG ( id );
