ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD (
  arbeidsgiver_aktor_id VARCHAR2(100 CHAR),
  arbeidsgiver_virksomhet_id NUMBER(19,0)
  );

ALTER TABLE BEREGNINGSRESULTAT_ANDEL
  ADD CONSTRAINT FK_BEREGNINGSRESULTAT_ANDEL_3 FOREIGN KEY (arbeidsgiver_virksomhet_id) REFERENCES VIRKSOMHET (id);

CREATE INDEX IDX_BEREGNINGSRESULTAT_ANDEL_6
  ON BEREGNINGSRESULTAT_ANDEL (arbeidsgiver_virksomhet_id);

COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.arbeidsgiver_aktor_id IS 'Arbeidsgivers aktør id.';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.arbeidsgiver_virksomhet_id IS 'Arbeidsgivers virksomhet.';

