insert into KODELISTE (ID,KODEVERK, KODE) values (SEQ_KODELISTE.NEXTVAL,'OPPGAVE_AARSAK','SETTVENT_STO');
insert into KODELISTE_NAVN_I18N (ID, KL_KODEVERK,KL_KODE,NAVN, SPRAK) values (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'OPPGAVE_AARSAK','SETTVENT_STO','Sett Arena utbetaling på vent','NB');
