UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1Y"}' WHERE KODE = 'INNFS' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
UPDATE KODELISTE SET  EKSTRA_DATA = '{"periode":"P1Y"}' WHERE KODE = 'PREMGR' AND KODEVERK = 'INNTEKT_PERIODE_TYPE';
