ALTER TABLE UTTAK_RESULTAT_PERIODE ADD MANUELT_BEHANDLET CHAR DEFAULT 'N' NOT NULL CHECK (MANUELT_BEHANDLET IN ('J', 'N'));

UPDATE UTTAK_RESULTAT_PERIODE SET MANUELT_BEHANDLET = 'J' WHERE BEGRUNNELSE IS NOT NULL;

COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.MANUELT_BEHANDLET IS 'Om perioden har blitt manuelt behandlet eller ikke'
