ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD ADD SAMTIDIG_UTTAKSPROSENT NUMBER(5, 2);
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.SAMTIDIG_UTTAKSPROSENT IS 'Samtidig uttaksprosent fra søknaden';

update UTTAK_RESULTAT_PERIODE_SOKNAD set SAMTIDIG_UTTAKSPROSENT = 10.00 where SAMTIDIG_UTTAK = 'J';
