ALTER TABLE AKSJONSPUNKT_DEF
  ADD TILBAKEHOPP_VED_GJENOPPTAKEL2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE AKSJONSPUNKT_DEF
SET TILBAKEHOPP_VED_GJENOPPTAKEL2 = TILBAKEHOPP_VED_GJENOPPTAKELSE;
COMMIT;
ALTER TABLE AKSJONSPUNKT_DEF
  DROP COLUMN TILBAKEHOPP_VED_GJENOPPTAKELSE;
ALTER TABLE AKSJONSPUNKT_DEF
  RENAME COLUMN TILBAKEHOPP_VED_GJENOPPTAKEL2 TO TILBAKEHOPP_VED_GJENOPPTAKELSE;

ALTER TABLE BEHANDLING
  ADD totrinnsbehandling2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE BEHANDLING
SET totrinnsbehandling2 = totrinnsbehandling;
COMMIT;
ALTER TABLE BEHANDLING
  DROP COLUMN totrinnsbehandling;
ALTER TABLE BEHANDLING
  RENAME COLUMN totrinnsbehandling2 TO totrinnsbehandling;

ALTER TABLE BEHANDLING_VEDTAK
  ADD BESLUTNING2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE BEHANDLING_VEDTAK
SET BESLUTNING2 = BESLUTNING;
COMMIT;
ALTER TABLE BEHANDLING_VEDTAK
  DROP COLUMN BESLUTNING;
ALTER TABLE BEHANDLING_VEDTAK
  RENAME COLUMN BESLUTNING2 TO BESLUTNING;

ALTER TABLE BEREGNING
  ADD overstyrt2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE BEREGNING
SET overstyrt2 = overstyrt;
COMMIT;
ALTER TABLE BEREGNING
  DROP COLUMN overstyrt;
ALTER TABLE BEREGNING
  RENAME COLUMN overstyrt2 TO overstyrt;

ALTER TABLE BEREGNING_RESULTAT
  ADD overstyrt2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE BEREGNING_RESULTAT
SET overstyrt2 = overstyrt;
COMMIT;
ALTER TABLE BEREGNING_RESULTAT
  DROP COLUMN overstyrt;
ALTER TABLE BEREGNING_RESULTAT
  RENAME COLUMN overstyrt2 TO overstyrt;

ALTER TABLE BEREGNINGSRESULTAT_ANDEL
  ADD bruker_er_mottaker2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE BEREGNINGSRESULTAT_ANDEL
SET bruker_er_mottaker2 = bruker_er_mottaker;
COMMIT;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL
  DROP COLUMN bruker_er_mottaker;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL
  RENAME COLUMN bruker_er_mottaker2 TO bruker_er_mottaker;

ALTER TABLE BG_PR_STATUS_OG_ANDEL
  ADD lønnsendring_i_perioden2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE BG_PR_STATUS_OG_ANDEL
SET lønnsendring_i_perioden2 = lønnsendring_i_perioden;
COMMIT;
ALTER TABLE BG_PR_STATUS_OG_ANDEL
  DROP COLUMN lønnsendring_i_perioden;
ALTER TABLE BG_PR_STATUS_OG_ANDEL
  RENAME COLUMN lønnsendring_i_perioden2 TO lønnsendring_i_perioden;

ALTER TABLE br_feriepenger
  ADD feriepenger_periode_tom2 DATE;
UPDATE br_feriepenger
SET feriepenger_periode_tom2 = trunc(FERIEPENGER_PERIODE_TOM);
COMMIT;
ALTER TABLE br_feriepenger
  DROP COLUMN feriepenger_periode_tom;
ALTER TABLE br_feriepenger
  RENAME COLUMN feriepenger_periode_tom2 TO feriepenger_periode_tom;

ALTER TABLE br_feriepenger
  ADD feriepenger_periode_fom2 DATE;
UPDATE br_feriepenger
SET feriepenger_periode_fom2 = trunc(FERIEPENGER_PERIODE_FOM);
COMMIT;
ALTER TABLE br_feriepenger
  DROP COLUMN feriepenger_periode_fom;
ALTER TABLE br_feriepenger
  RENAME COLUMN feriepenger_periode_fom2 TO feriepenger_periode_fom;

ALTER TABLE DOKUMENT_FELLES
  ADD saksnummer2 VARCHAR2(19 CHAR);
UPDATE DOKUMENT_FELLES
SET saksnummer2 = saksnummer;
COMMIT;
ALTER TABLE DOKUMENT_FELLES
  DROP COLUMN saksnummer;
ALTER TABLE DOKUMENT_FELLES
  RENAME COLUMN saksnummer2 TO saksnummer;
ALTER TABLE DOKUMENT_FELLES
  MODIFY (saksnummer NOT NULL);


ALTER TABLE DOKUMENT_FELLES
  ADD dokument_dato2 DATE;
UPDATE DOKUMENT_FELLES
SET dokument_dato2 = trunc(dokument_dato);
COMMIT;
ALTER TABLE DOKUMENT_FELLES
  DROP COLUMN dokument_dato;
ALTER TABLE DOKUMENT_FELLES
  RENAME COLUMN dokument_dato2 TO dokument_dato;
ALTER TABLE DOKUMENT_FELLES
  MODIFY (dokument_dato NOT NULL);

ALTER TABLE IAY_RELATERT_YTELSE
  ADD saksnummer2 VARCHAR2(19 CHAR);
UPDATE IAY_RELATERT_YTELSE
SET saksnummer2 = saksnummer;
COMMIT;
ALTER TABLE IAY_RELATERT_YTELSE
  DROP COLUMN saksnummer;
ALTER TABLE IAY_RELATERT_YTELSE
  RENAME COLUMN saksnummer2 TO saksnummer;

ALTER TABLE OPPGAVE_BEHANDLING_KOBLING
  ADD saksnummer2 VARCHAR2(19 CHAR);
UPDATE OPPGAVE_BEHANDLING_KOBLING
SET saksnummer2 = saksnummer;
COMMIT;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING
  DROP COLUMN saksnummer;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING
  RENAME COLUMN saksnummer2 TO saksnummer;
ALTER TABLE OPPGAVE_BEHANDLING_KOBLING
  MODIFY (saksnummer NOT NULL);

ALTER TABLE OPPDRAG_KONTROLL
  ADD saksnummer2 VARCHAR2(19 CHAR);
UPDATE OPPDRAG_KONTROLL
SET saksnummer2 = saksnummer;
COMMIT;
ALTER TABLE OPPDRAG_KONTROLL
  DROP COLUMN saksnummer;
ALTER TABLE OPPDRAG_KONTROLL
  RENAME COLUMN saksnummer2 TO saksnummer;
ALTER TABLE OPPDRAG_KONTROLL
  MODIFY (saksnummer NOT NULL);

ALTER TABLE FAGSAK
  ADD saksnummer2 VARCHAR2(19 CHAR);
UPDATE FAGSAK
SET saksnummer2 = saksnummer;
COMMIT;
ALTER TABLE FAGSAK
  DROP COLUMN saksnummer;
ALTER TABLE FAGSAK
  RENAME COLUMN saksnummer2 TO saksnummer;

ALTER TABLE FH_FAMILIE_HENDELSE
  ADD mor_for_syk_ved_fodsel2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE FH_FAMILIE_HENDELSE
SET mor_for_syk_ved_fodsel2 = mor_for_syk_ved_fodsel;
COMMIT;
ALTER TABLE FH_FAMILIE_HENDELSE
  DROP COLUMN mor_for_syk_ved_fodsel;
ALTER TABLE FH_FAMILIE_HENDELSE
  RENAME COLUMN mor_for_syk_ved_fodsel2 TO mor_for_syk_ved_fodsel;

ALTER TABLE GR_MEDLEMSKAP
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_MEDLEMSKAP
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_MEDLEMSKAP
  DROP COLUMN aktiv;
ALTER TABLE GR_MEDLEMSKAP
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_YTELSES_FORDELING
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_YTELSES_FORDELING
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_YTELSES_FORDELING
  DROP COLUMN aktiv;
ALTER TABLE GR_YTELSES_FORDELING
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_ARBEID_INNTEKT
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_ARBEID_INNTEKT
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_ARBEID_INNTEKT
  DROP COLUMN aktiv;
ALTER TABLE GR_ARBEID_INNTEKT
  RENAME COLUMN aktiv2 TO aktiv;


ALTER TABLE OPPTJENING
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE OPPTJENING
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE OPPTJENING
  DROP COLUMN aktiv;
ALTER TABLE OPPTJENING
  RENAME COLUMN aktiv2 TO aktiv;


ALTER TABLE UTTAK_RESULTAT
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE UTTAK_RESULTAT
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE UTTAK_RESULTAT
  DROP COLUMN aktiv;
ALTER TABLE UTTAK_RESULTAT
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE TOTRINNSVURDERING
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE TOTRINNSVURDERING
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE TOTRINNSVURDERING
  DROP COLUMN aktiv;
ALTER TABLE TOTRINNSVURDERING
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE UTTAK_RESULTAT
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE UTTAK_RESULTAT
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE UTTAK_RESULTAT
  DROP COLUMN aktiv;
ALTER TABLE UTTAK_RESULTAT
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_VERGE
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_VERGE
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_VERGE
  DROP COLUMN aktiv;
ALTER TABLE GR_VERGE
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_MEDLEMSKAP
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_MEDLEMSKAP
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_MEDLEMSKAP
  DROP COLUMN aktiv;
ALTER TABLE GR_MEDLEMSKAP
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE RES_BEREGNINGSRESULTAT_FP
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE RES_BEREGNINGSRESULTAT_FP
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE RES_BEREGNINGSRESULTAT_FP
  DROP COLUMN aktiv;
ALTER TABLE RES_BEREGNINGSRESULTAT_FP
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_MEDLEMSKAP_VILKAR_PERIODE
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_MEDLEMSKAP_VILKAR_PERIODE
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_MEDLEMSKAP_VILKAR_PERIODE
  DROP COLUMN aktiv;
ALTER TABLE GR_MEDLEMSKAP_VILKAR_PERIODE
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_BEREGNINGSGRUNNLAG
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_BEREGNINGSGRUNNLAG
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_BEREGNINGSGRUNNLAG
  DROP COLUMN aktiv;
ALTER TABLE GR_BEREGNINGSGRUNNLAG
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE FAGSAK_RELASJON
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE FAGSAK_RELASJON
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE FAGSAK_RELASJON
  DROP COLUMN aktiv;
ALTER TABLE FAGSAK_RELASJON
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE TOTRINNRESULTATGRUNNLAG
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE TOTRINNRESULTATGRUNNLAG
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE TOTRINNRESULTATGRUNNLAG
  DROP COLUMN aktiv;
ALTER TABLE TOTRINNRESULTATGRUNNLAG
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE GR_PERSONOPPLYSNING
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE GR_PERSONOPPLYSNING
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE GR_PERSONOPPLYSNING
  DROP COLUMN aktiv;
ALTER TABLE GR_PERSONOPPLYSNING
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE INNSYN_DOKUMENT
  ADD fikk_innsyn2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE INNSYN_DOKUMENT
SET fikk_innsyn2 = fikk_innsyn;
COMMIT;
ALTER TABLE INNSYN_DOKUMENT
  DROP COLUMN fikk_innsyn;
ALTER TABLE INNSYN_DOKUMENT
  RENAME COLUMN fikk_innsyn2 TO fikk_innsyn;

ALTER TABLE JOURNALPOST
  ADD journalpost_id2 VARCHAR2(20 CHAR);
UPDATE JOURNALPOST
SET journalpost_id2 = journalpost_id;
COMMIT;
ALTER TABLE JOURNALPOST
  DROP COLUMN journalpost_id;
ALTER TABLE JOURNALPOST
  RENAME COLUMN journalpost_id2 TO journalpost_id;
ALTER TABLE JOURNALPOST
  MODIFY (journalpost_id NOT NULL);

ALTER TABLE KODEVERK
  ADD kodeverk_synk_eksisterende2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE KODEVERK
SET kodeverk_synk_eksisterende2 = kodeverk_synk_eksisterende;
COMMIT;
ALTER TABLE KODEVERK
  DROP COLUMN kodeverk_synk_eksisterende;
ALTER TABLE KODEVERK
  RENAME COLUMN kodeverk_synk_eksisterende2 TO kodeverk_synk_eksisterende;

ALTER TABLE KODEVERK
  ADD kodeverk_synk_nye2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE KODEVERK
SET kodeverk_synk_nye2 = kodeverk_synk_nye;
COMMIT;
ALTER TABLE KODEVERK
  DROP COLUMN kodeverk_synk_nye;
ALTER TABLE KODEVERK
  RENAME COLUMN kodeverk_synk_nye2 TO kodeverk_synk_nye;

ALTER TABLE KODEVERK
  ADD sammensatt2 VARCHAR2(1 CHAR) DEFAULT 'N';
UPDATE KODEVERK
SET sammensatt2 = sammensatt;
COMMIT;
ALTER TABLE KODEVERK
  DROP COLUMN sammensatt;
ALTER TABLE KODEVERK
  RENAME COLUMN sammensatt2 TO sammensatt;

ALTER TABLE OKO_OPPDRAG_110
  ADD fagsystem_id2 NUMBER(19);
UPDATE OKO_OPPDRAG_110
SET fagsystem_id2 = fagsystem_id;
COMMIT;
ALTER TABLE OKO_OPPDRAG_110
  DROP COLUMN fagsystem_id;
ALTER TABLE OKO_OPPDRAG_110
  RENAME COLUMN fagsystem_id2 TO fagsystem_id;
ALTER TABLE OKO_OPPDRAG_110
  MODIFY (fagsystem_id NOT NULL);

ALTER TABLE OKO_OPPDRAG_LINJE_150
  ADD delytelse_id2 NUMBER(19);
UPDATE OKO_OPPDRAG_LINJE_150
SET delytelse_id2 = delytelse_id;
COMMIT;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  DROP COLUMN delytelse_id;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  RENAME COLUMN delytelse_id2 TO delytelse_id;

ALTER TABLE OKO_OPPDRAG_LINJE_150
  ADD henvisning2 NUMBER(19);
UPDATE OKO_OPPDRAG_LINJE_150
SET henvisning2 = henvisning;
COMMIT;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  DROP COLUMN henvisning;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  RENAME COLUMN henvisning2 TO henvisning;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  MODIFY (henvisning NOT NULL);

ALTER TABLE OKO_OPPDRAG_LINJE_150
  ADD ref_delytelse_id2 NUMBER(19);
UPDATE OKO_OPPDRAG_LINJE_150
SET ref_delytelse_id2 = ref_delytelse_id;
COMMIT;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  DROP COLUMN ref_delytelse_id;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  RENAME COLUMN ref_delytelse_id2 TO ref_delytelse_id;

ALTER TABLE OKO_OPPDRAG_LINJE_150
  ADD ref_fagsystem_id2 NUMBER(19);
UPDATE OKO_OPPDRAG_LINJE_150
SET ref_fagsystem_id2 = ref_fagsystem_id;
COMMIT;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  DROP COLUMN ref_fagsystem_id;
ALTER TABLE OKO_OPPDRAG_LINJE_150
  RENAME COLUMN ref_fagsystem_id2 TO ref_fagsystem_id;

ALTER TABLE SOEKNAD_VEDLEGG
  ADD VEDLEGG_PAKREVD2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE SOEKNAD_VEDLEGG
SET VEDLEGG_PAKREVD2 = VEDLEGG_PAKREVD;
COMMIT;
ALTER TABLE SOEKNAD_VEDLEGG
  DROP COLUMN VEDLEGG_PAKREVD;
ALTER TABLE SOEKNAD_VEDLEGG
  RENAME COLUMN VEDLEGG_PAKREVD2 TO VEDLEGG_PAKREVD;

ALTER TABLE UTTAK_RESULTAT_DOK_REGEL
  ADD til_manuell_behandling2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_DOK_REGEL
SET til_manuell_behandling2 = til_manuell_behandling;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_DOK_REGEL
  DROP COLUMN til_manuell_behandling;
ALTER TABLE UTTAK_RESULTAT_DOK_REGEL
  RENAME COLUMN til_manuell_behandling2 TO til_manuell_behandling;

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD flerbarnsdager2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE
SET flerbarnsdager2 = flerbarnsdager;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN flerbarnsdager;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN flerbarnsdager2 TO flerbarnsdager;

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD gradering_innvilget2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE
SET gradering_innvilget2 = gradering_innvilget;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN gradering_innvilget;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN gradering_innvilget2 TO gradering_innvilget;

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD manuelt_behandlet2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE
SET manuelt_behandlet2 = manuelt_behandlet;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN manuelt_behandlet;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN manuelt_behandlet2 TO manuelt_behandlet;

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD samtidig_uttak2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE
SET samtidig_uttak2 = samtidig_uttak;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN samtidig_uttak;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN samtidig_uttak2 TO samtidig_uttak;

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD fom2 DATE;
UPDATE UTTAK_RESULTAT_PERIODE
SET fom2 = trunc(fom);
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN fom;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN fom2 TO fom;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  MODIFY (fom NOT NULL);

ALTER TABLE UTTAK_RESULTAT_PERIODE
  ADD tom2 DATE;
UPDATE UTTAK_RESULTAT_PERIODE
SET tom2 = trunc(tom);
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  DROP COLUMN tom;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  RENAME COLUMN tom2 TO tom;
ALTER TABLE UTTAK_RESULTAT_PERIODE
  MODIFY (tom NOT NULL);

ALTER TABLE UTTAK_RESULTAT_PERIODE_AKT
  ADD gradering2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE_AKT
SET gradering2 = gradering;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE_AKT
  DROP COLUMN gradering;
ALTER TABLE UTTAK_RESULTAT_PERIODE_AKT
  RENAME COLUMN gradering2 TO gradering;

ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  ADD mottatt_dato2 DATE;
UPDATE UTTAK_RESULTAT_PERIODE_SOKNAD
SET mottatt_dato2 = trunc(mottatt_dato);
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  DROP COLUMN mottatt_dato;
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  RENAME COLUMN mottatt_dato2 TO mottatt_dato;

ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  ADD samtidig_uttak2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE UTTAK_RESULTAT_PERIODE_SOKNAD
SET samtidig_uttak2 = samtidig_uttak;
COMMIT;
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  DROP COLUMN samtidig_uttak;
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD
  RENAME COLUMN samtidig_uttak2 TO samtidig_uttak;

ALTER TABLE UTTAKSPERIODEGRENSE
  ADD MOTTATTDATO2 DATE;
UPDATE UTTAKSPERIODEGRENSE
SET MOTTATTDATO2 = trunc(MOTTATTDATO);
COMMIT;
ALTER TABLE UTTAKSPERIODEGRENSE
  DROP COLUMN MOTTATTDATO;
ALTER TABLE UTTAKSPERIODEGRENSE
  RENAME COLUMN MOTTATTDATO2 TO MOTTATTDATO;
ALTER TABLE UTTAKSPERIODEGRENSE
  MODIFY (MOTTATTDATO NOT NULL);

ALTER TABLE UTTAKSPERIODEGRENSE
  ADD FOERSTE_LOVLIGE_UTTAKSDAG2 DATE;
UPDATE UTTAKSPERIODEGRENSE
SET FOERSTE_LOVLIGE_UTTAKSDAG2 = trunc(FOERSTE_LOVLIGE_UTTAKSDAG);
COMMIT;
ALTER TABLE UTTAKSPERIODEGRENSE
  DROP COLUMN FOERSTE_LOVLIGE_UTTAKSDAG;
ALTER TABLE UTTAKSPERIODEGRENSE
  RENAME COLUMN FOERSTE_LOVLIGE_UTTAKSDAG2 TO FOERSTE_LOVLIGE_UTTAKSDAG;
ALTER TABLE UTTAKSPERIODEGRENSE
  MODIFY (FOERSTE_LOVLIGE_UTTAKSDAG NOT NULL);

ALTER TABLE UTTAKSPERIODEGRENSE
  ADD aktiv2 VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL;
UPDATE UTTAKSPERIODEGRENSE
SET aktiv2 = aktiv;
COMMIT;
ALTER TABLE UTTAKSPERIODEGRENSE
  DROP COLUMN aktiv;
ALTER TABLE UTTAKSPERIODEGRENSE
  RENAME COLUMN aktiv2 TO aktiv;

ALTER TABLE VILKAR_RESULTAT
  ADD overstyrt2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE VILKAR_RESULTAT
SET overstyrt2 = overstyrt;
COMMIT;
ALTER TABLE VILKAR_RESULTAT
  DROP COLUMN overstyrt;
ALTER TABLE VILKAR_RESULTAT
  RENAME COLUMN overstyrt2 TO overstyrt;

ALTER TABLE YF_FORDELING
  ADD annenForelderErInformert2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE YF_FORDELING
SET annenForelderErInformert2 = annenForelderErInformert;
COMMIT;
ALTER TABLE YF_FORDELING
  DROP COLUMN annenForelderErInformert;
ALTER TABLE YF_FORDELING
  RENAME COLUMN annenForelderErInformert2 TO annenForelderErInformert;

ALTER TABLE YF_FORDELING_PERIODE
  ADD arbeidstaker2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE YF_FORDELING_PERIODE
SET arbeidstaker2 = arbeidstaker;
COMMIT;
ALTER TABLE YF_FORDELING_PERIODE
  DROP COLUMN arbeidstaker;
ALTER TABLE YF_FORDELING_PERIODE
  RENAME COLUMN arbeidstaker2 TO arbeidstaker;

ALTER TABLE YF_FORDELING_PERIODE
  ADD samtidig_uttak2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE YF_FORDELING_PERIODE
SET samtidig_uttak2 = samtidig_uttak;
COMMIT;
ALTER TABLE YF_FORDELING_PERIODE
  DROP COLUMN samtidig_uttak;
ALTER TABLE YF_FORDELING_PERIODE
  RENAME COLUMN samtidig_uttak2 TO samtidig_uttak;

ALTER TABLE YF_FORDELING_PERIODE
  ADD flerbarnsdager2 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
UPDATE YF_FORDELING_PERIODE
SET flerbarnsdager2 = flerbarnsdager;
COMMIT;
ALTER TABLE YF_FORDELING_PERIODE
  DROP COLUMN flerbarnsdager;
ALTER TABLE YF_FORDELING_PERIODE
  RENAME COLUMN flerbarnsdager2 TO flerbarnsdager;

CREATE SEQUENCE SEQ_BEHANDLING_STEG_TYPE_SEKV MINVALUE 1005000 START WITH 1005000 INCREMENT BY 50 NOCACHE NOCYCLE;


COMMENT ON COLUMN AKSJONSPUNKT_DEF.TILBAKEHOPP_VED_GJENOPPTAKELSE IS 'Skal det hoppes tilbake slik at steget aksjonspunktet er koblet til kjøres på nytt';
COMMENT ON COLUMN BEHANDLING.TOTRINNSBEHANDLING IS 'Indikerer at behandlingen skal totrinnsbehandles';
COMMENT ON COLUMN BEHANDLING_VEDTAK.BESLUTNING IS 'Hvorvidt vedtaket er et beslutningsvedtak. Et beslutningsvedtak er et vedtak med samme utfall som forrige vedtak';
COMMENT ON COLUMN BEREGNING.OVERSTYRT IS 'Hvorvidt hele beregning er overstyrt av Saksbehandler';
COMMENT ON COLUMN BEREGNING_RESULTAT.OVERSTYRT IS 'Hvorvidt hele beregningsresultatet er overstyrt av Saksbehandler';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.SAKSNUMMER IS 'Saksnummer i GSAK';
COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS 'Saksnummer i GSAK';
COMMENT ON COLUMN FAGSAK.SAKSNUMMER IS 'Saksnummer (som GSAK har mottatt)';
COMMENT ON COLUMN OPPDRAG_KONTROLL.SAKSNUMMER IS 'Saksnummer i GSAK';
COMMENT ON COLUMN JOURNALPOST.JOURNALPOST_ID IS 'Journalpost-id';
COMMENT ON COLUMN KODEVERK.KODEVERK_SYNK_EKSISTERENDE IS 'Flagg til synk-batchen';
COMMENT ON COLUMN KODEVERK.KODEVERK_SYNK_NYE IS 'Flagg til synk-batchen';
COMMENT ON COLUMN KODEVERK.SAMMENSATT IS 'Skiller mellom sammensatt kodeverk og enkel kodeliste';
COMMENT ON COLUMN FH_FAMILIE_HENDELSE.MOR_FOR_SYK_VED_FODSEL IS 'Om mor er syk ved fødsel';
COMMENT ON COLUMN SOEKNAD_VEDLEGG.VEDLEGG_PAKREVD IS 'Om vedlegget er påkrevd';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.BRUKER_ER_MOTTAKER IS 'Angir om bruker eller arbeidsgiver er mottaker';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.LØNNSENDRING_I_PERIODEN IS 'true hvis inntektsmelding mangler og saksbehandler har vurdert at bruker har hatt lønnsendring i beregningsperioden';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_PERIODE_FOM IS 'Første dag i brukers feriepengeperiode';
COMMENT ON COLUMN BR_FERIEPENGER.FERIEPENGER_PERIODE_TOM IS 'Siste dag i brukers feriepengeperiode';
COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS 'Dato dokumentet er produsert';
COMMENT ON COLUMN INNSYN_DOKUMENT.FIKK_INNSYN IS 'Verdi som sier om dokumentet skal være med som vedlegg eller ikke';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DELYTELSE_ID IS 'Basert på fagsystemets id med start fra 100 for tre siste sifre i id';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.HENVISNING IS 'Behandlingsid, brukes ved avstemming';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_DELYTELSE_ID IS 'Identifikasjon av delytelsen som endres (fagsystemets id)';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_FAGSYSTEM_ID IS 'Oppdragsbasens identifikasjon av vedtaket som endres';
COMMENT ON COLUMN OKO_OPPDRAG_110.FAGSYSTEM_ID IS 'Fagsystemets identifikasjon av stønaden/oppdraget';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.SAKSNUMMER IS 'Saksnummer (som GSAK har mottatt)';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.TIL_MANUELL_BEHANDLING IS 'Om perioden er merket manuell behandling';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.FLERBARNSDAGER IS 'Angir om flerbarnsdager skal benyttes i perioden';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.GRADERING_INNVILGET IS 'Om gradering ble innvilget';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.MANUELT_BEHANDLET IS 'Om perioden har blitt manuelt behandlet eller ikke';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.SAMTIDIG_UTTAK IS 'Uttaksperiode har samtidig uttak';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.GRADERING IS 'Om aktiviteten er gradert';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.MOTTATT_DATO IS 'Mottatt dato for søknad';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.SAMTIDIG_UTTAK IS 'Samtidig uttak eller ikke';
COMMENT ON COLUMN UTTAKSPERIODEGRENSE.FOERSTE_LOVLIGE_UTTAKSDAG IS 'Dato for første lovlige uttak utregnet utifra mottattdato i denne tabellen';
COMMENT ON COLUMN UTTAKSPERIODEGRENSE.MOTTATTDATO IS 'Mottatt dato for søknad. Dersom søknadsfrist blir automatisk avklar, så vil dette feltet inneholde mottattdato fra søknad, ellers vil dette inneholde bekreftet mottattdato fra aksjonspunktet';
COMMENT ON COLUMN VILKAR_RESULTAT.OVERSTYRT IS 'Om vilkårsresultatet er overstyrt';
COMMENT ON COLUMN YF_FORDELING.ANNENFORELDERERINFORMERT IS 'Om det er huket av for at den andre forelder er kjent med hvilke perioder det er søkt om';
COMMENT ON COLUMN YF_FORDELING_PERIODE.ARBEIDSTAKER IS 'Er arbeidstype arbeidstaker';
COMMENT ON COLUMN YF_FORDELING_PERIODE.FLERBARNSDAGER IS 'Angir om flerbarnsdager skal benyttes i perioden';
COMMENT ON COLUMN YF_FORDELING_PERIODE.SAMTIDIG_UTTAK IS 'Om søker ønsker samtidig uttak';
