alter table IAY_EGEN_NAERING add NY_I_ARBEIDSLIVET VARCHAR2(1 CHAR) DEFAULT 'N';
ALTER TABLE IAY_EGEN_NAERING MODIFY NY_I_ARBEIDSLIVET NOT NULL;
COMMENT ON COLUMN IAY_EGEN_NAERING.NY_I_ARBEIDSLIVET IS 'J hvis søker er ny i arbeidslivet';
