COMMENT ON COLUMN AKSJONSPUNKT.AKSJONSPUNKT_STATUS IS 'FK:AKSJONSPUNKT_STATUS Fremmednøkkel til tabellen som inneholder status på aksjonspunktene';

COMMENT ON COLUMN AKSJONSPUNKT.BEHANDLING_ID IS 'Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN AKSJONSPUNKT.KL_REAKTIVERING_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_RESULTAT.BEREGNINGSGRUNNLAG_ID IS 'FK: Fremmednøkkel for kobling til beregningsgrunnlag';
COMMENT ON COLUMN BEHANDLING_RESULTAT.KL_AVSLAGSARSAK IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEHANDLING_TYPE_STEG_SEKV.KL_FAGSAK_YTELSE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BEREGNINGSGRUNNLAG.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BEREGNINGSGRUNNLAG_PERIODE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BEREGNINGSRESULTAT_ANDEL.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BEREGNINGSRESULTAT_FP.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BEREGNINGSRESULTAT_PERIODE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BG_AKTIVITET_STATUS.BEREGNINGSGRUNNLAG_ID IS 'Fremmednøkkel til tabell som knytter beregningsgrunnlagsaktivitetstatusen til et beregningsgrunnlag';
COMMENT ON COLUMN BG_AKTIVITET_STATUS.AKTIVITET_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BG_AKTIVITET_STATUS.KL_HJEMMEL IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.ID IS 'Primærnøkkel';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.BG_PERIODE_ID IS 'FK: Fremmednøkkel til tabell som knytter beregningsgrunnlagsandelen til en beregningsgrunnlagperiode';
COMMENT ON COLUMN BG_PR_STATUS_OG_ANDEL.AKTIVITET_STATUS IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.BR_FERIEPENGER_ID IS 'FK:BR_FERIEPENGER';
COMMENT ON COLUMN BR_FERIEPENGER_PR_AAR.BEREGNINGSRESULTAT_ANDEL_ID IS 'FK:BEREGNINGSRESULTAT_ANDEL';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.ID IS 'Primærnøkkel';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.FAGSAK_ID IS 'FK: Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.PROSESS_TASK_ID IS 'FK: Fremmednøkkel for knyttning til logging av prosesstask som ???';
COMMENT ON COLUMN FAGSAK_PROSESS_TASK.BEHANDLING_ID IS 'FK: Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN FAGSAK_RELASJON.FAGSAK_EN_ID IS 'FK:';

COMMENT ON COLUMN FAGSAK_RELASJON.KONTO_BEREGNING_ID IS 'FK:';


COMMENT ON COLUMN FH_ADOPSJON.FAMILIE_HENDELSE_ID IS 'FK: Fremmednøkkel som knytter adopsjonsinformasjonen til familiehendelse';

COMMENT ON COLUMN FH_TERMINBEKREFTELSE.FAMILIE_HENDELSE_ID IS 'FK: Fremmednøkkel som knytter terminbekreftelsen til familiehendelse';
COMMENT ON COLUMN FH_UIDENTIFISERT_BARN.FAMILIE_HENDELSE_ID IS 'FK: Fremmednøkkel som knytter fødselsdato for barn til familiehendelse';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.INNTEKTSMELDINGER_ID IS 'FK: Fremmednøkkel for kobling til inntektsmeldinger';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.OPPGITT_OPPTJENING_ID IS 'FK: Fremmenøkkel for kobling til egen oppgitt opptjening';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.IAY_REGISTER_ETTER_ID IS 'FK: Fremmednøkkel for kobling til inntektsmeldinger';
COMMENT ON COLUMN GR_ARBEID_INNTEKT.IAY_SAKSBEHANDLET_ETTER_ID IS 'FK: Fremmenøkkel for kobling til egen oppgitt opptjening';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.BEHANDLING_ID IS 'FK: Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.SOEKNAD_FAMILIE_HENDELSE_ID IS 'FK: Fremmednøkkel til tabell som knytter beregningsgrunnlagforekomsten til behandling';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.BEKREFTET_FAMILIE_HENDELSE_ID IS 'FK:';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.OVERSTYRT_FAMILIE_HENDELSE_ID IS 'FK';
COMMENT ON COLUMN GR_MEDLEMSKAP.REGISTRERT_ID IS 'FK:';
COMMENT ON COLUMN GR_MEDLEMSKAP.OPPGITT_ID IS 'FK:';
COMMENT ON COLUMN GR_MEDLEMSKAP.VURDERING_ID IS 'FK:';
COMMENT ON COLUMN GR_MEDLEMSKAP_VILKAR_PERIODE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN GR_MEDLEMSKAP_VILKAR_PERIODE.VILKAR_RESULTAT_ID IS 'FK: Fremmednøkkel for kobling til vilkårsresultat';
COMMENT ON COLUMN GR_MEDLEMSKAP_VILKAR_PERIODE.MEDLEMSKAP_VILKAR_PERIODE_ID IS 'FK: Fremmednøkkel for kobling til aggregat medlemskap_vilkar_periode';
COMMENT ON COLUMN GR_MEDLEMSKAP_VILKAR_PERIODE.AKTIV IS 'Angir aktivt grunnlag for vilkårsresultat (som igjen er koblet til behandling). Kun ett innslag tillates å være aktivt(J), men mange kan være inaktive(N)';
COMMENT ON COLUMN GR_PERSONOPPLYSNING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN GR_PERSONOPPLYSNING.SO_ANNEN_PART_ID IS 'FK:';
COMMENT ON COLUMN GR_PERSONOPPLYSNING.REGISTRERT_INFORMASJON_ID IS 'FK:';
COMMENT ON COLUMN GR_PERSONOPPLYSNING.OVERSTYRT_INFORMASJON_ID IS 'FK:';
COMMENT ON COLUMN GR_SOEKNAD.ID IS 'Primærnøkkel';
COMMENT ON COLUMN GR_SOEKNAD.SOEKNAD_ID IS 'FK:';

COMMENT ON COLUMN GR_VERGE.VERGE_ID IS 'FK:VERGE';
COMMENT ON COLUMN GR_YTELSES_FORDELING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN GR_YTELSES_FORDELING.SO_RETTIGHET_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.SO_FORDELING_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.SO_DEKNINGSGRAD_ID IS 'FK:';

COMMENT ON COLUMN GR_YTELSES_FORDELING.OVERSTYRT_FORDELING_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.BEKREFTET_FORDELING_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.UTENOMSORG_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.ALENEOMSORG_ID IS 'FK:';
COMMENT ON COLUMN GR_YTELSES_FORDELING.UTTAK_DOKUMENTASJON_ID IS 'FK:';
COMMENT ON COLUMN HISTORIKKINNSLAG_DEL.ID IS 'Primærnøkkel';
COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.JOURNALPOST_ID IS 'FK';
COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.DOKUMENT_ID IS 'FK:';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.HISTORIKKINNSLAG_DEL_ID IS 'FK:';

COMMENT ON COLUMN IAY_AKTIVITETS_AVTALE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_AKTIVITETS_AVTALE.YRKESAKTIVITET_ID IS 'FK:';


COMMENT ON COLUMN IAY_AKTOER_ARBEID.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_AKTOER_ARBEID.INNTEKT_ARBEID_YTELSER_ID IS 'FK:';
COMMENT ON COLUMN IAY_AKTOER_INNTEKT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_AKTOER_INNTEKT.INNTEKT_ARBEID_YTELSER_ID IS 'FK:';
COMMENT ON COLUMN IAY_AKTOER_YTELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_AKTOER_YTELSE.INNTEKT_ARBEID_YTELSER_ID IS 'FK';
COMMENT ON COLUMN IAY_ANNEN_AKTIVITET.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_ANNEN_AKTIVITET.OPPGITT_OPPTJENING_ID IS 'FK:';
COMMENT ON COLUMN IAY_EGEN_NAERING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_EGEN_NAERING.OPPGITT_OPPTJENING_ID IS 'FK.';



COMMENT ON COLUMN IAY_EGEN_NAERING.VIRKSOMHET_ID IS 'FK:';

COMMENT ON COLUMN IAY_GRADERING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_GRADERING.INNTEKTSMELDING_ID IS 'FK:';


COMMENT ON COLUMN IAY_INNTEKT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKT.AKTOER_INNTEKT_ID IS 'FK:';

COMMENT ON COLUMN IAY_INNTEKT_ARBEID_YTELSER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.INNTEKTSMELDINGER_ID IS 'FK:';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.MOTTATT_DOKUMENT_ID IS 'FK:';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.VIRKSOMHET_ID IS 'FK:';
COMMENT ON COLUMN IAY_INNTEKTSMELDING.ARBEIDSFORHOLD_ID IS 'FK:';
COMMENT ON COLUMN IAY_INNTEKTSMELDINGER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKTSMELDING_MANGLER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKTSPOST.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_INNTEKTSPOST.INNTEKT_ID IS 'FK: Fremmednøkkel til kodeverkstabellen for inntektsposttyper';


COMMENT ON COLUMN IAY_NATURAL_YTELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_NATURAL_YTELSE.TOM IS 'Fremmednøkkel til kodeverktabell for naturalytelsetype.';
COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.OPPGITT_OPPTJENING_ID IS 'FK:';
COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.VIRKSOMHET_ID IS 'FK:';



COMMENT ON COLUMN IAY_OPPGITT_ARBEIDSFORHOLD.KL_LANDKODER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN IAY_PERMISJON.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_PERMISJON.YRKESAKTIVITET_ID IS 'FK:';
COMMENT ON COLUMN IAY_PERMISJON.BESKRIVELSE_TYPE IS 'FK: Fremmednøkkel til tabell for beskrivelse av permisjonstyper';


COMMENT ON COLUMN IAY_RELATERT_YTELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_RELATERT_YTELSE.AKTOER_YTELSE_ID IS 'FK:AKTOER_YTELSE';


COMMENT ON COLUMN IAY_UTSETTELSE_PERIODE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.AKTOER_ARBEID_ID IS 'FK:';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.ARBEIDSFORHOLD_ID IS 'FK:';
COMMENT ON COLUMN IAY_YRKESAKTIVITET.ARBEIDSGIVER_VIRKSOMHET_ID IS 'FK:';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.ID IS 'Primærnøkkel';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.YTELSE_ID IS 'FK:YTELSE';
COMMENT ON COLUMN IAY_YTELSE_GRUNNLAG.ARBEIDSKATEGORI IS 'FK:ARBEIDSKATEGORI';
COMMENT ON COLUMN IAY_YTELSE_STOERRELSE.ID IS 'FK:YTELSE_GRUNNLAG Primærnøkkel';
COMMENT ON COLUMN IAY_YTELSE_STOERRELSE.VIRKSOMHET_ID IS 'FK:VIRKSOMHET';
COMMENT ON COLUMN INNSYN_DOKUMENT.INNSYN_ID IS 'FK:INNSYN Fremmednøkkel for kobling til aggregat INNSYN';
COMMENT ON COLUMN INNSYN_DOKUMENT.JOURNALPOST_ID IS 'FK: Journalpostens ID i JOARK';
COMMENT ON COLUMN INNSYN_DOKUMENT.DOKUMENT_ID IS 'FK: Referanse til dokumentet i Joark';
COMMENT ON COLUMN JOURNALPOST.JOURNALPOST_ID IS 'FK: Journalpostens ID i JOARK';
COMMENT ON COLUMN MEDLEMSKAP_OPPG_LAND.LAND IS 'FK:LANDKODER Landet for den oppgitte tilknytningen';
COMMENT ON COLUMN MEDLEMSKAP_OPPG_LAND.MEDLEMSKAP_OPPG_TILKNYT_ID IS 'FK:MEDLEMSKAP_OPPG_TILKNYT Som er koblingstabellen mellom hver enkelt oppgitt tilknytning og søknaden';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.MEDLEMSKAP_TYPE IS 'FK:MEDLEMSKAP_TYPE Type periode: ENDELIG, FORELØPIG eller AVKLARES';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.DEKNING_TYPE IS 'FK:MEDLEMSKAP_DEKNING Hva slags dekning som ligger i perioden - ofte en referanse til en lovhjemmel';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.KILDE_TYPE IS 'FK:MEDLEMSKAP_KILDE Angir kilden for informasjonen om medlemskap';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.LOVVALG_LAND IS 'FK:LANDKODER';
COMMENT ON COLUMN MEDLEMSKAP_PERIODER.STUDIE_LAND IS 'FK:LANDKODER';
COMMENT ON COLUMN MEDLEMSKAP_REGISTRERT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN MEDLEMSKAP_VILKAR_PERIODE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN MEDLEMSKAP_VILKAR_PERIODER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN MEDLEMSKAP_VILKAR_PERIODER.MEDLEMSKAP_VILKAR_PERIODE_ID IS 'FK:MEDLEMSKAP_VILKAR_PERIODE Fremmednøkkel til periodenes aggregat';
COMMENT ON COLUMN MEDLEMSKAP_VURDERING.MEDLEMSPERIODE_MANUELL_VURD IS 'FK:MEDLEMSKAP_MANUELL_VURD De mulige valgene for manuell vurdering av medlemsperiodene';
COMMENT ON COLUMN MEDLEMSKAP_VURDERING.FOM IS 'FOM dato for vurderingen';
COMMENT ON COLUMN MOTTATT_DOKUMENT.JOURNALPOST_ID IS 'FK: Journalpostens ID i JOARK';
COMMENT ON COLUMN MOTTATT_DOKUMENT.DOKUMENT_ID IS 'FK: Referanse til dokumentet i Joark';
COMMENT ON COLUMN MOTTATT_DOKUMENT.FAGSAK_ID IS 'FK: Fremmednøkkel til Fagsak';
COMMENT ON COLUMN OKO_GRAD_170.ID IS 'Primærnøkkel';
COMMENT ON COLUMN OKO_GRAD_170.OPPDRAGS_LINJE_150_ID IS 'FK: Fremmednøkkel for kopling til tabellen som holder detaljene for oppdraget til oppgjør';
COMMENT ON COLUMN OKO_OPPDRAG_ENHET_120.ID IS 'Primærnøkkel';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.ID IS 'Primærnøkkel';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.VEDTAK_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.DELYTELSE_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.SAKSBEH_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.UTBETALES_TIL_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_FAGSYSTEM_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_LINJE_150.REF_DELYTELSE_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_110.FAGSYSTEM_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_110.OPPDRAG_GJELDER_ID IS 'FK:';
COMMENT ON COLUMN OKO_OPPDRAG_110.SAKSBEH_ID IS 'FK:';
COMMENT ON COLUMN OKO_REFUSJONSINFO_156.ID IS 'Primærnøkkel';
COMMENT ON COLUMN OKO_REFUSJONSINFO_156.REFUNDERES_ID IS 'FK:';
COMMENT ON COLUMN OKO_REFUSJONSINFO_156.OPPDRAGS_LINJE_150_ID IS 'FK:';
COMMENT ON COLUMN OPPDRAG_KVITTERING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN OPPDRAG_KVITTERING.OPPDRAG_110_ID IS 'FK:';
COMMENT ON COLUMN OPPGAVE_BEHANDLING_KOBLING.OPPGAVE_ID IS 'FK:';
COMMENT ON COLUMN OPPLYSNING_ADRESSE.ADRESSE_ID IS 'FK:';
COMMENT ON COLUMN OPPTJENING.VILKAR_RESULTAT_ID IS 'FK:VILKAR_RESULTAT';


COMMENT ON COLUMN OPPTJENING_AKTIVITET.OPPTJENINGSPERIODE_ID IS 'FK:';

COMMENT ON COLUMN PO_ADRESSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN PO_ADRESSE.PO_INFORMASJON_ID IS 'FK:';
COMMENT ON COLUMN PO_INFORMASJON.ID IS 'Primærnøkkel';
COMMENT ON COLUMN PO_PERSONOPPLYSNING.ID IS 'Primærnøkkel';



COMMENT ON COLUMN PO_PERSONOPPLYSNING.PO_INFORMASJON_ID IS 'FK:';
COMMENT ON COLUMN PO_PERSONSTATUS.ID IS 'Primærnøkkel';
COMMENT ON COLUMN PO_PERSONSTATUS.PO_INFORMASJON_ID IS 'FK:';

COMMENT ON COLUMN PO_RELASJON.ID IS 'Primærnøkkel';
COMMENT ON COLUMN PO_RELASJON.PO_INFORMASJON_ID IS 'FK:';



COMMENT ON COLUMN PO_STATSBORGERSKAP.ID IS 'Primærnøkkel';
COMMENT ON COLUMN PO_STATSBORGERSKAP.PO_INFORMASJON_ID IS 'FK:';

COMMENT ON COLUMN RES_BEREGNINGSRESULTAT_FP.BEHANDLING_ID IS 'FK:BEHANDLING';
COMMENT ON COLUMN RES_BEREGNINGSRESULTAT_FP.BEREGNINGSRESULTAT_FP_ID IS 'FK:BEREGNINGSRESULTAT_FP';
COMMENT ON COLUMN SAMMENLIGNINGSGRUNNLAG.ID IS 'Primærnøkkel';
COMMENT ON COLUMN SAMMENLIGNINGSGRUNNLAG.BEREGNINGSGRUNNLAG_ID IS 'FK:';
COMMENT ON COLUMN SO_DEKNINGSGRAD.ID IS 'Primærnøkkel';
COMMENT ON COLUMN SO_OPPGITT_OPPTJENING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN SO_RETTIGHET.ID IS 'Primærnøkkel';
COMMENT ON COLUMN SO_SOEKNAD.FAR_SOEKER_TYPE IS 'FK:FAR_SOEKER_TYPE';
COMMENT ON COLUMN SO_SOEKNAD.ANNEN_PART_ID IS 'FK:SOEKNAD_ANNEN_PART';
COMMENT ON COLUMN SO_SOEKNAD.MEDLEMSKAP_OPPG_TILKNYT_ID IS 'FK:MEDLEMSKAP_OPPG_TILKNYT';
COMMENT ON COLUMN SO_SOEKNAD.FAMILIE_HENDELSE_ID IS 'FK:';
COMMENT ON COLUMN SO_SOEKNAD.FORDELING_ID IS 'FK:';
COMMENT ON COLUMN SO_SOEKNAD.RETTIGHET_ID IS 'FK:';
COMMENT ON COLUMN SO_SOEKNAD.DEKNINGSGRAD_ID IS 'FK:';
COMMENT ON COLUMN SO_SOEKNAD.OPPGITT_OPPTJENING_ID IS 'FK';
COMMENT ON COLUMN SO_SOEKNAD.BRUKER_ROLLE IS 'FK:RELASJONSROLLE_TYPE';
COMMENT ON COLUMN STOENADSKONTO.ID IS 'Primærnøkkel';
COMMENT ON COLUMN STOENADSKONTO.STOENADSKONTOBEREGNING_ID IS 'FK:';
COMMENT ON COLUMN STOENADSKONTOBEREGNING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTGAAENDE_HENDELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT.AKTIV IS 'Om dette uttaksresultatet er den aktive resultatet';
COMMENT ON COLUMN UTTAK_RESULTAT.BEHANDLING_RESULTAT_ID IS 'FK:BEHANDLING_RESULTAT Behandlingsresultatet til uttaksresultatet';
COMMENT ON COLUMN UTTAK_RESULTAT.OPPRINNELIG_PERIODER_ID IS 'FK:UTTAK_RESULTAT_PERIODER Opprinnelige periodene til uttaksresultatet';
COMMENT ON COLUMN UTTAK_RESULTAT.OVERSTYRT_PERIODER_ID IS 'FK:UTTAK_RESULTAT_PERIODER Overstyrte periodene til uttaksresultatet. Settes når saksbehandler overstyrer de opprinnelige periodene';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT_DOK_REGEL.UTTAK_RESULTAT_PERIODE_ID IS 'FK:UTTAK_RESULTAT_PERIODE Refererer til hvilken uttaksperiode regeldokumentasjonen gjelder for';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.UTTAK_RESULTAT_PERIODER_ID IS 'FK:UTTAK_RESULTAT_PERIODER Refererer til hvilken uttaksperioder perioden ligger i';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.PERIODE_RESULTAT_TYPE IS 'Hvilket resultat uttaksperioden har fått';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.PERIODE_RESULTAT_AARSAK IS 'Årsak til resultat uttaksperioden har fått';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE.GRADERING_AVSLAG_AARSAK IS 'Årsak til at gradering for uttaksperioden har blitt avslått';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.UTTAK_RESULTAT_PERIODE_ID IS 'FK:UTTAK_RESULTAT_PERIODE Hvilken uttaksperiode aktiviteten tilhører';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.UTTAK_AKTIVITET_ID IS 'FK:UTTAK_AKTIVITET Hvilken uttak aktivitet periode aktiviteten har';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_AKT.KL_TREKKONTO IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAKSPERIODEGRENSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN UTTAKSPERIODEGRENSE.BEHANDLING_RESULTAT_ID IS 'FK:BEHANDLING_RESULTAT Behandlingsresultatet til uttaksperiodegrense';
COMMENT ON COLUMN VILKAR.VILKAR_TYPE IS 'FK:VILKAR_TYPE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN VILKAR_RESULTAT.ORIGINAL_BEHANDLING_ID IS 'FK:BEHANDLING FK: BEHANDLING Fremmednøkkel for kobling til behandlingen denne raden i tabellen hører til';
COMMENT ON COLUMN VIRKSOMHET.ID IS 'Primærnøkkel';
COMMENT ON COLUMN YF_DOKUMENTASJON_PERIODER.ID IS 'Primærnøkkel';
COMMENT ON COLUMN YF_FORDELING.ID IS 'Primærnøkkel';
COMMENT ON COLUMN YF_FORDELING_PERIODE.VIRKSOMHET_ID IS 'FK:VIRKSOMHET';
