-- Nye kolonner for skille mellom strings og kodeverdier
ALTER TABLE HISTORIKKINNSLAG_FELT ADD FRA_VERDI_KODE VARCHAR2(100 char) NULL;
ALTER TABLE HISTORIKKINNSLAG_FELT ADD TIL_VERDI_KODE VARCHAR2(100 char) NULL;

COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.FRA_VERDI_KODE IS 'Feltets gamle verdi. Kun kodeverk';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.TIL_VERDI_KODE IS 'Feltets nye verdi. Kun kodeverk';

COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.FRA_VERDI IS 'Feltets gamle verdi. Kun string';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.TIL_VERDI IS 'Feltets nye verdi. Kun string';

-- migrering data fra gammel kolonn til ny kolonn
UPDATE HISTORIKKINNSLAG_FELT SET FRA_VERDI_KODE = FRA_VERDI WHERE KL_VERDI IS NOT NULL;
UPDATE HISTORIKKINNSLAG_FELT SET FRA_VERDI = NULL WHERE KL_VERDI IS NOT NULL;
UPDATE HISTORIKKINNSLAG_FELT SET TIL_VERDI_KODE = TIL_VERDI WHERE KL_VERDI IS NOT NULL;
UPDATE HISTORIKKINNSLAG_FELT SET TIL_VERDI = NULL WHERE KL_VERDI IS NOT NULL;

-- Nye kolonner for fra_verdi_kodeverk og til_verdi_kodeverk
ALTER TABLE HISTORIKKINNSLAG_FELT ADD KL_FRA_VERDI VARCHAR2(100 char) NULL;
ALTER TABLE HISTORIKKINNSLAG_FELT ADD KL_TIL_VERDI VARCHAR2(100 char) NULL;

COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_FRA_VERDI IS 'FK:KODELISTE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_TIL_VERDI IS 'FK:KODELISTE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

-- migrering data fra gammel kolonn til ny kolonn
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = KL_VERDI;
UPDATE HISTORIKKINNSLAG_FELT SET KL_TIL_VERDI = KL_VERDI;

-- drop kolonn KL_VERDI
ALTER TABLE HISTORIKKINNSLAG_FELT DROP COLUMN KL_VERDI;

-- oppdatere kodeverk
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' WHERE (KL_FRA_VERDI = 'INNVILGET_AARSAK' OR KL_FRA_VERDI = 'PERIODE_RESULTAT_AARSAK') AND FRA_VERDI_KODE LIKE '4%';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = 'INNVILGET_AARSAK' WHERE (KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' OR KL_FRA_VERDI = 'PERIODE_RESULTAT_AARSAK') AND FRA_VERDI_KODE LIKE '2%';

-- oppdatere script for fjernet kodeverk
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4001';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4010';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4011';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4014';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4015';
UPDATE HISTORIKKINNSLAG_FELT SET KL_FRA_VERDI = NULL, FRA_VERDI_KODE = NULL WHERE KL_FRA_VERDI = 'IKKE_OPPFYLT_AARSAK' AND fra_verdi_kode = '4017';
UPDATE HISTORIKKINNSLAG_FELT SET KL_TIL_VERDI = NULL, TIL_VERDI_KODE = NULL WHERE KL_TIL_VERDI = 'IKKE_OPPFYLT_AARSAK' AND TIL_VERDI_KODE = '4010';
UPDATE HISTORIKKINNSLAG_FELT SET KL_TIL_VERDI = NULL, TIL_VERDI_KODE = NULL WHERE KL_TIL_VERDI = 'IKKE_OPPFYLT_AARSAK' AND TIL_VERDI_KODE = '4015';
UPDATE HISTORIKKINNSLAG_FELT SET KL_TIL_VERDI = NULL, TIL_VERDI_KODE = NULL WHERE KL_TIL_VERDI = 'IKKE_OPPFYLT_AARSAK' AND TIL_VERDI_KODE = '4017';
UPDATE HISTORIKKINNSLAG_FELT SET KL_TIL_VERDI = NULL, TIL_VERDI_KODE = NULL WHERE KL_TIL_VERDI = 'IKKE_OPPFYLT_AARSAK' AND TIL_VERDI_KODE = '4001';

-- Foreign Keys
ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_81 FOREIGN KEY (NAVN, KL_NAVN) REFERENCES KODELISTE (KODE, KODEVERK);

-- Foreign Keys
ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_82 FOREIGN KEY (FRA_VERDI_KODE, KL_FRA_VERDI) REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_83 FOREIGN KEY (TIL_VERDI_KODE, KL_TIL_VERDI) REFERENCES KODELISTE (KODE, KODEVERK);

-- indekser
CREATE index IDX_HISTORIKKINNSLAG_FELT_3 on HISTORIKKINNSLAG_FELT(NAVN, KL_NAVN);
CREATE index IDX_HISTORIKKINNSLAG_FELT_4 on HISTORIKKINNSLAG_FELT(TIL_VERDI_KODE, KL_TIL_VERDI);
CREATE index IDX_HISTORIKKINNSLAG_FELT_5 on HISTORIKKINNSLAG_FELT(FRA_VERDI_KODE, KL_FRA_VERDI);
