-- FPFEIL-3271
UPDATE DOKUMENT_MAL_TYPE SET navn='Ikke mottatt søknad' WHERE kode='INNTID';

-- FPFEIL-3135
UPDATE KODELISTE_NAVN_I18N SET navn='Fakta om adopsjon'   WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='PUNKT_FOR_ADOPSJON'   AND SPRAK='NB';
UPDATE KODELISTE_NAVN_I18N SET navn='Fakta om fødsel'     WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='PUNKT_FOR_FOEDSEL'    AND SPRAK='NB';
UPDATE KODELISTE_NAVN_I18N SET navn='Fakta om medlemskap' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='PUNKT_FOR_MEDLEMSKAP' AND SPRAK='NB';
UPDATE KODELISTE_NAVN_I18N SET navn='Fakta om omsorg'     WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='PUNKT_FOR_OMSORG'     AND SPRAK='NB';
UPDATE KODELISTE_NAVN_I18N SET navn='Fakta om opptjening' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='PUNKT_FOR_OPPTJENING' AND SPRAK='NB';

-- PFP-1685
UPDATE KODELISTE_NAVN_I18N SET navn='Beregning' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='BEREGNING_ENGANGSSTOENAD' AND SPRAK='NB';
UPDATE KODELISTE_NAVN_I18N SET navn='Beregning' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='BEREGNING_FORELDREPENGER' AND SPRAK='NB';

-- PFP-1618
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-10: Påkrevd stønadsperiode mangler' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4006' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-10 sjuende ledd: Hull mellom forrige uttaksperiode og neste søknadsperiode' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4090' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-10 sjuende ledd: Hull mellom forrige utsettelseperiode og neste søknadsperiode' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4091' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-11 første ledd, jf. §14-14, jf. §14-13: Bare far har rett, mor fyller ikke aktivitetskravet' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4035' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-10 første ledd: Mor søker uttak før 12 uker før termin/fødsel' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4013' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-13 første ledd bokstav b, jf §21-3: Aktivitetskrav – utdanning ikke dokumentert' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4067' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-10 sjuende ledd: Hull mellom foreldrenes perioder' WHERE KL_KODEVERK='IKKE_OPPFYLT_AARSAK' AND KL_KODE='4005' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-12: Innvilget uttak av kvote' WHERE KL_KODEVERK='INNVILGET_AARSAK' AND KL_KODE='2003' AND SPRAK= 'NB';
UPDATE KODELISTE_NAVN_I18N SET NAVN='§14-12 tredje ledd: Overføring oppfylt, annen part har ikke rett til foreldrepenger' WHERE KL_KODEVERK='INNVILGET_AARSAK' AND KL_KODE='2020' AND SPRAK= 'NB';

UPDATE KODELISTE SET EKSTRA_DATA='{"fagsakYtelseType": {"FP": {"lovreferanse": "14-11,14-14,14-13"}}}' WHERE KODEVERK= 'IKKE_OPPFYLT_AARSAK' AND KODE= '4035';

