--Legg til nye kolonner
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD stillingsprosent NUMBER(19, 0) NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD uttaksgrad NUMBER(19, 0) NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL ADD dagsats_fra_bg NUMBER(19, 0) NULL;

UPDATE BEREGNINGSRESULTAT_ANDEL set dagsats_fra_bg = dagsats, stillingsprosent = 100, uttaksgrad = 100;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL MODIFY stillingsprosent NOT NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL MODIFY uttaksgrad NOT NULL;
ALTER TABLE BEREGNINGSRESULTAT_ANDEL MODIFY dagsats_fra_bg NOT NULL;
