CREATE TABLE FAGSAK_PROSESS_TASK (
  id                 NUMBER(19)                        NOT NULL,
  fagsak_id          NUMBER(19)                        NOT NULL,
  prosess_task_id    NUMBER(19)                        NOT NULL,
  behandling_id      NUMBER(19)                        NULL,
  versjon            NUMBER(19) DEFAULT 0              NOT NULL,
  opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av          VARCHAR2(20 CHAR),
  endret_tid         TIMESTAMP(3),
  CONSTRAINT PK_FAGSAK_PROSESS_TASK PRIMARY KEY (id),
  CONSTRAINT FK_FAGSAK_PROSESS_TASK_1 FOREIGN KEY (fagsak_id) REFERENCES FAGSAK,
  CONSTRAINT FK_FAGSAK_PROSESS_TASK_2 FOREIGN KEY (prosess_task_id) REFERENCES PROSESS_TASK,
  CONSTRAINT FK_FAGSAK_PROSESS_TASK_3 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING
);

CREATE SEQUENCE SEQ_FAGSAK_PROSESS_TASK MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE UNIQUE INDEX UIDX_FAGSAK_PROSESS_TASK_1 ON FAGSAK_PROSESS_TASK (fagsak_id, prosess_task_id);
CREATE UNIQUE INDEX IDX_FAGSAK_PROSESS_TASK_1 ON FAGSAK_PROSESS_TASK (fagsak_id);
CREATE UNIQUE INDEX IDX_FAGSAK_PROSESS_TASK_2 ON FAGSAK_PROSESS_TASK (prosess_task_id);
CREATE UNIQUE INDEX IDX_FAGSAK_PROSESS_TASK_3 ON FAGSAK_PROSESS_TASK (behandling_id);

COMMENT ON TABLE FAGSAK_PROSESS_TASK IS '1-M relasjonstabell for å mappe fagsak til prosess_tasks (som ikke er FERDIG)';
