ALTER TABLE MOTTATT_DOKUMENT ADD (XML_PAYLOAD_2 CLOB);

UPDATE MOTTATT_DOKUMENT SET XML_PAYLOAD_2 = XML_PAYLOAD;

ALTER TABLE MOTTATT_DOKUMENT DROP COLUMN XML_PAYLOAD;

ALTER TABLE MOTTATT_DOKUMENT RENAME COLUMN XML_PAYLOAD_2 TO XML_PAYLOAD;

COMMENT ON COLUMN MOTTATT_DOKUMENT.XML_PAYLOAD IS 'Strukturert informasjon fra det mottatte dokumentet';
