ALTER TABLE UTGAAENDE_HENDELSE ADD KILDE_ID VARCHAR2(40 char);


comment on column UTGAAENDE_HENDELSE.KILDE_ID is 'Id for kilden som oppretter hendelsen. f.eks. vedtak_id for vedtakhendelser';

CREATE INDEX IDX_UTHENDELSE_KILDE_ID ON UTGAAENDE_HENDELSE(KILDE_ID);
CREATE INDEX IDX_UTHENDELSE_TYPE ON UTGAAENDE_HENDELSE(TYPE);
CREATE INDEX IDX_UTHENDELSE_SEKVENSNUMMER ON UTGAAENDE_HENDELSE(SEKVENSNUMMER);
CREATE INDEX IDX_UTHENDELSE_AKTOER_ID ON UTGAAENDE_HENDELSE(AKTOER_ID);
