-- Familie hendelse
COMMENT ON TABLE GR_FAMILIE_HENDELSE IS 'Grunnlag familie-hendelse';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.BEHANDLING_ID IS 'Behandlingen grunnlaget gjelder for.';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.SOEKNAD_FAMILIE_HENDELSE_ID IS 'Søkers oppgitte data vedrørende søkers relasjon til barnet.';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.BEKREFTET_FAMILIE_HENDELSE_ID IS 'Data fra registere data vedrørende søkers relasjon til barnet.';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.OVERSTYRT_FAMILIE_HENDELSE_ID IS 'Saksbehandlers vurderinger vedrørende søkers relasjon til barnet.';
COMMENT ON COLUMN GR_FAMILIE_HENDELSE.aktiv IS 'Aktivflagg som sier om grunnlaget er aktiv eller ei.';

COMMENT ON TABLE FAMILIE_HENDELSE IS 'Familie hendelse';
COMMENT ON COLUMN FAMILIE_HENDELSE.ID IS 'Primærnøkkel';
COMMENT ON COLUMN FAMILIE_HENDELSE.ANTALL_BARN IS 'Antall barn';
COMMENT ON COLUMN FAMILIE_HENDELSE.FAMILIE_HENDELSE_TYPE IS 'Type hendelse(Fødsel, Termin, Adopsjon eller omsorgsovertakelse)';
COMMENT ON COLUMN FAMILIE_HENDELSE.MOR_FOR_SYK_VED_FODSEL IS 'Flagg om det har blitt dokumentert at mor er så syk ved fødsel at far kan søke på termin.';
COMMENT ON COLUMN TERMINBEKREFTELSE.NAVN IS 'Legen som utstedete terminbekreftelsen.';
COMMENT ON COLUMN ADOPSJON.ANKOMST_NORGE_DATO IS 'Datoen barnet ankom norge.';
COMMENT ON COLUMN ADOPSJON.FORELDREANSVAR_OPPFYLT_DATO IS 'Dato for når foreldreansvaret ble oppfylt.';

ALTER TABLE FAMILIE_HENDELSE RENAME TO FH_FAMILIE_HENDELSE;
ALTER TABLE UIDENTIFISERT_BARN RENAME TO FH_UIDENTIFISERT_BARN;
ALTER TABLE TERMINBEKREFTELSE RENAME TO FH_TERMINBEKREFTELSE;
ALTER TABLE ADOPSJON RENAME TO FH_ADOPSJON;

CREATE INDEX UIDX_UIDENTIFISERT_BARN_2 ON FH_UIDENTIFISERT_BARN(FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_SOEKNAD_1 ON SOEKNAD(FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_ADOPSJON_1 ON FH_ADOPSJON(FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_TERMINBEKREFTELSE_1 ON FH_TERMINBEKREFTELSE(FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_FAMILIE_HENDELSE_1 ON GR_FAMILIE_HENDELSE(SOEKNAD_FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_FAMILIE_HENDELSE_2 ON GR_FAMILIE_HENDELSE(BEKREFTET_FAMILIE_HENDELSE_ID);
CREATE INDEX IDX_FAMILIE_HENDELSE_3 ON GR_FAMILIE_HENDELSE(OVERSTYRT_FAMILIE_HENDELSE_ID);

--- Inntekt, arbeid, ytelse
ALTER TABLE GR_ARBEID_INNTEKT ADD CONSTRAINT FK_GR_ARBEID_INNTEKT_3 FOREIGN KEY (INNTEKTSMELDINGER_ID) REFERENCES INNTEKTSMELDINGER(ID);
ALTER TABLE GR_ARBEID_INNTEKT ADD CONSTRAINT FK_GR_ARBEID_INNTEKT_4 FOREIGN KEY (OPPGITT_OPPTJENING_ID) REFERENCES SO_OPPGITT_OPPTJENING(ID);
ALTER TABLE GR_ARBEID_INNTEKT ADD CONSTRAINT FK_GR_ARBEID_INNTEKT_5 FOREIGN KEY (OVERSTYRT_ID) REFERENCES INNTEKT_ARBEID_YTELSER(ID);
CREATE INDEX IDX_GR_ARBEID_INNTEKT_1 ON GR_ARBEID_INNTEKT(BEHANDLING_ID);
CREATE INDEX IDX_GR_ARBEID_INNTEKT_2 ON GR_ARBEID_INNTEKT(INNTEKT_ARBEID_YTELSER_ID);
CREATE INDEX IDX_GR_ARBEID_INNTEKT_3 ON GR_ARBEID_INNTEKT(INNTEKTSMELDINGER_ID);
CREATE INDEX IDX_GR_ARBEID_INNTEKT_4 ON GR_ARBEID_INNTEKT(OVERSTYRT_ID);
CREATE INDEX IDX_GR_ARBEID_INNTEKT_5 ON GR_ARBEID_INNTEKT(OPPGITT_OPPTJENING_ID);

-- Inntekt
COMMENT ON TABLE INNTEKT_ARBEID_YTELSER IS 'Mange til mange tabell for inntekt, arbeid, ytelser.';
ALTER TABLE INNTEKT_ARBEID_YTELSER DROP COLUMN INNTEKT_OPPLYSNINGER_ID;
ALTER TABLE INNTEKT_ARBEID_YTELSER DROP COLUMN ARBEID_OPPLYSNINGER_ID;
ALTER TABLE INNTEKT_ARBEID_YTELSER DROP COLUMN YTELSE_OPPLYSNINGER_ID;
ALTER TABLE INNTEKT_ARBEID_YTELSER RENAME TO IAY_INNTEKT_ARBEID_YTELSER;

COMMENT ON TABLE AKTOER_INNTEKT IS 'Tabell med rad per aktør med inntekt relatert til behandlingen.';
COMMENT ON COLUMN AKTOER_INNTEKT.AKTOER_ID IS 'Aktøren raden gjelder for';
ALTER TABLE AKTOER_INNTEKT ADD CONSTRAINT PK_AKTOER_INNTEKT PRIMARY KEY (ID);
CREATE INDEX IDX_AKTOER_INNTEKT_1 ON AKTOER_INNTEKT(AKTOER_ID);
CREATE INDEX IDX_AKTOER_INNTEKT_2 ON AKTOER_INNTEKT(INNTEKT_ARBEID_YTELSER_ID);
ALTER TABLE AKTOER_INNTEKT RENAME TO IAY_AKTOER_INNTEKT;

begin
  execute immediate 'DROP TABLE INNTEKT';
  exception when others then
  if sqlcode != -4043 then
    raise;
  end if;
end;
/
ALTER TABLE TMP_INNTEKT RENAME TO IAY_INNTEKT;
COMMENT ON TABLE IAY_INNTEKT IS 'Inntekter per virksomhet';
COMMENT ON COLUMN IAY_INNTEKT.AKTOER_INNTEKT_ID IS 'Fjernnøkkel aktør-inntekt';
COMMENT ON COLUMN IAY_INNTEKT.ARBEIDSGIVER_AKTOR_ID IS 'Aktøren referansen til den personligebedriften som har utbetalt inntekt.';
COMMENT ON COLUMN IAY_INNTEKT.ARBEIDSGIVER_VIRKSOMHET_ID IS 'Fjernnøkkel virksomhet';
CREATE INDEX IDX_INNTEKT_1 ON IAY_INNTEKT(AKTOER_INNTEKT_ID);
CREATE INDEX IDX_INNTEKT_2 ON IAY_INNTEKT(KILDE);
CREATE INDEX IDX_INNTEKT_3 ON IAY_INNTEKT(ARBEIDSGIVER_VIRKSOMHET_ID);
CREATE INDEX IDX_INNTEKT_4 ON IAY_INNTEKT(ARBEIDSGIVER_AKTOR_ID);
ALTER TABLE IAY_INNTEKT RENAME CONSTRAINT FK_TMP_INNTEKT_1 TO FK_INNTEKT_1;
ALTER TABLE IAY_INNTEKT ADD CONSTRAINT FK_INNTEKT_2 FOREIGN KEY (AKTOER_INNTEKT_ID) REFERENCES IAY_AKTOER_INNTEKT(ID);
ALTER TABLE IAY_INNTEKT ADD CONSTRAINT FK_INNTEKT_3 FOREIGN KEY (KILDE, KL_KILDE) REFERENCES KODELISTE (KODE, KODEVERK);

ALTER TABLE INNTEKTSPOST RENAME TO IAY_INNTEKTSPOST;
ALTER TABLE IAY_INNTEKTSPOST RENAME COLUMN INNTEKTSPOST_TYPE_KL TO KL_INNTEKTSPOST_TYPE;
COMMENT ON TABLE IAY_INNTEKTSPOST IS 'Utbetaling per type per periode';
COMMENT ON COLUMN IAY_INNTEKTSPOST.INNTEKTSPOST_TYPE IS 'Type utbetaling, lønn eller ytelse';
COMMENT ON COLUMN IAY_INNTEKTSPOST.BELOEP IS 'Utbetalt beløp';
ALTER TABLE IAY_INNTEKTSPOST ADD CONSTRAINT FK_INNTEKTSPOST_3 FOREIGN KEY (INNTEKTSPOST_TYPE, KL_INNTEKTSPOST_TYPE) REFERENCES KODELISTE (KODE, KODEVERK);
CREATE INDEX IDX_INNTEKTPOST_1 ON IAY_INNTEKTSPOST(INNTEKT_ID);
CREATE INDEX IDX_INNTEKTPOST_2 ON IAY_INNTEKTSPOST(INNTEKTSPOST_TYPE);

-- Virksomhet
COMMENT ON TABLE VIRKSOMHET IS 'Virksomhet fra enhetsregisteret';
COMMENT ON COLUMN VIRKSOMHET.ORGNR IS 'Bedriftens unike identifikator i enhetsregisteret';
COMMENT ON COLUMN VIRKSOMHET.NAVN IS 'Bedriftens navn i enhetsregisteret';
COMMENT ON COLUMN VIRKSOMHET.REGISTRERT IS 'Når virksomheten ble registrert i enhetsregisteret';
COMMENT ON COLUMN VIRKSOMHET.OPPSTART IS 'Når næringen startet opp';
COMMENT ON COLUMN VIRKSOMHET.AVSLUTTET IS 'Når næringen opphørte';
COMMENT ON COLUMN VIRKSOMHET.OPPLYSNINGER_OPPDATERT_TID IS 'Siste tidspunkt for forespørsel til enhetsregisteret';
CREATE INDEX IDX_VIRKSOMHET_1 ON VIRKSOMHET(ORGNR);

-- Arbeid
COMMENT ON TABLE AKTOER_ARBEID IS 'Tabell med rad per aktør med arbeid eller aktiviteter som er likestilt pensjonsgivende arbeid relatert til behandlingen.';
COMMENT ON COLUMN AKTOER_ARBEID.AKTOER_ID IS 'Aktøren raden gjelder for';
CREATE INDEX IDX_AKTOER_ARBEID_1 ON AKTOER_ARBEID(AKTOER_ID);
CREATE INDEX IDX_AKTOER_ARBEID_2 ON AKTOER_ARBEID(INNTEKT_ARBEID_YTELSER_ID);
ALTER TABLE AKTOER_ARBEID RENAME TO IAY_AKTOER_ARBEID;

COMMENT ON TABLE YRKESAKTIVITET IS 'Arbeid eller aktiviteter som er likestilt pensjonsgivende arbeid';
COMMENT ON COLUMN YRKESAKTIVITET.AKTOER_ARBEID_ID IS 'Fjernnøkkel';
COMMENT ON COLUMN YRKESAKTIVITET.ARBEIDSFORHOLD_ID IS 'Arbeidsforholds iden fra A-Ordningen. Løpenummer i bedriftens LPS-system.';
COMMENT ON COLUMN YRKESAKTIVITET.ARBEIDSGIVER_AKTOR_ID IS 'Aktøren referansen til den personligebedriften som har ansatt vedkommende.';
CREATE INDEX IDX_YRKESAKTIVITET_1 ON YRKESAKTIVITET(AKTOER_ARBEID_ID);
CREATE INDEX IDX_YRKESAKTIVITET_2 ON YRKESAKTIVITET(ARBEID_TYPE);
CREATE INDEX IDX_YRKESAKTIVITET_3 ON YRKESAKTIVITET(ARBEIDSGIVER_VIRKSOMHET_ID);
CREATE INDEX IDX_YRKESAKTIVITET_4 ON YRKESAKTIVITET(ARBEIDSGIVER_AKTOR_ID);
CREATE INDEX IDX_YRKESAKTIVITET_5 ON YRKESAKTIVITET(ARBEIDSGIVER_VIRKSOMHET_ID, ARBEIDSFORHOLD_ID);
ALTER TABLE YRKESAKTIVITET ADD CONSTRAINT FK_YRKESAKTIVITET_3 FOREIGN KEY (ARBEIDSGIVER_VIRKSOMHET_ID) REFERENCES VIRKSOMHET(ID);
ALTER TABLE YRKESAKTIVITET RENAME TO IAY_YRKESAKTIVITET;

COMMENT ON TABLE AKTIVITETS_AVTALE IS 'Ansettelses avtaler og avtaler om periode av en gitt type.';
COMMENT ON COLUMN AKTIVITETS_AVTALE.PROSENTSATS IS 'Stillingsprosent';
COMMENT ON COLUMN AKTIVITETS_AVTALE.ANTALL_TIMER IS 'Antall timer med avtalt arbeid';
COMMENT ON COLUMN AKTIVITETS_AVTALE.ANTALL_TIMER_FULLTID IS 'Antall timer som tilsvarer full stilling';
COMMENT ON COLUMN AKTIVITETS_AVTALE.BESKRIVELSE IS 'Saksbehandlers vurdering om perioden. Forekommer data her kun hvis den ligger i overstyrt.';
CREATE INDEX IDX_AKTIVITETS_AVTALE_1 ON AKTIVITETS_AVTALE(YRKESAKTIVITET_ID);
ALTER TABLE AKTIVITETS_AVTALE RENAME TO IAY_AKTIVITETS_AVTALE;

COMMENT ON TABLE PERMISJON IS 'Oversikt over avtalt permisjon hos arbeidsgiver';
COMMENT ON COLUMN PERMISJON.PROSENTSATS IS 'Antall prosent permisjon';
CREATE INDEX IDX_PERMISJON_1 ON PERMISJON(YRKESAKTIVITET_ID);
ALTER TABLE PERMISJON RENAME COLUMN BESKRIVELSE_TYPE_KL TO KL_BESKRIVELSE_TYPE;
ALTER TABLE PERMISJON ADD CONSTRAINT FK_PERMISJON_2 FOREIGN KEY (BESKRIVELSE_TYPE, KL_BESKRIVELSE_TYPE) REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE PERMISJON RENAME TO IAY_PERMISJON;

-- Inntektsmelding
ALTER TABLE INNTEKTSMELDINGER RENAME TO IAY_INNTEKTSMELDINGER;
COMMENT ON TABLE IAY_INNTEKTSMELDINGER IS 'Koblingstabell mellom grunnlag og inntektsmeldinger';

COMMENT ON TABLE INNTEKTSMELDING IS 'Inntektsmeldinger';
COMMENT ON COLUMN INNTEKTSMELDING.INNTEKT_BELOEP IS 'Oppgitt årslønn fra arbeidsgiver';
COMMENT ON COLUMN INNTEKTSMELDING.NAER_RELASJON IS 'Arbeidsgiver oppgir at søker har nær relasjon til arbeidsgiver';
COMMENT ON COLUMN INNTEKTSMELDING.ARBEIDSFORHOLD_ID IS 'Hvis inntektsmeldingen gjelder for kun et spesifikt arbeidsforhold så er denne satt.';
COMMENT ON COLUMN INNTEKTSMELDING.REFUSJON_BELOEP IS 'Beløpet arbeidsgiver ønsker refundert';
COMMENT ON COLUMN INNTEKTSMELDING.REFUSJON_OPPHOERER IS 'Dato for når refusjonen opphører';
COMMENT ON COLUMN INNTEKTSMELDING.START_DATO_PERMISJON IS 'Avtalt startdato for permisjonen fra arbeidsgiver';
CREATE INDEX IDX_INNTEKTSMELDING_1 ON INNTEKTSMELDING(INNTEKTSMELDINGER_ID);
CREATE INDEX IDX_INNTEKTSMELDING_2 ON INNTEKTSMELDING(VIRKSOMHET_ID);
CREATE INDEX IDX_INNTEKTSMELDING_3 ON INNTEKTSMELDING(VIRKSOMHET_ID, ARBEIDSFORHOLD_ID);
ALTER TABLE INNTEKTSMELDING RENAME TO IAY_INNTEKTSMELDING;

COMMENT ON TABLE GRADERING IS 'Arbeidsgivers informasjon om gradering';
COMMENT ON COLUMN GRADERING.ARBEIDSTID_PROSENT IS 'Avtalt arbeidstid i prosent under gradering';
CREATE INDEX IDX_GRADERING_1 ON GRADERING(INNTEKTSMELDING_ID);
ALTER TABLE GRADERING RENAME TO IAY_GRADERING;

COMMENT ON TABLE NATURAL_YTELSE IS 'Arbeidsgivers informasjon om oppstart og opphør av natural ytelser';
COMMENT ON COLUMN NATURAL_YTELSE.BELOEP_MND IS 'Verdi i kroner per måned';
CREATE INDEX IDX_NATURAL_YTELSE_1 ON NATURAL_YTELSE(INNTEKTSMELDING_ID);
ALTER TABLE NATURAL_YTELSE RENAME TO IAY_NATURAL_YTELSE;

COMMENT ON TABLE UTSETTELSE_PERIODE IS 'Arbeidsgivers informasjon om utsettelser.';
CREATE INDEX IDX_UTSETTELSE_PERIODE_1 ON UTSETTELSE_PERIODE(INNTEKTSMELDING_ID);
ALTER TABLE UTSETTELSE_PERIODE RENAME TO IAY_UTSETTELSE_PERIODE;

ALTER TABLE INNTEKTSMELDING_MANGLENDE RENAME TO IAY_INNTEKTSMELDING_MANGLER;
CREATE INDEX IDX_INNTEKTSMELDING_MANGLER_1 ON IAY_INNTEKTSMELDING_MANGLER(INNTEKTSMELDINGER_ID);
CREATE INDEX IDX_INNTEKTSMELDING_MANGLER_2 ON IAY_INNTEKTSMELDING_MANGLER(VIRKSOMHET_ID);

-- Ytelse
COMMENT ON TABLE AKTOER_YTELSE IS 'Tabell med rad per aktør med tilstøtende ytelser relatert til behandlingen.';
COMMENT ON COLUMN AKTOER_YTELSE.AKTOER_ID IS 'Aktøren raden gjelder for';
CREATE INDEX IDX_AKTOER_YTELSE_1 ON AKTOER_YTELSE(AKTOER_ID);
CREATE INDEX IDX_AKTOER_YTELSE_2 ON AKTOER_YTELSE(INNTEKT_ARBEID_YTELSER_ID);
ALTER TABLE AKTOER_YTELSE RENAME TO IAY_AKTOER_YTELSE;

CREATE INDEX IDX_YTELSE_1 ON YTELSE(AKTOER_YTELSE_ID);
ALTER TABLE YTELSE RENAME TO IAY_RELATERT_YTELSE;

CREATE INDEX IDX_YTELSE_GRUNNLAG_1 ON YTELSE_GRUNNLAG(YTELSE_ID);
ALTER TABLE YTELSE_GRUNNLAG RENAME TO IAY_YTELSE_GRUNNLAG;

CREATE INDEX IDX_YTELSE_STOERRELSE_1 ON YTELSE_STOERRELSE(YTELSE_GRUNNLAG_ID);
CREATE INDEX IDX_YTELSE_STOERRELSE_2 ON YTELSE_STOERRELSE(VIRKSOMHET_ID);
CREATE INDEX IDX_YTELSE_STOERRELSE_3 ON YTELSE_STOERRELSE(HYPPIGHET);
ALTER TABLE YTELSE_STOERRELSE RENAME TO IAY_YTELSE_STOERRELSE;

CREATE INDEX IDX_YTELSE_ANVIST_1 ON YTELSE_ANVIST(YTELSE_ID);
COMMENT ON COLUMN YTELSE_ANVIST.DAGSATS IS 'Dagsatsen på den relaterte ytelsen';
ALTER TABLE YTELSE_ANVIST RENAME TO IAY_YTELSE_ANVIST;

-- Oppgitt opptjening
ALTER TABLE SOEKNAD ADD CONSTRAINT FK_SOEKNAD_SO_OPPTJENING FOREIGN KEY (OPPGITT_OPPTJENING_ID) REFERENCES SO_OPPGITT_OPPTJENING(ID);
COMMENT ON TABLE SO_OPPGITT_OPPTJENING IS 'Inneholder brukers oppgitte opplysninger om arbeid eller aktiviteter som er likestilt pensjonsgivende arbeid.';

COMMENT ON TABLE ANNEN_AKTIVITET IS 'Aktiviteter som er likestilt pensjonsgivende arbeid.';
CREATE INDEX IDX_ANNEN_AKTIVITET_1 ON ANNEN_AKTIVITET(OPPGITT_OPPTJENING_ID);
ALTER TABLE ANNEN_AKTIVITET RENAME TO IAY_ANNEN_AKTIVITET;

COMMENT ON TABLE EGEN_NAERING IS 'Oppgitt informasjon om egen næringsvirksomhet';
COMMENT ON COLUMN EGEN_NAERING.BRUTTO_INNTEKT IS 'Brutto inntekt';
COMMENT ON COLUMN EGEN_NAERING.ENDRING_DATO IS 'Dato for endring i næringen';
COMMENT ON COLUMN EGEN_NAERING.NYOPPSTARTET IS 'Er næringen startet opp innenfor siste ligningsåret';
COMMENT ON COLUMN EGEN_NAERING.REGNSKAPSFOERER_NAVN IS 'Navn på oppgitt regnskapsfører';
COMMENT ON COLUMN EGEN_NAERING.REGNSKAPSFOERER_TLF IS 'Telefonnr til oppgitt regnskapsfører';
COMMENT ON COLUMN EGEN_NAERING.UTENLANDSK_VIRKSOMHET_NAVN IS 'Navn på virksomheten i utlandet hvis det er der den finnes.';
COMMENT ON COLUMN EGEN_NAERING.BEGRUNNELSE IS 'Saksbehandlers vurderinger av avslag på perioden';
CREATE INDEX IDX_EGEN_NAERING_1 ON EGEN_NAERING(OPPGITT_OPPTJENING_ID);
CREATE INDEX IDX_EGEN_NAERING_2 ON EGEN_NAERING(VIRKSOMHET_ID);
CREATE INDEX IDX_EGEN_NAERING_3 ON EGEN_NAERING(VIRKSOMHET_TYPE);
ALTER TABLE EGEN_NAERING RENAME TO IAY_EGEN_NAERING;

COMMENT ON TABLE OPPGITT_ARBEIDSFORHOLD IS 'Oppgitt informasjon om arbeidsforhold';
COMMENT ON COLUMN OPPGITT_ARBEIDSFORHOLD.UTENLANDSK_INNTEKT IS 'Inntekt fra utenlandsk arbeidsforhold';
COMMENT ON COLUMN OPPGITT_ARBEIDSFORHOLD.UTENLANDSK_VIRKSOMHET_NAVN IS 'Navn på virksomheten i utlandet hvis det er der den finnes';
ALTER TABLE OPPGITT_ARBEIDSFORHOLD ADD CONSTRAINT FK_OPPGITT_ARBEIDSFORHOLD_3 FOREIGN KEY (ARBEID_TYPE, KL_ARBEID_TYPE) REFERENCES KODELISTE (KODE, KODEVERK);
CREATE INDEX IDX_OPPGITT_ARBEIDSFORHOLD_1 ON OPPGITT_ARBEIDSFORHOLD(OPPGITT_OPPTJENING_ID);
CREATE INDEX IDX_OPPGITT_ARBEIDSFORHOLD_2 ON OPPGITT_ARBEIDSFORHOLD(VIRKSOMHET_ID);
ALTER TABLE OPPGITT_ARBEIDSFORHOLD RENAME TO IAY_OPPGITT_ARBEIDSFORHOLD;

COMMENT ON TABLE GR_YTELSES_FORDELING IS 'Grunnlag med informasjon om perioder vedrørende behandlingen';
COMMENT ON TABLE YF_FORDELING IS 'Mange til mange tabell mellom grunnlaget og periodene';
COMMENT ON TABLE YF_FORDELING_PERIODE IS 'Mange til mange tabell mellom grunnlaget og periodene';
COMMENT ON TABLE SO_RETTIGHET IS 'Søkers oppgitte rettigheter';
COMMENT ON TABLE SO_DEKNINGSGRAD IS 'Søkers oppgitte dekningsgradsinformasjon';

COMMENT ON COLUMN SO_DEKNINGSGRAD.DEKNINGSGRAD IS 'Søker har oppgitt følgende dekningsgrad';
COMMENT ON COLUMN SO_RETTIGHET.ALENEOMSORG IS 'Søker har oppgitt verdi om søkern har aleneomsorg';
COMMENT ON COLUMN SO_RETTIGHET.ANNEN_FORELDRE_RETT IS 'Søker har oppgitt verdi om den andre foreldren har rett';
COMMENT ON COLUMN SO_RETTIGHET.OMSORG_I_HELE_PERIODEN IS 'Søker har oppgitt verdi om omsorg hele perioden';
COMMENT ON COLUMN OPPTJENING.OPPTJENT_PERIODE IS 'Mengden opptjening vurdert som godkjent av opptjeningsvilkåret';
COMMENT ON COLUMN YF_FORDELING_PERIODE.BEGRUNNELSE IS 'Saksbehandlers begrunnelse for vurderingen av perioden';
COMMENT ON COLUMN YF_FORDELING_PERIODE.GRADERING IS 'Om det er gradering i perioden';
