alter table KODELISTE_RELASJON drop CONSTRAINT FK_KODELISTE_RELASJON_1;
alter table KODELISTE_RELASJON drop CONSTRAINT FK_KODELISTE_RELASJON_2;

ALTER TABLE YRKESAKTIVITET disable CONSTRAINT FK_YRKESAKTIVITET_2;
update YRKESAKTIVITET set ARBEID_TYPE = 'ORDINÆRT_ARBEIDSFORHOLD' where ARBEID_TYPE = 'ORDINAERT_ARBEIDSFORHOLD';
update KODELISTE set kode = 'ORDINÆRT_ARBEIDSFORHOLD' where kode = 'ORDINAERT_ARBEIDSFORHOLD' AND KODEVERK = 'ARBEID_TYPE';
ALTER TABLE YRKESAKTIVITET enable CONSTRAINT FK_YRKESAKTIVITET_2;

update KODELISTE set kode = 'FORENKLET_OPPGJØRSORDNING' where kode = 'FORENKLET_OPPGJOERSORDNING' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'NÆRING' where kode = 'SELVNAER' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'MILITÆR_ELLER_SIVILTJENESTE' where kode = 'MILITAER_ELLER_SIVILTJENESTE' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set kode = 'MILITÆR_ELLER_SIVILTJENESTE' where kode = 'MILITAER_ELLER_SIVILTJENESTE' AND KODEVERK = 'OPPTJENING_AKTIVITET_TYPE';

update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' where KODE = 'VENTELØNN' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' WHERE KODE = 'LØNN_UNDER_UTDANNING' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' WHERE KODE = 'ETTERLØNN_FRA_ARBEIDSGIVER' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' WHERE KODE = 'MILITÆR_ELLER_SIVILTJENESTE' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' WHERE KODE = 'SLUTTPAKKE' AND KODEVERK = 'ARBEID_TYPE';
update KODELISTE set EKSTRA_DATA = '{ "gui": "true" }' WHERE KODE = 'VARTPENGER' AND KODEVERK = 'ARBEID_TYPE';

UPDATE KODELISTE_RELASJON set KODE1 = 'MILITÆR_ELLER_SIVILTJENESTE', KODE2 = 'MILITÆR_ELLER_SIVILTJENESTE'
where kode1 = 'MILITAER_ELLER_SIVILTJENESTE' and KODEVERK1 = 'ARBEID_TYPE';
UPDATE KODELISTE_RELASJON set KODE1 = 'ORDINÆRT_ARBEIDSFORHOLD', KODE2 = 'ARBEID'
where kode1 = 'ORDINAERT_ARBEIDSFORHOLD' and KODEVERK1 = 'ARBEID_TYPE';
UPDATE KODELISTE_RELASJON set KODE1 = 'NÆRING', KODE2 = 'NÆRING'
where kode1 = 'SELVNAER' and KODEVERK1 = 'ARBEID_TYPE';
UPDATE KODELISTE_RELASJON set KODE1 = 'FORENKLET_OPPGJØRSORDNING', KODE2 = 'ARBEID'
where kode1 = 'FORENKLET_OPPGJOERSORDNING' and KODEVERK1 = 'ARBEID_TYPE';

UPDATE KODELISTE_RELASJON set KODE2 = 'FORENKLET_OPPGJØRSORDNING'
where kode2 = 'FORENKLET_OPPGJOERSORDNING' and KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';

UPDATE KODELISTE_RELASJON set KODE2 = 'ORDINÆRT_ARBEIDSFORHOLD'
where kode2 = 'ORDINAERT_ARBEIDSFORHOLD' and KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';

UPDATE KODELISTE_RELASJON set KODE2 = 'NÆRING'
where kode2 = 'SELVNAER' and KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';

UPDATE KODELISTE_RELASJON set KODE2 = 'MILITÆR_ELLER_SIVILTJENESTE', KODE1 = 'MILITÆR_ELLER_SIVILTJENESTE'
where kode2 = 'MILITAER_ELLER_SIVILTJENESTE' and KODEVERK1 = 'OPPTJENING_AKTIVITET_TYPE';


alter table ANNEN_AKTIVITET RENAME COLUMN ANNEN_OPPTJENING_TYPE TO ARBEID_TYPE;
alter table ANNEN_AKTIVITET RENAME COLUMN KL_ANNEN_OPPTJENING_TYPE TO KL_ARBEID_TYPE;
alter table ANNEN_AKTIVITET MODIFY KL_ARBEID_TYPE VARCHAR2(100) DEFAULT 'ARBEID_TYPE';

DELETE from KODELISTE_RELASJON where KODEVERK1 = 'ANNEN_OPPTJENING_TYPE';
DELETE from KODELISTE where kodeverk = 'ANNEN_OPPTJENING_TYPE';
DELETE from KODEVERK where kode = 'ANNEN_OPPTJENING_TYPE';

ALTER TABLE kodeliste_relasjon ADD CONSTRAINT fk_kodeliste_relasjon_1 FOREIGN KEY (kodeverk1, kode1) REFERENCES KODELISTE(kodeverk, kode);
ALTER TABLE kodeliste_relasjon ADD CONSTRAINT fk_kodeliste_relasjon_2 FOREIGN KEY (kodeverk2, kode2) REFERENCES KODELISTE(kodeverk, kode);
