ALTER TABLE PO_STATSBORGERSKAP RENAME CONSTRAINT PO_STATSBORGERSKAP_80 TO FK_PO_STATSBORGERSKAP_80;
ALTER TABLE PO_RELASJON RENAME CONSTRAINT PO_RELASJON_80 TO FK_PO_RELASJON_80;
ALTER TABLE PO_PERSONSTATUS RENAME CONSTRAINT PO_PERSONSTATUS_80 TO FK_PO_PERSONSTATUS_80;
ALTER TABLE PO_PERSONOPPLYSNING RENAME CONSTRAINT PO_PERSONOPPLYSNING_84 TO FK_PO_PERSONOPPLYSNING_84;
ALTER TABLE PO_PERSONOPPLYSNING RENAME CONSTRAINT PO_PERSONOPPLYSNING_82 TO FK_PO_PERSONOPPLYSNING_82;
ALTER TABLE PO_PERSONOPPLYSNING RENAME CONSTRAINT PO_PERSONOPPLYSNING_80 TO FK_PO_PERSONOPPLYSNING_80;
ALTER TABLE PO_ADRESSE RENAME CONSTRAINT PO_ADRESSE_80 TO FK_PO_ADRESSE_80;

ALTER TABLE PO_PERSONOPPLYSNING MODIFY NAVN VARCHAR2(100 CHAR);
ALTER TABLE PO_ADRESSE MODIFY ADRESSELINJE1 NULL;

COMMENT ON COLUMN PO_ADRESSE.ADRESSELINJE4 IS 'Adresselinje 4';

create index IDX_PO_ADRESSE_5 on PO_ADRESSE(ADRESSE_TYPE);
create index IDX_PO_PERSONOPPLYSNING_3 on PO_PERSONOPPLYSNING(REGION);
create index IDX_PO_PERSONOPPLYSNING_4 on PO_PERSONOPPLYSNING(BRUKER_KJOENN);
create index IDX_PO_PERSONOPPLYSNING_5 on PO_PERSONOPPLYSNING(SIVILSTAND_TYPE);
create index IDX_PO_PERSONSTATUS_4 on PO_PERSONSTATUS(PERSONSTATUS);
create index IDX_PO_RELASJON_5 on PO_RELASJON(RELASJONSROLLE);
create index IDX_PO_STATSBORGERSKAP_4 on PO_STATSBORGERSKAP(STATSBORGERSKAP);
