DROP INDEX IDX_FAGSAK_PROSESS_TASK_1;
CREATE INDEX IDX_FAGSAK_PROSESS_TASK_1 ON FAGSAK_PROSESS_TASK (fagsak_id);

DROP INDEX IDX_FAGSAK_PROSESS_TASK_2;
CREATE INDEX IDX_FAGSAK_PROSESS_TASK_2 ON FAGSAK_PROSESS_TASK (prosess_task_id);

DROP INDEX IDX_FAGSAK_PROSESS_TASK_3;
CREATE INDEX IDX_FAGSAK_PROSESS_TASK_3 ON FAGSAK_PROSESS_TASK (behandling_id);
