-- CREATE NEW TABLE OPPDRAG_KVITTERING
CREATE TABLE OPPDRAG_KVITTERING (
  id                    NUMBER(19) NOT NULL,
  versjon               NUMBER(19) DEFAULT 0 NOT NULL,
  alvorlighetsgrad      VARCHAR2(2 CHAR),
  beskr_melding         VARCHAR2(300 CHAR),
  melding_kode          VARCHAR2(8 CHAR),
  OPPDRAG_110_ID        NUMBER(19) NOT NULL,
  opprettet_av          VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  opprettet_tid         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  endret_av             VARCHAR2(20 CHAR),
  endret_tid            TIMESTAMP(3),
  CONSTRAINT PK_OPPDRAG_KVITTERING PRIMARY KEY (id),
  CONSTRAINT FK_OPPDRAG_KVITTERING_1 FOREIGN KEY (OPPDRAG_110_ID) REFERENCES OKO_OPPDRAG_110(id)
);

CREATE SEQUENCE SEQ_OPPDRAG_KVITTERING MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_OPPDRAG_KVITTERING_1 ON OPPDRAG_KVITTERING (OPPDRAG_110_ID);

