-- Slett koder fra Ytelseskontrakt-tjenesten
-- Må gjøres senere ettersom BEHANDLING_RELATERT_YTELSE ikke er slettet ennå. Misforståelse
-- DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_TEMA' AND KODE = 'AA';
-- DELETE FROM KODELISTE WHERE KODEVERK = 'RELATERT_YTELSE_TEMA' AND KODE = 'DAGP';
