ALTER TABLE FAGSAK
  DROP CONSTRAINT FK_FAGSAK_1;
ALTER TABLE FAGSAK
  ADD (arsak_type VARCHAR2(100), kl_arsak_type VARCHAR2(100) DEFAULT 'FAGSAK_ARSAK');
ALTER TABLE FAGSAK
ADD (ytelse_type VARCHAR2(100), kl_ytelse_type VARCHAR2(100) DEFAULT 'FAGSAK_YTELSE');

UPDATE FAGSAK fs
SET fs.arsak_type = (SELECT fr.FAGSAK_ARSAK_TYPE
                     FROM FAGSAK_RELASJON fr
                     WHERE fr.ID = fs.FAGSAK_RELASJON_ID),
  fs.ytelse_type  = (SELECT fr.FAGSAK_YTELSE_TYPE
                     FROM FAGSAK_RELASJON fr
                     WHERE fr.ID = fs.FAGSAK_RELASJON_ID);

ALTER TABLE FAGSAK
  ADD
  CONSTRAINT FK_FAGSAK_1 FOREIGN KEY (kl_arsak_type, arsak_type) REFERENCES KODELISTE (kodeverk, kode);
ALTER TABLE FAGSAK
  ADD
  CONSTRAINT FK_FAGSAK_2 FOREIGN KEY (kl_ytelse_type, ytelse_type) REFERENCES KODELISTE (kodeverk, kode);

ALTER TABLE FAGSAK_RELASJON
  ADD (fagsak_en_id NUMBER(19),
  fagsak_to_id NUMBER(19),
  konto_beregning_id NUMBER(19), aktiv VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL);
ALTER TABLE FAGSAK_RELASJON
  ADD CONSTRAINT CHK_FAGSAK_RELASJON CHECK (AKTIV IN ('J', 'N'));

CREATE UNIQUE INDEX UIDX_FAGSAK_RELASJON_01
  ON FAGSAK_RELASJON (
    (CASE WHEN AKTIV = 'J'
      THEN
        fagsak_en_id
     ELSE NULL END),
    (CASE WHEN AKTIV = 'J'
      THEN AKTIV
     ELSE NULL END)
  );
CREATE UNIQUE INDEX UIDX_FAGSAK_RELASJON_02
  ON FAGSAK_RELASJON (
    (CASE WHEN AKTIV = 'J' AND fagsak_to_id IS NOT NULL
      THEN
        fagsak_to_id
     ELSE NULL END),
    (CASE WHEN AKTIV = 'J' AND fagsak_to_id IS NOT NULL
      THEN AKTIV
     ELSE NULL END)
  );
UPDATE FAGSAK_RELASJON fr
SET aktiv            = 'J',
  fagsak_en_id       = (SELECT id
                        FROM FAGSAK f
                        WHERE f.FAGSAK_RELASJON_ID =
                              fr.ID),
  konto_beregning_id = (SELECT id
                        FROM
                          STOENADSKONTOBEREGNING f
                        WHERE f.FAGSAK_RELASJON_ID =
                              fr.ID);

ALTER TABLE FAGSAK_RELASJON
  DROP CONSTRAINT FK_FAGSAK_RELASJON_81;
ALTER TABLE FAGSAK_RELASJON
  DROP CONSTRAINT FK_FAGSAK_RELASJON_80;

ALTER TABLE FAGSAK_RELASJON
  DROP COLUMN FAGSAK_YTELSE_TYPE;
ALTER TABLE FAGSAK_RELASJON
  DROP COLUMN KL_FAGSAK_YTELSE;
ALTER TABLE FAGSAK_RELASJON
  DROP COLUMN FAGSAK_ARSAK_TYPE;
ALTER TABLE FAGSAK_RELASJON
  DROP COLUMN KL_FAGSAK_ARSAK;

ALTER TABLE FAGSAK_RELASJON
  ADD
  CONSTRAINT FK_FAGSAK_RELASJON_1 FOREIGN KEY (fagsak_en_id) REFERENCES FAGSAK (ID);
ALTER TABLE FAGSAK_RELASJON
  ADD
  CONSTRAINT FK_FAGSAK_RELASJON_2 FOREIGN KEY (fagsak_to_id) REFERENCES FAGSAK (ID);
ALTER TABLE FAGSAK_RELASJON
  ADD
  CONSTRAINT FK_FAGSAK_RELASJON_3 FOREIGN KEY (konto_beregning_id) REFERENCES STOENADSKONTOBEREGNING (ID);

ALTER TABLE FAGSAK
  DROP COLUMN FAGSAK_RELASJON_ID;
ALTER TABLE STOENADSKONTOBEREGNING
  DROP COLUMN FAGSAK_RELASJON_ID;
ALTER TABLE STOENADSKONTOBEREGNING
  DROP COLUMN BEHANDLING_ID;

COMMENT ON TABLE FAGSAK_RELASJON IS 'Fagsaks relasjon';
COMMENT ON COLUMN FAGSAK_RELASJON.ID IS 'Primærnøkkel';
COMMENT ON COLUMN FAGSAK_RELASJON.fagsak_en_id IS 'Fjernnøkkel til første fagsaken i relasjonen.';
COMMENT ON COLUMN FAGSAK_RELASJON.fagsak_to_id IS 'Fjernnøkkel til andre fagsaken i relasjonen.';
COMMENT ON COLUMN FAGSAK_RELASJON.konto_beregning_id IS 'Fjernnøkkel til stønadskontoberegningen som eies av relasjonen.';
COMMENT ON COLUMN FAGSAK_RELASJON.aktiv IS 'Aktivflagg som sier om relasjonen er aktiv eller ei.';

CREATE INDEX IDX_FAGSAK_RELASJON_1 ON FAGSAK_RELASJON(fagsak_en_id);
CREATE INDEX IDX_FAGSAK_RELASJON_2 ON FAGSAK_RELASJON(fagsak_to_id);
CREATE INDEX IDX_FAGSAK_RELASJON_3 ON FAGSAK_RELASJON(konto_beregning_id);
