ALTER TABLE KLAGE_VURDERING_RESULTAT ADD VEDTAKSDATO_PAKLAGD_BEHANDLING DATE;
UPDATE KLAGE_VURDERING_RESULTAT SET VEDTAKSDATO_PAKLAGD_BEHANDLING = SYSDATE where VEDTAKSDATO_PAKLAGD_BEHANDLING is null;
ALTER TABLE KLAGE_VURDERING_RESULTAT MODIFY (VEDTAKSDATO_PAKLAGD_BEHANDLING not null);

COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT.VEDTAKSDATO_PAKLAGD_BEHANDLING IS 'Referanse til påklaget behandling';
