INSERT INTO KODELISTE (id, kodeverk, kode, navn, gyldig_fom)
VALUES (seq_kodeliste.nextval, 'RELATERT_YTELSE_TILSTAND', 'ÅPEN', 'Åpen', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, navn, gyldig_fom)
VALUES (seq_kodeliste.nextval, 'RELATERT_YTELSE_TILSTAND', 'LØPENDE', 'Løpende', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, navn, gyldig_fom)
VALUES (seq_kodeliste.nextval, 'RELATERT_YTELSE_TILSTAND', 'AVSLUTTET', 'Avsluttet', to_date('2000-01-01', 'YYYY-MM-DD'));

UPDATE BEHANDLING_REL_YTELSER SET RELATERT_YTELSE_TILSTAND = 'ÅPEN' WHERE RELATERT_YTELSE_TILSTAND = 'ÅPEN_SAK';

UPDATE BEHANDLING_REL_YTELSER SET RELATERT_YTELSE_TILSTAND = 'LØPENDE' WHERE RELATERT_YTELSE_TILSTAND = 'LØPENDE_VEDTAK';

UPDATE BEHANDLING_REL_YTELSER SET RELATERT_YTELSE_TILSTAND = 'AVSLUTTET' WHERE RELATERT_YTELSE_TILSTAND = 'LUKKET_SAK';

DELETE FROM KODELISTE WHERE KODE IN ('ÅPEN_SAK', 'LØPENDE_VEDTAK', 'LUKKET_SAK') AND KODEVERK = 'RELATERT_YTELSE_TILSTAND';
