-- drop foreign key
ALTER TABLE OPPLYSNING_ADRESSE DROP CONSTRAINT FK_OPPLYSNING_ADRESSE_1;

-- add columns
ALTER TABLE OPPLYSNING_ADRESSE ADD mottaker_navn VARCHAR2(40 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD adresselinje1 VARCHAR2(40 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD adresselinje2 VARCHAR2(40 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD adresselinje3 VARCHAR2(40 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD postnummer    VARCHAR2(20 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD poststed      VARCHAR2(40 CHAR);
ALTER TABLE OPPLYSNING_ADRESSE ADD land          VARCHAR2(40 CHAR);
