@Library('deploy')
import deploy

def deployLib = new deploy()

def call(body) {
    try {
		env.LANG = "nb_NO.UTF-8"
		
		sh "java -version"
		sh "mvn --version"
		sh "echo $PATH"
		
        stage ('Build') {
			sh 'mvn -s ../mvn-settings.xml install -DskipTests' 
        }
		
	} catch (error) {
		throw error
	}
}

return this;