#!/usr/bin/env groovy


def call(body) {
    try {
		env.LANG = "nb_NO.UTF-8"
		 
        stage ('Build') {
            steps {
                sh 'mvn install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
		
	} catch (error) {
		throw error
	}
}

return this;